### ISSUE TITLE
UserInfo/IdToken is null when receiving token from on-premise ADFS

### ISSUE THREAD

**Issue by gameleon-dev** [AzureAD/azure-activedirectory-library-for-dotnet#1002]
When acquiring a token from a on-premise ADFS (Windows Server 2012 R2) endpoint through the ADAL libraries the result contains no id token or userinfo object. 

![token](https://user-images.githubusercontent.com/5390147/36853620-409126b4-1d6f-11e8-9eb8-3f6da06cb209.png)

While I am able to retrieve some of the ADFS user's exposed values from the access token instead (including the upn and email), the ADAL library seems to be basing several caching queries and checks on the id token or userinfo values, which causes at least two issues.

**Issue 1:**

Since the UserInfo/idtoken is missing, a cached token does not have its user identifier associated with it once its being cached. This causes silent retrieval of the token by identifier to fail.
Example retrieval (using psuedo values for resource, identifier and client id):

`await ctx.AcquireTokenSilentAsync("urn:myresource",  "myclientid", new UserIdentifier("example@example.com", UserIdentifierType.OptionalDisplayableId));`

Due to the absence of the userinfo/idtoken, once a token is retrieved the library doesn't associate the cached version of the token with its user identifier, therefore the above call will fail since no tokens in cache will match the query for the identifier.

**Issue 2:**

While the `UserIdentifierType.OptionalDisplayableId` option for the identifier succeeds (and properly occupies the username field in case of a prompt in non-silent flows), setting the type to the `UserIdentifierType.RequiredDisplayableId` or `UserIdentifierType.UniqueId` will fail with a AdalUserMismatchException because of a check the library performs based on the (in this case empty) UserInfo.

/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenInteractiveHandler.cs, Line 172-182:

```
string uniqueId = (resultEx.Result.UserInfo != null && resultEx.Result.UserInfo.UniqueId != null) ? resultEx.Result.UserInfo.UniqueId : "NULL";
string displayableId = (resultEx.Result.UserInfo != null) ? resultEx.Result.UserInfo.DisplayableId : "NULL";

if (this.UserIdentifierType == UserIdentifierType.UniqueId && string.Compare(uniqueId, this.UniqueId, StringComparison.Ordinal) != 0)
{
	throw new AdalUserMismatchException(this.UniqueId, uniqueId);
}

if (this.UserIdentifierType == UserIdentifierType.RequiredDisplayableId && string.Compare(displayableId, this.DisplayableId, StringComparison.OrdinalIgnoreCase) != 0)
{
	throw new AdalUserMismatchException(this.DisplayableId, displayableId);
}
```

**Comment by CryogenicPotato** [comment]
Same issue here, UserInfo is null when acquiring tokens from ADFS v3 (Windows Server 2012 R2)

**Comment by jennyf19** [comment]
@gameleon-dev @CryogenicPotato 
Thanks for reaching out. Apologize for the delayed response.

ADAL cannot control what is returned by ADFS. UserInfo and IdToken might be null if not returned by the service, which is what is happening in your case.

You will need to use this [AcquireTokenSilentAsync method](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/adalv3/dev/src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.cs#L237) which passes in only the resource and clientId. It will then pull any user from the cache that matches the specified resource and clientId, so if you have no UserInfo returned, it doesn't matter, the AT Silent call will still work. 

You can see this method calls another [AT Silent method](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/adalv3/dev/src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.cs#L239), but uses `UserIdentifier.AnyUser` as a parameter.

Can you try calling this method instead and let us know if this works for you?

cc: @jmprieur

**Comment by gameleon-dev** [comment]
@jennyf19 Thanks for the information. Then we will retest this use case as soon as we have a ADFS 2016 server available on premise.

**Comment by jennyf19** [comment]
@gameleon-dev - Keep us posted. Mind if we close this issue for the time being?
