### ISSUE TITLE
ADAL throws "InvalidAuthorityTypeTemplate" during device flow if authority is ADFS 

### ISSUE THREAD

**Issue by mualigit** [AzureAD/azure-activedirectory-library-for-dotnet#1012]
Currently, [AcquireDeviceCodeHandler.cs](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/62a82c78b2a8504065f342309f8015dde8b9eccc/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireDeviceCodeHandler.cs) throws an exception if the authority is ADFS. This will block if the ADFS implements device code flow.

Relevant code snippet:
```
private void ValidateAuthorityType()
        {
            if (this.authenticator.AuthorityType == AuthorityType.ADFS)
            {
                throw new AdalException(AdalError.InvalidAuthorityType,
                    string.Format(CultureInfo.CurrentCulture, AdalErrorMessage.InvalidAuthorityTypeTemplate, this.authenticator.Authority));
            }
        }
```

ADAL should either check the oauth metadata doc for the devicecode url (in case of ADFS) and block the device code flow if the url is not present. Or it can just remove this check and throw appropriately if the device code endpoint is not present.

**Comment by henrik-me** [comment]
Currently tracking the design change request internally in https://identitydivision.visualstudio.com/DevEx/_workitems/edit/363571

**Comment by henrik-me** [comment]
@mualigit : feel free to provide a PR with suggested changes which you have validated works with ADFS and we can take a look at it.

**Comment by henrik-me** [comment]
Closing as we are not adding new features to ADAL. 

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
