### ISSUE TITLE
Make context.AcquireDeviceCodeAsync cancellable 

### ISSUE THREAD

**Issue by crmann1** [AzureAD/azure-activedirectory-library-for-dotnet#1013]
When acquiring a token from AcquireDeviceCodeAsync the method will loop and poll the server to wait for the user to enter their device code in the website.  However, this polling can take ~15 minutes. If the user wants to stop waiting for the token, or they no longer want to authenticate there is no way to cancel the device code polling loop. 

Can the method be updated to take a cancellation token that cancels the polling loop?

**Comment by henrik-me** [comment]
@jmprieur : great feature request. It makes sense to add this functionality. Not sure about the timeline, however if @crmann1 feel free to propose a change.

**Comment by jmprieur** [comment]
@crmann1 that's something we implemented in MSAL.NET (3.x)
We won't do it in ADAL.NET, therefore closing the ADAL issue (fixed in MSAL)
