### ISSUE TITLE
Inline documentation: Authenticationcontext.TokenCache property unsettable

### ISSUE THREAD

**Issue by CamSoper** [AzureAD/azure-activedirectory-library-for-dotnet#1014]
This is a reference doc issue that requires a change to the underlying `///` comments.

From @Runyang-CSS (https://github.com/Azure/azure-docs-sdk-dotnet/issues/309):

> In the description of TokenCache property, it says "To turn OFF token caching, set TokenCache to null." https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.tokencache?view=azure-dotnet
>
>But there is no setter for the property, or setTokenCache method in Authenticationcontext class. How to set it?

cc: @mtillman

**Comment by jmprieur** [comment]
Thanks for your feedback. We'll have a look at the XML comment error
Meanwhile to understand how to un-serialize the token cache, please read:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Token-cache-serialization
