### ISSUE TITLE
Xamarin Android Not Installing Correctly v3.19.2

### ISSUE THREAD

**Issue by jamesmcroft** [AzureAD/azure-activedirectory-library-for-dotnet#1015]
After updating the NuGet package to the latest 3.19.2, I've noticed that the Android project (targeting Android 6.0) is no longer able to build as it cannot find the AuthenticationAgentContinuationHelper or PlatformParameters classes which are part of the Android component of the ADAL library.

Digging into this further by opening up the nupkg, there are dependencies which refer to supporting MonoAndroid10 however there is no folder in the lib to support MonoAndroid10. The minimum version appears to be MonoAndroid70. 

Either the dependencies are wrong or the libs folders have changed and need correcting to prevent causing confusion. 

It does appear that the dependencies vs actual libs is in a bit of state at the moment.

**Comment by SomkaPe** [comment]
I did not manage to reproduce an issue using  test Android app which uses 3.19.2,
could you please provide details ? what error message do you get and what do you mean under "there are dependencies which refer to supporting MonoAndroid10"

**Comment by jmprieur** [comment]
@jamesmcroft : drawing your attention on Petro's question above

**Comment by jamesmcroft** [comment]
Apologies @jmprieur & @SomkaPe. 

I've taken a look at this with a separate quick test app targeting Android 6.0 with an Android class library and PCL installing this version and it installed as expected, looking for the DLLs in the monoandroid7 folder.

I'm going to take another look at this though trying not to use the new PackageReference csproj format as I'm not sure if this could be the cause as my solution is quite old and still uses packages.config. 

When I looked at the csproj for the affecting Android app which had the library installed, the reference to the folder in packages was looking for the DLLs in netstandard1.3.

**Comment by jmprieur** [comment]
Thanks for the update, @jamesmcroft 
Closing the issue as external based on your feedback.

Feel free to re-open if you think we are doing something wrong.
