### ISSUE TITLE
iOS AuthenticationAgentUIViewController not dismissed when authentication task finishes

### ISSUE THREAD

**Issue by smstuebe** [AzureAD/azure-activedirectory-library-for-dotnet#1016]
Is there a reason, why `callbackMethod` is called before `DismissViewController` in `AuthenticationAgentUIViewController`? e.g.

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/ec4c95bd7aa0f7ab5d239976943b9776eb5b0fa5/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/AuthenticationAgentUIViewController.cs#L155-L156

The Problem  I have is, that I have code like that (which is pretty common in Xamarin Apps) :

```csharp
try
{
    var auth = await _authenticationContext.AcquireTokenAsync(...);
    // do stuff
}
catch (Exception ex)
{
    await _userDialogs.AlertAsync("### error");
}
```

`_userDialogs` is an instance of [Alan Ritchie's UserDialogs ](https://github.com/aritchie/userdialogs) which uses `UIApplication.SharedApplication.GetTopViewController()` to get the top ViewController. And so it happens that **after** `AcquireTokenAsync` returns or throws an exception, the navigation stack is in an undefined state and this results in Errors like these: 

>  Warning: Attempt to present <UIAlertController: 0x104602800> on <AuthenticationAgentUINavigationController: 0x10be47000> whose view is not in the window hierarchy!

In my opinion it should clean up everything, dismiss the VC completely and than return. What do you think?

**Comment by jennyf19** [comment]
@smstuebe Thanks for bringing this to our attention. We'll take a look and get back to you.

**Comment by henrik-me** [comment]
@smstuebe . My general thought on this is that we would not do any cleanup before we are done with all the work we need to do which includes doing the callback. 

It will take time for us to fully validate if this will have any impact on other customer scenarios and we have no current plans on changing this behavior. 

Did you try changing this value to validate if it actually works for you to change the order?

Does the library you mention have overrides or workarounds for this kind of behavior. I'm thinking there might be other controls which behaves similarly. E.g. Can you manually pop the window off the navigation stack?

Also will it be possible for you to be more specific in your exception handling and thus be able to handle this scenario?

**Comment by jennyf19** [comment]
@smstuebe - I did some testing w/Xamarin iOS and there is no reason to not shut down the UI as soon as it is done. I will make the change you suggested.

**Comment by henrik-me** [comment]
pls. see my comment in the related PR. it is about ensuring that the callback actually is performed.
