### ISSUE TITLE
AcquireTokenByAuthorizationCodeAsync returns a null exception

### ISSUE THREAD

**Issue by eylult** [AzureAD/azure-activedirectory-library-for-dotnet#1023]
Hi, 

We are having trouble logging into our product's PPE environment. When we call the below code snippet with an MSFT O365 account; it returns an exception. 
result = await authContext.AcquireTokenByAuthorizationCodeAsync(aadCode, uri, clientAssertion, resource);
We have an aadCode, the uri is pointing to a page through localhost and the resource is set as sdfpilot.microsoft.com. 

The exception that is returned is null; so there is no error code. 

This account is asking for MFA and I saw that there is an error code "// AADSTS50076: The user is required to use multi-factor authentication. Please retry with a new authorize request for this resource." related to that; but it is not returning that code either. Exception ex is just null. 

Can you help us understand what might be going on? 

Thanks,

**Comment by jennyf19** [comment]
@eylult - Thanks for the above information.
Can you please share the [ADAL logs](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net#new-way-of-logging-controlling-pii-adalnet--318) and possibly a [Fiddler trace](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/62a82c78b2a8504065f342309f8015dde8b9eccc/adal/README.md#network-traces)?
Thank you.

**Comment by jmprieur** [comment]
@eylult : are you using it part of a Web Application?
See [Acquiring tokens with authorization codes on web apps](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-with-authorization-codes-on-web-apps)

**Comment by eylult** [comment]
Thank you. We've updated our Adal version and fixed the issue.
