### ISSUE TITLE
Custom implementation of TokenCache always deserializes refreshToken as null

### ISSUE THREAD

**Issue by michaelsrichter** [AzureAD/azure-activedirectory-library-for-dotnet#1025]
Hi, looking for help or guidance on this topic:

We are currently using ADAL for .Net V3. ADAL V3 hides the Refresh Token. While developing our own implementation of the TokenCache, I noticed when serializing/deserializing the class that the refresh token is always set to NULL. According to this blog http://www.cloudidentity.com/blog/2015/08/13/adal-3-didnt-return-refresh-tokens-for-5-months-and-nobody-noticed, it isn’t needed. I’m concerned this isn’t true in a multi-server environment with load balancing, where in-memory caching won’t work.

**Comment by jennyf19** [comment]
@michaelsrichter - Here are [two samples](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Token-cache-serialization#some-of-the-samples-illustrating-token-cache-serialization) that use token cache serialization.

**Comment by kamalbabu** [comment]
@michaelsrichter  I have the same concern . 
I do want my refresh token in a distributed cache rather than in memory. How can i achieve this?

**Comment by jmprieur** [comment]
@kamalbabu : the page that @jennyf19 shared has several samples and links that might help you. It mentions the simple case but also
- this sample which shows a cache implemented with a Database (for a Web API where in memory and file cache are not adapted): https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof
- this article which explains how to create a distributed cache: https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/token-cache

what other information would you like to have?

**Comment by jmprieur** [comment]
Closing as we think we have answered and there was not answer to our question
