### ISSUE TITLE
UniversalView Incompatibility

### ISSUE THREAD

**Issue by Xeno-Xamarin** [AzureAD/azure-activedirectory-library-for-dotnet#1027]
Hi all !

I'm working on Xamarin.Forms app with 2 assemblies :

- Microsoft.Identity.Client
- Microsoft.IdentityModel.Clients.ActiveDirectory

It seems we have some problems to work with both of them ( on IOS part )
![devenv_2018-04-04_09-36-00](https://user-images.githubusercontent.com/22169151/38294598-a47f597a-37eb-11e8-8874-1c36a5fd4d09.png)

Any idea to fix it ?

**Comment by jmprieur** [comment]
@Xeno-Xamarin : It seems you are mixing ADAL.NET and MSAL.NET ?
Can you please describe your scenario? 
I suggest you read the following page to understand which to choose: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Register-your-application-with-Azure-Active-Directory

**Comment by jennyf19** [comment]
@Xeno-Xamarin - Any update on this? Have you got things working?

**Comment by jmprieur** [comment]
Using both ADAL.NET and MSAL.NET should probably be avoided, but it's now a supported scenario from ADAL.NET 4.0.0-preview and MSAL.NET 2.0.0-preview
