### ISSUE TITLE
CoreCLR library writes logging to console

### ISSUE THREAD

**Issue by AArnott** [AzureAD/azure-activedirectory-library-for-dotnet#1028]
I'm using Microsoft.IdentityModel.Clients.ActiveDirectory 3.19.2 in a .NET Core console application and the console where I am interacting with the user is essentially corrupted by ADAL's logging of access token handling to the same console.

Libraries shouldn't be writing to the console uninvited. Please fix this.

**Comment by AArnott** [comment]
I think @crmann1 may have already fixed this in his fork.

**Comment by jmprieur** [comment]
Thanks @AArnott  for the heads-up

**Comment by AArnott** [comment]
Looks like this is a dupe of #928. 
From the docs you point to there, I learned I can stop the console logging using 
```cs
LoggerCallbackHandler.UseDefaultLogging = false;
```

That takes the priority of this bug down for me, but IMO console logging from a library should not be on by default.

**Comment by jennyf19** [comment]
Fixed with hotfix release [3.19.3](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/v3.19.3) and verified by our own testing and @AArnott
