### ISSUE TITLE
Can't login when inside corporation network

### ISSUE THREAD

**Issue by gi097** [AzureAD/azure-activedirectory-library-for-dotnet#1032]
I am using `ADAL.NET` in `Xamarin`. The login works fine, however when I am inside the corporation network the `ADFS` redirects to the internal server, which should not happen, it returns a `404`. How can I force the app to redirect to our external server? Are there some parameters that I am missing?

**Comment by jmprieur** [comment]
Hello @gi097 
Did you do all what is recommended in the following paragraph: [Properties of PlatformParameter specific to WinRT and UWP (Corporate network)](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows#properties-of-platformparameter-specific-to-winrt-and-uwp-corporate-network)

Alternatively, if this application is only meant to run on a domain, you might want to consider using [AcquireTokenSilentAsync using Integrated authentication on Windows (Kerberos)](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-Integrated-authentication-on-Windows-(Kerberos))

**Comment by jennyf19** [comment]
Thanks @jbpoulsen - we'll look into this issue

**Comment by Anant-Dabhi** [comment]
I have same issue on one of my user WIA not work in corporate network however it user try to access from outside network it working perfect.
In internal network when user set "EnablePrivateNetwork=1" it working but changing reg. value for every user is not feasible solution.

Is that any other  workaround for above issue?

**Comment by jmprieur** [comment]
@tatvaanant : maybe the solution is to work with the domain admins so that they add this registry key in the group policies: http://woshub.com/how-to-create-modify-and-delete-registry-keys-using-gpo/

**Comment by henrik-me** [comment]
@tatvaanant @gi097 @jbpoulsen : Is this still an issue for you? I do not thing that the library can do anything about it. PrivateNetwork must be set and for a corporate network that has as mentioned above likely to be set using group policies. I will close the issue, however please feel free to re-open if you find that there is something the library can do here.
