### ISSUE TITLE
Are there any plans to support authentication for .NET Core?

### ISSUE THREAD

**Issue by ivannp** [AzureAD/azure-activedirectory-library-for-dotnet#1036]
The UI used for authentication seems to be Windows based.

**Comment by jmprieur** [comment]
ADAL.NET does support authentication, but not interactive authentication:

**Why?**
.NET Core does not provide (to my knowledge) any Web browser, and they are required for ADAL.NET. Please read [ADAL.NET uses an embedded web browser](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/ADAL.NET-uses-an-embedded-web-browser).

**What can you do?**
You can other flows depending on if you are using a desktop/mobile application, or a Web App/Web API. Please see: [Public client application](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-a-token-return-AuthenticationResult-and-possibly-UserInfo#public-client-application) and [Confidential client applications](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-a-token-return-AuthenticationResult-and-possibly-UserInfo#confidential-client-applications) and the summaries
