### ISSUE TITLE
Making use of refresh token returned by no-resource AcquireTokenByAuthorizationCodeAsync

### ISSUE THREAD

**Issue by jorupp** [AzureAD/azure-activedirectory-library-for-dotnet#1040]
Unless I'm missing something, this library doesn't offer a way to make use of the refresh token returned by `AcquireTokenByAuthorizationCodeAsync` when no resource is supplied.  There's no corresponding `AcquireTokenSilentAsync` where you a resource isn't required, and even if there was, `AcquireTokenByAuthorizationCodeAsync` doesn't save the refresh token in the `TokenCache` supplied when creating the `AuthenticationContext`.

Here's my scenario:  I have a custom Azure AD app that uses delegated access to access several other applications.  When a user logs in, I redirect them to get a code which I redeem via `AcquireTokenByAuthorizationCodeAsync` for an accessToken + uniqueId.  Then, when I go to access a another system, I call `AcquireTokenSilentAsync` with it's resource and a `UserIdentifier` built from the uniqueId.  If that doesn't give me back a token (ie. because it's not in the cache yet or it's timed out), I call `AcquireTokenAsync` with a `UserAssertion` built from that access token.  Great.  Now, a couple of hours later, the user takes an action that requires I call another system.  This time, the `AcquireTokenAsync` call fails because the access token for the `UserAssertion` has expired.  But there's no way for me to get a new one without running the user through getting a new code and calling `AcquireTokenByAuthorizationCodeAsync`.

Am I missing something here, or is this not a use case that's intended to be supported?  Or am I going about this wrong?  Should I be making `AcquireTokenAsync` calls as soon as I log the user in for every system I could access so I get resource-specific refresh tokens?

**Comment by jmprieur** [comment]
Hello @jorupp : I understand that that you are building an ASP.NET Web application, and get notified when it gets the authorization code, and redeem the token.

I suggest you read this page of the conceptual documentation [](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-with-authorization-codes-on-web-apps), and in particular [It's a first step to make calls to other Web APIs on behalf of the user](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-with-authorization-codes-on-web-apps#its-a-first-step-to-make-calls-to-other-web-apis-on-behalf-of-the-user) which explains how to leverage the token cache

**Comment by jorupp** [comment]
I'm using the token cache for the resource-specific calls without issue.  In my scenario, I'm dealing with a number of different resources, and was planning not to acquire tokens for them until necessary, at which point I'll use the token cache.  I'm trying to figure out how to leverage the refresh token (likely via the token cache) for the *non-resource* authentication so I can get a new `UserAssertion` at any time from the cache without having to get a new authorizationCode.

**Comment by jmprieur** [comment]
@jorupp : 
When you use the on-behalf-of flow, and acquire a token for a different resource, but in the name of the same user, ADAL.NET should get you a token (indeed, leveraging the refresh token). Isn't it what you are observing? you will need, however to add dependencies to these resources in the azure portal during the app registration.

I don't understand, though, what a *non-resource* authentication is. Can you please tell us more about this scenario? is it that you'd want to access to resources (still in the name of the user), which you are discovering dynamically?

**Comment by jmprieur** [comment]
@jorupp : I suppose that calling AcquireTokenAsync for every resource you might use could be a good workaround. Also, for the issue you see, is it for the same user?

**Comment by jorupp** [comment]
@jmprieur, yes, this is for the same user the whole time (I'm using a distinct user token cache w/ persistence per-user).

**Comment by jmprieur** [comment]
@jorupp what exception is returned by `AcquireTokenSilentAsync` when you try to get a token for *resource2* ? can you tell me a bit more?

**Comment by jorupp** [comment]
@jmprieur I'm not sure if it returns an exception or just null - didn't think to log it since it was totally expected - how can it possibly get a token silently if there's not one in the cache...

**Comment by jorupp** [comment]
@jmprieur maybe I wasn't clear, _resource1_ and _resource2_ are two *different* resources.  The tokens acquired for the first aren't valid (or even candidates) for the second.

**Comment by jmprieur** [comment]
@jorupp is your organization using AAD or ADFS?

- With AAD you can get a token for another resource and the same user if you have a multiple resource refresh (contained in the cache maintained by ADAL)
- ADFS does not support this.

**Comment by jorupp** [comment]
@jmprieur AAD.  I looked at the tokens stored in the cache.  There weren't any non-resource-based ones.
