### ISSUE TITLE
"Could not load file or assembly" on Azure Functions v2 (.NET Core) for v3.16.1 and newer

### ISSUE THREAD

**Issue by gotgenes** [AzureAD/azure-activedirectory-library-for-dotnet#1048]
Starting with v3.16.1, there is an issue loading `Microsoft.IdentityModel.Clients.ActiveDirectory` in Azure Functions v2 targeting .NET Core. When referencing newer versions of this library, running the function with Azure Function Core Tools gives an error like the following:

```
[5/8/18 10:17:59 PM] Microsoft.Azure.WebJobs.Host: Error indexing method 'TokenExpiration.RunAsync'. System.Private.CoreLib: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.16.1.24801, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.16.1.24801, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

While @xpillons filed Azure/azure-functions-host#2373 against the Azure Functions project, I couldn't find a corresponding issue for the ADAL project. It seems this might be an issue with this library, as versions 3.16.0 and older do not cause this issue.

**Comment by jmprieur** [comment]
@gotgenes did you try with ADAL.NET 3.19.4 ?

**Comment by gotgenes** [comment]
@jmprieur Yes. I started with `Microsoft.IdentityModel.Clients.ActiveDirectory` v3.19.4. Searching for the error is what led me to Azure/azure-functions-host#2373.

**Comment by henrik-me** [comment]
@gotgenes do you have a sample app or a set of repro steps?
Also are other parts of Azure Functions or what you do referencing other libraries which depends on other ADAL versions?

**Comment by henrik-me** [comment]
Thanks @awernick. Have you validated the sample on Windows/Mac or only on your Linux box?

**Comment by awernick** [comment]
I have only verified on Linux, maybe someone else can verify if it also happens on other platforms?

**Comment by henrik-me** [comment]
I will verify this on Windows. However the change made between 3.16.0 and 3.16.1 is only a version change and a change affecting the .net for desktop apps, nothing have changed for Core in that change. Others suggest that they had a mix of ADAL v.2 and ADAL v3 libraries, which will not work (however given this works on 3.16.0 it's a different issue).

**Comment by henrik-me** [comment]
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
