### ISSUE TITLE
OBO scenario with OpenID Connect and authorization code flow

### ISSUE THREAD

**Issue by skyflyer** [AzureAD/azure-activedirectory-library-for-dotnet#1052]
I'm trying to wire up a scenario where one can use OpenID Connect *authorization code* flow to retrieve an id_token (and access_token) from AD FS and use that access token to retrieve resource-specific access token for downstream WebAPIs to use (see "image" below).

Additionally, I have the same questions regarding `TokenCache` as outlined in #514, which was closed with a working workaround, but not a "proper" solution.

I'd like to leverage OpenID Connect middleware as much as possible, but in the end, I don't mind sticking ADAL in there if it makes things easier. Having said that, there is a problem with "token cache" and storing tokens for a particular user based on the "object identifier", since that identifier is not known at the time "code" is recieved -- app tries to redeem the access token based on an "authorization code flow".

The [sample](https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore) which is provided uses `id_token code` response type, which is a "hybrid" approach. Given that "authorization code" flow is more secure than "implicit" or "hybrid", I'm wondering how to store an access token for this particular user in ADAL if the user's unique indentifier (i.e. `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier`) is not know at the time we're calling `AcquireTokenByAuthorizationCodeAsync`?

Please correct me if I'm wrong in understanding, but this is how I envision the flow:

To illustrate the scenario:
```
                              /--> ASP.NET Core WebAPI 1 (App W1)
                             /
User --> ASP.NET Core MVC (App A) -----> ASP.NET Core WebAPI 2 (App W2)
                            \
                             \-> ASP.NET Core WebAPI 3 (App W3)
```

1. User authenticates to the App A using the code flow
1. As part of the response, an `access_token` is supplied in addition to `id_token`
1. After getting the `id_token` (hence obtaining the nameidentifier claim), App A stores the `access_token` and `refresh_token` in the TokenCache (the challenge is here `<--`)
1. When requesting bearer token for W1, App A uses ADAL to request an access token for `App W1` and uses the cached `access_token` to obtain it. AD FS returns an access token fro `App W1` which is sent in a HTTP header to `App W1` which can validate it.
1. Similar scenarios occur when accessing `App W2` and `App W3`, where ADAL is "silently" requesting access tokens from ADFS on behalf of the user.

This works if I'm using `id_token code` `ResponseType` (hybrid flow), but not if I'm using `code`, because in this case, the token cache can't be populated based on the user's identifier.

I am currently (for demonstration purposes) using a naive implementation of the token cache, as presented in the sample https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore, but the challenge becomes bigger once we want to use a distributed cache for that.

One possible workaround I see is using a custom cache implementation which would store the cache in the client's cookie (encrypted) thus removing the need for an object identifier.

Am I missing something obvious?

**Comment by henrik-me** [comment]
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
