### ISSUE TITLE
Blank Login with ADFS Self Signed Certificate

### ISSUE THREAD

**Issue by sroyvs** [AzureAD/azure-activedirectory-library-for-dotnet#1054]
I'm doing some testing with an internal test ADFS server which is using a self-signed certificate, and when I get to the login page I simply get a empty white dialog.

![capture](https://user-images.githubusercontent.com/20728797/40128746-c5252900-5908-11e8-93ab-b14459b727ef.PNG)

**Comment by sroyvs** [comment]
Got the same result on an android device, and this is the [log](https://paste.ee/p/295br) from the point where AcquireTokenAsync was called

**Comment by jennyf19** [comment]
@sroyvs Thanks - I'll take a look

**Comment by jennyf19** [comment]
@sroyvs In Android, the developer can disable [webview](https://developer.android.com/reference/android/webkit/WebView), but ADAL needs the webview to launch the UI with the log-in screen. Can you double check you have webview enbabled?

Also, does your Android manifest look something like this: 
```<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="auto">
	<uses-sdk />
	<application></application>
	<uses-permission android:name="android.permission.GET_ACCOUNTS" />
	<uses-permission android:name="android.permission.MANAGE_ACCOUNTS" />
	<uses-permission android:name="android.permission.USE_CREDENTIALS" />
	<uses-permission android:name="android.permission.INTERNET" />
</manifest>
```

**Comment by sroyvs** [comment]
Added those extra permissions, but still the same.  But I was able to get around the problem by getting a valid SSL certificate for our test environment.  Maybe having the option to connect to an ADFS server with a self-signed certificates would be nice to have option for testing purposes, but not that important I guess.

**Comment by jennyf19** [comment]
@sroyvs Thanks for the feedback. I'll go ahead and close this issue.
