### ISSUE TITLE
Could not load type 'System.Security.Cryptography.SHA256Cng'

### ISSUE THREAD

**Issue by gastart** [AzureAD/azure-activedirectory-library-for-dotnet#1067]
I have a class library targeted for .net framework 4.6.2 where I am using library Microsoft.IdentityModel.Clients.ActiveDirectory v3.19.6

I have a class library where I have my nunit tests targeted for .net core 2.0 and when I run the test that makes use of the class library I created above I get

**System.TypeLoadException : Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.**

I do not have the exception when I target the latter project to .net framework 4.6.2.

**Comment by jmprieur** [comment]
@brentschmaltz @mafurman @GeoK : do you have some idea / input?

**Comment by brentschmaltz** [comment]
@gastart can you provide a stack trace?
The type is available since 3.5: 
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256cng?view=netframework-4.5.2

What version of .Net did you install on the machine?

**Comment by carolineocea** [comment]
Hi 
I'm having the same problem with a .net core console app and a class library targeting .NET fwk 4.6.2. I have the .NET frameworks 4.5.1 to 4.72 installed on the machine as well as .net core 2.1.400.

@brentschmaltz Here is part of my stacktrace :
`   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.CryptographyHelper.CreateSha256Hash(String input)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.LogReturnedToken(AuthenticationResult result)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.PostRunAsync(AuthenticationResult result)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenForClientCommonAsync(String resource, ClientKey clientKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource, ClientCredential clientCredential)`

@gastart did you figure out a workaround?

Thank you,
Caroline

**Comment by brentschmaltz** [comment]
@carolineocea will you have an issue if you build a .net core console app and target .net core 2.0?

**Comment by jmprieur** [comment]
MSAL.NET should support crypto correctly.
Won't fix in ADAL.NET

**Comment by rich617** [comment]
Use the "netstandard1.3" platform for .NET Core and NOT "net45". That solved the problem for me.

**Comment by jimmycwj** [comment]
Agreed. MSAL.NET solved my problem. @jmprieur
