### ISSUE TITLE
When AuthenticationContext acquires a new token using a Refresh Token, why does the returned token exclude scope information?

### ISSUE THREAD

**Issue by ckarras** [AzureAD/azure-activedirectory-library-for-dotnet#1070]
Using ADAL 2.29 and ADFS 2016, I have an application that calls a Web API, and this Web API expects tokens with scope = user_impersonation. 

- The app requests this scope explicitly in OpenIdConnectAuthenticationOptions. 
- Then, in AuthorizationCodeReceived, I call authContext.AcquireTokenByAuthorizationCode, and the acquired token contains the requested scope (confirmed by inspecting results in Fiddler and in the TokenCache)
- Every time the application needs to call the Web API, it provides a Authorization Bearer header with a token obtained by authContext.AcquireTokenSilent. If the original token obtained by AcquireTokenByAuthorizationCode is still valid, then this token contains the scope "user_impersonation" as expected.
- But once the token expires, ADAL automagically uses the refresh token to retrieve a new token from ADFS. This new token is missing the "scope" claim.

Where should I fix this? Is there a setting in ADFS 2016 that omits the scope from tokens obtained using a refresh token? Or is there something I need to specify in ADAL (2.29) to ensure the scope is requested?

As a test, I used Fiddler to capture the request sent to ADFS with the refresh token. This request provides the following parameters:
- client_id
- client_secret
- grant_type=refresh_token
- refresh_token
- But *not* the scope

I tried modifying the request in Fiddler to include scope=user_impersonation, and the returned token now includes this scope. This leads me to believe that ADAL should somehow be configured to explicitly ask for scopes when it uses a refresh token, but can't find where to configure it.

**Comment by jmprieur** [comment]
@ckarras : is it an option for you to upgrade to ADAL V3.x ?

**Comment by ckarras** [comment]
@jmprieur Not for now: I'm trying to fix a bug in an existing production application, ADAL v3 would require too many code changes that are unrelated to the bug I'm trying to fix (updating it causes several compilation errors due to modified method signatures, and I also see that the structure of the source code has significantly changed between 2.x and 3.x). I already updated to the latest ADAL v2.x (2.29), but doing and testing all the changes required for switching to v3 is not a risk we can take at this time.

What has changed in v3.x that would resolve this? I can't find an overload of AcquireTokenSilent or AcquireTokenSilentAsync that takes an additional scope parameter.

**Comment by henrik-me** [comment]
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
