### ISSUE TITLE
How to share tokens between Xamarin.iOS apps and native iOS apps?

### ISSUE THREAD

**Issue by Kyle-Reis** [AzureAD/azure-activedirectory-library-for-dotnet#1074]
Hi, is it possible for Xamarin.iOS apps which use this library to share tokens with native apps which use the [Objective-C library](https://github.com/AzureAD/azure-activedirectory-library-for-objc)? If so, how can this be accomplished?

**Comment by jmprieur** [comment]
This is not possible yet, @Kyle-Reis but we are working right now on enabling a shared cache between all the ADAL and MSAL libraries.
