### ISSUE TITLE
Customer question: What does AcquireTokenAsync failure look like?

### ISSUE THREAD

**Issue by CamSoper** [AzureAD/azure-activedirectory-library-for-dotnet#1110]
Hi there! I'm the docs author at the [Azure .NET SDK docs site](https://docs.microsoft.com/dotnet/azure), and a customer submitted the following question. Please be sure to @ them in your response. Thanks! 

@rocifier asked regarding [AuthenticationContext.AcquireTokenAsync Method (Microsoft.IdentityModel.Clients.ActiveDirectory)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.acquiretokenasync?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_AuthenticationContext_AcquireTokenAsync_System_String_System_String_System_Uri_Microsoft_IdentityModel_Clients_ActiveDirectory_IPlatformParameters_Microsoft_IdentityModel_Clients_ActiveDirectory_UserIdentifier_System_String_): 

How can I detect a failure in obtaining the token? Is a null value returned? Are exceptions returned eg. if there is a timeout or if you are not authorized?

**Comment by henrik-me** [comment]
@CamSoper @rocifier 

We generally use exceptions for error handling. We should have those documented in the reference doc as well. Keeping this issue open to ensure we track that.

Something about the exceptions you can expect in the library:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Exceptions-in-ADAL.NET

Some additional info on Aquiring Tokens
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-a-token-return-AuthenticationResult-and-possibly-UserInfo
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows
