### ISSUE TITLE
Js Alert not shown in Xamarin.Android and Xamarin.iOS webviews

### ISSUE THREAD

**Issue by IlyaSemenchenko** [AzureAD/azure-activedirectory-library-for-dotnet#1115]
One of our customers has ADFS on their tenant and after redirect JS alert with inputs for login and password are shown. 
![microsoftteams-image 3](https://user-images.githubusercontent.com/39047408/42411196-840e205e-8200-11e8-9764-e1fed2068087.png)
In the mobile app it redirects to the right url, but alert is now shown.
![simulator screen shot - iphone 7 - 2018-07-07 at 16 17 43](https://user-images.githubusercontent.com/39047408/42411240-61906f68-8201-11e8-82c2-92a1b9d42a7b.png)
Does anyone faced this issue and have workarounds?
Thanks.

**Comment by jmprieur** [comment]
Can you please provide repro steps? Can you reference a sample which exhibits this behavior: we don't have enough information to act on this issue for the moment.

**Comment by jmprieur** [comment]
Closing this issue as we did not get more information that would enable us to act on it
