### ISSUE TITLE
AcquireToken TokenCache BeforeAccessNotification failing on deserialization

### ISSUE THREAD

**Issue by chetanmnit2003** [AzureAD/azure-activedirectory-library-for-dotnet#1116]
Hi,

I am getting following exception intermittently on custom token cache implementation for BeforeAccessNotification. Can anyone help if I am doing something wrong here.

My implementation of the method..

/// <summary> 
/// Notification raised before ADAL accesses the cache. 
/// </summary> 
/// <param name="args">The token cache notification arguments.</param>
internal void BeforeAccessNotification(TokenCacheNotificationArgs args) 
{     
 // Retrieve the last write     
 byte[] tokenCacheBytes = null;     
 tokenCacheBytes = this.cache.Get(this.cacheKey, true);     
 if (tokenCacheBytes != null)    
  {        this.Deserialize(tokenCacheBytes);     
 }
}

Result:

"exceptionMessage": "System.ArgumentException: The key already existed in the dictionary.    at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.Add(TKey key, TValue value)       at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.Deserialize(Byte[] state)    at Microsoft.MarketplaceServices.Account.Management.Service.Caching.CustomTokenCache.BeforeAccessNotification(TokenCacheNotificationArgs args)    at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.OnBeforeAccess(TokenCacheNotificationArgs args)    at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__69.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__1d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.MarketplaceServices.Account.Management.Service.Clients.AppTokenClient.<>c__DisplayClass8_0.<<AcquireTokenAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.MarketplaceServices.Account.Management.Service.Clients.AppTokenClient.<AcquireTokenAsync>d__8.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
--

**Comment by bgavrilMS** [comment]
Hi @chetanmnit2003 - could you provide a few more details here? What library are you using ADAL or MSAL (Microsoft.Client.Identity ?) and what version?

Is your app using Turkish culture?

Here are 2 reference implementations of the cache, first one for a WPF client app (cache is stored in a file) and second one for web app (cache is stored in the session)

https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/TodoListClient/TokenCacheHelper.cs
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/TodoListClient/TokenCacheHelper.cs

**Comment by chetanmnit2003** [comment]
Hi,

I am using Microsoft.IdentityModel.Clients.ActiveDirectory and I was on the older version. No, it's not related to Turkish culture. 

I can see that newer package is thread safe as it’s locking the method so I hope, I won’t see this issue with new version. 

Code with new version would be deployed next week and I would update the thread. Thanks for help.

**Comment by bgavrilMS** [comment]
Cool, thanks for the update. I'll close the thread now, please open it if you encounter problems.
