### ISSUE TITLE
AcquireTokenSilentAsync with Client Credential flow does not find cached token

### ISSUE THREAD

**Issue by web265p3** [AzureAD/azure-activedirectory-library-for-dotnet#1134]
What I am doing is pretty easy. I'm acquiring a token via client credentials for my service:

```
            AuthenticationResult result = null;
            try
            {
                result = await context.AcquireTokenSilentAsync(resource, clientId);
            }
            catch(AdalSilentTokenAcquisitionException e)
            {
                clientCredential = new ClientCredential(clientId, "MyClientSecretKey");
                result = await context.AcquireTokenAsync(resource, clientCredential);
            }
```

After the first call of this code fragment, "context" contains a cached token. I can see this when I debug. But AcquireTokenSilentAsync always throws the AdalSilentTokenAcquisitionException so I always have to get another token. 

Because I am using client credential flow, all user regarding properties are not set. 
Is this function also working without user context? Anything to be aware of, if I have no user context?

**Comment by jmprieur** [comment]
@web265p3 
Client credentials benefits from the cache automatically (See the last line of this paragraph: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows#client-credentials-with-application-secret-in-adalnet). You don't need to call `AcquireTokenSilentAsync` for the non-user flows.

See the sample: https://github.com/Azure-Samples/active-directory-dotnet-daemon/blob/master/TodoListDaemon/Program.cs#L104

Thanks for your question. I've updated https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token#recommended-pattern-to-acquire-a-token to make this clearer

**Comment by jmprieur** [comment]
David, feel free to reopen if I did not answer your question, BTW
