### ISSUE TITLE
Making an AT expire would cause an exception

### ISSUE THREAD

**Issue by rayluo** [AzureAD/azure-activedirectory-library-for-dotnet#1135]
This might not happen in real world, but it can be reproduced by using the [DesktopTestApp and click the Expire-Access-Token button](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/27bf9fa0a12a1d7ab7e8305d32688014ab757721/msal/tests/dev%20apps/DesktopTestApp/MsalUserAccessTokenControl.cs#L39), which will then trigger a NullReferenceException at [this line](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/27bf9fa0a12a1d7ab7e8305d32688014ab757721/msal/src/Microsoft.Identity.Client/TokenCache.cs#L1009).

**Comment by jmprieur** [comment]
No customer impact. This is a more a refactoring
