### ISSUE TITLE
Hard refresh access token without login back

### ISSUE THREAD

**Issue by njangir2** [AzureAD/azure-activedirectory-library-for-dotnet#1137]
Hi, 

I am working in a xamarin application where I need to hard refresh AD access token without logging back to the application.
At the time of login to xamarin application I am calling method `AuthenticationContext.AcquireTokenAsync(resourceUrl, clientId, returnUri, platformParameters)` and this method generate access token without any issue.
The problem that I am facing is that on a user action I want to hard refresh the access token.
Hard refresh mean here is that refresh token should be newly generated for the particular resource and client id.
After successful login whenever I call method `AuthenticationContext.AcquireTokenSilentAsync(resource, clientid)` it return the same old access token.
I need a way by which I can regenerate this access token without logout and login back.

Thanks,
Narendra

**Comment by jmprieur** [comment]
@njangir2 : did you have a look at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows#properties-or-platformparameters-constructors-parameters-common-to-most-platforms ?
I think that a ``PromptBehavior.RefreshSession`` should work.

**Comment by njangir2** [comment]
@jmprieur : I have checked this [link](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows#properties-or-platformparameters-constructors-parameters-common-to-most-platforms) and verified in my xamarin app.
As of now we are targetting UWP and in our App.xamal.cs of UWP app we are setting platform parameters as `new PlatformParameters(PromptBehavior.Auto, false)`
On user action when I call method `AuthenticationContext.AcquireTokenAsync(resourceUrl, clientId, returnUri, platformParameters)` it returns me access token without showing the login prompt but this token is same as older (as per my understanding this access token is being returned from the token cache.)
I tried clearing token cache (by calling AuthenticationContext.TokenCache.Clear()) before calling `AcquireTokenAsync `method and and this time it shows me login prompt which I dont want as user is already logged in.
I have also tried setting PromptBehavior to `PromptBehavior.Never` without clearing token cache and same older access token is returned.
With the configuration PromptBehavior to `PromptBehavior.Never` when I tried to hard refresh access token after clearing token cache I got the exception 

> PromptBehavior.Never is supported in SSO mode only (null or application's callback URI as redirectUri)
> Parameter name: redirectUri

Please let me know how I can proceed from here.

**Comment by jmprieur** [comment]
Did you try with AcquireTokenSilentAsync? 
Otherwise, we recomment to move to MSAL.NET (which GA-ed). 
The model in MSAL.NET is clearer, that you call AcquireTokenSilent to get a token from the cache, and if you don't, you have the interaction. You can also force another token.
