### ISSUE TITLE
MSAL: Embedded browser shows only black website

### ISSUE THREAD

**Issue by KarinBerg** [AzureAD/azure-activedirectory-library-for-dotnet#1141]
Hello,
I use the latest nuget from MyGet to test the fallback when Chrome is not available.
Unfortunately, on my Android devices embedded web view shows only a black page. I attached a screenshot:
![screenshot_20180720-151401](https://user-images.githubusercontent.com/20112746/43004471-2c458ea4-8c30-11e8-9de0-64b55ec01637.png)

Can you tell me why I don't see my Azure B2C signup page?

Used devices:
Samsung Galaxy S6 (SM-G920F) with Android 7.0 (newest software update)
Samsung Galaxy S8 (SM-G950F) with Android 8.0.0 (newest software update)
LG Google Nexus 5X with Android 8.1.0 (newest software update)

**Comment by jmprieur** [comment]
thanks @KarinBerg 
do you have repro steps (like a sample we could try?)
Thanks!

**Comment by jennyf19** [comment]
@KarinBerg - Thanks for letting us know. Do you have this in the `MainActivity.cs` file for the Android app?
 ```
protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
{
       base.OnActivityResult(requestCode, resultCode, data);
       AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, ResultCode, data);
}
```
Also, can you please open this issue in the [MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issueshttps://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues) - Thank you.

**Comment by KarinBerg** [comment]
@jennyf19 & @jmprieur: 
Sorry, I used not the newest package. After @jmprieur explained it to me I used the correct one which is working :)

Sorry, for making trouble :)

**Comment by jennyf19** [comment]
@KarinBerg - that's great! Thanks for letting us know that it is working. If you run into any other issues, let us know. 
Out of curiosity, which nuget package were you using?
