### ISSUE TITLE
PublicClientApplication.Remove() is not removing user from TokenCache

### ISSUE THREAD

**Issue by KarinBerg** [AzureAD/azure-activedirectory-library-for-dotnet#1142]
Hello,
I use MSAL in my Xamarin.Forms app (targeting iOS and Android).
I have the following SignOut() Method:
```
public void SignOut()
{
       foreach (var user in publicClientApplication.Users)
        {
              publicClientApplication.Remove(user);
        }
}
```

But after this foreach the user list still contain a user.

I use the MyGet package "2.0.0-internal20001dev". In the lastest releases 1.1.4-preview0002 version on nuget.org this works.

Do I have to use another version? 

P.S.: Do you know when there is a new official release?

**Comment by jennyf19** [comment]
@KarinBerg Thanks - Just to clarify...it does not work with this package: "2.0.0-internal20001dev" but works with this package "1.1.4-preview0002"

Our next release is being intensively tested right now, will be v2-preview.

**Comment by KarinBerg** [comment]
Yes, that is correct. 
Works not with “2.0.0-internal20001dev” and works with “1.1.4-preview0002”
