### ISSUE TITLE
Feature request: change User-Agent header

### ISSUE THREAD

**Issue by alexrainman** [AzureAD/azure-activedirectory-library-for-dotnet#1144]
When you do an ADAL authenticate it will redirect you to ADFS. If you are on a corporate network then, if the client string sent by the request to ADFS matches various strings held in ADFS, it assumes the client can negotiate NTLM / Kerberos. If it does not match these it will offer the form based logon.

ADAL will not work when the user is on the corporate network unless i can change the User-Agent header to something that not matches the ones held in ADFS.

**Comment by jmprieur** [comment]
@alexrainman : sorry if my question is native. Isn't it possible for the ADFS admin to add user agent strings?

**Comment by alexrainman** [comment]
Actually i want the opposite thing. I want to use a random User-Agent not registered on ADFS so i can see the form based logon instead of ADFS trying to do WIA for me when im inside the corporate network.

**Comment by alexrainman** [comment]
Thats when i am inside the corporate network.

**Comment by alexrainman** [comment]
They have to keep Safari and Chrome in ADFS so users can use these browsers and negotiate kerberos when they are inside the corporate network but from the mobile app, i need to see the form based logon to be able to authenticate as these accounts only exists on AAD.

**Comment by alexrainman** [comment]
Any help on this? How i can cahnge User-Agent? Please?

**Comment by jmprieur** [comment]
you cannot for the moment, @alexrainman. We are discussing the best way to enable this:
cc; @bgavrilMS @henrik-me @danieldobalian

**Comment by alexrainman** [comment]
@jmprieur without this we cannot move forward. Do you have an idea when?

**Comment by henrik-me** [comment]
@alexrainman : This is not on our current roadmap. Can't give an ETA at the moment. 

CC: @jmprieur

**Comment by alexrainman** [comment]
I found a workaround for now.

On my main Application:

```cs
public void OnActivityResumed(Activity activity)
{
    if (activity.Title == "Sign in")
    {
        var frame = activity.FindViewById<FrameLayout>(Android.Resource.Id.Content);

        if (frame != null)
        {
            var layout = (RelativeLayout)frame.GetChildAt(0);

            if (layout != null)
            {
                var webView = (WebView)layout.GetChildAt(0);

                if (webView != null)
                {
                    //"Mozilla/5.0 (Linux; Android 6.0.1; SM-N920P Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36 PKeyAuth/1.0";
                    webView.Settings.UserAgentString = webView.Settings.UserAgentString.Replace("Chrome", "Safari");
                }
            }
        }
    }
}
```

**Comment by henrik-me** [comment]
Creative solution. thanks for bringing the workaround back here allowing for others to see this.

**Comment by jmprieur** [comment]
Done in MSAL.NET
Won't fix in ADAL.NET

the creative workaround explained above can be used :)
