### ISSUE TITLE
"Method not found: AcquireToken(System.String, Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate)

### ISSUE THREAD

**Issue by levalencia** [AzureAD/azure-activedirectory-library-for-dotnet#1150]
I followed the following document to create a x509 certificate with the Azure AD App Registration.

https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread

I generated the .pfx file, set the password, and I also registered the app in my tenant Azure AD, and then updated the manifest with the keycredentials section.

Then, I am creating a WEB API that receives some parameters, including the .pfx file.

  

     [HttpPut]
            public async Task<IHttpActionResult> PutTenant([ModelBinder(typeof(TenantModelBinder))] Tenant tenant)
            {
                try
                {               
                    var cert = new X509Certificate2(tenant.CertificateFile, tenant.CertificatePassword, X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable);
    
                    using (var cc = new OfficeDevPnP.Core.AuthenticationManager().GetAzureADAppOnlyAuthenticatedContext(tenant.SiteCollectionTestUrl, tenant.ApplicationId, tenant.TenantDomainUrl, cert))
                    {
                        cc.Load(cc.Web, p => p.Title);
                        cc.ExecuteQuery();
                    };
                }
                catch (System.Exception)
                {
                    return BadRequest("Configuration Invalid");
                }

I am using the bytearray coming from the HttpRequest to create the x509 object.

However I get this error:

    Message	"Method not found: 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResult Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireToken(System.String, Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate)'."	string

Stacktrace:

    at OfficeDevPnP.Core.AuthenticationManager.<>c__DisplayClass36_0.<GetAzureADAppOnlyAuthenticatedContext>b__0(Object sender, WebRequestEventArgs args)\r\n   at Microsoft.SharePoint.Client.ClientRuntimeContext.OnExecutingWebRequest(WebRequestEventArgs args)\r\n   at Microsoft.SharePoint.Client.ClientContext.GetWebRequestExecutor()\r\n   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()\r\n   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()\r\n   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()\r\n   at TenantManagementWebApi.Controllers.TenantController.<PutTenant>d__2.MoveNext() in C:\\Users\\levm3\\source\\repos\\TenantManagementWebApi\\Controllers\\TenantController.cs

The error is thrown in the executequery

really clueless here.

Update:

I noticed this in my web.config

     <dependentAssembly>
            <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
            <bindingRedirect oldVersion="0.0.0.0-3.19.5.13701" newVersion="3.19.5.13701"/>
          </dependentAssembly>

and this on my packages.config

      <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="3.19.5" targetFramework="net461" />

issue also posted here:
https://stackoverflow.com/questions/51554510/method-not-found-acquiretokensystem-string-microsoft-identitymodel-clients-a

**Comment by jennyf19** [comment]
@levalencia Which platform are you using? The StackOverFlow link does not work for me.

**Comment by levalencia** [comment]
Sorry wrongnlink

https://stackoverflow.com/questions/51200031/the-method-not-found-acquiretokensystem-string-microsoft-identitymodel-client

**Comment by jennyf19** [comment]
@levalencia Thanks - which  platform?

**Comment by levalencia** [comment]
. Net web api

**Comment by jmprieur** [comment]
@levalencia I've asked a few questions on the SO question. I'm wondering if you would be using 2 nuget packages that use conflicting versions of ADAL (ADAL v2.0 and ADAL v3) ?

**Comment by levalencia** [comment]
I just answered there, lets keep the conversation in SO.

**Comment by jmprieur** [comment]
Closing this issue.
