### ISSUE TITLE
Full .NET Clear Browser Cache to force a full log out?

### ISSUE THREAD

**Issue by benhysell** [AzureAD/azure-activedirectory-library-for-dotnet#1181]
Question - How to force user to enter email and password on every AcquireTokenAsync call.

Why this is needed - We are using the library on a shared workstation with multiple users accessing a resource in Azure from a .NET desktop application.  Users arrive, use the application, and then leave.  If the next user types in someone else's email address they can acquire that person's token, and effectively steal their identity.

Given: 
```
_clientApp.TokenCache.Clear();
```

I can clear the token cache, however next time I come around to authenticate my user:
```
_clientApp.AcquireTokenAsync(webApiId, clientId, new Uri(@"https://localhost"), new PlatformParameters(PromptBehavior.Always))
```

The user is prompted to enter their email address, but if they had done a log in recently they are not challenged for a password.  A bad actor can just type in someone else's email address, effectively stealing their identity.
 
Is there updated guidance on how to force password challenge on every log in attempt?  The best I'm finding is two year old questions on StackOverflow with the comment 'its on the backlog'.

[https://stackoverflow.com/questions/37792244/logout-does-not-work-when-using-microsoft-authentication-library-msal](https://stackoverflow.com/questions/37792244/logout-does-not-work-when-using-microsoft-authentication-library-msal)

[https://stackoverflow.com/questions/47517434/how-to-sign-out-from-azure-ad-2-0-msal-in-a-desktop-application](https://stackoverflow.com/questions/47517434/how-to-sign-out-from-azure-ad-2-0-msal-in-a-desktop-application)

**Comment by jmprieur** [comment]
@benhysell :are you using ADAL.NET or MSAL.NET ? (this is the repo for ADAL.NET and you provided links for MSAL.NET, but code for ADAL.NET)
If you are using MSAL.NET, the library currently uses the system web browser, and therefore you can sign-out directly from the browser.
Also adding @xerners who is currently working on enabling the shared device scenario (where indeed signout is absolutely required)

**Comment by benhysell** [comment]
@jmprieur I just checked my NuGet - Microsoft.IdentityModel.Clients.ActiveDirectory 3.19.8...that appears to be ADAL.NET?  

Sorry for the confusion with regards to StackOverflow.  I'm having a hard time finding a single source of truth for ' this is the recommended path to ensure log out in shared device scenarios.'

How far down the backlog does this scenario live?  Next release, Q1 of this year, Q4 of 2042?

**Comment by jmprieur** [comment]
@benhysell :we are heads down working on MSAL.NET (currently in preview, but we want to GA soon). Signout is will probably be available in MSAL before ADAL.NET

I suggest you check if MSAL could not work for you: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal

**Comment by benhysell** [comment]
@jmprieur I'll head over there today.

If I understand correctly, sign out for multiple devices is not supported over there as well?  Would this be the proper issue to track that:
[https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/589](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/589)

Appreciate the responses, I was crawling all over the web last night trying to find guidance, and I wasn't finding anything especially clear.

**Comment by jmprieur** [comment]
Yes, @benhysell this is the issue to track, you are right.
Now, MSAL being the system browser, you can also probably sign-out in the browser, which signs out from every app

**Comment by jmprieur** [comment]
Closing this issue as this is not something we'll do in ADAL.NET (but **we'll do it in MSAL.NET**)
