### ISSUE TITLE
AdalSilentTokenAcquisitionException on consent required

### ISSUE THREAD

**Issue by bretthackermsft** [AzureAD/azure-activedirectory-library-for-dotnet#1184]
Having added another API to a previously consented app registration, I'd like to monitor for exceptions and redirect the user to re-consent. However the error that's thrown(AdalSilentTokenAcquisitionException) indicates that no token was found in the cache, while the inner exception (AdalServiceException) correctly notes that the user hasn't consented. Would it be possible for that inner exception to be re-thrown so we don't have to inspect? The problem in this situation is being mis-identified: there WAS a token in the cache.
![adalexception](https://user-images.githubusercontent.com/24515695/43920129-ac0f32ae-9bdd-11e8-8258-d5ba58a7546e.png)

**Comment by jmprieur** [comment]
@bretthackermsft : I don't know if this is an option for you to update to MSAL.NET, but from MSAL.NET 2.2.0, we now expose the body in the MsalServiceException in addition to the HttpResponseHeaders, which should solve your issue?

**Comment by bretthackermsft** [comment]
Heh...I'd prefer not to at this stage. I'm just peeking at the innerException inside AdalSilentTokenAcquisitionException now - not a huge workaround, just struck me as odd that I couldn't trap the more meaningful error, since there's an explicit exception object for it and it's obviously throwing farther down the stack.
