### ISSUE TITLE
calling AcquireTokenSilentAsync in xamarin forms application throwing object reference error

### ISSUE THREAD

**Issue by suresh-dev** [AzureAD/azure-activedirectory-library-for-dotnet#1194]
I am using ADAL 3.19.8 nuget package for AAD authentication.

i was able to get authentication token and login to the application. after relaunching the application I am trying to make request to get the access token by using the below code, it throw an object reference error
at AcruireTokenSilentAsync method.

```
 var authContext = new AuthenticationContext(authority);
            AuthenticationResult authResult;
            try
            {
                if (authContext.TokenCache.ReadItems().Any())
                    authContext = new AuthenticationContext(authContext.TokenCache.ReadItems().First().Authority, authContext.TokenCache);

                authResult = await authContext.AcquireTokenSilentAsync(resource, clientId);

                return authResult;
            }
            catch (AdalSilentTokenAcquisitionException ex)
            {
                var uri = new Uri(returnUri);
                var platformParams = new PlatformParameters((Activity)Forms.Context);
                authResult = await authContext.AcquireTokenAsync(authority, clientId, uri, platformParams);
                return authResult;
            }
```

can anyone please suggest any ideas to overcome this

**Comment by jmprieur** [comment]
Can you please share the exact location of the exception? 
Did you see the code in the following section of the conceptual documentation? https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AuthenticationContext-the-connection-to-Azure-AD#case-when-the-authority-is-not-known-in-advance
BTW, in your code, you should probably use intermediate variables (for example `authContext.TokenCache`): you could check if they are null before accessing members.

**Comment by suresh-dev** [comment]
I am getting exception while the debugger hits at the below line
authResult = await authContext.AcquireTokenSilentAsync(resource, clientId);

and TokenCache is not null

**Comment by jmprieur** [comment]
@suresh-dev : do you have a repro sample?

**Comment by suresh-dev** [comment]
Actually i don't have repro sample, code which i have posted is a bit of my app.

i can give the methods which i am using for o365 login and acquire token silent 
```

        public async Task<AuthenticationResult> AcquireRefreshTokenAsync(string authority, string resource, string clientId, string aadUser, string returnUri)
        {
            var authContext = new AuthenticationContext(authority);
            AuthenticationResult authResult;
            try
            {
                if (authContext.TokenCache.ReadItems().Any())
                    authContext = new AuthenticationContext(authContext.TokenCache.ReadItems().First().Authority, authContext.TokenCache);

                authResult = await authContext.AcquireTokenSilentAsync(resource, clientId);

                return authResult;
            }
            catch (AdalSilentTokenAcquisitionException ex)
            {
                var uri = new Uri(returnUri);
                var platformParams = new PlatformParameters((Activity)Forms.Context);
                authResult = await authContext.AcquireTokenAsync(authority, clientId, uri, platformParams);
                return authResult;
            }
            catch (AdalException ex)
            {
                return null;
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public async Task<AuthenticationResult> AuthenticateAsync(string authority, string resource, string clientId, string returnUri)
        {
            var authContext = new AuthenticationContext(authority);
            if (authContext.TokenCache.ReadItems().Any())
                authContext = new AuthenticationContext(authContext.TokenCache.ReadItems().First().Authority, authContext.TokenCache);

            var uri = new Uri(returnUri);
            var platformParams = new PlatformParameters((Activity)Forms.Context);
            var authResult = await authContext.AcquireTokenAsync(resource, clientId, uri, platformParams);

        

            return authResult;
        }
```

**Comment by jennyf19** [comment]
@suresh-dev Can you try with [ADALv4.2.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v4.2.0)?

**Comment by henrik-me** [comment]
Is it correct to assume that the code you have above is Android specific?

@suresh-dev, I'm closing the issue, however pls. feel free to re-open if upgrading to ADAL v4.3 didn't address the issue. 

There seems to be a few things, which I'm not sure will truyly work for you as you are re-using variable on other object. I recommend as Jean-Marc pointed out that you store the tokenCache in a separate object and pass that in. The same with the Authority. Our standard pattern for calling silent can be found here:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token
