### ISSUE TITLE
SharePoint REST Api needs user context, but Adal library for .NET Core does not support username + password anymore

### ISSUE THREAD

**Issue by web265p3** [AzureAD/azure-activedirectory-library-for-dotnet#1204]
Accessing the SharePoint REST API does not work with Client Credentials. In this case you need a user context. I wrote a service, accessing SPO REST in .NET Core 2.0, but it seems, that UserPasswordCredential class is not supported in .NET Core ADAL library anymore.
I know that using username and password credentials is not recommendet, but for SharePoint services I do not see another way yet. 
What would you recommend me?

I wrote my own code to get a SharePoint token like this:

> 
>      HttpClient client = new HttpClient();
>                 string tokenEndpoint = "https://login.microsoftonline.com/" + tenantId + "/oauth2/token";
>                 var body = "resource=" + SharePointResource + "&client_id=" + SPClientId + "&grant_type=password&username=" + _UserName + "&password=" + _Password;
>                 var stringContent = new StringContent(body, Encoding.UTF8, "application/x-www-form-urlencoded");
>                 var result = await client.PostAsync(tokenEndpoint, stringContent).ContinueWith<string>((response) =>
>                 {
>                     return response.Result.Content.ReadAsStringAsync().Result;
>                 });
>                 JObject jobject = JObject.Parse(result);
>                 var token = jobject["access_token"].Value<string>();
>                 SharePointToken = token;    

This works, but now I cannot use the Token-Cache anymore and for every single call I generate a new token. :( And anyway: It does not seem very professional to me.

**Comment by henrik-me** [comment]
Username/Password was never supported in ADAL for .NET Core. It's interesting that you say that it worked for you though. We have the support in MSAL, thus I recommend that you move to MSAL.

**Comment by jmprieur** [comment]
MSAL.NET supports it
Won't fix for ADAL.NET
