### ISSUE TITLE
Distributed TokenCache backed by Azure Key Vault

### ISSUE THREAD

**Issue by mmaitre314** [AzureAD/azure-activedirectory-library-for-dotnet#1209]
More a guidance question than an issue: has anyone implemented a distributed `TokenCache` serializing to Key Vault? Any guidance and code samples available?

I went through docs here, which is almost what we need: 
https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/token-cache#encrypting-cached-tokens
We use Web Apps in multiple regions for high-availability, so token encryption looks like a challenge and using Key Vault instead of Redis should avoid that issue.

I was also wondering whether the opaque `byte[]` to serialize is guaranteed to be backward compatible when upgrading the ADAL.NET Nuget package in the future. I would like to avoid all our unattended jobs to start failing when upgrading the Nuget package because they cannot read refresh tokens anymore.

One thing that seems missing is async versions of `AfterAccess`, `BeforeAccess`, and `BeforeWrite` to avoiding blocking during network calls. We hit hard-to-debug deadlocks when blocking in ASP.NET.

**Comment by bgavrilMS** [comment]
Got it, so this is a feature request for async cache extensibily methods.

**Comment by jmprieur** [comment]
@jmprieur

**Comment by jmprieur** [comment]
The async serialization methods are available in MSAL.NET 4.0
Won't fix for ADAL
