### ISSUE TITLE
Changelog doesn't contain details for versions > 3.17.2

### ISSUE THREAD

**Issue by Yonisha** [AzureAD/azure-activedirectory-library-for-dotnet#1213]
Given that version 3.19.8 was released, the changelog is incomplete.

**Comment by jmprieur** [comment]
Hello @Yonisha : I don't understand your question. Can you provide repro steps (where to look at):
We have explained all the changes in each release: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases ?

**Comment by Yonisha** [comment]
Sorry jmprieur, hit enter too soon. closing
