### ISSUE TITLE
PiiLoggingEnabled causes duplicate logs

### ISSUE THREAD

**Issue by sliekens** [AzureAD/azure-activedirectory-library-for-dotnet#1215]
I implemented a logging callback according to the example in the wiki.

My code:

```csharp
public void ConfigureLogCallback(bool showPii)
{
    LoggerCallbackHandler.PiiLoggingEnabled = showPii;
    LoggerCallbackHandler.LogCallback = (logLevel, message, containsPii) =>
    {
        switch (logLevel)
        {
            case LogLevel.Information:
                _logger.LogInformation(message);
                break;
            case LogLevel.Warning:
                _logger.LogWarning(message);
                break;
            case LogLevel.Error:
                _logger.LogError(message);
                break;
            case LogLevel.Verbose:
            default:
                _logger.LogDebug(message);
                break;
        }
    };
}

```

This works but I noticed that I get duplicate logs if I enable PII logging.
- one log without PII
- one log including PII

Sample: (PII is redacted, highlighted in bold)
> 2018-08-21T11:07:58.4531944Z: fb1d13b5-e441-441f-8e77-0a61f32c391d - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.8.16603', file version '3.19.50615.2240' and informational version '60156f308468ccbe517904f2bb43a8a763434aee' is running...
> 
> 2018-08-21T11:08:02.6246715Z: fb1d13b5-e441-441f-8e77-0a61f32c391d - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.8.16603', file version '3.19.50615.2240' and informational version '60156f308468ccbe517904f2bb43a8a763434aee' is running...
 
> 2018-08-21T11:08:03.7379710Z: fb1d13b5-e441-441f-8e77-0a61f32c391d - LoggerBase.cs: === Token  Acquisition started:
>       CacheType: null
>        Authentication Target: User
>        , Authority Host: login.microsoftonline.com
>
> 2018-08-21T11:08:34.2839114Z: fb1d13b5-e441-441f-8e77-0a61f32c391d - LoggerBase.cs: === Token  Acquisition started:
>        **Authority: https://login.microsoftonline.com/redacted.onmicrosoft.com/oauth2/
>        Resource: https://graph.microsoft.com
>        ClientId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx**
>        CacheType: null
>        Authentication Target: User

> 2018-08-21T11:08:35.9259439Z: fb1d13b5-e441-441f-8e77-0a61f32c391d - LoggerBase.cs: Username provided in user assertion - True
> 
> 2018-08-21T11:11:38.7018460Z: fb1d13b5-e441-441f-8e77-0a61f32c391d - LoggerBase.cs: Username provided in user assertion - True
> 

> 2018-08-21T11:20:03.8119659Z: fb1d13b5-e441-441f-8e77-0a61f32c391d - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 8/21/2018 11:47:04 AM +00:00
>
> 2018-08-21T11:20:05.0271802Z: fb1d13b5-e441-441f-8e77-0a61f32c391d - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 8/21/2018 11:47:04 AM +00:00**Access Token Hash: AIQ...redacted...oY=**

**Comment by jmprieur** [comment]
Thanks for your feedback, @StevenLiekens 
this is by (questionable :-) ) design.
See see the second bullet point of https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net#new-way-of-logging-controlling-pii-adalnet--318

**Comment by sliekens** [comment]
Oh okay. I'll just do this then:

```csharp
LoggerCallbackHandler.LogCallback = (logLevel, message, containsPii) =>
{
    if (LoggerCallbackHandler.PiiLoggingEnabled && !containsPii)
    {
        // ignore logs with a different PII setting
        return;
    }
    switch (logLevel)
    {
        case LogLevel.Information:
            _logger.LogInformation(message);
            break;
        case LogLevel.Warning:
            _logger.LogWarning(message);
            break;
        case LogLevel.Error:
            _logger.LogError(message);
            break;
        case LogLevel.Verbose:
        default:
            _logger.LogDebug(message);
            break;
    }
};
```

**Comment by jennyf19** [comment]
@StevenLiekens 
Double logging has been removed in  [MSAL v2.2.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.2.0) 
cc: @MarkZuber

**Comment by sliekens** [comment]
@jennyf19  Actually I think it's kind of neat that you can have both PII and scrubbed logging enabled at the same time. I was just confused about why that was happening (because of the strange API design).
