### ISSUE TITLE
msal can't get token with embedded browser

### ISSUE THREAD

**Issue by cansado2930** [AzureAD/azure-activedirectory-library-for-dotnet#1218]
Hi,
I have built the dev branch in order to use the MSAL SDK for android because I need to use the embedded browser because some users haven’t installed chrome. I have seen that steps for external browser works perfectly. But If I change the line to App.UIParent = new UIParent(this, true); then it doesn’t works. The flow for users works well, it opens the embedded browser and I can enter email, pass and accept permissions, but then, when the browser is closed, the code can’t get the token. It is null.
Do I have to do some additional step in addition of changing the before line? 
Thank you

**Comment by jennyf19** [comment]
@cansado2930 - Could you open this in the [MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues)? 
Can you provide us with the [MSAL logs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#logging-in-msalnet). Are you seeing this with an Android device and/or simulator? Which Android version? Also, can you share the code you are using for the acquire token call?

**Comment by cansado2930** [comment]
Ok, I'm going to change it to other repo.
