### ISSUE TITLE
"invalid_grant" error was thrown when trying to pass usertoken as on-behalf of token to Microsoft Graph API.

### ISSUE THREAD

**Issue by vedeevi** [AzureAD/azure-activedirectory-library-for-dotnet#1234]
Hi All,

We having an issue when trying to generate a AAD token using UserAssertion and client credentials for targeting to Graph API as resource. Following are our configurations which were used to send the request...

https://login.microsoftonline.com:443/{tenantId}/oauth2/v2.0/token
With this parameters :
client_id: app id declare inside Azure
client_secret : secret declare for the app inside azure
assertion : user token obtain AAD during sign-in to application
scope : https://graph.microsoft.com/user.read offline_access
requested_token_use : on_behalf_of
grant_type : urn:ietf:params:oauth:grant-type:jwt-bearer
client_assertion_type : urn:ietf:params:oauth:client-assertion-type:jwt-bearer

response :
{"error":"invalid_grant","error_description":"AADSTS50013: Assertion contains an invalid signature. [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: 'EFF66E7F5B6F9302F161A1D2DEAEA5523518206C', Found key 'Start=06/21/2018 00:00:00, End=06/21/2020 00:00:00']\r\nTrace ID: 6161cc29-60c1-4264-8469-342152201c00\r\nCorrelation ID: 95d6c4b6-a414-4510-b131-3775af8c1801\r\nTimestamp: 2018-08-28 09:33:19Z","error_codes":[50013],"timestamp":"2018-08-28 09:33:19Z","trace_id":"6161cc29-60c1-4264-8469-342152201c00","correlation_id":"95d6c4b6-a414-4510-b131-3775af8c1801"}

Please let us know what is the issue with this...

Thanks & Regards,
Vedeevi

**Comment by jmprieur** [comment]
@vedeevi : how did you get your JWT token in the application calling your Web API?
Do you have repro steps?

**Comment by vedeevi** [comment]
@jmprieur, This is a Bot Framework API and we get the user token from Cortana channel. We are using this userToken to generate a on-bhehalf-of token to Graph API to get other details of the user. When we are trying to do get this Graph API token, we are getting above mentioned error "invalid_grant", "error_description":"AADSTS50013: Assertion contains an invalid signature. [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: 'EFF66E7F5B6F9302F161A1D2DEAEA5523518206C',

**Comment by jmprieur** [comment]
@vedeevi : Do I read correctly that the authority you used is: https://login.microsoftonline.com:443/{tenantId}/oauth2/v2.0/token ?

It should be **only** https://login.microsoftonline.com/{tenantId}

**Comment by jmprieur** [comment]
Closing as I believe we've answered. Feel free to reopen

**Comment by jmprieur** [comment]
Also ADAL.NET supports the v1.0 endpoint, not the v2.0 endpoint. It cannot consume a v2.0 token

**Comment by vsabado** [comment]
> @jmprieur, This is a Bot Framework API and we get the user token from Cortana channel. We are using this userToken to generate a on-bhehalf-of token to Graph API to get other details of the user. When we are trying to do get this Graph API token, we are getting above mentioned error "invalid_grant", "error_description":"AADSTS50013: Assertion contains an invalid signature. [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: 'EFF66E7F5B6F9302F161A1D2DEAEA5523518206C',

Hello, I'm trying to do the same as you are. What was the fix that worked for you?
