### ISSUE TITLE
Silent exception in Xamarin Android

### ISSUE THREAD

**Issue by arielbh** [AzureAD/azure-activedirectory-library-for-dotnet#1240]
**Which Version of ADAL are you using ?**
ADAL 3.19.8

**Which platform has the issue?**
Xamarin android

**What authentication flow has the issue?**
Mobile - Android

**Expected behavior**
When I'm calling Microsoft Graph on an Android Device, I expect my call to return successfully with available token which was received via the login flow of the ADAL 

**Actual behavior**
Calling await client.GetByteArrayAsync(uri).ConfigureAwait(false); with standard HTTPClient hangs. 
In the log I can see the following info:
27:39.340 E/        (12987): 2018-08-30T14:27:39.3383080Z: 85d02ace-8399-4005-b9f0-90a03fc6619e - LoggerBase.cs: Exception type: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException, ErrorCode: Authenticator cancels the request ---> Exception type: System.ArgumentException
08-30 17:27:39.340 E/        (12987):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerProxy.GetBrokerOptions (Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.AuthenticationRequest request) [0x00072] in <191c0f636ed643539057bc17e12c857b>:0 
08-30 17:27:39.340 E/        (12987):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerProxy.GetIntentForBrokerActivity (Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.AuthenticationRequest request, Android.App.Activity callerActivity) [0x00002] in <191c0f636ed643539057bc17e12c857b>:0 

Thanks!

**Comment by jmprieur** [comment]
@arielbh 
The exception is saying that:
- the device has a broker installed (Microsoft Authenticator)
- Your application is leveraging a broker
- Authenticator canceled the call. 

This could be because the user (you?) canceled sign-in in Authenticator? 
Or is there an update of authenticator available for Android?

cc: @danieldobalian @trwalke @jennyf19  in case they have ideas

**Comment by arielbh** [comment]
@jmprieur The device opens up the sign-in dialog if needed, other requests that uses the auth-token works. Only when I try to access the Microsoft Graph with the same authenticator it fails silently (without trying to open UI on the device).

**Comment by jmprieur** [comment]
could you please try with ADAL.NET 4.0.0-preview to see if you see the same?

**Comment by jmprieur** [comment]
Also, could you please check the broker logs (in the help section of authenticator).
If you want, you could send the logs to powerlift and send me the code (Jean-Marc.Prieur at Microsoft.com)

**Comment by bgavrilMS** [comment]
Closing, please reopen if you have more info.

**Comment by trwalke** [comment]
I have assisted ariel in resolving his first issue, however, he has run into another issue after the fix.
From Ariel: "I've got inconsistent behavior between different users and different devices regarding successfull silent retrieval of the token.
I'm including 2 Android Logs. The first is a failing and you can see the exception:
09-27 13:54:05.081 I/        (11137): 2018-09-27T10:54:05.0807840Z: 1eb563a5-822a-493c-9ce7-66e41ef8e78b - LoggerBase.cs: No matching token was found in the cache[0:] Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException: Failed to acquire token silently as no token was found in the cache."

[Logs.txt](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/files/2425141/Logs.txt)

**Comment by trwalke** [comment]
The customer experienced issues with the redirect URI not being consistent across different machines. Here is a link to our wiki describing the situation
(https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Leveraging-brokers-on-Android-and-iOS#redirect-uri-during-development).

**Comment by jmprieur** [comment]
@trwalke : thanks for this. I understand that this issue is therefore closed?
