### ISSUE TITLE
AuthenticationResult.Deserialize： AuthenticationResult does not contains a definition for Deserialize

### ISSUE THREAD

**Issue by QiyuanHU** [AzureAD/azure-activedirectory-library-for-dotnet#1270]
**Which Version of ADAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
ADAL 3.19.4.11002

**Which platform has the issue?**
net45

**Repro**
AuthenticationResult does not contains a definition for Deserialize

```csharp
public static AuthenticationResult CreateAuthenticationResult(string tenantId, string userName, string uniqueId, DateTimeOffset offset, string tokenString = TokenString)
        {
            JsonSerializer serializer = new JsonSerializer();
            serializer.DateParseHandling = DateParseHandling.DateTimeOffset;

            JsonSerializerSettings microsoftDateFormatSettings = new JsonSerializerSettings
            {
                DateFormatHandling = DateFormatHandling.MicrosoftDateFormat
            };

            var microsoftJson = JsonConvert.SerializeObject(offset.DateTime, microsoftDateFormatSettings);
            var serializedString = string.Format(tokenString, tenantId, userName, uniqueId, microsoftJson, offset.Offset.Minutes);
            return AuthenticationResult.Deserialize(serializedString);
        }
```

**Expected behavior**
We can create the AuthenticationResult using AuthenticationResult.Deserialize

**Actual behavior**
AuthenticationResult.Deserialize is not defined

**Possible Solution**

**Additional context/ Logs / Screenshots**
We just upgraded to this version 3.19.4.10022, is this method got deprecated? Did not find any doc for this, if so, how can I create AuthenticationResult. This is for our test purpose only

**Comment by bgavrilMS** [comment]
@QiyuanHU 

What version did you upgrade from? 2.x ? Deserialize is not part of the public API in 3.x, however this object is deserialized from a json object we get from the STS, you can have a look at our code to see how we deserialize it etc. 

https://github.com:443/AzureAD/azure-activedirectory-library-for-dotnet.git/blob/dev/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationResult.cs#L38

**Comment by jmprieur** [comment]
@QiyuanHU : did you read this: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Token-cache-serialization ?
