### ISSUE TITLE
Cross-thread operation exception when setting ownerWindow in PlatformParameters 

### ISSUE THREAD

**Issue by rhythmnewt** [AzureAD/azure-activedirectory-library-for-dotnet#1277]
**Which Version of ADAL are you using ?**
ADAL 3.18.0 and later

**Which platform has the issue?**
net462

**What authentication flow has the issue?**
* Desktop 
    * [ X] Interactive
 
Other? - please describe;

**Repro**
Create new WinForms project targeting .NET 462 and add the following code to handle Load event.
```csharp
   private async void Form1_Load(object sender, EventArgs e)
        {
            WindowState = FormWindowState.Normal;

            //fill in as necessary for correct auth
            const string resource = "https://www.myresource.com/";
            const string clientId = "client_id_guid";
            const string redirectUri = "https://myredirecturi";
            const string authority = "https://login.windows.net/myauthority/oauth2/token";

            var context = new AuthenticationContext(authority, true, TokenCache.DefaultShared);

            var result = await context.AcquireTokenAsync(resource, clientId,
                new Uri(redirectUri),
                new PlatformParameters(PromptBehavior.SelectAccount, this));
        }
```

**Expected behavior**
Windows form is shown in the background with the browser login window in the foreground. The browser login window is the child of the windows form.

**Actual behavior**
Exception is thrown: 
System.InvalidOperationException: 'Cross-thread operation not valid: Control 'Form1' accessed from a thread other than the thread it was created on.'

**Possible Solution**

**Additional context/ Logs / Screenshots**
[WindowsFormsApp1.zip](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/files/2425029/WindowsFormsApp1.zip)

If you downgrade the library to 3.17.3 there is no issue with the cross-threading.

**Comment by rhythmnewt** [comment]
Bueller?

**Comment by MarkZuber** [comment]
@rhythmnewt 

Still investigating.  But I have a short term workaround that should hopefully get you unblocked.  

When you construct the PlatformParameters, send in "null" instead of "this" for the owner window.  The owner window is only used for trying to center the browser around the owner app window.  If it's null, then the browser will be centered on the current screen.  That should be the only difference in functionality and I'll get back to this thread once I've gotten deeper on the issue with ownerWindow.

**Comment by MarkZuber** [comment]
Pull request for fix is out:  https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1328

**Comment by henrik-me** [comment]
fixed in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v4.3.0

**Comment by henrik-me** [comment]
This has now been released

**Comment by rhythmnewt** [comment]
@MarkZuber the issue was around the modality of the window, don't want the user to click in the app screen while the login flow is active.

Thank you all for taking care of it!
