### ISSUE TITLE
ADAL 3.19.x leaks `System.Net.Http.HttpRequestException` from Windows Integrated Authentication flow

### ISSUE THREAD

**Issue by mjcheetham** [AzureAD/azure-activedirectory-library-for-dotnet#1285]
**Which Version of ADAL are you using ?**
ADAL 3.19.4, but the same code path/problem is present in 3.19.8 (the latest in the 3.x line)

**Which platform has the issue?**
net45

**What authentication flow has the issue?**
* Desktop 
    * [x] WIA

**Repro**
This one might be hard to repro as it requires a domain joined machine with a _broken_ set of domain controllers such that the following error occurs:
> "The system cannot contact a domain controller to service the authentication request".

The ADAL library call below, in the aforementioned setup, leaks an exception which is not an `AdalException` nor an `AdalServiceException`.

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/60156f308468ccbe517904f2bb43a8a763434aee/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/AuthenticationContextIntegratedAuthExtensions.cs#L48

**Expected behavior**
The call to `AcquireTokenAsync` throws an `AdalException`.

**Actual behavior**
The call to `AcquireTokenAsync` throws an `System.Net.Http.HttpRequestException`.

**Possible Solution**
Ensure the call to `System.Net.Http.HttpClient::SendAsync` in the code below (line 127 in HttpClientWrapper.cs which exists in a `try-catch` already) catches all possible exceptions, and wraps them in an `AdalException`:

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/60156f308468ccbe517904f2bb43a8a763434aee/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Http/HttpClientWrapper.cs#L103-L132

In the stack for this error (see the 'additional context' section below) there are several opportunities to `catch` and handle/wrap such an exception. My suggestion is the `catch (Exception)` at the lowest level of ADAL to also prevent any other arbitrary exception from leaking without being wrapped in an `AdalException`. Another possibility would be to `catch` an exception in the WIA/IWA specific code paths, such as here:

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/60156f308468ccbe517904f2bb43a8a763434aee/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/WsTrust/WsTrustRequest.cs#L103

..or here:

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/60156f308468ccbe517904f2bb43a8a763434aee/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenNonInteractiveHandler.cs#L136

**Additional context/ Logs / Screenshots**
The exception stack trace from our application ([Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows)):

```
An error occurred while sending the request.
The remote server returned an error: (401) Unauthorized
The system cannot contact a domain controller to service the authentication request. Please try again later.

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized. ---> System.ComponentModel.Win32Exception: The system cannot contact a domain controller to service the authentication request. 
Please try again later
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, 
SecurityStatus& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.NegotiateClient.DoAuthenticate(String challenge, WebRequest webRequest, 
ICredentials credentials, Boolean preAuthenticate)
   at System.Net.NegotiateClient.Authenticate(String challenge, WebRequest webRequest, ICredentials 
credentials)
   at System.Net.AuthenticationManagerDefault.Authenticate(String challenge, WebRequest request, 
ICredentials credentials)
   at System.Net.AuthenticationState.AttemptAuthenticate(HttpWebRequest httpWebRequest, ICredentials 
authInfo)
   at System.Net.HttpWebRequest.CheckResubmitForAuth()
   at System.Net.HttpWebRequest.CheckResubmit(Exception& e, Boolean& disableUpload)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper.<GetResponseAsy
nc>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.WsTrust.WsTrustRequest.<SendRequestAsy
nc>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenNonInteractiveHandle
r.<PreTokenRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsyn
c>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>
d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<
AcquireTokenAsync>d__0.MoveNext()
```

**Comment by bgavrilMS** [comment]
@jmprieur - We had a look at the code and it looks like this will not happen in ADAL v4 since we've refactored IWA. 

Workaround for v3 is to catch that exception.

**Comment by jmprieur** [comment]
@mjcheetham : is it an option to move to MSAL ?

**Comment by mjcheetham** [comment]
@jmprieur the main features we'd need to ensure to move to MSAL is:
- AAD, MSA, ADFS and NTLM/WIA support
- can read and write through to existing ADAL v2 or v3 caches
- can continue to use "v1" applications/client IDs

**Comment by jmprieur** [comment]
@mjcheetham 
- MSAL.NET now supports all the flows that ADAL.NET supports: See [Supported grants](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal#supported-grants)
- there is cache compatibility between ADAL v3, ADAL v4 and MSAL.NET: See [Do you want to migrate from ADAL.NET to MSAL.NET ?](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/adalnet4-0-preview#do-you-want-to-migrate-from-adalnet-to-msalnet-). Moreover, we are working on adding an override on MSAL.NET to AcquireTokenByRefreshToken, which should help handling the ADAL v2 -> MSAL.NET update scenario
- you can continue using the v1 applications and client IDs as now an app is an app: there is no longer v1 apps and v2 apps, but only apps (but there are still v1 tokens and v2 tokens, depending on what the Web api can handle). fore more information see [Scopes for a v1.0 Web api](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal#scopes-for-a-v10-application)

**Comment by jmprieur** [comment]
Closing this issue as we won't fix this in ADAL.NET (and it's fixed in MSAL.NET). We now encourage everybody to move to MSAL.NET
