### ISSUE TITLE
Expired RefreshToken in the TokenCache is not replaced even after additional login

### ISSUE THREAD

**Issue by bganapa** [AzureAD/azure-activedirectory-library-for-dotnet#1299]
**Which Version of ADAL are you using ?**
2.28.31117.1411

**Which platform has the issue?**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [x] Username Password

**Issue**
The issue is exposed through azure powershell latest AzureRM Version 5.6.0. This version of azure powershell uses 2.28.31117.1411 version of ADAL dll.

The user is doing Add-AzureRmAccount  for the first time. This gets a new AccessToken and RefreshToken
The subsequent Add-AzureRmAccount  executions does not replace the RefreshToken even if the RefreshToken is expired.

Since the RefreshToken is expired, subsequent calls to get AccessToken for different audiences like graph results in failure.

**Repro**
do Add-AzureRmAccount , wait till the RefreshToken expires (typically 40 hours in azurestack ADFS environments), Do Add-AzureRmAccount again in the same powerhsell session.

**Expected behavior**
A new RefreshToken is obtained with the relogin if the existing existing RefreshToken is expired in TokenCache

**Actual behavior**
Expired RefreshToken is not replaced in the TokenCache after relogin

**Comment by jmprieur** [comment]
ADAL.NET 3.x, 4.x and MSAL.NET 2.x work fine. Is it an option to migrate to these versions? (ideally you'd want to upgrade to MSAL.NET 2.x, which is where all the innovation happens)

**Comment by bganapa** [comment]
@markcowl for the possibility updating the ADAL 3.* in AzureRm.Profile module
