### ISSUE TITLE
ADAL is not returning cached tokens in multi-resource scenarios

### ISSUE THREAD

**Issue by arunsmiles** [AzureAD/azure-activedirectory-library-for-dotnet#1305]
ADAL Version that repros this issue: v3.19.8 (Latest Stable)

As part of our API call, we need on-behalf-of tokens for multiple resources like substrate, graph.windows.net, graph.microsoft.com etc. We expect ADAL to cache these tokens and return the cached tokens when we request the tokens for the same resource next time. But because of some issue with internal implementation of ADAL library, ADAL is not returning cached tokens in case multiple tokens (for different resources) are there in the cache for the same user, instead it is fetching a new token from AAD service. We are able to easily reproduce this issue locally also (even with latest version of ADAL library). 

```
var authenticationContext = new AuthenticationContext(authority, false, new Tokencache());
 
var userAssertion = new UserAssertion(serviceToken, JwtBearerAssertionType, userPrincipalName);
 
// fetch token for Substrate. This fetches a new token from AAD and stores it in cache
var result = authenticationContext.AcquireTokenAsync(“https://substrate.office.com”, clientAssertionCert, userAssertion); 
 
// fetch token for Graph. Instead of using the user Assertion passed, ADAL uses the refresh token of Substrate from cache to fetch a new token and store it in cache
var result = authenticationContext.AcquireTokenAsync("https://graph.microsoft.com", clientAssertionCert, userAssertion); 
 
// fetch token for Graph again. Because of the issue in ADAL library, instead of taking the token for Graph from the cache, it again fetches a new token from ADAL using the refresh token for Substrate
var result = authenticationContext.AcquireTokenAsync("https://graph.microsoft.com", clientAssertionCert, userAssertion);
```

More details to the ADAL cache implementation:

We digged into the ADAL library implementation, added logging to this and found that first time for a resource we fetch the token and store it in cache. The next time we try to fetch token for the same resource, it sees if there is a cached token for the resource. If it finds, it takes from the cache and return without making an ADAL call. But when we try to fetch token for a new resource, it sees if there is a cached token for the resource. If it doesn't find one, first it tries to see if there is a cached multi resource refresh token and instead of fetching a new token, it uses the multi resource refresh token(for the resource 1) and make call to ADAL to fetch a new token for the second resource. The userAssertionHash value in this case (case when we use refresh token to fetch token) is always set to null. So the next time, we try to fetch a token for resource2, it cannot find the matching token from cache as the userAssertionHash is null in the cache, but we pass the userAssertion. So it again uses the refresh token to fetch a new token for resource2. This happens everytime we try to fetch token for the resource2 resulting in an external ADAL call.

Is this issue tracked already? How do we address this?

**Comment by henrik-me** [comment]
@MarkZuber / @jennyf19 : Can you pls. take a look? 
CC: @bgavrilMS @jmprieur

**Comment by henrik-me** [comment]
@arunsmiles : this is the right place to bring ADAL issues to attention. we will investigate, we may need additional information, in which case we will reach out to you.

**Comment by arunsmiles** [comment]
@henrik-me thanks for the response. We tried a fix to populate user assertion hash before the store operation in cache and that worked for us. It'd be great if you can validate the issue and fix and help us with a patch release. Fixing it in the calling application is quite convoluted, so we'd like the version of ADAL with the fix to mitigate the issue.

**Comment by henrik-me** [comment]
@arunsmiles : Can you pls. post a PR with your changes? We may put this change in v4 as we are about to remove the preview tag from that. Can you pls. try v4? (There is a binary breaking change, which is fixed by compiling otherwise you should not be seeing any differences)

@MarkZuber and @jennyf19 will look at your solution and help evaluate and ship a fix

**Comment by arunsmiles** [comment]
@henrik-me - we're working on identifying the right place to change for our fix to be more generic. We'll send a PR shortly. In the meantime, we got a workaround to use ATS first and use AT in case of exception, which we're trying out to mitigate the issue.

**Comment by jmprieur** [comment]
the ADAL pattern is normally
```CSharp
try 
{
  AcquireTokenSilentAsync(...)
}
catch()
{
 AcquireTokenAsync()
}
```
which makes it work

See https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token#recommended-pattern-to-acquire-a-token (which is more for public client apps, but is also the recommended way for OBO today)

we are also looking at your proposal.

**Comment by jmprieur** [comment]
Closing this issue as the recommended pattern worked (as shared on a different channel). 
We'll consider improving the experience to avoid an exception in MSAL.NET (but not ADAL.NET)
