### ISSUE TITLE
MsalServiceException AADSTS50049 when targeting B2C

### ISSUE THREAD

**Issue by DaRosenberg** [AzureAD/azure-activedirectory-library-for-dotnet#1314]
I just migrated our code to MSAL 2.2.0 and also changed to use the `b2clogin.com` domain instead of the `login.microsoft.com` domain we were using before.

I cannot seem to figure out how to construct the correct `authority` string. Here is what my code currently looks like:

```cs
private const string mTenant = "ideliverableb2c.onmicrosoft.com";
private const string mClientId = "d77e...caa6"; // Obfuscated here
private const string mSignInPolicyName = "B2C_1_si";

private PublicClientApplication mClientApplication =
    new PublicClientApplication(mClientId, authority: $"https://ideliverableb2c.b2clogin.com/tfp/{mTenant}/{mSignInPolicyName}")
    {
        RedirectUri = $"msal-{mClientId}://auth",
        ValidateAuthority = false
    };
```

I have tried various different ways to format the authority string, but no matter what I do I get the same exception when I call `mClientApplication.AcquireTokenAsync()`:

`Microsoft.Identity.Client.MsalServiceException: AADSTS50049: Unknown or invalid instance.`

Response body:

```json
{
    "error":"invalid_instance",
    "error_description":"AADSTS50049: Unknown or invalid instance.\r\nTrace ID: 6b61d006-7a2a-4b7e-b497-3cd6d9dc3800\r\nCorrelation ID: 78054f61-e0a9-4685-b761-64bc728ff90d\r\nTimestamp: 2018-10-09 19:28:23Z",
    "error_codes":[50049],
    "timestamp":"2018-10-09 19:28:23Z",
    "trace_id":"6b61d006-7a2a-4b7e-b497-3cd6d9dc3800",
    "correlation_id":"78054f61-e0a9-4685-b761-64bc728ff90d"
}
```

What am I doing wrong here?

**Comment by jennyf19** [comment]
@DaRosenberg 
Have you seen this [doc](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory-b2c/b2clogin.md)? Make sure you have updated your application, wherever it refers to `login.microsoftonline.com` (policy references, etc...) now needs to use `your-tenant-name.b2clogin.com`.

Also, try removing the `-` in the redirectUri `$"msal-{mClientId}://auth"` to
 `$"msal{mClientId}://auth"`

The way you set up the authority looks fine, so I would double check the b2c registration.
`$"https://{tenant}.b2clogin.com/tfp/{tenant}.onmicrosoft.com/{policyName}"`

**Comment by jennyf19** [comment]
@DaRosenberg Also, could you open this on the [MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues?q=is%3Aopen+is%3Aissue) - thank you!

**Comment by DaRosenberg** [comment]
@jennyf19 OK, sorry wasn't sure since the code is now in this repo, and so is the release. I will move this issue to the other repo and respond to your comments there.

**Comment by jennyf19** [comment]
@DaRosenberg yes...it's very confusing, but thanks for opening it up in MSAL. Much appreciated!
