### ISSUE TITLE
authentication_ui_failed in UWP background task

### ISSUE THREAD

**Issue by xiaoningning** [AzureAD/azure-activedirectory-library-for-dotnet#1316]
**Which Version of ADAL are you using ?**
ADAL 3.19.8

**Which platform has the issue?**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * Interactive
 
UWP desktop App has the following capabilities checked:
* internetClientServer
* privateNetworkClientServer
* sharedUserCertificates
* enterpriseAuthentication

ADAL is coded in a C# winRT component, which is called by UWP App.  When the App is launched, the authentication UI works as expected.  However, the App can be triggered as a UWP background task.  ADAL is always called in the background task entry point class.  If App is launched, it works.  **But if only the background task is triggered, ADAL throws authentication_ui_failed.**

Any solution of this?

**Comment by jmprieur** [comment]
@MarkZuber : do you think that the work you've been doing would fix this?

**Comment by bgavrilMS** [comment]
@xiaoningning  - what are you trying to do ? 

Interactive authentication requires UI, i.e. we need to be able to display a browser to the user. Are you able to update the UI from your background task? 

I would propose that you move your auth code in the non-background task code. When the user starts the app, you can apply the normal pattern - silent auth (i.e. try to get a token from the cache), otherwise interactive auth.

**Comment by xiaoningning** [comment]
@bgavrilMS : ADAL.net just needs to launch web based UI for interactive authentication, not App UI itself.  Could it launch a web based UI in a background thread?  Or there is a platform limitation to do it in a background task?

**Comment by henrik-me** [comment]
@xiaoningning : 
As Bogdan suggests, pls try calling the library on the UI thread when you do the interactive flow. 
Can you pls. provide a set of more detailed repro steps 
CC: @MarkZuber

**Comment by bgavrilMS** [comment]
@xiaoningning 

This is where we invoke the browser and where you see the error https://github.com:443/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/uap/WebUI.cs#L71

I suspect that we can't access CoreApplication.MainView from a background thread. As @henrik-me stated, please call AcquireTokenAsync on a thread that has access to the MainView. 

You can however make silent calls (i.e. request a token from the cache) on your background thread if you like, so you can imagine an architecture like: 

background task - does silent calls only
foreground / application logic - checks if a token is available, if not, perform the full flow (a silent call and an interactive flow).

Let me know if this works for you.

**Comment by xiaoningning** [comment]
Now the App sends toast notification from the background thread.  Then the toast notification activates App.  However, in ToastNotificationActivatedEvent handler, it still could not launch the ADAL UI although the App foreground is being activated. 

Another interesting is that if App is launched, bit not activated currently, the background task could still launch ADAL UI.
