### ISSUE TITLE
ADAL concurrency, resiliency and testing questions

### ISSUE THREAD

**Issue by carlosscastro** [AzureAD/azure-activedirectory-library-for-dotnet#1330]
I'm using Adal C# library (latest nuget version as of today) to authenticate using Microsoft Converged App credential. I first call AcquireTokenSilentAsync() and catch the exception when the token is not in cache, and call AcquireTokenAsync(resource, clientCredentials) then.

I have 3 questions around this scenario:

1. Let's suppose there is high concurrency and my token expires. suddenly, I'll have a trillion threads calling AcquireTokenAsync(). Does Adal internally have some mechanism to make sure that a given token is refreshed only once simultaneously in a given process? Or if I call AcquiretokenAsync on each request, then all will hit the auth API? 

2. What is the retrying and backoff on failures when using the network to acquire the token? Is it configurable?

3. Is there a way to force the renewal of the token using ADAL? If I call AcquireTokenAsync I just get the exact same token with exact expiration time as the one I had. For testing purposes, I want to accelerate / force the renewal. How should I do that?

**Comment by henrik-me** [comment]
@carlosscastro : thanks for your questions. ADAL v3 and ADAL v4 has a set of differences however regarding the http stack they are mostly the same. We are putting in additional optimizations in MSAL.NET for the http stack. 
1. A trillion threads is a lot of threads, I wonder where you will find all of those :) The answer depends a bit on the platform as there are some differences across iOS, Android, .NET, UWP, and .net core. If the requests are all silent they can happen concurrently, however if the calls are interactive you will likely run into issues. In general for the time being we recommend only having one call at a time however we are not actively blocking you from having more calls going (though various internals will likely have trouble as some state might be shared). Short: You should probably stick to one request at a time.

2. For 429 we send this information back to the developer allowing the developer to wait the time AAD suggests. We also offer guidance on how to handle the returned error. You can see the adal wiki page on the server errors here: **https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Exceptions-in-ADAL.NET** however for MSAL.NET we have a wiki page which describes the usage even better: **https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/retry-after**

3. You can delete the cache entry (read more about the cache [here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Token-cache-serialization) and follow the samples. Several samples shows how to do this. Alternatively you can pass in PromptBehavior.Always in the PlatformInformation.

Note: We have worked planned to help prevent multiple calls if AAD returns a 429.

CC: @jmprieur

**Comment by carlosscastro** [comment]
@henrik-me Thanks for your detailed answer. 

I have follow up questions to be able to execute on your great answers. For the record, we are using .NET core and .NET Framework, Microsoft.IdentityModel.Clients.ActiveDirectory 3.19.8.

1- Should we use another library or version, or is this the recommended one for this?
2- Regarding your suggestion on a single request simultaneously, this is quite the bummer, because it means adding some sort of mutual exclusion and potential for resource starvation. Is it the solution to have a single static authentication context in my web app and lock on it to make the request, maintaining a small timeout to avoid starving requests on the lock? In our context, each request is a message being sent from to a bot. A popular bot receives tons of message all the time. 

Thanks again for your valuable answers Henrik!

**Comment by henrik-me** [comment]
@carlosscastro : agree it's a bit of a bummer for certain scenarios, though for most this is still acceptable. Having said that we are working on improving this (though a trillion auth objects will not be quite what I expect will work on most systems). 
We are going to be making some additional improvements in ADAL.NET 4, however the real improvements and removal of the constraints for 1 object is only going to be possible in MSAL (the code is in this repo, however the GitHub repo for MSAL can be found here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet. In general I would recommend moving to MSAL.
CC: @jmprieur

**Comment by henrik-me** [comment]
@carlosscastro : you can see one of the latest modifications for MSAL here: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1334

(for the differences and migration help, see https://aka.ms/adal-net-to-msal-net)

**Comment by carlosscastro** [comment]
@henrik-me Thanks for your answers! I don't really have trillion requests, it was just a way of saying! I do have significant traffic though, but auto-scale maintains it below 75% of machines capacity.

MSAL looks interesting, but I saw it is preview, which means that I cannot include it in services that are GA unfortunately. Once it is stable I would be happy to add it.
