### ISSUE TITLE
ADAL does not build in VS2017

### ISSUE THREAD

**Issue by robgarrett** [AzureAD/azure-activedirectory-library-for-dotnet#1342]
Latest version of development branch of ADAL and latest version of VS2017. Opening any solutions and building gives the error: 

Microsoft.Identity.Core.csproj : error MSB4057: The target "Clean" does not exist in the project.
2>Done building project "Microsoft.Identity.Core.csproj" -- FAILED.

**Comment by henrik-me** [comment]
@robgarrett : are you building the dev branch?

I'm using 2017 (15.8.7) and the build, clean etc. works with-out any issues for me on the dev branch (which is where the latest adal, v4, is).

**Comment by bgavrilMS** [comment]
Hi @robgarrett 

Could you try the following: 

Build with the command line. From a developer command prompt:
```
msbuild /t:restore LibsNoSamples.sln
```

then

```
msbuild LibsNoSamples.sln 
```

- see what that returns. I suspect that you are missing some Xamarin targets that implement the Clean target

**Comment by robgarrett** [comment]
I get an error about missing __GetRestoreSettingsPerFramework. I'm building the lib without samples solution.

**Comment by MarkZuber** [comment]
I ran into this yesterday with a new Windows 10 VM and the issue was that I hadn't installed UWP support for VS2017 yet.  Can you confirm you have the packages there installed?

**Comment by bgavrilMS** [comment]
We documented the VS components needed to build the solution here https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Pre-requisites-to-build-ADAL.NET-and-MSAL.NET

**Comment by robgarrett** [comment]
Yup, that did it, I was missing a few components.
Thanks for all the help.

**Comment by jmprieur** [comment]
Closing as @robgarrett managed to build ADAL.NET
