### ISSUE TITLE
PromptBehavior enum is exposed on NetCore 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/azure-activedirectory-library-for-dotnet#1349]
**Which Version of ADAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
ADAL 4+, dev

**Which platform has the issue?**
netstandard1.3 (i.e. netcore apps will target this)

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**
On netstandard we expose PromptBehavior enum. Not a big deal since PlatformParameters cannot be instantiated with PromptBehavior.

**Expected behavior**
PromptBehavior implies UI is support, which is not the case

**Actual behavior**
PromptBehavior should not be exposed on netstandard

**Comment by jmprieur** [comment]
Proposing Won't fix as:
- Libraries using the .NET Standard could manipulate the enum (maybe)
- also we just GAed ADAL.NET. I'm not too keen to take a public API breaking change, even if probably nobody used it.
@henrik-me proposing to close as won't fix.

**Comment by bgavrilMS** [comment]
Agreed...

**Comment by henrik-me** [comment]
Minor issue, won't fix is fine with me
