### ISSUE TITLE
Username/Password out-of-focus issues when redirecting to a 3rd party IDP: Shibboleth

### ISSUE THREAD

**Issue by wc2222** [AzureAD/azure-activedirectory-library-for-dotnet#135]
Impact:
- All Shibboleth users and potential other 3rd party federated Identity Provider users.
- Unacceptable UX experience

To repro:
1. Enter the user name: testuser1@fabrikam2015.com
2. The ADAL.NET library will redirect the user to her IDP sign in page, in this case Shibboleth

Expected Result:
User can see the full user name and password field, and the realm they are trying to sign in to.

Actual Result:
These three fields are out of focus, and there is no scroll bar for the user to move to locate the focus properly.

**Comment by RandalliLama** [comment]
Shibboleth needs to provide ux that works in mobile/native.  There isn't much that ADAL can do about this.
