### ISSUE TITLE
Authentication dialog on Android is stripping the port number when attempting to authenticate

### ISSUE THREAD

**Issue by jamesmcroft** [AzureAD/azure-activedirectory-library-for-dotnet#1363]
**Which Version of ADAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
ADAL 3.19.8

**Which platform has the issue?**
Xamarin.Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**

Providing a URL with a port number (e.g. https://testenvironment.companyname.co.uk:54843/adfs) as the Authority/Resource appears to be stripping the port number when trying to show the web view for Android. This causes the authentication dialog to not show a white screen for a few minutes before showing an error which shows the URL attempted to request without the port number.

With our Windows client, this is working as expected, only having the issue on Android.

**Expected behavior**
When a URL is provided, whether with port number or not, should show the authentication dialog for logging in.

**Actual behavior**
This causes the authentication dialog to not show a white screen for a few minutes before showing an error which shows the URL attempted to request without the port number.

**Comment by jmprieur** [comment]
@MarkZuber I pre-assigned this one to you for now

**Comment by jmprieur** [comment]
@jamesmcroft : is this still an issue for you?

**Comment by jamesmcroft** [comment]
I will update to the latest version (5.0.5) of the NuGet packages and explore this further.

**Comment by henrik-me** [comment]
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
