### ISSUE TITLE
UseCorporateNetwork is not passed to WebAuthenticationBroker because Azure DevOps redirectUri is not one of the two expected ones

### ISSUE THREAD

**Issue by jevansaks** [AzureAD/azure-activedirectory-library-for-dotnet#1386]
**Which Version of ADAL are you using ?**
ADAL 4.3.0

**Which platform has the issue?**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**

```csharp
  var platformParameters = new PlatformParameters(PromptBehavior.Auto, true);
  var authResult = await authCtx.AcquireTokenAsync(_resourceId, _clientId, new Uri("urn:ietf:wg:oauth:2.0:oob"), platformParameters);
```

**Expected behavior**
Expected: Authentication dialog pops up and user is able to log in with the flow as normal.

**Actual behavior**
Actual: Authentication dialog pops up, user enters their user name and then is redirected to a page showing "We can't connect to the service you need right now. Check your network connection or try this again later.". This same app with authentication works when running off of the corporate network.

**Possible Solution**
In the WebUI.cs code the app passes in UseCorporateNetwork = true and that request is overridden to be false because I haven't passed in one of the two expected canonical redirect URIs. I can't do that because Azure DevOps requires the redirect uri be "urn:ietf:wg:oauth:2.0:oob", [as documented here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code).

Specifically the WebUI.cs code here is resolving to WebAuthenticationOptions.UseCorporateNetwork:

```csharp
            bool ssoMode = ReferenceEquals(redirectUri, Constants.SsoPlaceHolderUri);
            if (uiParent.UseHiddenBrowser && !ssoMode && redirectUri.Scheme != Constant.MsAppScheme)
            {
                throw new AdalException(AdalError.UapRedirectUriUnsupported);
            }

            WebAuthenticationResult webAuthenticationResult;
            WebAuthenticationOptions options = (uiParent.UseCorporateNetwork &&
                                                (ssoMode || redirectUri.Scheme == Constant.MsAppScheme))
                ? WebAuthenticationOptions.UseCorporateNetwork
                : WebAuthenticationOptions.None;
```

And I don't understand why it's overriding what the app passed in. 

**Additional context/ Logs / Screenshots**
![image](https://user-images.githubusercontent.com/20667023/48019487-6bc66a00-e0e8-11e8-929a-1578ce380f45.png)

**Comment by jevansaks** [comment]
Specifically the WebUI.cs code here is resolving to WebAuthenticationOptions.UseCorporateNetwork:

```csharp
            bool ssoMode = ReferenceEquals(redirectUri, Constants.SsoPlaceHolderUri);
            if (uiParent.UseHiddenBrowser && !ssoMode && redirectUri.Scheme != Constant.MsAppScheme)
            {
                throw new AdalException(AdalError.UapRedirectUriUnsupported);
            }

            WebAuthenticationResult webAuthenticationResult;
            WebAuthenticationOptions options = (uiParent.UseCorporateNetwork &&
                                                (ssoMode || redirectUri.Scheme == Constant.MsAppScheme))
                ? WebAuthenticationOptions.UseCorporateNetwork
                : WebAuthenticationOptions.None;
```

And I don't understand why it's overriding what the app passed in.

**Comment by henrik-me** [comment]
@jevansaks : Thanks for your feedback. We had a brief discussion internally on this. We will investigate.

**Comment by samukasantos** [comment]
Hey guys, 

Is there any solution for this issue ? I'm facing the same error and tried to use WebAuthenticationBroker assigning WebAuthenticationOptions.UseCorporateNetwork directly and the error is System.ArgumentException: Value does not fall within the expected range. Do you guys have any suggestion ?

**Comment by jevansaks** [comment]
It's a limitation of WebAuthenticationBroker and I doubt it will ever be resolved. I ultimately created an Azure Application with my app's ms-app:// URI (the one that `WebAuthenticationBroker.GetCurrentApplicationCallbackUri()` returns). You can register an Azure Application here: https://apps.dev.microsoft.com.

**Comment by jennyf19** [comment]
@samukasantos Can you try what @jevansaks is suggesting? Basically add this code to your app:
```csharp
var x = Windows.Security.Authentication.Web.WebAuthenticationBroker.GetCurrentApplicationCallbackUri();
```
Take the value (something like this: `ms-app://s-1-15-2-111638678-219698677-36916742-1909548894-372823757-39941306-27685825/`) and register the value as a redirectUri in the portal for this app. 

Let me know if you still run into issues. Also, please try with the most recent version of the library. Thanks.

**Comment by jevansaks** [comment]
@jennyf19 what's confusing most people (it confused me for a long time) is that the ADAL samples all use `872cd9fa-d31f-45e0-9eab-6e460a02d1f1` as the client ID but they don't explain where that came from. It appears to be Visual Studio's own client ID that just happens to work if you use it in your own app with callback URL "urn:ietf:wg:oauth:2.0:oob". Except that it doesn't have a callback URL registered that would allow WebAuthenticationBroker to UseCorporateNetwork.

Frustratingly, WebAuthenticationBroker grants all permissions during debug sessions so you get "it works on my machine" behavior and then it breaks when you deploy your app.

**Comment by jennyf19** [comment]
@jevansaks I see. Thanks for the explanation. Looks like we have some documentation/sample updates to do this area.

**Comment by jmprieur** [comment]
This was documented
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows#getting-the-redirect-uri-in-the-case-of-windows-universal-apps
