### ISSUE TITLE
Requesting a token with aud in the format 'spn: {id}'

### ISSUE THREAD

**Issue by omerlh** [AzureAD/azure-activedirectory-library-for-dotnet#1396]
**Is your feature request related to a problem? Please describe.**
There are cases where the server request that the token `aud` will be in the format `spn:<id>`. For example, Kubernetes cluster created with ACS engine is expecting tokens in this format - see this issue Azure/acs-engine#4189. In order to authenticate the users to Kubernetes server, I need a token in this format.

**Describe the solution you'd like**
See issue AzureAD/azure-activedirectory-library-for-nodejs#128 - look like all that is required is a simple way to change the API version. I looked, and it seems that there is no way to change it.

**Describe alternatives you've considered**
There is not a lot I can do here, besides waiting for ACS engine to remove the requirement.
**Additional context**

**Comment by jmprieur** [comment]
@omerlh 
See #1493 where a workaround is proposed: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1493#issuecomment-460996923

I've also added an entry in the Q&Q to help how to use ADAL.NET with Kubernetes: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/ADAL-.NET-Q-&-A#using-adal-with-kubernetes

**Comment by omerlh** [comment]
Thanks! I'll check and update if this solves the issue.

**Comment by omerlh** [comment]
I tried using:
```csharp
Environment.SetEnvironmentVariable("ExtraQueryParameter", "api-version=1.0");
```
But the requst failed with:
```
Timestamp: 2019-02-18 10:43:18Z ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (BadRequest). ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: {"error":"invalid_request","error_description":"AADSTS500501: Invalid value for 'api-version'.\r\nTrace ID: 10953cf7-f431-45a4-872e-2ef433022e00\r\nCorrelation ID: 543a5065-d1e1-4231-a242-96c4a0e5d51c\r\nTimestamp: 2019-02-18 10:43:18Z","error_codes":[500501],"timestamp":"2019-02-18 10:43:18Z","trace_id":"10953cf7-f431-45a4-872e-2ef433022e00","correlation_id":"543a5065-d1e1-4231-a242-96c4a0e5d51c"}: Unknown error
```
Can you please help?

**Comment by jmprieur** [comment]
Apparently, this failed from the instance discovery which was not expecting the api-version=1.0 (whereas the token acquisition accepts it).

Would you please try a work around where you first attempt to get a token before setting your environment variable? I suspect you've set it at the start of your app? could you set it just before the AcquireTokenXX call (but not before the first AcquireTokenSilentAsync)

**Comment by omerlh** [comment]
So I'll have to request a token twice? Once to fetch the metadata and once to get the token? This is pretty hacky. Also, once the metadata is expired, a request to retrieve them will fail... Not sure this is a good enough solution. Will it be easier using MSAL?

**Comment by jmprieur** [comment]
@omerlh: I agree that this is hacky (but the environment variable is as well). You don't need to acquire the token twice as I'm pretty sure you use the [recommended pattern](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token#recommended-pattern-to-acquire-a-token):
AcquireTokenSilentAsync and if fails then call AcquireTokenAsync
I'm just saying add the environment variable before the call to AcquireTokenAsync

yes, I'd think it would be simpler with MSAL 3.x (not released yet, but which is coming soon), you'll be able to pass ExtraQueryParameters in any AcquireTokenXXX

For instance:

```CSharp
app.AcquireTokenInteractive(scopes)
 .WithExtraQueryParameters(extraQueryParameters)
 .ExecuteAsync();
```

more about what is coming in (work in progress) https://aka.ms/msal-net-3x

**Comment by omerlh** [comment]
Ok, waiting for it :) So far, I'm unable to [request a token] using MSAL. So I hope I'll be able to solve this first. Thanks!
