### ISSUE TITLE
Xamarin iOS support for HttpClient handler

### ISSUE THREAD

**Issue by ghost** [AzureAD/azure-activedirectory-library-for-dotnet#1397]
**Which Version of ADAL are you using ?**
ADAL 3.19.8
**Which platform has the issue?**
iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**
The question is does the HttpClientFactory for Xamarin iOS use the standard .NET Http Client Handler, or does it use what the client app has set for the http client handler in the Xamarin Project setup?  Specifically if I built a new app and use this nuget package if I have NSUrlSession set as the supported Http Client is the ADAL code using this or is it using the .NET Library.

**Expected behavior**
What ever the project has set as the Http Client that the nuget package uses that.

**Actual behavior**
We believe the http client is the .NET Managed Http Client because we are seeing BSD socket requests instead of standard HTTP traffic when the token is requested.

**Possible Solution**
Honor the settings that the client has or allow the injection of the Http Client Handler so that the developer can override the http client handler with a specific on that implements NSUrlSession/NSUrlConnectionHandler

**Additional context/ Logs / Screenshots**
![screen shot 2018-11-09 at 12 05 09 pm](https://user-images.githubusercontent.com/176927/48277465-c594a000-e418-11e8-9f98-d88b3fce127d.png)

**Comment by henrik-me** [comment]
You might have to look at the proxy settings: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/with-proxy
Note: For ADAL v4 the http stack is different and may behave differently, though under the hood it's still using the HttpClient.

**Comment by henrik-me** [comment]
@jmprieur : Seems like a feature ask we have discussed previously regarding the HttpHandler.

**Comment by ghost** [comment]
this is correct - we would like this as a feature.

**Comment by henrik-me** [comment]
@biozal : The library is currently using the std. net HttpHandler as you probably already had found. We will investigate what it will take to offer custom HttpHandlers.

**Comment by ghost** [comment]
You already have a factory for this with an Interface called IHttpClientFactory that is in Microsoft.Identity.Core.Http.  Really the building blocks for it are already there - you just need to allow a Native Http Client Factory be provided by the client or you build one for each platform and allow the dev to configure which one that it should use with a default to the .NET Standard implementation so you can mitigate the change risk.  

FY - When I look at the iOS Native code for the ADAL library - it's clearly using NSURLSession.

**Comment by bgavrilMS** [comment]
@biozal - the HttpClientFactory was added on ADAL 4.x, it wasn't there on ADAL 3.19.8. We're only taking critical fixes into ADAL v3, so anything we discuss here will be for ADAL 4. There should be no problems upgrading though, they are source compatible.

I'm looking at adding a mechanism for setting a custom HttpMessageHandler. This should be enough to set NSUrlSession, or would you like to be able to new up your own HttpClient altogether?

**Comment by ghost** [comment]
> @biozal - the HttpClientFactory was added on ADAL 4.x, it wasn't there on ADAL 3.19.8. We're only taking critical fixes into ADAL v3, so anything we discuss here will be for ADAL 4. There should be no problems upgrading though, they are source compatible.
> 
> I'm looking at adding a mechanism for setting a custom HttpMessageHandler. This should be enough to set NSUrlSession, or would you like to be able to new up your own HttpClient altogether?

I think you will find most companies that need this feature will want the full ability to add in there own HttpClient.  This gives them the ability to hand events, setup logging, etc in a way that just adding in NSUrlSession doesn't, and it solves the issue on other platforms like Android which faces similar set of problems unless you allow the custom http client.  Makes it a clean and simple solution.  

FYI - in v4 it looks like you aren't using UIWebView anymore - that actually is a big deal for some enterprise clients that use security solutions around protecting UIWebView as the new solution doesn't support the same hooks.  I'm all for the new approach - but for some companies the move between v3 and v4 is bigger than just upgrading the nuget package.

**Comment by bgavrilMS** [comment]
Hi again @biozal - we're be looking at adding this functionality in MSAL and not in ADAL. Is it an option for you to move to MSAL ? We can help if you need assistance. 

The main concern is: 

- In the current model, we'd need to add another parameter (IHttpFactory or a lambda () => HttpClient) to the AuthenticationContext constructor. There are already so many of them that they are a cause of confusion for ADAL users. In MSAL we will add a configuratio object.

**Comment by ghost** [comment]
> Hi again @biozal - we're be looking at adding this functionality in MSAL and not in ADAL. Is it an option for you to move to MSAL ? We can help if you need assistance.
> 
> The main concern is:
> 
> * In the current model, we'd need to add another parameter (IHttpFactory or a lambda () => HttpClient) to the AuthenticationContext constructor. There are already so many of them that they are a cause of confusion for ADAL users. In MSAL we will add a configuratio object.

When I last looked at MSAL the biggest issue was documentation and release lifecycle as everything was in preview and we have a policy at the company I work for where we can't ship production apps with preview/beta code in them.  I'm not against this move if official versions of the nuget package are released similar to ADAL.  Is there any features we loose in MSAL that ADAL does support?

**Comment by jmprieur** [comment]
@biozal : MSAL.NET is at parity with ADAL.NET except for:
- MSAL.NET does not supports the broker (authenticator / company portal) on Xamarin.iOS and Xamarin.Android, as those are not yet AAD v2.0. But this is coming
- if you want to use an authority which is a direct ADFS authority, note that MSAL.NET only supports ADFS 2019. of course ADFS federated with Azure AD is supported

Documentation should really not be an issue (MSAL.NET is even better documented than ADAL.NET now). It's still a preview and we'll GA based on adoption and feedback.

For a full understanding of the differences and migration, see [Differences between ADAL.NET and MSAL.NET Apps](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal)

**Comment by henrik-me** [comment]
@biozal @jmprieur : Minor clarification. ADFS 2019 is not yet supported in MSAL.NET. We are still working on the details

**Comment by biozal** [comment]
Can someone point out to me where the request is made to /oauth2/token?  I can't seem to find this in either library.  According to the documentation when the authorize request returns then the token request should be made:  https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code

**Comment by bgavrilMS** [comment]
We have added a ctor for AuthenticationContext that takes in an HttpClient. It will solve this issue. It will be available in the next release.

**Comment by bgavrilMS** [comment]
This has been implemented in ADAL 4.5.0

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/with-proxy
