### ISSUE TITLE
Acquiring a token with Windows Integrated Authentication throws unknown_user_type exception with managed AD account type

### ISSUE THREAD

**Issue by nflello** [AzureAD/azure-activedirectory-library-for-dotnet#1398]
**Which Version of ADAL are you using ?**
ADAL 4.3.0
This also applies to MSAL 2.3.1-preview

**Which platform has the issue?**
UWP

**What authentication flow has the issue?**
* Desktop / Mobile
    * Integrated Windows Auth

**Repro**
For ADAL:
```csharp
AuthenticationContext context = new AuthenticationContext(authority);
await context.AcquireTokenAsync(resource, clientId, new UserCredential());
```

For MSAL:
```csharp
PublicClientApplication app = new PublicClientApplication(clientId, authority);
await app.AcquireTokenByIntegratedWindowsAuthAsync(new string[] { "user.read" });
```

**Expected behavior**
My machine is connected to my company's Azure AD in a managed setup as well as the company network, so I expect to be able to sign in with my windows credentials.

**Actual behavior**
"unknown_user_type" exception is thrown.
The message for MSAL reports:
"Unsupported User Type 'Managed'. Please see https://aka.ms/msal-net-up"
This link is not of help for this issue.

**Additional context/ Logs / Screenshots**
The documentation does not mention that a federated setup is required for this flow
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-Integrated-authentication-on-Windows-(Kerberos)
or
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication

The ADAL library code explicitly checks for a federated account:
```csharp
protected internal /* internal for test only */ override async Task PreTokenRequestAsync()
    {
        await base.PreTokenRequestAsync().ConfigureAwait(false);

        if (!SupportADFS)
        {
            var userRealmResponse = await _commonNonInteractiveHandler.QueryUserRealmDataAsync(Authenticator.UserRealmUriPrefix)
               .ConfigureAwait(false);

            if (string.Equals(userRealmResponse.AccountType, "federated", StringComparison.OrdinalIgnoreCase))
            {
                WsTrustResponse wsTrustResponse = await _commonNonInteractiveHandler.PerformWsTrustMexExchangeAsync(
                    userRealmResponse.FederationMetadataUrl,
                    userRealmResponse.CloudAudienceUrn,
                    UserAuthType.IntegratedAuth).ConfigureAwait(false);

                // We assume that if the response token type is not SAML 1.1, it is SAML 2
                _userAssertion = new UserAssertion(wsTrustResponse.Token, (wsTrustResponse.TokenType == WsTrustResponse.Saml1Assertion) ? OAuthGrantType.Saml11Bearer : OAuthGrantType.Saml20Bearer);
            }
            else
            {
                throw new AdalException(AdalError.UnknownUserType);
            }
        }
    }
```

MSAL is similar:
```csharp
		private async Task<UserAssertion> FetchAssertionFromWsTrustAsync()
		{
			// ...

			if (!userRealmResponse.IsFederated)
			{
				throw new MsalException(
					MsalError.UnknownUserType,
					string.Format(
						CultureInfo.CurrentCulture,
						MsalErrorMessage.UnsupportedUserType,
						userRealmResponse.AccountType));
			}

			// ...
		}
```

Using Telerik Fiddler, I've determined that the network call to determine the user type is:
https://login.microsoftonline.com/common/userrealm/{user}?api-version=1.0

For example,
https://login.microsoftonline.com/common/userrealm/github.com?api-version=1.0
reports a managed account type.

**Comment by bgavrilMS** [comment]
Ack, I see the problem - looking into this now.

**Comment by mahoekst** [comment]
I hit the same issue running the iwa-console sample on a AAD joined machine.

**Comment by bgavrilMS** [comment]
I had a look at this versus the implementation in ADALv3. They both do the same thing, i.e. IWA fails for managed users. 

My understanding of "managed" vs "federated" users is that: 
- managed users have been created entirely in AAD and have no AD backing
- federated users were created in an AD and were "federated" (copied) to AAD

Integrated Windows Auth is an old auth protocol that works by calling a specific AD endpoint. In case on managed users, this endpoint does not exist, because AD does not exist. I will update the documentation and the exceptions to offer a better explanation. 

I am not aware of any protocol that would allow a managed user to connect without interaction, please let me know if you think otherwise.
