### ISSUE TITLE
MSAL performance degradation in .NET Framework compared to .NET Core

### ISSUE THREAD

**Issue by carlosscastro** [AzureAD/azure-activedirectory-library-for-dotnet#1406]
Using the latest MSAL version, we observe that retrieving a token from the cache using AcquireTokenForClientAsync takes ~0 milliseconds in .NET Core and ~25 milliseconds in .NET Framework. Evidence suggests that potentially the issue may be while flushing the telemetry helper in the Flush operation of TelemetryHelper.Dispose [here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/msal/src/Microsoft.Identity.Client/TokenCache.cs#L311).

To reproduce, create a .NET Core console app and a .NET Framework console app, add MSAL nuget package to both and copy the following code into program.cs:

```csharp
using Microsoft.Identity.Client;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;

namespace MsalMiniLoad
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            AcquireManyTokens().GetAwaiter().GetResult();
        }

        static TokenCache cache = new TokenCache();
        static TokenCache cache2 = new TokenCache();
        static ConfidentialClientApplication app = new ConfidentialClientApplication("a40e1db0-b7a2-4e6e-af0e-b4987f73228f", "https://login.microsoftonline.com/botframework.com", "localhost:8040", new ClientCredential("sbF0902^}tyvpvEDXTMX9^|"), cache2, cache);
        private static Semaphore authContextSemaphore = new Semaphore(1, 1);
        private static async Task AcquireManyTokens()
        {
            List<Task<AuthenticationResult>> tasks = new List<Task<AuthenticationResult>>();

            for (int i = 0; i < 1000; i++)
            {
                tasks.Add(AcquireTokenAndTime(app));
            }
            await Task.WhenAll(tasks);
            Console.ReadLine();
        }

        private static async Task<AuthenticationResult> AcquireTokenAndTime(ConfidentialClientApplication app)
        {
            Stopwatch watch = Stopwatch.StartNew();
            bool acquired = false;
            try
            {
                acquired = authContextSemaphore.WaitOne(TimeSpan.FromSeconds(30));//.ConfigureAwait(false);
                if (acquired)
                {
                    var res = await app.AcquireTokenForClientAsync(new[] { "https://api.botframework.com/.default" }, false).ConfigureAwait(false);
                    watch.Stop();
                    Console.WriteLine(watch.ElapsedMilliseconds);
                    return res;
                }
                else
                {
                    throw new TimeoutException();
                }
            }

            catch (Exception ex)
            {
                throw;
            }
            finally
            {
                if (acquired)
                    authContextSemaphore.Release();
            }
        }
    }
}
```

Here are the first rows of output for each platform:

### .NET Core

```
Hello World!
2377
1190
0
0
0
0
0
0
0
0
0
0
0
0
0
```

### .NET Framework

```
Hello World!
510
472
31
32
23
27
25
24
25
24
28
25
22
24
30
28
33
36
29
```

### Profiling

I did a quick profile using [perfview](https://github.com/Microsoft/perfview) and we are potentially spending most of the time while flushing the telemetry helper in the Flush operation of TelemetryHelper.Dispose [here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/msal/src/Microsoft.Identity.Client/TokenCache.cs#L311).

#### Call stack
![msal_callstack](https://user-images.githubusercontent.com/21318528/48577267-9c1dbd80-e8cb-11e8-9eb2-6a4a46e0b8c8.png)

#### Aggregated time spent on method ranked by time

![msal_names](https://user-images.githubusercontent.com/21318528/48577287-a6d85280-e8cb-11e8-9349-f6fba2642e45.png)

**Comment by jmprieur** [comment]
Thanks @carlosscastro  for the detailed repros and analysis

**Comment by carlosscastro** [comment]
Sure!

I think the fix is to turn this line to false
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1406

**Comment by carlosscastro** [comment]
Of course there is an analysis required of the consequences of not flushing here. Didn't mean to oversimplify - setting that line to false would help this issue but we'd need to verify the side effects and the original reason why it was set to true.

**Comment by MarkZuber** [comment]
Fixed with PR [1407]
