### ISSUE TITLE
AuthenticationParameters.CreateFromResourceUrlAsync() returns an authority which is an enpoint, whereas ADAL.NET 4.x constructor now only accepts authorities (not endpoints)

### ISSUE THREAD

**Issue by AshleyAsh90** [AzureAD/azure-activedirectory-library-for-dotnet#1410]
_Originally posted by @AshleyAsh90 in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1346#issuecomment-439492660_

**Comment by jmprieur** [comment]
@AshleyAsh90 : 
I don't understand this issue. Can you please provide repro steps and use the template which is proposed?

**Comment by AshleyAsh90** [comment]
Hi, 
I apologize, let me try to make myself clear. In the below link:
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/connect-customer-engagement-web-services-using-oauth
The section under "Discover the authority at run time" has below code:

AuthenticationParameters ap = AuthenticationParameters.CreateFromResourceUrlAsync(  
                        new Uri("https://mydomain.crm.dynamics.com/api/data/")).Result;  
  
String authorityUrl = ap.Authority;  
String resourceUrl  = ap.Resource;  
Here the resource url that is returned in ap.authority is in the format  "https://login.microsoftonline.com/{Guid}/oauth2/authorize" rather than the https://login.microsoftonline.com/{Guid} that is expected now in ADAL4.4.0 to acquire the token. Is this something that should be handled internally?

**Comment by jmprieur** [comment]
Renamed the title. Thanks for the explanation, @AshleyAsh90 
this is an inconsistency:
- either we let the constructors of AuthenticationContext to accept endpoints for resources (was the case in ADAL 3.x, no longer in ADAL 4.x)
- or we change AuthenticationParameters.CreateFromResourceUrlAsync() to return an authority, and not an endpoint (probably the cleanest)

Meanwhile, @AshleyAsh90 can you strip-out the /oauth2/authorize in your app?

**Comment by AshleyAsh90** [comment]
@jmprieur Thank you for looking into this.
And yes I did proceed to strip that part out and was able to continue . :)

**Comment by rajrao** [comment]
What is the status of this issue? I am using ADAL 4.5.1 and get the error

"AADSTS90002: Tenant 'authorize' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator. | AADSTS90002: Tenant 'authorize' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator."

```
var crmBaseUrl = "https://orgName.crm.dynamics.com/api/data";
string applicationId = "GUID";
string clientSecret = "secret";
string api = "/V9.1/";

//retrieve authority url and resource
//and then get the authentication token
AuthenticationParameters ap = AuthenticationParameters.CreateFromResourceUrlAsync(new Uri(crmBaseUrl)).Result;
Console.WriteLine($"Authority: {ap.Authority}");
Console.WriteLine($"Resouce: {ap.Resource}");

//fix for issue 1410: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1410 The fix is this part: .Replace(@"oauth2/authorize","");
var authority = ap.Authority.Replace(@"oauth2/authorize","");
AuthenticationContext authContext = new AuthenticationContext(authority, false);
Task<AuthenticationResult> taskResult = authContext.AcquireTokenAsync(ap.Resource, new ClientCredential(applicationId, clientSecret));

//without the fix for issue 1410: you get the following error on the next line:
/*AADSTS90002: Tenant 'authorize' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.*/
AuthenticationResult result = taskResult.Result;
```

**Comment by henrik-me** [comment]
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
