### ISSUE TITLE
Same code produces different behaviors on different Android Devices

### ISSUE THREAD

**Issue by arielbh** [AzureAD/azure-activedirectory-library-for-dotnet#1416]
**Which Version of ADAL are you using ?**
ADAL 4.4.0

**Which platform has the issue?**
Xamarin.Forms on Android

**What authentication flow has the issue?**
Mobile + Interactive with Broker

The issue at hand is that the same code base is being run on 3 different Android devices. 2 devices are able to present the user to select the account from the broker app, however in the 3rd device, from some unknown reason it doesn't cache the selection and AcquireTokenSilentAsync call is failing repeatedly forcing the user to re-select his account multiple times.

**Repro**

```csharp
private string _userName = string.Empty;

        private async Task<AuthenticationResult> PerformAuthenticateAsync(string resource, object context,
            AuthenticationContext authContext)
        {
            

            try
            {
                var result = await authContext.AcquireTokenSilentAsync(resource, _configurationService.Auth.ClientId,
                    new UserIdentifier(_userName, UserIdentifierType.OptionalDisplayableId),
                    _platformAuthenticator.GetPlatformParameters(context));
                return GetAuthenticationResult(result);

            }
            catch (AdalServiceException ex) when (ex.Message == "User canceled authentication")
            {
                authContext.TokenCache.Clear();
                var result = await authContext.AcquireTokenAsync(resource, _configurationService.Auth.ClientId,
                    _platformAuthenticator.RedirectUri ?? _defaultRedirectUri,
                    _platformAuthenticator.GetPlatformParameters(context));
                return GetAuthenticationResult(result);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                authContext.TokenCache.Clear();
                var result = await authContext.AcquireTokenAsync(resource, _configurationService.Auth.ClientId,
                    _platformAuthenticator.RedirectUri ?? _defaultRedirectUri,
                    _platformAuthenticator.GetPlatformParameters(context));
                _userName = result.UserInfo.DisplayableId;
                return GetAuthenticationResult(result);
            }
        }
```

**Expected behavior**
The use should be presented the broker dialog one time and consecutive calls to AcquireTokenSilentAsync should return the cached token from the selection. 

**Actual behavior**
AcquireTokenSilentAsync fails, then the exception is thrown and catch statements are being called repeatedly.

**Additional context/ Logs / Screenshots**
11-20 17:17:32.540 I/        (16394): 2018-11-20T15:17:32.5400290Z: 668ec90a-7dc5-4b64-84ef-6a68bcaa1244 - AdalLoggerBase.cs: ADAL PCL.Android with assembly version '4.4.0.0', file version '4.4.0.0' and informational version '4.4.0' is running...
11-20 17:17:32.541 I/        (16394): 2018-11-20T15:17:32.5408800Z: 668ec90a-7dc5-4b64-84ef-6a68bcaa1244 - AdalLoggerBase.cs: === Token Acquisition started: 
11-20 17:17:32.541 I/        (16394): 	CacheType: null
11-20 17:17:32.541 I/        (16394): 	Authentication Target: User
11-20 17:17:32.541 I/        (16394): 	, Authority Host: login.microsoftonline.com
11-20 17:17:32.542 V/        (16394): 2018-11-20T15:17:32.5420480Z: 668ec90a-7dc5-4b64-84ef-6a68bcaa1244 - AdalLoggerBase.cs: Loading from cache.
11-20 17:17:32.549 I/        (16394): 2018-11-20T15:17:32.5487600Z: 00000000-0000-0000-0000-000000000000 - AdalLoggerBase.cs: Deserialized 1 items to token cache.
11-20 17:17:32.550 V/        (16394): 2018-11-20T15:17:32.5498150Z: 668ec90a-7dc5-4b64-84ef-6a68bcaa1244 - AdalLoggerBase.cs: Looking up cache for a token...
11-20 17:17:32.550 I/        (16394): 2018-11-20T15:17:32.5505350Z: 668ec90a-7dc5-4b64-84ef-6a68bcaa1244 - AdalLoggerBase.cs: An item matching the requested resource was found in the cache
11-20 17:17:32.556 I/        (16394): 2018-11-20T15:17:32.5564330Z: 668ec90a-7dc5-4b64-84ef-6a68bcaa1244 - AdalLoggerBase.cs: 24.2740610333333 minutes left until token in cache expires
11-20 17:17:32.557 I/        (16394): 2018-11-20T15:17:32.5569430Z: 668ec90a-7dc5-4b64-84ef-6a68bcaa1244 - AdalLoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
11-20 17:17:32.558 I/        (16394): 2018-11-20T15:17:32.5584760Z: 668ec90a-7dc5-4b64-84ef-6a68bcaa1244 - AdalLoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 11/20/2018 3:41:49 PM +00:00
11-20 17:17:32.573 D/Mono    (16394): Assembly Ref addref Microsoft.Rest.ClientRuntime[0xde6fe440] -> System.Net.Primitives[0xc3b94be0]: 3
11-20 17:17:32.581 D/Mono    (16394): Assembly Ref addref Microsoft.Dww.Wally.Common[0xde6fd900] -> Plugin.Geolocator[0xde6febc0]: 2
11-20 17:17:32.581 D/Mono    (16394): Assembly Ref addref Plugin.Geolocator[0xde6febc0] -> Plugin.Geolocator.Abstractions[0xde6feb00]: 3
11-20 17:17:32.582 D/Mono    (16394): Unloading image System.Threading.Tasks.dll [0xbfbae600].
11-20 17:17:32.583 D/Mono    (16394): Image addref System.Threading.Tasks[0xbfb1a3c0] -> System.Threading.Tasks.dll[0xc281bf00]: 6
11-20 17:17:32.583 D/Mono    (16394): Config attempting to parse: 'System.Threading.Tasks.dll.config'.
11-20 17:17:32.583 D/Mono    (16394): Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/etc/mono/assemblies/System.Threading.Tasks/System.Threading.Tasks.config'.
11-20 17:17:32.583 D/Mono    (16394): Assembly Ref addref Plugin.Geolocator.Abstractions[0xde6feb00] -> System.Threading.Tasks[0xc2c048c0]: 4
11-20 17:17:32.589 D/Mono    (16394): Assembly Ref addref Plugin.Geolocator[0xde6febc0] -> Xamarin.GooglePlayServices.Base[0xdd4188c0]: 3
11-20 17:17:32.589 D/Mono    (16394): Assembly Ref addref Plugin.Geolocator[0xde6febc0] -> Xamarin.GooglePlayServices.Basement[0xdd418920]: 3
11-20 17:17:32.590 D/Mono    (16394): Assembly Ref addref Plugin.Geolocator[0xde6febc0] -> Xamarin.GooglePlayServices.Location[0xdd418aa0]: 2
11-20 17:17:32.590 D/Mono    (16394): Assembly Ref addref Xamarin.GooglePlayServices.Location[0xdd418aa0] -> Xamarin.GooglePlayServices.Base[0xdd4188c0]: 4
11-20 17:17:32.592 I/        (16394): 2018-11-20T15:17:32.5919160Z: 21c02ac1-2eef-4dd0-ab7b-d962e78137df - AdalLoggerBase.cs: ADAL PCL.Android with assembly version '4.4.0.0', file version '4.4.0.0' and informational version '4.4.0' is running...
11-20 17:17:32.593 I/        (16394): 2018-11-20T15:17:32.5931010Z: 21c02ac1-2eef-4dd0-ab7b-d962e78137df - AdalLoggerBase.cs: === Token Acquisition started: 
11-20 17:17:32.593 I/        (16394): 	CacheType: null
11-20 17:17:32.593 I/        (16394): 	Authentication Target: User
11-20 17:17:32.593 I/        (16394): 	, Authority Host: login.microsoftonline.com
11-20 17:17:32.594 V/        (16394): 2018-11-20T15:17:32.5942820Z: 21c02ac1-2eef-4dd0-ab7b-d962e78137df - AdalLoggerBase.cs: Loading from cache.
11-20 17:17:32.595 D/Mono    (16394): DllImport searching in: '__Internal' ('(null)').
11-20 17:17:32.595 D/Mono    (16394): Searching for 'java_interop_jnienv_call_static_object_method'.
11-20 17:17:32.595 D/Mono    (16394): Probing 'java_interop_jnienv_call_static_object_method'.
11-20 17:17:32.595 D/Mono    (16394): Found as 'java_interop_jnienv_call_static_object_method'.
11-20 17:17:32.600 I/        (16394): 2018-11-20T15:17:32.5998620Z: 00000000-0000-0000-0000-000000000000 - AdalLoggerBase.cs: Deserialized 1 items to token cache.
11-20 17:17:32.600 V/        (16394): 2018-11-20T15:17:32.6006490Z: 21c02ac1-2eef-4dd0-ab7b-d962e78137df - AdalLoggerBase.cs: Looking up cache for a token...
11-20 17:17:32.601 I/        (16394): 2018-11-20T15:17:32.6010960Z: 21c02ac1-2eef-4dd0-ab7b-d962e78137df - AdalLoggerBase.cs: An item matching the requested resource was found in the cache
11-20 17:17:32.607 I/        (16394): 2018-11-20T15:17:32.6070820Z: 21c02ac1-2eef-4dd0-ab7b-d962e78137df - AdalLoggerBase.cs: 24.2732166666667 minutes left until token in cache expires
11-20 17:17:32.607 I/        (16394): 2018-11-20T15:17:32.6075760Z: 21c02ac1-2eef-4dd0-ab7b-d962e78137df - AdalLoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
11-20 17:17:32.609 I/        (16394): 2018-11-20T15:17:32.6091520Z: 21c02ac1-2eef-4dd0-ab7b-d962e78137df - AdalLoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 11/20/2018 3:41:49 PM +00:00
11-20 17:17:32.621 D/Mono    (16394): Assembly Ref addref Microsoft.Rest.ClientRuntime[0xde6fe440] -> System.Threading[0xdd461580]: 4
11-20 17:17:32.626 D/Mono    (16394): Assembly Ref addref Xamarin.GooglePlayServices.Location[0xdd418aa0] -> Xamarin.GooglePlayServices.Tasks[0xdd418c20]: 2
11-20 17:17:32.631 D/Mono    (16394): Assembly Ref addref System.Threading.Tasks[0xc2c048c0] -> System.Core[0xdd419040]: 15
11-20 17:17:32.927 D/Mono    (16394): Assembly Ref addref System.IO.Pipelines[0xde6ff5e0] -> System.Memory[0xde6ff6a0]: 4
11-20 17:17:32.963 D/Mono    (16394): Assembly Ref addref Microsoft.AspNetCore.Http.Connections.Client[0xde6fd3c0] -> System.Memory[0xde6ff6a0]: 5
11-20 17:17:33.409 I/        (16394): 2018-11-20T15:17:33.4090130Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: ADAL PCL.Android with assembly version '4.4.0.0', file version '4.4.0.0' and informational version '4.4.0' is running...
11-20 17:17:33.409 I/        (16394): 2018-11-20T15:17:33.4097600Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: === Token Acquisition started: 
11-20 17:17:33.409 I/        (16394): 	CacheType: null
11-20 17:17:33.409 I/        (16394): 	Authentication Target: User
11-20 17:17:33.409 I/        (16394): 	, Authority Host: login.microsoftonline.com
11-20 17:17:33.410 V/        (16394): 2018-11-20T15:17:33.4107350Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Loading from cache.
11-20 17:17:33.415 I/        (16394): 2018-11-20T15:17:33.4156220Z: 00000000-0000-0000-0000-000000000000 - AdalLoggerBase.cs: Deserialized 1 items to token cache.
11-20 17:17:33.416 V/        (16394): 2018-11-20T15:17:33.4166270Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Looking up cache for a token...
11-20 17:17:33.435 I/        (16394): 2018-11-20T15:17:33.4351670Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: An old item was removed from the cache
11-20 17:17:33.435 V/        (16394): 2018-11-20T15:17:33.4358120Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Looking up cache for a token...
11-20 17:17:33.436 I/        (16394): 2018-11-20T15:17:33.4361960Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: No matching token was found in the cache
11-20 17:17:33.436 I/        (16394): 2018-11-20T15:17:33.4365820Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
11-20 17:17:33.438 V/        (16394): 2018-11-20T15:17:33.4385700Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Looking up cache for a token...
11-20 17:17:33.439 I/        (16394): 2018-11-20T15:17:33.4390900Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: No matching token was found in the cache
11-20 17:17:33.439 I/        (16394): 2018-11-20T15:17:33.4393170Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
11-20 17:17:33.440 V/        (16394): 2018-11-20T15:17:33.4406980Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Looking up cache for a token...
11-20 17:17:33.441 I/        (16394): 2018-11-20T15:17:33.4411260Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: No matching token was found in the cache
11-20 17:17:33.441 I/        (16394): 2018-11-20T15:17:33.4413370Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
11-20 17:17:33.442 V/        (16394): 2018-11-20T15:17:33.4426550Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Looking up cache for a token...
11-20 17:17:33.443 I/        (16394): 2018-11-20T15:17:33.4430780Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: No matching token was found in the cache
11-20 17:17:33.443 I/        (16394): 2018-11-20T15:17:33.4432860Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
11-20 17:17:33.445 V/        (16394): 2018-11-20T15:17:33.4448760Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Looking up cache for a token...
11-20 17:17:33.445 I/        (16394): 2018-11-20T15:17:33.4456030Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: No matching token was found in the cache
11-20 17:17:33.446 I/        (16394): 2018-11-20T15:17:33.4462430Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
11-20 17:17:33.467 V/        (16394): 2018-11-20T15:17:33.4673180Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Broker supports to add user through app
11-20 17:17:33.477 V/        (16394): 2018-11-20T15:17:33.4767460Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Broker supports to add user through app
11-20 17:17:33.477 V/        (16394): 2018-11-20T15:17:33.4774300Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: It switched to broker for context: Microsoft.Wally.Mobile.Android
11-20 17:17:33.477 V/        (16394): 2018-11-20T15:17:33.4777590Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: User is specified for background token request
11-20 17:17:33.487 V/        (16394): 2018-11-20T15:17:33.4870280Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Target account is not found
11-20 17:17:33.487 V/        (16394): 2018-11-20T15:17:33.4876440Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Token is not returned from backgroud call
11-20 17:17:33.488 V/        (16394): 2018-11-20T15:17:33.4880780Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Launch activity for Authenticator
11-20 17:17:33.488 V/        (16394): 2018-11-20T15:17:33.4884610Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Starting Authentication Activity
11-20 17:17:33.489 V/        (16394): 2018-11-20T15:17:33.4888540Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Initial request to authenticator
11-20 17:17:33.533 E/        (16394): 2018-11-20T15:17:33.5319590Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Exception type: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException
11-20 17:17:33.533 E/        (16394): , ErrorCode: failed_to_acquire_token_silently
11-20 17:17:33.533 E/        (16394): 
11-20 17:17:33.533 E/        (16394):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper.AcquireToken (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload) [0x00211] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:17:33.533 E/        (16394):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper+<>c__DisplayClass14_0.<AcquireTokenUsingBrokerAsync>b__0 () [0x00000] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:17:33.533 E/        (16394):   at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <fe08c003e91342eb83df1ca48302ddbb>:0 
11-20 17:17:33.533 E/        (16394):   at System.Threading.Tasks.Task.Execute () [0x00000] in <fe08c003e91342eb83df1ca48302ddbb>:0 
11-20 17:17:33.533 E/        (16394): --- End of stack trace from previous location where exception was thrown ---
11-20 17:17:33.533 E/        (16394):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper+<AcquireTokenUsingBrokerAsync>d__14.MoveNext () [0x000c8] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:17:33.542 E/        (16394): 2018-11-20T15:17:33.5424050Z: 32876229-fb5c-43e1-9979-97802c20a8a1 - AdalLoggerBase.cs: Exception type: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException
11-20 17:17:33.542 E/        (16394): , ErrorCode: failed_to_acquire_token_silently
11-20 17:17:33.542 E/        (16394): 
11-20 17:17:33.542 E/        (16394):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper.AcquireToken (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload) [0x00211] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:17:33.542 E/        (16394):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper+<>c__DisplayClass14_0.<AcquireTokenUsingBrokerAsync>b__0 () [0x00000] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:17:33.542 E/        (16394):   at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <fe08c003e91342eb83df1ca48302ddbb>:0 
11-20 17:17:33.542 E/        (16394):   at System.Threading.Tasks.Task.Execute () [0x00000] in <fe08c003e91342eb83df1ca48302ddbb>:0 
11-20 17:17:33.542 E/        (16394): --- End of stack trace from previous location where exception was thrown ---
11-20 17:17:33.542 E/        (16394):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper+<AcquireTokenUsingBrokerAsync>d__14.MoveNext () [0x000e5] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:17:33.542 E/        (16394): --- End of stack trace from previous location where exception was thrown ---
11-20 17:17:33.542 E/        (16394):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase+<RunAsync>d__53.MoveNext () [0x003d8] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:17:33.543 I/        (16394): 2018-11-20T15:17:33.5432130Z: 00000000-0000-0000-0000-000000000000 - AdalLoggerBase.cs: Serializing token cache with 0 items.
11-20 17:17:38.105 W/zygote  (16394): Checksum mismatch for dex base.apk
Thread started: <Thread Pool> #20
[0:] Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException: Failed to acquire token silently as no token was found in the cache. Call method AcquireToken
  at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper.AcquireToken (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload) [0x00211] in <243c572443ef40ad8dce3a888e14c5d4>:0 
  at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper+<>c__DisplayClass14_0.<AcquireTokenUsingBrokerAsync>b__0 () [0x00000] in <243c572443ef40ad8dce3a888e14c5d4>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <fe08c003e91342eb83df1ca48302ddbb>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <fe08c003e91342eb83df1ca48302ddbb>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper+<AcquireTokenUsingBrokerAsync>d__14.MoveNext () [0x000e5] in <243c572443ef40ad8dce3a888e14c5d4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase+<RunAsync>d__53.MoveNext () [0x0069c] in <243c572443ef40ad8dce3a888e14c5d4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext+<AcquireTokenSilentCommonAsync>d__44.MoveNext () [0x000c0] in <243c572443ef40ad8dce3a888e14c5d4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext+<AcquireTokenSilentAsync>d__30.MoveNext () [0x00089] in <243c572443ef40ad8dce3a888e14c5d4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Dww.Wally.Common.Security.Authenticator+<PerformAuthenticateAsync>d__7.MoveNext () [0x0008e] in C:\Ariel\OB\DWW\Client\src\Client\Wally\Wally.Common\Security\Authenticator.cs:45 
	ErrorCode: failed_to_acquire_token_silently

**Comment by jmprieur** [comment]
@arielbh : do you use the same version of the broker on all the devices?
Normally when the broker is installed, on Android, the token is cached by the broker, not ADAL.

**Comment by arielbh** [comment]
> @arielbh : do you use the same version of the broker on all the devices?
> Normally when the broker is installed, on Android, the token is cached by the broker, not ADAL.

@jmprieur Yes. Both uses Microsoft Authenticator Version: 6.3.10.

**Comment by jmprieur** [comment]
@arielbh : the `authContext.TokenCache.Clear()` would explain the behavior you see. 
Can you please share with me the full content of the AdalServiceException ?

**Comment by arielbh** [comment]
> @arielbh : the `authContext.TokenCache.Clear()` would explain the behavior you see.
> Can you please share with me the full content of the AdalServiceException ?

It is not. First it doesn't explain why it behaves different;y on different devices. Second, I've commented it out and it didn't change the behavior I've reported. Sadly.

It's actually not a AdalServiceException. It's ArgumentNullException
[0:] System.ArgumentNullException: Value cannot be null.
Parameter name: id
  at Microsoft.IdentityModel.Clients.ActiveDirectory.UserIdentifier..ctor (System.String id, Microsoft.IdentityModel.Clients.ActiveDirectory.UserIdentifierType type) [0x0000e] in <243c572443ef40ad8dce3a888e14c5d4>:0 
  at Microsoft.Dww.Wally.Common.Security.Authenticator+<PerformAuthenticateAsync>d__7.MoveNext () [0x00044] in C:\Ariel\OB\DWW\Client\src\Client\Wally\Wally.Common\Security\Authenticator.cs:47 
T

**Comment by henrik-me** [comment]
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
