### ISSUE TITLE
ADAL crashes without a way to catch it when there is no Internet connection

### ISSUE THREAD

**Issue by arielbh** [AzureAD/azure-activedirectory-library-for-dotnet#1417]
**Which Version of ADAL are you using ?**
ADAL 4.4.0

**Which platform has the issue?**
Xamarin.Forms on Android

**What authentication flow has the issue?**
Mobile Interactive + Broker

**Repro**

```csharp
    private string _userName = string.Empty;

        private async Task<AuthenticationResult> PerformAuthenticateAsync(string resource, object context,
            AuthenticationContext authContext)
        {
            

            try
            {
                var result = await authContext.AcquireTokenSilentAsync(resource, _configurationService.Auth.ClientId,
                    new UserIdentifier(_userName, UserIdentifierType.OptionalDisplayableId),
                    _platformAuthenticator.GetPlatformParameters(context));
                return GetAuthenticationResult(result);

            }
            catch (AdalServiceException ex) when (ex.Message == "User canceled authentication")
            {
                authContext.TokenCache.Clear();
                var result = await authContext.AcquireTokenAsync(resource, _configurationService.Auth.ClientId,
                    _platformAuthenticator.RedirectUri ?? _defaultRedirectUri,
                    _platformAuthenticator.GetPlatformParameters(context));
                return GetAuthenticationResult(result);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                authContext.TokenCache.Clear();
                var result = await authContext.AcquireTokenAsync(resource, _configurationService.Auth.ClientId,
                    _platformAuthenticator.RedirectUri ?? _defaultRedirectUri,
                    _platformAuthenticator.GetPlatformParameters(context));
                _userName = result.UserInfo.DisplayableId;
                return GetAuthenticationResult(result);
            }
        }
```

**Expected behavior**
In case there is no internet from any reason to the device, it shouldn't crash the app. it should allow the developers the catch the issue and present the user with the relevant information. Note that even crashes when the device is connected to the WiFi but from some reason, no internet connection is available.

**Actual behavior**
When there is no internet connection the app crashes.

**Additional context/ Logs / Screenshots**
11-20 17:20:56.754 E/mono    (16806): Unhandled Exception:
11-20 17:20:56.754 E/mono    (16806): System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: NameResolutionFailure
11-20 17:20:56.754 E/mono    (16806):   at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x00044] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.754 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x000cc] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.755 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at System.Net.WebOperation+<Run>d__57.MoveNext () [0x0009a] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.755 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at System.Net.WebCompletionSource`1+<WaitForCompletion>d__15[T].MoveNext () [0x00094] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.755 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__241`1[T].MoveNext () [0x000c5] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.755 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.755 E/mono    (16806):   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <fe08c003e91342eb83df1ca48302ddbb>:0 
11-20 17:20:56.755 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <25ebe1083eaf4329b5adfdd5bbb7aa57>:0 
11-20 17:20:56.755 E/mono    (16806):    --- End of inner exception stack trace ---
11-20 17:20:56.755 E/mono    (16806):   at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <25ebe1083eaf4329b5adfdd5bbb7aa57>:0 
11-20 17:20:56.755 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at System.Net.Http.HttpClient+<SendAsyncWorker>d__49.MoveNext () [0x000ca] in <25ebe1083eaf4329b5adfdd5bbb7aa57>:0 
11-20 17:20:56.755 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper+<GetResponseAsync>d__28.MoveNext () [0x0025c] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.755 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient+<GetResponseAsync>d__23`1[T].MoveNext () [0x0010e] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.755 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient+<GetResponseAsync>d__22`1[T].MoveNext () [0x0006d] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.755 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.755 E/mono    (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.InstanceDiscovery+<DiscoverAsync>d__10.MoveNext () [0x000cd] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.InstanceDiscovery+<GetMetadataEntryAsync>d__6.MoveNext () [0x00141] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator+<UpdateFromTemplateAsync>d__47.MoveNext () [0x000ce] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase+<PreRunAsync>d__60.MoveNext () [0x00076] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase+<RunAsync>d__53.MoveNext () [0x0069c] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext+<AcquireTokenCommonAsync>d__43.MoveNext () [0x000e8] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext+<AcquireTokenAsync>d__31.MoveNext () [0x0008b] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at Microsoft.Dww.Wally.Common.Security.Authenticator+<PerformAuthenticateAsync>d__7.MoveNext () [0x00301] in C:\Ariel\OB\DWW\Client\src\Client\Wally\Wally.Common\Security\Authenticator.cs:63 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at Microsoft.Dww.Wally.Common.Security.Authenticator+<AuthenticateAsync>d__4.MoveNext () [0x00069] in C:\Ariel\OB\DWW\Client\src\Client\Wally\Wally.Common\Security\Authenticator.cs:26 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at Microsoft.Dww.Wally.Mobile.Services.MobileApplicationService+<Initialize>d__9.MoveNext () [0x0005b] in C:\Ariel\OB\DWW\Client\src\Mobile\Wally.Mobile\Wally.Mobile\Services\MobileApplicationService.cs:50 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at Microsoft.Dww.Wally.Mobile.ViewModels.BootstrapViewModel+<<get_LaunchCommand>b__18_0>d.MoveNext () [0x0003d] in C:\Ariel\OB\DWW\Client\src\Mobile\Wally.Mobile\Wally.Mobile\ViewModels\BootstrapViewModel.cs:100 
11-20 17:20:56.756 E/mono    (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.756 E/mono    (16806):   at (wrapper dynamic-method) System.Object.25(intptr,intptr)
11-20 17:20:56.756 E/mono    (16806):   at (wrapper native-to-managed) System.Object.25(intptr,intptr)
11-20 17:20:56.768 E/mono-rt (16806): [ERROR] FATAL UNHANDLED EXCEPTION: System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: NameResolutionFailure
11-20 17:20:56.768 E/mono-rt (16806):   at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x00044] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x000cc] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at System.Net.WebOperation+<Run>d__57.MoveNext () [0x0009a] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at System.Net.WebCompletionSource`1+<WaitForCompletion>d__15[T].MoveNext () [0x00094] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__241`1[T].MoveNext () [0x000c5] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <3e9b3e26c4694baab3f689687ad40612>:0 
11-20 17:20:56.768 E/mono-rt (16806):   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <fe08c003e91342eb83df1ca48302ddbb>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <25ebe1083eaf4329b5adfdd5bbb7aa57>:0 
11-20 17:20:56.768 E/mono-rt (16806):    --- End of inner exception stack trace ---
11-20 17:20:56.768 E/mono-rt (16806):   at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <25ebe1083eaf4329b5adfdd5bbb7aa57>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at System.Net.Http.HttpClient+<SendAsyncWorker>d__49.MoveNext () [0x000ca] in <25ebe1083eaf4329b5adfdd5bbb7aa57>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper+<GetResponseAsync>d__28.MoveNext () [0x0025c] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient+<GetResponseAsync>d__23`1[T].MoveNext () [0x0010e] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient+<GetResponseAsync>d__22`1[T].MoveNext () [0x0006d] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.InstanceDiscovery+<DiscoverAsync>d__10.MoveNext () [0x000cd] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.InstanceDiscovery+<GetMetadataEntryAsync>d__6.MoveNext () [0x00141] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator+<UpdateFromTemplateAsync>d__47.MoveNext () [0x000ce] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase+<PreRunAsync>d__60.MoveNext () [0x00076] in <243c572443ef40ad8dce3a888e14c5d4>:0 
11-20 17:20:56.768 E/mono-rt (16806): --- End of stack trace from previous location where exception was thrown ---
11-20 17:20:56.768 E/mono-rt (16806):   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase+<RunAsync>d__53.MoveNext (
11-20 17:20:56.790 E/libEGL  (16806): validate_display:171 error 3008 (EGL_BAD_DISPLAY)
11-20 17:20:56.790 I/chatty  (16806): uid=10161(Microsoft.Wally.Mobile.Android) RenderThread identical 2 lines
11-20 17:20:56.790 E/libEGL  (16806): validate_display:171 error 3008 (EGL_BAD_DISPLAY)
11-20 17:20:56.790 D/OpenGLRenderer(16806): eglQuerySurface
11-20 17:20:56.790 E/libEGL  (16806): validate_display:171 error 3008 (EGL_BAD_DISPLAY)
11-20 17:20:56.790 I/OpenGLRenderer(16806): Checking abandoned damageFrame
11-20 17:20:56.790 I/OpenGLRenderer(16806): Surface query width is 1200
11-20 17:20:56.791 F/OpenGLRenderer(16806): Failed to set damage region on surface 0xc1f136a0, error=EGL_BAD_DISPLAY
11-20 17:20:56.792 F/libc    (16806): Fatal signal 6 (SIGABRT), code -6 in tid 16862 (RenderThread), pid 16806 (.Mobile.Android)

**Comment by bgavrilMS** [comment]
Hi @arielbh - I had a look at this. Indeed, if the phone is in "Airplane mode" or no connection is available, you get an HttpRequestException. This is a System.Net.Http exception, so you can easily catch it and handle it. 

Looking at the code, I see that we do throw an AdalException only on .net desktop, but the check is quite weak - it only checks that a network connetion exists, even if there is no Internet. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/000412ef82e02741236f1b4d05304d339db8d8a6/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/WebUI.cs#L103 

There is a work item (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/592) to improve the experience on MSAL, and I am tempted to say that we would only implement it there, since there is an easy workaround for ADAL and we are focusing on MSAL for the future. (CC @jmprieur , @henrik-me ) . Is this acceptable?

**Comment by bgavrilMS** [comment]
Oh, and looking at your code: 

1. You should not clear the cache if the authentication fails, that's quite extreme -> the user will have to perform interactive auth again
2. Pretty much all of the AcquireToken* methods will make network calls. So what you code will do: 

- try to acquire a token silent --> fail because of the HttpRequestException
- catch this exception and perform an acquireToken --> fail because of HttpRequestException (I believe this is why you have the impression that the exception is somehow unhanlded)

My suggestion is to have a big try / catch on all this method and treat HttpRequestException, e.g. by showing a "Network down" message to your users.
