### ISSUE TITLE
Issue upgrading ADAL 3.x to 4.x on Android

### ISSUE THREAD

**Issue by CryogenicPotato** [AzureAD/azure-activedirectory-library-for-dotnet#1422]
**Which Version of ADAL are you using ?**
4.4.1

**Which platform has the issue?**
Xamarin Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**
Upgrade NuGet package in a native Xamarin.Android project from ver. 3.19.8 to ver. 4.4.1, I am unable to resolve reference to **AuthenticationAgentContinuationHelper** and the **AcquireTokenAsync** method does not support PlatformParameters anymore.

![schermata 2018-11-21 alle 09 51 57](https://user-images.githubusercontent.com/36990292/48830408-d6c4a180-ed74-11e8-9b10-39163dbe4baa.png)

![schermata 2018-11-21 alle 09 53 23](https://user-images.githubusercontent.com/36990292/48830372-beed1d80-ed74-11e8-8338-ffecdca3b9e5.png)

**Expected behavior**
Due to the documentation I expect the class AuthenticationAgentContinuationHelper to exist and the AcquireTokenAsync method to accept PlatformParameters on Android as well.

**Actual behavior**
AuthenticationAgentContinuationHelper is unresolved and PlatformParameters with PromptBehavior constructor is not available anymore.

**Possible Solution**
Check the AuthenticationAgentContinuationHelper for Xamarin.Android and bring back the same old constructor for AcquireTokenAsync method.

**Comment by jmprieur** [comment]
@CryogenicPotato, as you probably know, ADAL.Net provides a Nuget package containing several DLL, one by [supported platform](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/ADAL.NET-supports-multiple-application-architectures-and-multiple-platforms#adalnet-supports-multiple-platforms). We've seen cases were NuGet did not upgrade to the right platform.
Can you please make sure that the DLL that was picked-up (HintPath in your project) is the `monoandroid8.1` implementation?

**Comment by CryogenicPotato** [comment]
@jmprieur yes I guess you were right, the value we see is targetFramework="monoandroid71"

now we raised the Android target framework of the project to 8.1 and the errors went away.

Thank you

**Comment by jmprieur** [comment]
thanks for the update @CryogenicPotato
