### ISSUE TITLE
Incremental consent question

### ISSUE THREAD

**Issue by dmcweeney** [AzureAD/azure-activedirectory-library-for-dotnet#1425]
Folks,

I have been trying to implement incremental consent handling but on ASP.Net Core 2.1 via a piece of middleware the works kindof like the OAuth2CoreRedeemerMiddleware in the ASP.Net sample.

I have configured my middleware after the UseAuthentication middleware and in the OpenIdConnectOptions configuration set the SkipUnrecognizedRequests = true.

However the Asp.Net Core middleware kicks out with a "Correlation failed." error.

So I am starting to think I should be implementing this in the MessageReceived handler?
Am I correct in this thinking?

Other problem is that the HttpContext.User is not being set at this level.

Is there any Asp.Net Core 2 samples coming down the line?

Thanks

Donal

**Comment by dmcweeney** [comment]
Hi,

Just some updates...

If I set a custom callback path I get the AAD callback path not registered error.

A sample of the callback url coming into the app is:
GET /signin-oidc?code=theBigLongCode&state=eecfbc7c-e9a5-4f57-a20e-0e357191efec&session_state=80dee8cb-f80d-499c-a9c2-112c201d7fae

If I call UseAuthentication() before I call UseMyMiddleware(), the Asp.Net Core authentication middleware kicks out with a "Correlation failed." error.
The problem is happening in the OpenIdConnectHandler.HandleRemoteAuthenticateAsync(). As far as I can see there is not any logic in this method to skip the handler, once the request is targeted at the signin callback path.
See: [here](https://github.com/aspnet/Security/blob/26d27d871b7992022c082dc207e3d126e1d9d278/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L433
) and [here](https://github.com/aspnet/Security/blob/26d27d871b7992022c082dc207e3d126e1d9d278/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L517
)

Also in this case, in the MessageReceived handler there is not a an authenticated user on the httpContext.

If I call UseMyMiddleware() before I call UseAuthentication(), my middleware kicks in but I dont have an authenticated user on the httpContext. I can cache the users's tenantId and userId in the state cache I have on my server when I generate the authorization url - that way I can bind to the correct token cache entry for the user on the callback.

But does this create a small security issue?
Is there any other way to get this working on Asp.Net Core 2.1?

Thanks, Donal

**Comment by jmprieur** [comment]
Helllo @dmcweeney 
This question is more for https://github.com/aspnet/security, not ADAL.NET

Do you mind posting it there? (and cross reference to help others)
Thanks!

And there are ASP.NET Core 2.1 samples coming, such as https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 (and incremental consent is next on our list)

This sample is not an ASP.NET Core 2.1 sample, but it illustrates incremental consent: https://github.com/azure-samples/active-directory-dotnet-daemon-v2 (even admin consent, in fact)

**Comment by dmcweeney** [comment]
@jmprieur will add question to [security](https://github.com/aspnet/security) but wont be until at least tomorrow at this stage...

**Comment by jmprieur** [comment]
@dmcweeney.
I've asked them the question and am working on improving the ASP.NET Core 2.1 sample (this is the [part](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/aspnetcore2-2-signInAndCallGraph/Controllers/HomeController.cs#L50) I'm improving).

The principal is that we can send a challenge overriding the scopes. Imagine you want new `scopes` (in MSAL.NET), or resources in ADAL.NET

below with v2.0 / MSAL.NET:
```CSharp
  string[] additionalBuildInScopes = new string[] { "openid", "offline_access",  "profile" }; // needed by ADAL.NET and MSAL.NET
  AuthenticationProperties properties = new AuthenticationProperties();
  properties.SetParameter<ICollection<string>>(OpenIdConnectParameterNames.Scope, 
                                                                              scopes.Union(additionalBuildInScopes).ToList());
 return Challenge(properties);
```

I'm still working on it and hope to have a fully working sample by the end of the week.

**Comment by dmcweeney** [comment]
@jmprieur thanks for this - it should help in figuring out how to get through the OpenIdConnectHandler.

Just some background... my app is composed of a web server running on Azure App service, which spools an SPA when invoked and the client interacts with the web app using web api calls.

The incremental consent requirements arise in the backend processing of a subset of the web api calls. 

When this happens I use the ConfidentialClientApplication.GetAuthorizationRequestUrlAsync(). The web api returns an error code and the authorization requestUrl to the client SPA.
The client side code navigates to that url.
AAD password prompt is displayed - password is entered.
AAD additional consent prompt is displayed - Additional scopes are consented.
AAD redirects to the callback path on the server...
The OpenIdConnectHandler handles the request and fails with the correlation failure occurs because there is no correlation cookie!

Slightly more complex!

**Comment by dmcweeney** [comment]
@jmprieur think I have the answer...

In the OpenIdConnectEvents.MessageReceived handler inject some code to test if the request url is for a code redemption request. If it is then

```
messageReceivedContext.SkipHandler() ;
return Task.FromResult( 0 );
```
The "incremental consent" code redemption callback url looks like:
GET /signin-oidc?code=theBigLongCode&state=eecfbc7c-e9a5-4f57-a20e-0e357191efec&session_state=80dee8cb-f80d-499c-a9c2-112c201d7fae

The "normal consent" callback looks like:
POST /signin-oidc
code=theCode
&id_token=theIdToken
&state=BigLongStatestr
&session_state=aGuid

Really the only "safe" differences to test for are:-
- Method - POST v GET
- there is no id_token 
- state is a Guid compared to a long encoded string

**Comment by jmprieur** [comment]
Thanks for the update, @dmcweeney 
I've added a PR for incremental consent in a Web App: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/24

Can we close this issue?

**Comment by dmcweeney** [comment]
@jmprieur looking forward to seeing the other IC samples that come out over time. Closing but will reopen if needs be...

**Comment by jmprieur** [comment]
Thanks @dmcweeney
