### ISSUE TITLE
Constant for Ocp-Apim-Subscription-Key

### ISSUE THREAD

**Issue by vanillajonathan** [AzureAD/azure-activedirectory-library-for-dotnet#1426]
**Is your feature request related to a problem? Please describe.**
In all my projects I do:
```cs
client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", _options.SubscriptionKey);
```
So I have to repeat the hard-coded "Ocp-Apim-Subscription-Key" string in my projects.

**Describe the solution you'd like**
An easy way to add my Ocp-Apim-Subscription-Key to the outgoing HTTP requests sent by my `HttpClient`.

**Additional context**
Consider adding a constant for `Ocp-Apim-Subscription-Key`, or an `AddOcpApimSubscriptionKey` extension method.

**Comment by jmprieur** [comment]
@vanillajonathan : is it a request on ADAL.NET?
Can you please use the provided template to add issues to the ADAL.NET repo (with repro steps)

**Comment by vanillajonathan** [comment]
@jmprieur It is for the [Microsoft.IdentityModel.Clients.ActiveDirectory](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/) package.

**Comment by jmprieur** [comment]
@vanillajonathan : I don't understand what your scenario is. I don't know what the Apim subscription key is. Can you please elaborate what your scenario is? what code you'd like to write to solve which problem? in which context do you use ADAL.NET ?

**Comment by vanillajonathan** [comment]
The "Ocp-Apim-Subscription-Key" is used by by the [Azure API Management](https://azure.microsoft.com/en-us/services/api-management/) service.

It is mentioned in the [Import and publish your first API](https://docs.microsoft.com/en-us/azure/api-management/import-and-publish) article.

The Azure API Management service sits in front of my Web APIs (and provides features such as rate limiting, etc).
To call my Azure API Management service I need to provide the `Ocp-Apim-Subscription-Key` header along with every HTTP request.

I use ADAL to get get an access token that I supply as a Bearer token to authenticate my HTTP requests.

```cs
private async Task<HttpClient> GetClient()
{
    var client = new HttpClient();
    var token = await GetTokenAsync(); // AcquireTokenAsync using ADAL

    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
    client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", _options.OcpApimSubscriptionKey);
    
    return client;
}
```

**Comment by jmprieur** [comment]
@vanillajonathan 
ADAL.NET is an authentication library. It's used to acquire tokens for many Web APIs, not only the Azure API Management service

This seems a good suggestion for the [Azure SDK for .NET and .NET Core](https://docs.microsoft.com/en-us/dotnet/azure/), though or for the https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.apimanagement?view=azure-Dotnet nuget package.

Closing this issue as won't fix for ADAL.NET, but I think you should raise it in the Azure SDK. for .NET: https://github.com/Azure/azure-sdk-for-net

**Comment by vanillajonathan** [comment]
You are right. Thank you for pointing me in the right direction.

**Comment by vanillajonathan** [comment]
Cross-reference: Azure/azure-sdk-for-net/issues/5052

**Comment by jmprieur** [comment]
Thanks for the cross reference @vanillajonathan !
