### ISSUE TITLE
Silent authentication not working with multiple resources

### ISSUE THREAD

**Issue by Sathis81** [AzureAD/azure-activedirectory-library-for-dotnet#1427]
When upgrading ADAL latest version (4.1.0-Preview or above) in our application, the Silent Token is not working. 
We are using multiple resourceURI in our application and it is asking authentication for each resourceURI’s. 
The same problem was there in below 3.16.0 versions and it was fixed in 3.19.0 version. But the same problem we are facing with latest versions (4.1.0 & above).

We are using Visual Studio 2017 (15.8.2) & Authenticator app (6.3.10) & Xamarin.Forms (3.4.0.1008975)

**Comment by henrik-me** [comment]
@Sathis81 : Can you pls. provide repro steps? Please also use the template for opening bugs as that will ensure we get all the information we need to investigate the issue.

**Comment by jmprieur** [comment]
@jennyf19 : can this be also related to the work you've been doing?

**Comment by jennyf19** [comment]
@jmprieur - not sure. I have only looked at the MSAL cache. Would need to dive into ADAL and check what we are doing there. But based on the error, sounds like a similar issue.

**Comment by jennyf19** [comment]
@Sathis81 @AshleyAsh90 Are you both using Authenticator?

**Comment by AshleyAsh90** [comment]
@jennyf19  I am not using Authenticator app.

**Comment by bgavrilMS** [comment]
@Sathis81  - we have made some fixes around Android + Authenticator in ADAL 4.5.0. Please try it out. If still fails, please email full logs (including pii) to bogavril@microsoft.com
