### ISSUE TITLE
Can we get user alias from access token

### ISSUE THREAD

**Issue by John12x** [AzureAD/azure-activedirectory-library-for-dotnet#1437]
I have an MVC app accessing WEB API through azure aad access token, I have a requirement to read user alias from access token.

How can I do that. 

Any code samples/references are much appreciated.

**Comment by jmprieur** [comment]
You should not read anything from the access token yourself. The access token could become encrypted in the future, and your application would break. 
ASP.NET delegates this to the [Microsoft Identity Extension for .NET](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) library to do it, and populates the ClaimsPrincipal object with the claims.

If you are working with ASP.NET Core, the claims principal is the .User property of the HttpContext which is everywhere (including in the controllers).
Then from the claims principal, you can use

```CSharp
claimsPrincipal.FindFirstValue("preferred_username");
```

You could have a look at this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/aspnetcore2-2-signInAndCallGraph/Extensions/ClaimPrincipalExtension.cs
