### ISSUE TITLE
AcquireTokenSilent

### ISSUE THREAD

**Issue by leflaco83** [AzureAD/azure-activedirectory-library-for-dotnet#144]
Hi! I'm having this exception when trying to run the AcquireTokenSilent method on AuthenticationContext class : 
AdalSilentTokenAcquisitionException
Message : Failed to acquire token silently. Call method AcquireToken.

I'm following this sample code https://github.com/AzureADSamples/WebApp-WebAPI-OpenIDConnect-DotNet, so the scenario is the same. I searched on the web but every solution I found wasn't the right one. I also took a look at the source code and I found this code in the AcquireTokenSilentHandler class  :

```c#
protected override Task<AuthenticationResult> SendTokenRequestAsync()
{
    Logger.Verbose(this.CallState, "No token matching arguments found in the cache");
    throw new AdalSilentTokenAcquisitionException();
}
```
So, is this feature not implemented or I just can't figure out what is going on?

Thanks a lot.

Rodrigo

**Comment by vibronet** [comment]
The feature is definitely implemented. Are you executing the example code precisely as is, or did you modify anything in it? Typical issues with AcquireTokenSilent in web scenarios are:
- The cache is empty. AcquireTokenSilent works by returning cached tokens or using refresh tokens from the cache. In the OpenId Connect samples, the application first acquires access and refresh tokens at sign in time and places them in a cache instance. If something happens to the cache between that time and the time in which you call AcquireTokenSilent, or if you fail to initialize AuthenticationContext with the exact same cache instance, the request will fail.
- The cache contains more than one token matching the parameters, for example for 2 different users. In that case ADAL needs more info (like the ID of the user you want ta token for) to disambiguate the request
- You are requesting a token from a new AAD tenant. Refresh tokens in the cache will work for requesting new tokens only from the same tenant they were originally issued from
You can verify in which situation you are by inspecting the content of the cache before making your AcquireTokenSilent call, simply call myAuthContext.TokenCache.ReadItems and examine the results in the debugger.
HTH

**Comment by leflaco83** [comment]
Hi Vittorio, thanks a lot for the quick response. You are right, I think I misunderstood the samples and my scenario its a little bit different. Thing is I didn't get a token before a call to AcquireTokenSilent.

Regards, 
Rodrigo

**Comment by MJems** [comment]
I am getting same error, actually i converted application to ASP.NET, and checked all 3 scenario mentioned on above comment, and those are fine. still getting same issue.

can you please help me to fix this issue ASAP.

**Comment by kpanwar** [comment]
If you use the latest 2.24 then you will get an inner exception that will tell you why acquire token silent failed. Can you check and share the details.

**Comment by MJems** [comment]
Here is the complete source code. This is website so open this as website not project.
[WebSite15.zip](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/files/240045/WebSite15.zip)

**Comment by MJems** [comment]
I converted this into ASP.NET, and when it called below code(AcquireTokenSilentAsync) nothing happened. on above thread code is attached.

`internal static async Task EnsureOutlookServicesClientCreatedAsync(string capabilityName)
{
var signInUserId = ClaimsPrincipal.Current.FindFirst(ClaimTypes.NameIdentifier).Value;
var userObjectId = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
var tenantId = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;

    AuthenticationContext authContext = new AuthenticationContext(string.Format("{0}/{1}", SettingsHelper.AuthorizationUri, tenantId), new ADALTokenCache(signInUserId));

    try
    {
        DiscoveryClient discClient = new DiscoveryClient(SettingsHelper.DiscoveryServiceEndpointUri,
            async () =>
            {
                var authResult = await authContext.AcquireTokenSilentAsync(SettingsHelper.DiscoveryServiceResourceId, new ClientCredential(SettingsHelper.ClientId, SettingsHelper.AppKey), new UserIdentifier(userObjectId, UserIdentifierType.UniqueId));

                return authResult.AccessToken;
            });

        var dcr = await discClient.DiscoverCapabilityAsync("Contacts");

        return new OutlookServicesClient(dcr.ServiceEndpointUri,
            async () =>
            {
                var authResult = await authContext.AcquireTokenSilentAsync(dcr.ServiceResourceId, new ClientCredential(SettingsHelper.ClientId, SettingsHelper.AppKey), new UserIdentifier(userObjectId, UserIdentifierType.UniqueId));

                return authResult.AccessToken;
            });
    }
    catch (AdalException exception)
    {
        //Handle token acquisition failure
        if (exception.ErrorCode == AdalError.FailedToAcquireTokenSilently)
        {
            authContext.TokenCache.Clear();
            throw exception;
        }
        return null;
    }
    catch (Exception ex)
    {

        throw;
    }
}`

**Comment by MJems** [comment]
It get fixed, working now.
