### ISSUE TITLE
generateRedirectUriForBroker.ps1 doesn't work or include support for non-Windows platforms

### ISSUE THREAD

**Issue by ghost** [AzureAD/azure-activedirectory-library-for-dotnet#1451]
**Which Version of ADAL are you using ?**
ADAL 3.19.8, ADAL 4.4.1

**Which platform has the issue?**
Mac OS X, Windows 10

**What authentication flow has the issue?**
N/A

Other? - please describe;
The issue is coming in with the script that is used to generate the Redirect URI for Android called generateRedirectUriForBroker.ps1 which the documentation clearly states you should use.  This script has the following issues:

1.)  It's built for Windows only.  Calling COM objects and then a batch script doesn't work on the Mac, which a lot of Xamarin developers use.

2.)  It calls out to signature.cmd which I can't find anywhere in the repo.

**Repro**

**Expected behavior**
Expect the script to run on all platforms that would be use for Android and that PowerShell supports of which Mac OS X is an environment that Android can and is used and PowerShell runs on Mac OS X without issues.

**Actual behavior**
The script will not run.  

**Possible Solution**
Write script to be cross platform and not call out to batch files or scripts not included in the repo.

**Additional context/ Logs / Screenshots**

**Comment by lvita** [comment]
Even on Windows, it's not clear where to find that signature.cmd file.

**Comment by bgavrilMS** [comment]
If you configure some random redirect uri, then you will get a runtime exception complaining that the uri is not correct. The exception will tell you which redirect uri to use.

**Comment by rbev** [comment]
@bgavrilMS yes and you can but generating a production-signed build may require gated checkins etc, so you need to be able to determine this string ahead of time for the production builds.

here's the contents signature.cmd from before it vanished from the repo, note that it will still return a string even if you get the password/ wrong.

```
::	Broker RedirectUri
::
:: 1- Please copy your debug.keystore file into desktop from
:: 	your "C:\users\yourname\.android" folder
:: 2- Run this in git console or install openssl
:: 3- Java Jdk is needed for keytool.exe
@echo off
REM Set your folders here
:: %1 JDK bin
:: %2 store pass
:: %3 alias
:: %4 keystore full path
:: %5 openssl path
%1 -storepass %2 -exportcert -alias %3 -keystore %4 | %5 sha1 -binary |  %5 base64 > tag.txt
```

**Comment by rbev** [comment]
For those who are interested in a powershell-only solution I ended up using `keytool -list` to get a non-binary version of the SHA1 hash.

```
	$keysOutput = & $keytool -storepass $pass -list -keystore $key_store 
	write-verbose ([String]::Join("`r`n", $keysOutput))
```

From there you just need to parse the output and convert the hex strings into base64, which is fairly trivial with regex and `System.Convert`
I ended up just printing a redirectUri for every key in the keystore, clearly that's not ideal on a large keystore but worked great for me.

**Comment by jmprieur** [comment]
@jennyf19 : shouldn't we re-add the scripts?
do we want to update the wiki with the suggestion above?
Is it the same for MSAL.NET ?

**Comment by henrik-me** [comment]
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
