### ISSUE TITLE
AuthenticationContext authority changed when AcquireTokenAsync(string resource, ClientCredential clientCredential) is called

### ISSUE THREAD

**Issue by LaurensAdema** [AzureAD/azure-activedirectory-library-for-dotnet#1453]
**Which Version of ADAL are you using ?**
ADAL 4.0.0-preview and up

**Which platform has the issue?**
netcore

**What authentication flow has the issue?**
Acquiring application token for Graph API

**Repro**

```csharp
string AuthString = string.Format("https://login.microsoftonline.com/{0}/oauth2/token", Config.TenantId);
string ResourceUrl = "https://graph.microsoft.com/";

AuthenticationContext authenticationContext = new AuthenticationContext(AuthString, true);
ClientCredential clientCred = new ClientCredential(Config.ApplicationId, Config.ApplicationSecret);
try
{
    AuthenticationResult authenticationResult = await authenticationContext.AcquireTokenAsync(ResourceUrl, clientCred);
    return authenticationResult.AccessToken;
}
catch (Exception e)
{
    throw;
}
```

**Expected behavior**
A request to https://login.microsoftonline.com/{0}/oauth2/token should be made, which would return a token.

**Actual behavior**
A request to https://login.microsoftonline.com/token/oauth2/token is made. Which results in "AADSTS90002: Tenant token not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator."

**Possible Solution**
Something in the flow of AcquireTokenAsync(string resource, ClientCredential clientCredential) changes the authority in the AuthenticationContext to "https://login.microsoftonline.com/token/oauth2/token"

**Additional context/ Logs / Screenshots**
Fiddler screenshot of request made from 4 and up
![image](https://user-images.githubusercontent.com/10165658/49525648-7ffbb380-f8ae-11e8-97cf-de92a7ea59fd.png)
Fiddler screenshot of request made from latest (4.4.1)
![image](https://user-images.githubusercontent.com/10165658/49526616-7a9f6880-f8b0-11e8-8ba1-6b885a5da6f0.png)
Fiddler screenshot of request made from 3.19.8
![image](https://user-images.githubusercontent.com/10165658/49526277-c998ce00-f8af-11e8-9434-d28f7d51bbbe.png)
Confirmation of correct auth context
![image](https://user-images.githubusercontent.com/10165658/49525970-2d6ec700-f8af-11e8-90ef-0ae822358ef4.png)

**Comment by jmprieur** [comment]
@LaurensAdema, `https://login.microsoftonline.com/{0}/oauth2/token`  is not an authority, it's an endpoint. The authority is `https://login.microsoftonline.com/{0}/`

your code should be:
```CSharp
string AuthString = string.Format("https://login.microsoftonline.com/{0}/", Config.TenantId);
```

In ADAL 4.x we have made the verification of the authority more strict than in ADAL 3.x

cc: @henrik-me

**Comment by henrik-me** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1346

**Comment by LaurensAdema** [comment]
Confirmed working, thanks for the info!
