### ISSUE TITLE
AcquireTokenSilentAsync returns adalSilentTokenException on consecutive calls with message"Failed to acquire token silently as no token was found in the cache". 

### ISSUE THREAD

**Issue by AshleyAsh90** [AzureAD/azure-activedirectory-library-for-dotnet#1454]
**Which Version of ADAL are you using ?**
ADAL 4.4.1

**Which platform has the issue?**
.net Standard

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**

```csharp
Code derived from ref: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token

AuthenticationContext ac = new AuthenticationContext(authority);
AuthenticationResult result=null;
try
{
 result = await ac.AcquireTokenSilentAsync(resource, clientId);
}
catch (AdalException adalException)
{
 if (adalException.ErrorCode == AdalError.FailedToAcquireTokenSilently
     || adalException.ErrorCode == AdalError.InteractionRequired)
  {
   result = await ac.AcquireTokenAsync(resource, clientId, redirectUri,
                                       new PlatformParameters(PromptBehavior.Auto));
  }
}
```

**Expected behavior**
On calling the method with above code in a reasonable timeframe where the token shouldn't expire, Return the previously acquired token before going into the AcquireTokenAsync call a second time

**Actual behavior**
AdalSilentTokenException with message
{Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException: Failed to acquire token silently as no token was found in the cache. Call method AcquireToken
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenSilentHandler.SendTokenRequestAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.CheckAndAcquireTokenUsingBrokerAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenSilentCommonAsync(String resource, ClientKey clientKey, UserIdentifier userId, IPlatformParameters parameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenSilentAsync(String resource, String clientId, UserIdentifier userId)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenSilentAsync(String resource, String clientId)
   at{}
	ErrorCode: failed_to_acquire_token_silently}

**Possible Solution**
Just let it Call AcquireTokenAsync as part of catch block

**Additional context/ Logs / Screenshots**
Please see the article ref:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token

**Comment by jmprieur** [comment]
@AshleyAsh90 : If the code you use is this one, then I see that you re-create the AuthenticationContext each time without using the cache parameter in the constructor of Authentication. Therefore the token cache will always be empty each time (assuming you are running on .NET Desktop or .NET Core)

You probably want to keep the AuthenticationContext in a variable, and just call the code in the try/catch block several times in a reasonable timeframe where the token shouldn't expire

I suggest you have a look at one of our samples, for instance https://github.com/azure-samples/active-directory-dotnet-native-desktop.

**Comment by AshleyAsh90** [comment]
Hi @jmprieur 
"-->You probably want to keep the AuthenticationContext in a variable, and just call the code in the try/catch block several times in a reasonable timeframe where the token shouldn't expire"

I had the AuthenticationContext defined as a global variable and just had the try catch block called each time. It wasn't re-initialized in each call.  

-->If the code you use is this one, then I see that you re-create the AuthenticationContext each time without using the cache parameter in the constructor of Authentication. Therefore the token cache will always be empty each time (assuming you are running on .NET Desktop or .NET Core)

This is true, I donot use the TokenCache param in my calls. Should I be using that? I do not see any examples suggesting to use that and the link you provided has the same link I have referenced in regards to using the AcquireTokenSilentAsync at the bottom. I am a little lost here. Could you kindly help?

**Comment by jmprieur** [comment]
if you don't re-create the authentication context (which is when you pass-in the token cache), you are fine.
Do you want to share your code with me, so that I have a look?
Jean-Marc.Prieur at Microsoft.com

**Comment by AshleyAsh90** [comment]
By re-creating you mean re-initializing right? Just so we are on the same page. 
Ok here is the code, I am just calling the getTokenAsync method with the _authContext predefined
```C#
async Task getTokenAsync()
{
if(setCredentials)
 {
      try
           {
            _authResult = await _authContext.AcquireTokenSilentAsync(_ap.Resource, _creds.ClientId);
           }
     catch(AdalSilentTokenAcquisitionException adalSilentTokenException)
           {
             if (adalSilentTokenException.ErrorCode == AdalError.FailedToAcquireTokenSilently || adalSilentTokenException.ErrorCode == AdalError.InteractionRequired)
                {
                    _authResult = await _authContext.AcquireTokenAsync(_ap.Resource, _creds).Result;
                }
            }
 if(_authResult.AcessToken !=null)
        {
          token=_AuthResult.AccesToken
        }

}
```
Sorry my formatting maybe messed up. Thanks for helping me !

**Comment by yuriiharasymovych** [comment]
Gents, 
I'm encountering the same. Is there any specifics how to create Authentication context ?
Btw, I'm using the same code for AuthenticationContext initialization as @AshleyAsh90

**Comment by AshleyAsh90** [comment]
@jmprieur Is this related to issue #1427 ?
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1427

**Comment by ajaysbsic** [comment]
Hi, I am stuck in the same problem , any suggestion?

**Comment by AshleyAsh90** [comment]
Any updates on this?

**Comment by jmprieur** [comment]
I'm confused.
can you please share with us (attach) a solution with repro steps?

**Comment by ajaysbsic** [comment]
Yes, Open entitlement file , allow keychain and in project properties add your entitlement in bundle signing

**Comment by jmprieur** [comment]
@ajaysbsic : did anybody in this thread mention anywhere that this was with Xamarin iOS?

**Comment by ajaysbsic** [comment]
I didn’t notice that , removing my comment

**Comment by jmprieur** [comment]
you did not need to, @ajaysbsic. You might be right, that this might be on iOS :)
It's just that this whole thread is completely lacking context.

**Comment by AshleyAsh90** [comment]
@jmprieur Sorry, I will attach a solution soon. But to provide context, I am using this as a part of authentication call in a .Net standard project.

**Comment by AshleyAsh90** [comment]
@jmprieur  I missed a part of your article. Could you please close this as not a bug. it was a misunderstanding from my part. I missed this below part of the article:

> 
"Note that, AcquireTokenSilent does not need to be called in the Client credentials flow (when the application acquires token without a user, but in its own name). "

I am using ClientCredentials flow and did not need to use AcquireTokenSilentAsync-which is used-if I understand correctly now, to avoid prompts to user.
A quick qn though-does AcquireTokenAsync also check for a valid token in memory cache before it makes a call to obtain a token using refresh token?

**Comment by jmprieur** [comment]
yes, it does. Thanks for the update @AshleyAsh90
