### ISSUE TITLE
AuthenticationContext constructor should throw an explicit exception when authority is not a proper authority

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/azure-activedirectory-library-for-dotnet#1455]
**Is your feature request related to a problem? Please describe.**
ADAL.NET 4.x is also less forgiving than ADAL 3.x when setting the authority in the constructor of AuthenticationContext. Valid authorities should be, in the case of Azure AD v1.0:
- https://login.microsoftonline.com/{Guid}, where the Guid is the tenant ID
- https://login.microsoftonline.com/domainName, where the domain name is a domain associated with your tenant
- https://login.microsoftonline.com/common which, in the case of ADAL.NET means any Azure AD tenant 

It cannot be https://login.microsoftonline.com/common/OAuth2/endpoint even if this for could have been wrongly accepted in ADAL 3.x

**Describe the solution you'd like**
throw a very explicit exception: if the authority passed in the constructor, or an override of acquire token ends with /oauth2/token with  /oauth2/authorize we should throw with a InvalidArgumentException saying “authority ‘{0}’ is not a valid authority. See https://aka.ms/adalnet4-authority

**Describe alternatives you've considered**
- revert back to the behavior that was in ADAL 3.x (be less strict). 
  - PRO: this would be consistent with the result of `AuthenticationParameters.CreateFromResourceUrlAsync()`. See also #1410
  - CONS:
     - the authority is not an endpoint
     - the change helps customers moving to national/sovereign clouds, and also to v2.0 / MSAL.NET (which is strict)
- do nothing (It seems that several customers were using the endpoint instead of proper authorities in the construction of AuthenticationContext): See #1453

**Additional context**

**Comment by jmprieur** [comment]
@henrik-me @MarkZuber 
actually, it seems a number of partners docs and samples improperly use endpoints instead of authority. For instance, I just replied to an issue in this one: https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app (for azure storage), and proposed a PR to fix this doc article, but I also need to verify which other are affected.

Which makes me think: this might be easier to (and more lazy) to just change the constructor so that it accepts the endpoints?

**Comment by henrik-me** [comment]
@jmprieur : Understood. Instead of throwing an exception for token and access end-points we can modify the authority? For other cases I would still prefer we throw exceptions. Thoughts?

**Comment by jmprieur** [comment]
@henrik-me : yes. Let's avoid regressing only the scenarios which customer complains about (thart is when they pass endpoints). This will also "solve" #1410

**Comment by henrik-me** [comment]
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
