### ISSUE TITLE
[iOS] UIKit exception while acquiring token in background

### ISSUE THREAD

**Issue by alexrainman** [AzureAD/azure-activedirectory-library-for-dotnet#1456]
**Which Version of ADAL are you using ?**

ADAL 4.4.1

**Which platform has the issue?**

iOS

**What authentication flow has the issue?**

Mobile (Acquiring token silently or interactively in a background thread)

**Repro**

Authenticator will use this in the authenticate method:

```csharp
var controller = UIApplication.SharedApplication.KeyWindow.RootViewController;
var platformParams = new PlatformParameters(controller);
```

**Expected behavior**

No exception.

**Actual behavior**

Throws exception and acquiring a token fails.

**Possible Solution**

In AppDelegate:

```cs
public static UIViewController CurrentViewController()
{
    UIViewController vc = null;
    UIApplication.SharedApplication.InvokeOnMainThread(() =>
    {
        var window = UIApplication.SharedApplication.KeyWindow;
        vc = window.RootViewController;
        if (vc is UINavigationController navController)
        {
            vc = navController.ViewControllers.Last();
        }
        else
        {
            while (vc.PresentedViewController != null)
            {
                vc = vc.PresentedViewController;
            }
        }
    });
    return vc;
}
```

Then in the authenticator authenticate method:

```cs
var controller = AppDelegate.CurrentViewController();
var platformParams = new PlatformParameters(controller);
```

**Comment by jmprieur** [comment]
@alexrainman can you please share a bit more about the exception?
can you please [enable logging](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net) ?

**Comment by jennyf19** [comment]
@alexrainman - any update on this? are you able to provide logs, as mentioned by @jmprieur?

**Comment by alexrainman** [comment]
The issue is not there in the latest version. Thanks

**Comment by jennyf19** [comment]
@alexrainman Thanks for the update.
