### ISSUE TITLE
Need advice regarding redirect URIs during development

### ISSUE THREAD

**Issue by nilsi** [AzureAD/azure-activedirectory-library-for-dotnet#1458]
Hi,

I read the part Redirect URI during development here:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/leveraging-brokers-on-Android-and-iOS#redirect-uri-during-development

But how is this suppose to work if I already have deployed the app to Playstore? Can I have multiple redirect URIs added to the app registration at the same time without breaking the old URI our customers using for the released version of the app?

Another solution would be to not use broker for development but I don't like to add code like:
```
if (Build.debug) {
    //do not use broker and set redirect URI to http://localhost
}
```
Im not sure but I think the debug signature of the app will be different depending on developer machine? In that case it might be cumbersome to add all redirect URIs for all developers to the registration. And someone might accidentially remove the production URI.

How can we handle this in a nice way? Thanks

**Comment by jmprieur** [comment]
hi @nilsi 
yes you can have several redirect URI registered in the application registration (in the **Authentication** page)
cc: @trwalke and @jennyf19 for the signature

**Comment by trwalke** [comment]
Hi @nilsi 
When you deployed your app to the app store, did you sign your apk with a specific certificate/keystore? If not. You should create one and share it with developers so that you can use the same redirect URI on all machines since the redirect URI is dependent on the certificate/keystore used to sign the apk. You can then easily add the new redirect URI to the app registration and your customers will experience no issues.

**Comment by jmprieur** [comment]
@nilsi : if you are happy with these answers please close the issue.

**Comment by nilsi** [comment]
Hi, @trwalke  @jmprieur so the recommended workflow is to have one redirect URI for the customers that is signed with the key used on Playstore. And then for development share one key that is used within the team for debug builds?

**Comment by jmprieur** [comment]
yes, @nilsi
