### ISSUE TITLE
ADAL 4.4 version user name and pwd flow does not work.

### ISSUE THREAD

**Issue by akjind** [AzureAD/azure-activedirectory-library-for-dotnet#1460]
**Which Version of ADAL are you using ?** ---> **ADAL 4.4.0.0**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

**Which platform has the issue?** net45

**What authentication flow has the issue?** Desktop Username Password
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;
In ADAL 2.22 version - we were having the below code that used to work fine for console application:

var authContext = new AuthenticationContext(loginUrl);
var nativeClientAuthResult = authContext.AcquireToken(url.ToString(), nativeClientId, new Uri(redirectUrl), PromptBehavior.Auto);

From the above token, we were able to authenticate to the other service API end point.

After updating to ADAL 4.4 version and moving to Web App, we need to do the AAD Auth using username and pwd, we are able to get the token after updating the code to below:

var nativeClientAuthResult = authContext.AcquireTokenAsync(urlString, slmNativeClientId, new UserPasswordCredential("RedmondServiceAccount", "ServiceActPwd")).Result;
            var _loggedInUserAccessToken = nativeClientAuthResult.AccessToken;

If we use the token got in the above step and submit it to the other service API end point then its getting rejected with the exception:

"arrValErrs":["50058"],"sErrorCode":"50058","sErrTxt":"","sResetPasswordPrefillParam":"username","onPremPasswordValidationConfig":{"isUserRealmPrecheckEnabled":true},"fSwitchDisambig":true,"oCancelPostParams":{"error":"access_denied","error_subcode":"cancel","state":"AppProxyState%3a%7b%22InvalidTokenRetry%22%3atrue%2c%22IsMsofba%22%3afalse%2c%22OriginalRawUrl%22%3a%22https%3a%5c%2f%5c%2fssladmintest-microsoft.msappproxy.net%5c%2fapi%5c%2frequest%22%2c%22RequestProfileId%22%3a%224a3860fc-b296-429b-8133-74b7e79d9e8f%22%7d%23EndOfStateParam%23","add_account":null},"

**Repro**

```csharp
var nativeClientAuthResult = authContext.AcquireTokenAsync(urlString, slmNativeClientId, new UserPasswordCredential("RedmondServiceAccount", "ServiceActPwd")).Result;
            var _loggedInUserAccessToken = nativeClientAuthResult.AccessToken;

```

**Expected behavior**
Based on the token that we get from the above code(ADAL 4.4) - we should be able to get authenticated against the other service API end point.(As we are able to get authenticated with ADAL 2.22 code)

**Actual behavior**
Getting access denied exception:
"arrValErrs":["50058"],"sErrorCode":"50058","sErrTxt":"","sResetPasswordPrefillParam":"username","onPremPasswordValidationConfig":{"isUserRealmPrecheckEnabled":true},"fSwitchDisambig":true,"oCancelPostParams":{"error":"access_denied","error_subcode":"cancel","state":"AppProxyState%3a%7b%22InvalidTokenRetry%22%3atrue%2c%22IsMsofba%22%3afalse%2c%22OriginalRawUrl%22%3a%22https%3a%5c%2f%5c%2fssladmintest-microsoft.msappproxy.net%5c%2fapi%5c%2frequest%22%2c%22RequestProfileId%22%3a%224a3860fc-b296-429b-8133-74b7e79d9e8f%22%7d%23EndOfStateParam%23","add_account":null},"

**Possible Solution**
Token got in ADAL 4.4 scenario should work

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net

**Comment by jmprieur** [comment]
@akjind : 
- does it work with ADAL.NET 3.19.8 ? (it has the same API surface as ADAL.NET 4.x, so this should not be difficult to update the nuget package and test)
- Are you in an ADFS environment? Is the error AADSTS50058
__

Aside, you should **not** use username/password in a Web App.  Web apps are confidential clients, whereas username / passwords is a public client application flow.
- if you want to call the API on behalf of the signed-in user, you should use [by authorization code (Web Apps)](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-with-authorization-codes-on-web-apps)
- otherwise if you want to call the API for the application itself, you want to use [Client credentials](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows)

**Comment by jmprieur** [comment]
Closing this issue as we did not get more information that would enable us to act on it
