### ISSUE TITLE
"Scope" parameter causing refresh failure with ADFS 3.0

### ISSUE THREAD

**Issue by aweFalafelApps** [AzureAD/azure-activedirectory-library-for-dotnet#1467]
Using ADAL 4.4.2 w/ ADFS 3.0 automatic token refresh fails with ADFS server error:
`The OAuth access token request received is invalid. A 'scope' parameter was received in the request and AD FS does not support any scope. Received scope: 'openid'.`
  
I've not been able to find a way to add scopes in this version of ADFS, but perhaps I've missed it.

Any guidance would be appreciated. Could this parameter be made optional somehow?

**Comment by henrik-me** [comment]
ADAL v4 + always the openid scope. Our own ADFS 3.0 tests are green though, not sure if this is something which can be configured for ADFS. 

///

Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
