### ISSUE TITLE
tokenCache is always NULL for debug log in ADAL v3.19.8 or later - src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenHandlerBase.cs

### ISSUE THREAD

**Issue by shigeyf** [AzureAD/azure-activedirectory-library-for-dotnet#1471]
**Which Version of ADAL are you using ?** - v3.19.8 or later

**Which platform has the issue?** - all platform

**What authentication flow has the issue?** - no issues in authentication flow

**Other? - please describe**;
This is a debug log issue - please see the code below in the constructor of AcquireTokenHandlerBase.
There is no code to set TokenCache instance to a 'tokenCache' private property in the constructor before the line.
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenHandlerBase.cs#L71

**Expected behavior**
**Possible Solution**
Should be okay with the following patch:

diff --git a/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenHandlerBase.cs b/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenHandlerBase.cs
index 14532502..b644564a 100644
--- a/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenHandlerBase.cs
+++ b/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenHandlerBase.cs
@@ -54,6 +54,7 @@ namespace Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows
         protected AcquireTokenHandlerBase(RequestData requestData)
         {
             this.Authenticator = requestData.Authenticator;
+            this.tokenCache = requestData.TokenCache;
             this.CallState = CreateCallState(this.Authenticator.CorrelationId);
             brokerHelper.CallState = this.CallState;

**Additional context/ Logs / Screenshots** - N/A

**Comment by jennyf19** [comment]
@shigeyf This has been fixed and changes are in dev.
