### ISSUE TITLE
[Doubt] Leveraging brokers on Android and iOS( Xamarin Forms )

### ISSUE THREAD

**Issue by talk2stephan** [AzureAD/azure-activedirectory-library-for-dotnet#1474]
My doubt is regarding this [wiki](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/leveraging-brokers-on-Android-and-iOS) page

**Doubt 1**
Is it possible to implement Azure AD B2C Authentication using **Microsoft Authenticator App**

**Doubts 2**

If it is possible, Do we have some sample demonstrating the implementation of the same?

**Doubt 3**

Do we have some documentation about the usage of Authenticator app along with Azure AD

**Comment by jmprieur** [comment]
@talk2stephan 
you are right B2C application cannot leverage the brokers, for two reasons:

1. B2C apps are written in MSAL.NET (not ADAL.NET), whereas for the moment broker is only supported by ADAL. This is coming to MSAL though.
2. even when MSAL.NET supports brokers, we don't think B2C is supported.
