### ISSUE TITLE
[Question] Token Request Windows Server 2016 ADFS from .Net Core Console Application

### ISSUE THREAD

**Issue by roblangston** [AzureAD/azure-activedirectory-library-for-dotnet#1475]
**Which Version of ADAL are you using ?**
ADAL 4.4.2

**Which platform has the issue?**
.Net Core 2.1

Other? - please describe;
Could someone describe the correct procedure of requesting a token via ADFS from a .Net Core 2.1 console application.  The ADAL library doesn't seem to support the scenario when a user is already logged into a machine joined to a domain and you don't want the user to re-authenticate.  Typical usage scenario would be a service account running a console application deployed to a server.  We have everything working for full .Net framework console apps, web apps etc but have been unable to do the same for .Net Core.  I think it all stems down to the fact .Net Core doesn't support any UI element and stepping through the codebase it seems the desired framework needs to support creating an authorisation dialog.  Are we missing something obvious as I have done a fair amount of Google searching and have only found developers asking the same question without any answers.

**Comment by bgavrilMS** [comment]
.Net core does not have any UI indeed. However, you seem to be describing 2 scenarios:

1. Integrated Windows Auth - this will log in a user without showing UI if they are domain joined or AAD joined. For .Net Core, this is not available on ADAL. However, it is available on our next gen auth library MSAL https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki

2. A service account running a console application does not sound like the scenario above. Consider authenticating the service account without user credentials (i.e. not in the name of a user) - https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows

**Comment by roblangston** [comment]
Many thanks for taking the time to reply but I am unsure point 1. above is a valid solution.  Using the MSAL library, ADFS is not supported as an authority when using Integrated Windows Auth.

**Comment by bgavrilMS** [comment]
Right, you have a point, I believe ADFS is not yet supported in MSAL. @jmprieur can confirm. 

What about using client credentials, i.e. authentication not on behalf of a user, but on behalf on an app itself? It doesn't seem right that a service account is getting a token.

**Comment by roblangston** [comment]
Thanks again for coming back.  If I add a little context, maybe it will be clearer as to what we are trying to achieve.  Also I hope this is not going too far off topic.  We have a suite of WebAPIs written in .Net Core 2.1.  They are secured against claims being returned in the token from the ADFS server.  i.e. the controllers are decorated with the [Authorize] attribute specifying the role names returned in the token (JWT).  These roles are claims which are in turn mapped against AD Groups.  When a user requests a token, they will automatically get these roles back on the token if they are a member of the AD group.  The console app we are building is deployed onto a server and runs as a service account.  The service account is a member of the AD groups and so it tries to get a token containing the necessary roles to access the APIs (this is where the ADAL library is failing currently from .Net Core).

We tried registering the console application in ADFS and requesting a token via a shared secret.  We managed to get a valid token but it did not contain the role names needed for access to the API.  I am guessing it was because the roles are mapped from AD groups and connecting via a shared secret doesn't supply the necessary information.  I am wondering if we need some custom rules set-up to provide certain roles back as claims if the connecting application has provided a shared secret i.e. its not possible to cascade the claims set against the AD groups.

On a side note, we have managed to get a valid token without using the ADAL library by hitting the ADFS endpoints manually with two HTTP requests providing the necessary header details.  I would rather not have to go this route as it means another internal library we will have to maintain going forward.

**Comment by bgavrilMS** [comment]
Interesting scenario, I am not that familiar with groups so adding @jmprieur to see if he can help

**Comment by jmprieur** [comment]
@roblangston : did you have a look at the following sample:
https://github.com/Azure-Samples/active-directory-dotnet-webapp-groupclaims ?
It's not specifically about ADFS, but this should help you?

Also, are you hitting adfs directly (do you pass an ADFS authority in the AuthenticationContext constructor) ? or is it federated with Azure AD ? (you pass https://login.microsoftonline.com/common or  https://login.microsoftonline.com/domainname) ?

**Comment by roblangston** [comment]
Thanks, I will take a look at the examples you have provided.

There is no Azure interaction present, it is all on-premises ADFS.

**Comment by henrik-me** [comment]
ADFS 2019 is supported in MSAL.

///

Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
