### ISSUE TITLE
AcquireTokenSilentAsync parameters should include scopes to be requested

### ISSUE THREAD

**Issue by dskantz** [AzureAD/azure-activedirectory-library-for-dotnet#1481]
When using ADAL to Aquire App-tokens using the Client Credential Flow, there should be a way of specifying which scopes to request from the token endpoint.

When I'm using the Code Flow driven by Microsoft.Owin.Security.OpenIdConnect the configuration for OpenIdConnect lets me specify which Scopes to request. And using the resulting Code from that flow with AcquireTokenByAuthorizationCodeAsync the returned token will contain the Scopes as requested in the Owin configuration. This is all good.

However, when using the ADAL library to aquire an Application Token using the Client Credential Flow there is no way of specifying which scopes you request for that token. Since no scopes where requested an application access token is issued without scopes. Hence, in the recieving API I cannot use the scopes claim to Authorize requests, since the access token does not contain any scopes.

My suggestion is: add an optional parameter "string scopes" to AcquireTokenSilentAsync method, if specified this will be added as the scope-parameter in the call to the token endpoint.

**Comment by jmprieur** [comment]
@dskantz : I'm a bit confused.
ADAL targets the Azure AD v1.0 endpoint, and therefore you specify a resource: See https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows

If you want to specify scopes, then you need to use MSAL.NET. See https://aka.ms/msal-net-client-credentials. Note that even then, the scope is reduced to aResource/.default as Client credentials use the static registration (because there is no user in the loop to consent to any scope)

**Comment by dskantz** [comment]
We are using the ADAL to acquire tokens from a ADFS 2016 on prem. According
to the OAuth2.0 Spec (https://tools.ietf.org/html/rfc6749#section-4.4) when
using the Client Credential Flow the scope parameter is optional. You are
right that there is no user in the loop to consent, however, the
application has been granted permission to the scope.

When requesting a token using Client Credential Flow from the ADFS 2016
token endpoint, an Application AccessToken is issued containing the
requested scopes, if permissions for that client and the requested scopes
are set up. If there are no permissions set up no access token will be
issued.

So, in the API we are able to distinguish between a client that does have
permissions to a scope and one that does not simply by inspecting the
scopes included in the application access token.

I dont think we can use MSAL.NET with our on prem ADFS?

**Comment by jmprieur** [comment]
ADAL.NET supports ADFS 2016, and you can pass a resource. 
Otherwise, MSAL.NET will support ADFS 2018 soon.
Which version of ADFS do you target, @dskantz ?

**Comment by dskantz** [comment]
At the moment ADFS 2016, and yes I can pass a resource but not scopes.

Perhaps I’m not interpreting the specs correctly? I was under the impression that sending requested scopes in Client Credential Flow was ok and actually something supported by the standard. Not trying to win an argument I’m just trying to figure out if I’m doing this the wrong way before I’ve strayed too far from the OAuth specs.

**Comment by jmprieur** [comment]
Sorry, @dskantz I just realized why I was confused by your question.
ADAL.NET leverages the Azure AD v1.0 endpoint, which is not OIDC/Auth2.0 compliant. The Azure AD v2.0 endpoint (Microsoft Identity Platform v2.0) on the other hand **is** OIDC/Auth 2.0 compliant, however, MSAL.NET (which leverages it) does not support ADFS yet.

to use ADAL, you just pass as `resource` the resource part (App ID URI) corresponding to the scope you are interested in. You'll find more information in https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison

**Comment by jmprieur** [comment]
@dskantz : closing this question (which I believe is answered)
feed free to reopen if you disagree
