### ISSUE TITLE
Custom HttpClient not used for every call to the service

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/azure-activedirectory-library-for-dotnet#1488]
**Which Version of ADAL are you using ?**
4.5

**Which platform has the issue?**
all

**Repro**
Use the new AuthenticationContext constructor that takes in an `HttpClient`. Some flows use a new HttpClient everytime.

**Expected behavior**
the passed in httpclient should be used everywhere

**Actual behavior**
the httpClient is not used in some calls, such as the auth code request. 
the custom httpClient is used for calls to the MEX endpoint.

Note: this is where we create a new HttpClient https://github.com:443/AzureAD/azure-activedirectory-library-for-dotnet.git/blob/dev/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Http/HttpClientWrapper.cs#L66
This is also bad for perf, because we should reuse this httpClient.

**Comment by GroupeElanz** [comment]
Same issue here.
Using a proxy is mandatory for us, so we use a custom HttpClient to specify the proxy (as described here: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/with-proxy) but not all the calls use this proxy.
Is there a workaround except setting a proxy at system level?

**Comment by bgavrilMS** [comment]
Yes, could you try to use the WebRequest.defaultwebproxy described in the same wiki page in the last paragraph?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GroupeElanz** [comment]
Hello, this works and that's the same behavior as setting the proxy on web.config, but our customer wants to isolate only the ADAL calls through a specific proxy with specific credentials.

**Comment by nikitinvalera** [comment]
Hi Bogdan,
WebRequest.defaultwebproxy will not help for .NET core project, so I wonder if ALL Handlers (like AcquireTokenForClientHandler) will ever (will they?) use custom configured HttpClient?

This is a problem for us, since we're behind corporate firewall.

**Comment by GroupeElanz** [comment]
Hello,
Is there already a planned date for the release of a version which includes the correction?

**Comment by javisst** [comment]
Hi, we are also behind a corporate proxy and very interested in a solution to that.

**Comment by bgavrilMS** [comment]
This is being actively worked on.

**Comment by vadirajgk** [comment]
We are also facing same issue in our test server, I think ADAL API is not allowing it to read the proxy values passed in the HttpClient object for the AuthenticationContext call. It will work fine when we add proxy in IE for that user account login only but we can not do this. Also we can not add proxy on system level. 

Please let us know the ETA for this.  This is impacting by holding the multiple application's production release from one month.

**Comment by henrik-me** [comment]
PR: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1530

**Comment by zapalap** [comment]
It looks like the custom IHttpClientFactory passed to the new AuthenticationContext constructor is not actually used further. 

It's because of this code:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/c66dc64cc293b8704535f879ce62a47a19e9940e/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Core/ServiceBundle.cs#L70-L80

So even if the httpClientFactory parameter is not null it's not being passed to the ServiceBundle constructor.

**Comment by jennyf19** [comment]
@zapalap this has been fixed and will be in 5.0.1-preview release. fix is merged into dev. thank you.

**Comment by jennyf19** [comment]
included in [ADAL 5.0.1-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v5.0.1-preview)
