### ISSUE TITLE
Error in token acquisition when password contains special characters 

### ISSUE THREAD

**Issue by brenkehoe** [AzureAD/azure-activedirectory-library-for-dotnet#1492]
**Which Version of ADAL are you using ?**
4.5.0

**Which platform has the issue?**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;
Calling AcquireTokenAsync with resource, clientid and credential
**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of ADAL

**Repro**
Call AcquireTokenAsync with a credential where the password contains special characters such as < or &

**Expected behavior**
Passwords with special characters should be handled. This works correctly in version 3.19.8

**Actual behavior**
The following error occurs AADSTS90013: Invalid input received from the user.

**Comment by bgavrilMS** [comment]
Can repro, I tried a password similar to 

`Na<&>ko&&<bzz>`

**Comment by bgavrilMS** [comment]
MSAL is not affected. It seems that the underlying issue is that we set the Content-Type to 

`Content-Type: application/x-www-form-urlencoded; charset=utf-8`

It's the charset that is problematic. Removing it makes the http request pass. 

I will follow up with the server guys to better understand if this a bug on their side. I cannot just remove the charset as it was added a long time ago to support some other scenario.

**Comment by bgavrilMS** [comment]
Server guys confirmed this a bug on their side. Will track this getting fixed and update the thread.

**Comment by jmprieur** [comment]
meanwhile, @brenkehoe, if you want to move to MSAL.NET, this will solve this issue: https://aka.ms/adal-net-to-msal-net

**Comment by jmprieur** [comment]
Internal bug on the Microsoft identity platform service: 647691

**Comment by bgavrilMS** [comment]
I believe this has been fixed.

**Comment by filippo-orru** [comment]
If this has been fixed, the link and known issues section can be removed from https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication

**Comment by bgavrilMS** [comment]
Done, thanks
