### ISSUE TITLE
[Used in PowerShell] System.Net.Http, Version=4.1.1.0

### ISSUE THREAD

**Issue by jameswhollister** [AzureAD/azure-activedirectory-library-for-dotnet#1494]
Just switched to a new dev machine and seeing a problem I didn't have on my other one. When I try to instantiate a new AuthenticationContext it throws the exception:

`Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

Some prerequisite net core library or something else I need to do to get it up and running?

**Comment by jmprieur** [comment]
@jameswhollister : do you use ADAL ? or try to build it?
if you try to build it, I would suggest you have a look at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Pre-requisites-to-build-ADAL.NET-and-MSAL.NET

**Comment by jameswhollister** [comment]
This project is a powershell module, I'm referencing  the Microsoft.IdentityModel.Clients.ActiveDirectory nuget package.

**Comment by henrik-me** [comment]
Can you pls. provide a detailed repro step?

///

Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
