### ISSUE TITLE
WebBrowser state messages go directly to Trace.

### ISSUE THREAD

**Issue by christav** [AzureAD/azure-activedirectory-library-for-dotnet#150]
In WindowsFormsWebAuthenticationDialogBase.cs, line 191, there's a call to output diagnostic information that uses Trace.WriteLine. When using ADAL in a console app, this results in extra useless logging junk all over my console output. Trace.WriteLine is for apps, not for libraries.

Put this logging behind a TraceSwitch so it can be turned off like you've done in the main ADAL library.

**Comment by afshins** [comment]
Fixed.

**Comment by afshins** [comment]
@christav the fix is now released.
