### ISSUE TITLE
Using ADAL in ASP.Net Core, service to service

### ISSUE THREAD

**Issue by emilssonn** [AzureAD/azure-activedirectory-library-for-dotnet#1501]
**Is your feature request related to a problem? Please describe.**
I cannot find documentation or a sample how to use ADAL (.net core) when doing service to service calls in a none console app.

**Describe the solution you'd like**
Documentation or sample of how to use ADAL (.net core) in the most optimal way when doing service to service calls and not in an console application.

For example, if I have a asp.net core 2.2 singleton class that needs to aquire access tokens for service to service calls. How should I use ADAL in the most optimal way?

```
public class SingletonService
{
    private readonly ClientCredential _clientCredential;
    private readonly AuthenticationContext _authenticationContext;

    public SingletonService(string instance, string tentantid, string applicationid, string clientsecret)
    {
        _authenticationContext = new AuthenticationContext(instance + tenantid);
        _clientCredential = new ClientCredential(applicationid, clientsecret);
    }

    public string GetAccessTokenForXAPI(applicationId)
    {
        var result = await _authenticationContext.AcquireTokenAsync(applicationId, _clientCredential);

        return result.AccessToken;
    }
}
```

Is this good way? `GetAccessTokenForXAPI` can be called to get an access token to x, y and more apis.
Maybe the SingletonService class should be a typed httpclient and inject the httpclient in the AuthenticationContext, creating a new AuthenticationContext in each GetAccessTokenForXAPI call.
If doing so, is the httpclient used (see #1488)?

**Describe alternatives you've considered**
I have looked at https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity. Is this how you should use it, static ClientCredential and AuthenticationContext?

**Comment by jmprieur** [comment]
@emilssonn. 
Do I understand that you want to have a Web App or Web API that calls services in its own identity (not on behalf of a user?). 
Whatever the case, since these are confidential client applications, there are several ways of injecting the client creds. This can be in config file for your Web App / API ? or getting from KeyVault (we are missing a sample for this use case)
which would you be interested in?

Here are all the ADAL.NET samples we have for daemon apps (client credentials flow)
https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v1-code#daemon-applications-accessing-web-apis-with-the-applications-identity

(and we have a couple more for MSAL.NET: https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#daemon-applications)

**Comment by emilssonn** [comment]
@jmprieur 
Yes, I have a web api that calls services in its own identity (not on behalf of a user).
What I am looking for is basically best practice for managing the lifetime of the AuthenticationContext and if I should use my own HttpClient for best performance and connection/socket use.

The daemon apps and the example you provided uses static AuthenticationContext, is that considered ok for web api:s aswell (static/singleton class)? It is hard to know if the samples show the recommended way of using it or just the functionality of it since the rest of the sample might not be optimal (not reusing HttpClients etc).

**Comment by jmprieur** [comment]
@emilssonn. Given that this is a daemon app a static/singleton AuthenticationContext (ADAL) / ConfidentialClienApplication (MSA) is absolutely fine. 

If your Web API was calling other downstream APIs on behalf of users, that would not be the case (as there would be a need for one cache per user)

What do you mean your own HttpClient? you mean initializing AuthenticationContext with yours?

**Comment by emilssonn** [comment]
@jmprieur. Given that a web api does **not** call other downstram APIs on behalf of users, it should be ok to use static/singleton AuthenticationContext?

Exactly, initializing AuthenticationContext with my own HttpClient, is that the most optimal way to go?

**Comment by jmprieur** [comment]
@emilssonn , I think so. asking @henrik-me @bgavrilMS @MarkZuber @jennyf19 @trwalke for confirmation.

**Comment by henrik-me** [comment]
Initializing AuthenticationContext with your own HttpClient makes sense.

The simplest may be to use a static however the AuthContext is not thread safe and if used across threads then you may run into issues.

**Comment by emilssonn** [comment]
@henrik-me @jmprieur . The sample https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity uses a static AuthenticationContext in the controller, is that considered thread safe? It sounds like the safest bet is to always create a new AuthenticationContext when getting a accesstoken (including from the built-in cache).

**Comment by jmprieur** [comment]
yes, you are right @emilssonn. I've created an issue to update the sample.
Proposing to close this question as I believe it's answered
Feel free to reopen if you disagree.
