### ISSUE TITLE
AquireTokenAsync is failing with System.Net.WebException: The operation has timed out

### ISSUE THREAD

**Issue by rishavraj10** [AzureAD/azure-activedirectory-library-for-dotnet#1502]
Hi,

We are using 2.14 version of ADAL library for dotnet. We are seeing the intermittent calls failing for AquireTokenAsync with System.Net.WebException: The operation has timed out.

Are there internal retries implemented? Will upgrading the ADAL verison help us with this issue? or should we add external reties around this?

**Comment by jmprieur** [comment]
@rishavraj10, ADAL v3/v4 implement one retry. [Exceptions](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Exceptions-in-ADAL.NET) also surface the Headers in including the retry-after headers.

But you might want to move directly to MSAL.NET. [See retry in MSAL.NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/retry-after)

**Comment by jmprieur** [comment]
@rishavraj10. This is fixed in This is fixed in ADAL 4.5.1 (See #1489)
