### ISSUE TITLE
Documentation for Broker is confusing for Android support

### ISSUE THREAD

**Issue by ghost** [AzureAD/azure-activedirectory-library-for-dotnet#1505]
Documentation is related to this page:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/leveraging-brokers-on-Android-and-iOS

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [X] documentation needs clarification
- [X] error(s) in example
- [X] needs example

### Description Of The Issue
Documentation that supports Android is out of date and confusing.  I will bring up the following points:

1.) Update the application manifest - this section is confusing and isn't clear what you should setup for API 23 and higher.   So is GET_ACCOUNTS, USE_CREDENTIALS, and MANAGE_ACCOUNTS required for API 23 and higher or only GET_ACCOUNTS?  

2.) Register a Redirect URI for your application - these directions provide no support on where to find the powershell script or how to run this on a Mac.

3.) Redirect URI during development - this is confusing and why isn't it recommended that you setup Visual Studio to generate the APK using the same keystore file that you use for non-debug builds?

4.) Directions on advanced logging are completely missing making it complex to find problems.  Better guidance should be provided.

**Comment by jennyf19** [comment]
@biozal Going to close this, but let's sync up next week or sometime soon to discuss this and update our documentation. :)
