### ISSUE TITLE
AcquireTokenAsync(resource, clientId, userAssertion).Result deadlocks under ASP.NET

### ISSUE THREAD

**Issue by Lexey** [AzureAD/azure-activedirectory-library-for-dotnet#151]
AcquireTokenAsync(resource, clientId, userAssertion).Result deadlocks under ASP.NET 4.5 due to a well-known problem with synchronization contexts.
I guess, this method internals (and other similar methods) should explicitly call .ConfigureAwait(false).

**Comment by afshins** [comment]
@Lexey Please add more details including repro steps and we will try to fix it. Thanks.
