### ISSUE TITLE
ADAL does not properly support .NET Core 3

### ISSUE THREAD

**Issue by albahari** [AzureAD/azure-activedirectory-library-for-dotnet#1510]
Note: not sure if this a bug or new feature request.

**Which Version of ADAL are you using ?**
4.5.1

**Which platform has the issue?**
netcore 3

**Is this a new or existing app?**
a. I am creating a new release of LINQPad which targets .NET Core 3 instead of .NET Framework. LINQPad uses ADAL to authenticate Azure SQL connections via Universal authentication. This used to work with .NET Framework, but not properly with .NET Core 3 because there is no PlatformParameters.PromptBehavior property.

**Repro**

The PlatformParameters.PromptBehavior property exists in the .NET Framework target, but not in the .NET Core 3 target.

**Expected behavior**
I would expect to see PlatformParameters.PromptBehavior when targeting .NET Core 3.

**Possible Solution**
It looks like there is no .NET Core target, and so under .NET Core 3 it uses the netstandard1.3 target. It looks like you need to add a .NET Core 3 target with PlatformParameters.PromptBehavior enabled.

**Comment by jmprieur** [comment]
@albahari 
is it an option for you to move to [MSAL.NET](https://aka.ms/msal-net) ?
Future innovation, including the support for .NET Core 3 will rather happen in MSAL.NET rather than ADAL.NET

**Comment by albahari** [comment]
> is it an option for you to move to MSAL.NET ?

I'm happy to use any library that allows users to interactively log on with Universal Authentication to SQL Azure. But as far I can see, this is not the case right now with MSAL. From [this page](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-Tokens)

"Public flows will often acquire token interactively, having the user sign-in. Remember that this is not possible yet in .NET Core as .NET core does not provide UI capabilities and this is required for interactive authentication"

**Comment by jmprieur** [comment]
you're right @albahari : the AcquireTokenInteractive is not yet available on .NET Core 3.0, but it will eventually (See MSAL.NET issue https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/901).
We don't have plans to support it on ADAL.NET

for help to migrate from ADAL.NET to MSAL.NET see [Differences between ADAL.NET and MSAL.NET applications](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal)

**Comment by albahari** [comment]
Thanks - I'll look forward to that.
