### ISSUE TITLE
Password flow powershell AcquireTokenAsync failing because no client secret

### ISSUE THREAD

**Issue by myhsyd** [AzureAD/azure-activedirectory-library-for-dotnet#1515]
**Which Version of ADAL are you using ?**
ADAL v4.0.30319

**Which platform has the issue?**
Powershell 5.1.16299.666
PSModule AzureADPreview 2.0.2.5

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [X] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
New app - PS code for Azure Automation

**Repro**

$authResult = [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions]::AcquireTokenAsync($authContext, $resourceAppIdURI, $clientid, $userCredentials)
        

**Expected behavior**
Getting a token

**Actual behavior**
 System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: 
                         AADSTS7000218: The request body must contain the following 
                         parameter: 'client_assertion' or 'client_secret'.

**Comment by frankhu-2021** [comment]
The reason that this error is occurring is because the app registration that was created in the Azure Portal is a web app/api. 

The Password flow requires a Native Application Registration, otherwise it **requires** a client secret.
