### ISSUE TITLE
Review and Update Android Broker implementation to bypass Account Picker

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/azure-activedirectory-library-for-dotnet#1516]
**Is your feature request related to a problem? Please describe.**
Currently, to fully integrate Android Broker, you have to also invoke the Account Picker to be able to get a list of Microsoft accounts from the broker. Unless this is done, the list returned is empty, causing ADAL to switch to interactive auth from silent auth. 

This is causing quite a lot of disruption / supportability issues.

**Describe the solution you'd like**
I've discussed with the Android team and they have added a service to the Authenticator that can be queried for the Microsoft accounts. It bypasses the AccountPicker. This solution was reviewed by Google. 

The .net implementation does not take into account the new approach.

**Comment by jmprieur** [comment]
@bgavrilMS : is it in the current broker? or in the future broker? in other words, can we work on this now or should we wait for the new broker?

this generates a lot support, so I'd recommend we take this high pri.

**Comment by bgavrilMS** [comment]
We could first implement the broker in MSAL to get a better idea of how this is done, if we can do it soon. Otherwise, I think ADAL for Android already uses the new approach.

**Comment by jmprieur** [comment]
The wiki is updated.
