### ISSUE TITLE
|PlatformParamters(PromptBehavior, object) should throw an ArgNull exception if passed null obj

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/azure-activedirectory-library-for-dotnet#1519]
**Which Version of ADAL are you using ?**
5.0.0-preview

**Which platform has the issue?**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**

```csharp
new PlatformParamters(PromptBehaviour.Auto, null);
```

**Expected behavior**
This should continue to work or throw a meaningful exception.

**Actual behavior**
New ctor overload results in a strange ArgNullException, related to ICustomWebUi

**Comment by trwalke** [comment]
Addressed in [ADAL V5.0.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v5.0.0-preview)
