### ISSUE TITLE
ADAL.NET 5.x needs to support the MSAL 3.x token serialization format

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/azure-activedirectory-library-for-dotnet#1520]
**Is your feature request related to a problem? Please describe.**
MSAL 3.0.0 introduces a breaking change in the Json token serialization format so that the token cache can be shared with application written with other MSAL libraries (MSAL.Python, MSAL.Java)

**Describe the solution you'd like**
ADAL 5. must support the MSAL 3.x format in addition to the MSAL V2.0 format for customers wanted to migrate their cache

Add new methods on Token cache:

```CSharp
    public class TokenCache {
       ... 
       public void DeserializeAdalV3(byte[] adalState);
        public void DeserializeMsalV2(byte[] bytes);
        public void DeserializeMsalV3(byte[] bytes);
        public byte[] SerializeAdalV3();
        public byte[] SerializeMsalV2();
        public byte[] SerializeMsalV3();
    }
```

**Comment by trwalke** [comment]
Addressed in [ADAL V5.0.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v5.0.0-preview)
