### ISSUE TITLE
ADAL.NET 5.x needs to provide an extensibility mechanism so that partners provide their own Web View

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/azure-activedirectory-library-for-dotnet#1521]
**Is your feature request related to a problem? Please describe.**
Some partners need to provide their own Web View

**Describe the solution you'd like**
Like in MSAL.NET,  provide an extensibility mechanism: a new interface `ICustomWebUi `  to be implemented by extenders

```CSharp
namespace Microsoft.IdentityModel.Clients.ActiveDirectory.Extensibility {
    public interface ICustomWebUi {
        Task<Uri> AcquireAuthorizationCodeAsync(Uri authorizationUri, Uri redirectUri);
    }
```

On the .NET Framework - both .NET Fx and .NET Core - provide a new constructor to `PlatformParameters `
```CSharp
  public class PlatformParameters : IPlatformParameters {
        public PlatformParameters(PromptBehavior promptBehavior, ICustomWebUi customWebUi);
        public ICustomWebUi CustomWebUi { get; }
    }
```

Add more error messages to surface errors with extensions:
```CSharp
    public static class AdalError {
        public const string CustomWebUiRedirectUriMismatch = "custom_webui_invalid_mismatch";
        public const string CustomWebUiReturnedInvalidUri = "custom_webui_returned_invalid_uri";
        public const string HttpRequestTimeoutResilience = "http_request_timeout";
        public const string NetStandardCustomWebUi = "netcore_custom_webui";
        public const string StateMismatchError = "state_mismatch";
    }
```

and in .NET core provide both the class and the constructor
See https://aka.ms/msal-net-3x for details about the MSAL.NET

**Comment by trwalke** [comment]
Addressed in [ADAL V5.0.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v5.0.0-preview)
