### ISSUE TITLE
Policy integration in Mobile application 

### ISSUE THREAD

**Issue by snehalsilicus** [AzureAD/azure-activedirectory-library-for-dotnet#1524]
I'm trying to integrate a custom policy in Xamarin native application but not getting proper solution. 

I have already implemented everything properly and login functionality is working all right. But only guest users added in B2C directory are able to login for now and not member users. How can I integrate particular POLICY created on azure portal.

Please help me doing this and let me know in advance if its not possible. If there is any other package that I can use in Xamarin Native for azure authentication please update me urgent. I also want to hide cancel button which get displayed on iOS login screen. I think this is also possible with POLICY.

**Comment by jmprieur** [comment]
@snehalsilicus : I think that you should rather use MSAL.NET. you'll find a good sample here: https://github.com/Azure-Samples/active-directory-b2c-xamarin-native

**Comment by snehalsilicus** [comment]
@jmprieur Thanks

**Comment by jmprieur** [comment]
@snehalsilicus shall we close this issue?

**Comment by snehalsilicus** [comment]
@jmprieur Well, I'm still facing problems with POLICY integration with library you suggested may be I'm missing out something there. Actually I had already integrated this package successfully and it Is working seamlessly. It is just that I wanted to integrate policy for some changes and configuration. 
Are you sure it is not possible with Microsoft.IdentityModels.Clients.ActiveDirectory package?

**Comment by jmprieur** [comment]
It might be possible, @snehalsilicus, but I would not think so, and don't think we have samples for this? the recommended path for B2C is definitively using MSAL.NET

**Comment by snehalsilicus** [comment]
Okay Thanks @jmprieur . We can close the ticket then.
