### ISSUE TITLE
get 406  Accessing WS metadata exchange failed

### ISSUE THREAD

**Issue by samsakni** [AzureAD/azure-activedirectory-library-for-dotnet#1528]
**Which Version of ADAL are you using ?**
5.4.0

**Which platform has the issue?**
net461

**What authentication flow has the issue?**
* Desktop 
    * [ ] Username Password

Other? - please describe;

3 line code as below

UserPasswordCredential userPasswordCredential = new UserPasswordCredential("AuzreTeneantUser","Password");

 AuthenticationContext context = new AuthenticationContext($"https://login.windows.net/{TenantId}");
 var token = await context.AcquireTokenAsync(ServiceAudience.ServiceBusAudience.ToString(), ClientId, userPasswordCredential);

When get token, get error as below

System.UnauthorizedAccessException: accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 406 (NotAcceptable). ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException.....

Seems the reason seems when call nexus.password.com, the Accept format is "Application/Json" and return 406 error.

**Comment by jennyf19** [comment]
@samsakni Can you confirm you're using the latest version of ADAL?

Do you have a fiddler trace you can share?

**Comment by henrik-me** [comment]
Can you please describe you scenario in more details?
Also a fiddler trace and detailed logs will help the investigation.

///

Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
