### ISSUE TITLE
AcquireTokenAsync throws an exception after version update

### ISSUE THREAD

**Issue by shertu** [AzureAD/azure-activedirectory-library-for-dotnet#1529]
**Which Version of ADAL are you using ?**
Attempting to update to 4.3.0 from 3.19.8.

**Which platform has the issue?**
netcore

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [x] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
This is a new app or experiment, and I have upgraded to a new version of ADAL

**Repro**

```csharp
public OAuthMessageHandler(Uri serviceUri, string clientId, string clientSecret,
		HttpMessageHandler innerHandler)
	: base(innerHandler) {

	// Obtain the Azure Active Directory Authentication Library (ADAL) authentication context.
	AuthenticationParameters ap = AuthenticationParameters.CreateFromResourceUrlAsync(
			new Uri(serviceUri, "/api/data/")).Result;
	var authContext = new AuthenticationContext(ap.Authority, false);
	//Note that an Azure AD access token has finite lifetime, default expiration is 60 minutes.

	var clientCredential = new ClientCredential(clientId, clientSecret);

	AuthenticationResult authResult = authContext.AcquireTokenAsync(serviceUri.GetLeftPart(UriPartial.Authority), clientCredential).Result;
	//AuthenticationResult authResult = authContext.AcquireToken(serviceUrl, clientId, userCredential);
	//AuthenticationResult authResult = authContext.AcquireToken(serviceUrl, clientId, new Uri(redirectUrl), PromptBehavior.Always);
	authHeader = new AuthenticationHeaderValue("Bearer", authResult.AccessToken);
};
```

**Expected behavior**
When updating my NuGet package for Microsoft.IdentityModel.Clients.ActiveDirectory from 3.19.8 to 4.3.0, this method which worked previously, now throws an exception.

**Actual behavior**
When executing this piece of code:
```csharp
authContext.AcquireTokenAsync(serviceUri.GetLeftPart(UriPartial.Authority), clientCredential).Result;
```

The follow exception(s) are thrown:
1. AdalServiceException: AADSTS90002: Tenant 'authorize' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.
Trace ID: acf4dd1c-8f64-41a9-8e30-c64b66101a00
Correlation ID: 49907ea5-701d-46a6-a60c-537051098fee
Timestamp: 2019-03-13 02:01:23Z

2. HttpRequestException: Response status code does not indicate success: 400 (BadRequest).

3. AdalException: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'authorize' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: acf4dd1c-8f64-41a9-8e30-c64b66101a00\r\nCorrelation ID: 49907ea5-701d-46a6-a60c-537051098fee\r\nTimestamp: 2019-03-13 02:01:23Z","error_codes":[90002],"timestamp":"2019-03-13 02:01:23Z","trace_id":"acf4dd1c-8f64-41a9-8e30-c64b66101a00","correlation_id":"49907ea5-701d-46a6-a60c-537051098fee"}: Unknown error

**Possible Solution**
I do not know how to solve this issue.

**Additional context/ Logs / Screenshots**
Available upon request.

**Comment by jmprieur** [comment]
@shertu : this is a duplicate of https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1410 which has some work around

cc: @henrik-me @jennyf19

**Comment by shertu** [comment]
Understood. Thanks.
