### ISSUE TITLE
AcquireTokenByDeviceCodeAsync needs to support CancellationToken

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/azure-activedirectory-library-for-dotnet#1533]
**Which Version of ADAL are you using ?**
ADAL 5.0.0-preview

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [x] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**

AcquireTokenByDeviceCodeAsync will internally poll for the access token but doesn't support cancellation.  CancellationToken support is needed in this API to allow the developer to cancel the operation as needed.

**Comment by jmprieur** [comment]
how did I miss that ? :)

**Comment by MarkZuber** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1534
