### ISSUE TITLE
FOCI cache compatibility in ADAL

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/azure-activedirectory-library-for-dotnet#1537]

**Comment by jmprieur** [comment]
PR is #1546

**Comment by henrik-me** [comment]
removing fixed: introduced writing the cache to C:\temp. that should be updated.

**Comment by henrik-me** [comment]
@bgavrilMS : PR link?

**Comment by jennyf19** [comment]
released in [ADAL 5.0.1-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v5.0.1-preview)
