### ISSUE TITLE
RedirectUri should be case sensitive

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-library-for-dotnet#1538]
**Which Version of ADAL are you using ?**
All.

**Which platform has the issue?**
All, but specifically iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
Affects apps that use mixed casing in their BundleId and are using broker

**Repro**

BundleId is:
`com.company.MyCatApp`

RedirectUri is:
`<app-scheme>://com.company.MyCatApp`

In this case, we throw: 
`AdalServiceException: source application bundle identifier should be same as the redirect URI domain`

**Expected behavior**
Since BundleId is case sensitive from Apple's perspective AND according to OpenId spec, "The URI MUST exactly match one of the Redirection URI values for the Client pre-registered at the OpenID Provider, with the matching performed as described in Section 6.2.1 of [RFC3986] (Simple String Comparison). ", ADAL should send the redirectUri exactly as the customer has registered. 

**Actual behavior**
ADAL expects the developer to send in a Uri for the RedirectUri, not a string value:
```@csharp
context.AcquireTokenAsync(Resource, ClientId, new Uri(RedirectUri), new PlatformParameters(PromptBehavior.SelectAccount));
```

According to the [spec](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=netframework-4.7.2#remarks), new Uri() will automatically lowercase the value passed in, so ADAL is handling a lowercased redirectUri. When sending this value to broker, it does not match a BundleId that has uppercase letters.

**Possible Solution**
Team needs to discuss how to handle this. 

[Related ADAL issue](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1345)

**Comment by IlyaSemenchenko** [comment]
Hi @jennyf19 , I wrote in related bug, that I could make a Pull Request for the issue. My fix is to add new method to AuthenticationContext where redirectUrl is string, not Uri. And mark as deprecated old methods.
If you OK with this kind of implementation, please assign task to me. Thanks

**Comment by jennyf19** [comment]
Thanks @IlyaSemenchenko. Let me discuss how we want to proceed as a team and also w/our iOS broker team. I will get back to you here asap.

**Comment by jmprieur** [comment]
won't fix in ADAL.NET
will be taken care of in the broker.
cc: @jennyf19
