### ISSUE TITLE
Xamarin ADAL AcquireTokenAsync not returning result! OnActivityResult is hit

### ISSUE THREAD

**Issue by cmw9706** [AzureAD/azure-activedirectory-library-for-dotnet#1541]
**Which Version of ADAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
ADAL 4.5.1

**Which platform has the issue?**
Xamarin.Android

**What authentication flow has the issue?**
* Desktop / Mobile
    * [** ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**

**Repro**

```csharp
                var authContext = new AuthenticationContext(_securityOptions.Authority, false);

                var authResultAsync = await authContext.AcquireTokenAsync(_securityOptions.ResourceUri,
                    _securityOptions.ClientId, new Uri(_securityOptions.RedirectUrl),
                    (IPlatformParameters)App.AuthenticationPrompt);

return authResultAsync;
```

**Expected behavior**
The authContext will return a AuthorizationResult that I can use to see the accesstoken

**Actual behavior**
My breakpoint on return authResultAsync; is never hit and OnActivityResult is hit, I am redirected into my app and I am never able to store my AccessToken

I have confirmed that I can get a token via web browsers and postman! I have followed all the documentation online and I am experiencing this. 

I have this code in an authservice that is newed up via DI.

My OnActivityResult looks like this
```csharp
        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data);
        }
```

**Comment by jennyf19** [comment]
@cmw9706 would you mind trying w/the lastest adal version [v.5.0.0-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v5.0.0-preview), just so we are using the latest and greatest? thanks.

To confirm, this was working in previous versions of ADAL? do you remember which one? and in the other issue, you mentioned it works w/a new app but not an existing app? With the existing app, which version were you on before moving to 4.5.1? will try to repro.

**Comment by soufianemarly** [comment]
i have the same probleme with some research i found that we need to refresh the token but until now i wasn't able to do that please share if you already have the solution 

this is my code : 

       public async Task<AuthenticationResult> Authenticate(string authority, string resource, string clientId, string returnUri)
        {
            AuthenticationResult authResult = null;
            try
            {
                var authContext = new AuthenticationContext(authority);
                if (authContext.TokenCache.ReadItems().Any())
                    authContext = new AuthenticationContext(authContext.TokenCache.ReadItems().First().Authority);
                var uri = new Uri(returnUri);
                PlatformParameters platformParams = null;
#if __ANDROID__

                platformParams = new PlatformParameters((Android.App.Activity)Forms.Context);
#endif
#if __IOS__
                Device.BeginInvokeOnMainThread(() =>
                {
                    UIViewController controller = new UIViewController();
                    controller = UIApplication.SharedApplication.KeyWindow.RootViewController;
                    platformParams = new PlatformParameters(controller);
                });
#endif

                UserDialogs.Instance.HideLoading();
                authResult =  authContext.AcquireTokenAsync(resource, clientId, uri, platformParams).Result;

            }
            catch (Exception e)
            {

                Console.WriteLine("Execption : " + e.Message);
            }

            return authResult;
        }

**Comment by cmw9706** [comment]
@jennyf19 I have a project that this code does not work in. To eliminate causes, I started up a fresh new xamarin project and took the exact same code and put it in the new project. The code works perfectly in the new project, but **does not** work in the old project. I need it to work in the old project.

Just updated to 5.0.0 with no luck. I have tried making all my build setting the same between the two projects and still am having a hard time.

**Comment by cmw9706** [comment]
Version on both projects is 4.5.1

**Comment by jennyf19** [comment]
@cmw9706 I am currently unable to repro this. Could you send [logs](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net#new-way-of-logging-controlling-pii-adalnet--318)?

**Comment by cmw9706** [comment]
[xam.android.logs.docx](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/files/2997800/xam.android.logs.docx)


@jennyf19 Here you go! Nothing that I saw out of the ordinary (I am still running 5.0.0)

**Comment by cmw9706** [comment]
@jennyf19 Let me know if you want them in a different format

**Comment by cmw9706** [comment]
WHOA, so I just looked at the logs for my project that does work and I notice it actually logs the token acquisition as having completed! sooooo thats something? The code is exactly the same but the logs are different. Still no idea why?

SUCCESSFUL LOGS
`[Mono] Assembly Ref addref Microsoft.IdentityModel.Clients.ActiveDirectory[0xa376d600] -> System.Runtime.Serialization[0x8a61c0c0]: 3
[] 2019-03-22T18:29:20.5578670Z: 00000000-0000-0000-0000-000000000000 - AdalLoggerBase.cs: ExtendedExpiresIn(0) is less than ExpiresIn(3600). Set ExpiresIn as ExtendedExpiresIn
[Information][False]: 2019-03-22T18:29:20.5579830Z: 00000000-0000-0000-0000-000000000000 - AdalLoggerBase.cs: ExtendedExpiresIn(0) is less than ExpiresIn(3600). Set ExpiresIn as ExtendedExpiresIn
[] 2019-03-22T18:29:20.6049190Z: 
AdalLoggerBase.cs: Storing token in the cache...
[Verbose][False]: 2019-03-22T18:29:20.6050510Z:
AdalLoggerBase.cs: Storing token in the cache...
[] 2019-03-22T18:29:20.6108290Z: 
AdalLoggerBase.cs: An item was stored in the cache
[Verbose][False]: 2019-03-22T18:29:20.6109760Z: 
AdalLoggerBase.cs: An item was stored in the cache
[] 2019-03-22T18:29:20.6539910Z:  AdalLoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 3/22/2019 7:29:20 PM +00:00
[Information][True]: 2019-03-22T18:29:20.6541270Z: AdalLoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 3/22/2019 7:29:20 PM +00:00Access Token Hash: 
	 User id: 
[] 2019-03-22T18:29:20.6642410Z: 00000000-0000-0000-0000-000000000000 - AdalLoggerBase.cs: Serializing token cache with 1 items.
[Information][False]: 2019-03-22T18:29:20.6643830Z: 00000000-0000-0000-0000-000000000000 - AdalLoggerBase.cs: Serializing token cache with 1 items.
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_call_void_method'.
[Mono] Probing 'java_interop_jnienv_call_void_method'.
[Mono] Found as 'java_interop_jnienv_call_void_method'.`

OTHER LOGS
`[Mono] Assembly Ref addref Microsoft.Identity.Client[0xa376d9c0] -> Mono.Android[0xa17c2d20]: 49
[Mono] Assembly Ref addref Microsoft.Identity.Client[0xa376d9c0] -> System[0xa17c3aa0]: 15
Thread finished: <Thread Pool> #3
Thread started: <Thread Pool> #11
[Choreographer] Skipped 561 frames!  The application may be doing too much work on its main thread.
[IInputConnectionWrapper] finishComposingText on inactive InputConnection
[EGL_emulation] eglMakeCurrent: 0x8f13b680: ver 3 0 (tinfo 0x8efabca0)
[IInputConnectionWrapper] finishComposingText on inactive InputConnection
[eglCodecCommon] glUtilsParamSize: unknow param 0x000085b5
[eglCodecCommon] glUtilsParamSize: unknow param 0x000085b5`

**Comment by jennyf19** [comment]
@cmw9706 The "other logs" shows Microsoft.Identity.Client, which is MSAL, not ADAL. Are you using both in the same scenario?

**Comment by cmw9706** [comment]
@jennyf19 Sorry for the confusion, I have MSAL pulled into the project because I have an IAuthenticator interface was an ADAL implementation and a MSAL implementation incase we ever want to upgrade our ADFS. The library is in the app, but is never used. I am only using ADAL implementation at the moment

**Comment by cmw9706** [comment]
OH MY GOD! I THINK I JUST REALIZED WHATS HAPPENING!
I am calling the `AuthenticationContinuationHelper` (MSAL) not `AuthenticationAgentContinuationHelper` (ADAL)

Changed it out and it worked like a dream! @jennyf19  Thank you so much, I feel like such a dummy. I really appreciate you calling that out!

**Comment by jennyf19** [comment]
@cmw9706 awesome! so glad you got it figured out. thanks for letting us know so quickly!
