### ISSUE TITLE
can't load type PromptBehavior from Microsoft.IdentityModel.Clients.ActiveDirectory

### ISSUE THREAD

**Issue by WangGangCH** [AzureAD/azure-activedirectory-library-for-dotnet#1550]
I'm using Microsoft.IdentityModel.Clients.ActiveDirectory.3.14.2 in .net framework 4.6.2, a very generic console application. it will throw exception:

Could not load type 'Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior' from assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by jennyf19** [comment]
@WangGangCH can you try with the latest version of [adal 5.0.0](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v5.0.0-preview)?

**Comment by WangGangCH** [comment]
we depend on other package which can't be upgraded to the latest one. is there any available version around 3.14+ working well?

**Comment by jennyf19** [comment]
@WangGangCH what is the package that has the dependency?

**Comment by jennyf19** [comment]
@WangGangCH any update on this?
