### ISSUE TITLE
Update wiki/reference documentation to cover SynchronizationContext usage

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/azure-activedirectory-library-for-dotnet#1552]
### Documentation Related To Component:
Wiki / reference documentation

### Please check those that apply

- [ ] typo
- [ x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

Update wiki/reference documentation to cover SynchronizationContext usage for AcquireTokenInteractive flows.

**Comment by MarkZuber** [comment]
Updated wiki here:  https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows

  - Note that on Windows, you must call AcquireTokenAsync for interactive flows on the UI thread so that the embedded browser gets the appropriate UI synchronization context.  Not calling from the UI thread may cause messages to not pump properly and/or deadlock scenarios with the UI.

**Comment by jennyf19** [comment]
Included in [5.0.3-preview release](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/5.0.3-preview)
