### ISSUE TITLE
ADAL + MSAL app sharing cache ignores MSAL cache

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/azure-activedirectory-library-for-dotnet#1569]
**Which Version of ADAL are you using ?**
All versions

**Which platform has the issue?**
All

While some ADAL operations, such as looking for an RT or clearing the cache, work on both the ADAL and the MSAL cache, most operations simply ignore the MSAL cache: `ReadItems`, `DeleteItem`, `Count` simply ignore the MSAL cache. 

Impact: Sign-out, silent login, and displaying a list of accounts are broken in ADAL when sharing cache with an MSAL app.

**Comment by jmprieur** [comment]
Not a regression.
This is a limitation in ADAL. The other way round works (MSAL). The advice is for these scenarios, move to MSAL.NET

won't fix.
