### ISSUE TITLE
Question: When is the target for an RTM release of v5?

### ISSUE THREAD

**Issue by bergmeister** [AzureAD/azure-activedirectory-library-for-dotnet#1570]
You have published 5.0.0 and 5.0.1 as previews (which I find confusing as I'd have expected the 2nd preview to rather be 5.0.0-preview2 btw) but when are you planning to go RTM (i.e. would it be worth the risk of us trying and using the preview but know that you will go RTM before our internal product released)?

**Comment by MarkZuber** [comment]
We are planning to remove the preview tag from the 5.x ADAL product by the end of April.  We had a few API changes we've made and are getting final validation on those with partners before we remove the preview tag and ensure the API remains stable.  Hopefully that aligns with your timeline.  I'm going to close this particular issue out but please feel free to reactivate or open a new one if you have further questions.

**Comment by bergmeister** [comment]
Thanks for the info, very helpful :)
April is more than close enough for us.
