### ISSUE TITLE
OBO flow with in-memory cache fails

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-library-for-dotnet#1574]
**Which Version of ADAL are you using ?**
v5.0.1-preview

**Which platform has the issue?**
Web API

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [x] OBO

Other? - please describe;

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of ADAL

**Repro**
Need to investigate a possible cache issue with OBO in 5.0.1-preview. See email thread for more details.

**Comment by jmprieur** [comment]
I believe that the issue was with the sample. https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2 or https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 (which are both using the `MSALPerUserMemoryTokenCacheProvider` which got fixed there?

**Comment by jmprieur** [comment]
Closing the issue
