### ISSUE TITLE
Obtain token endpoint from metadata when calling 'AcquireTokenByAuthorizationCode' method

### ISSUE THREAD

**Issue by fujie** [AzureAD/azure-activedirectory-library-for-dotnet#158]
In current version of ADAL.NET, when exchange authZ code to access token using 'AcquireTokenByAuthorizationCode', ADAL set token endpoint static in 'Authenticator.UpdateFromTemplateAsync' as following.
- replace last part of uri to tenant id
- add 'oauth2/token/'

This works fine when using AAD, but when I want to use 3rd party OpenID Provider this change to endpoint address causes connection problem, so it's better to obtain endpoint address from metadata( .well-known/configuration) for generic use cases.
I know that ADAL is for AAD/ADFS, but I believe that AAD/ADFS is following the standards like OAuth/OpenID Connect, and this means that ADAL become useful library for 3rd party identity providers aligning these standards.

**Comment by vibronet** [comment]
Thank you Naohiro for the feedback. As you mention, ADAL is tied to Azure AD and ADFS hence you are likely to find other logic that takes advantage of AD specific features and would not work against 3rd parties.

**Comment by Stephanvs** [comment]
Hi,

I also found that the version 3.x branch also reflects this behaviour, are there any plans to change this to also support other third party implementations of the oauth?

I'm actually very interested in the way this framework is architected and the platforms it supports, however I'm not authenticating against an AD :disappointed:

**Comment by afshins** [comment]
We do not have any plan to support third party OAuth providers. We may add some extensibility points in the future, but there is no immediate plan for that either.

**Comment by Stephanvs** [comment]
Thanks for taking the time to reply though.
