### ISSUE TITLE
Microsoft.IdentityModel.Clients.ActiveDirectory v3.14.0 not working after installing Microsoft.CrmSdk.XrmTooling.CoreAssembly v9.0.2.12

### ISSUE THREAD

**Issue by pratiksoni-oa** [AzureAD/azure-activedirectory-library-for-dotnet#1585]
**ADAL 3.14.0**

**Which platform has the issue?**
    net4.6.2, 

Issue is occurring while creating object of Azure storage

**Is this a new or existing app?**
This is the new app that we are developing to connect to Azure storage to get Container Tag list.

**Repro**

**To connect with CRM below code is used:**
```csharp
var client = new CrmServiceClient(connectionString);
            if (client.LastCrmException != null) throw client.LastCrmException;
            else if (client.LastCrmError != null) throw new Exception(client.LastCrmError);
            else return client;
```
**To connect with Azure below code is used:**
```csharp
_azure = Azure
                .Configure()
                .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                .Authenticate(credentials)
                .WithSubscription(subscriptionId);
```

when above connection to azure line is executed, it goes into infinite loop. But when I removed all my CRM packages it started working fine.

**Expected behavior**
If it is not working with any specific version or DLL it would be helpful if it can be mentioned 
**OR**
It should get execute and return the azure object.

**Actual behavior**
Execution goes into infinite loop.

**Comment by bgavrilMS** [comment]
ADAL 3.14 is very old and we do not support it anymore. Please update to latest version.
