### ISSUE TITLE
ADAL version 2.4 AcquireToken Error

### ISSUE THREAD

**Issue by samgithub-duplicate** [AzureAD/azure-activedirectory-library-for-dotnet#159]
I am able to authenticate a user when working locally, using the line

AuthenticationResult result = context.AcquireToken(resource,clientID, returnURI, PromptBehavior.Always);

Locally, I get the signin screen and the UserInfo.

When I publish the web app to Azure, the code above fails with this error

"Error HRESULT E_FAIL has been returned from a call to a COM component"

[COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.] Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask(Task`1 task) +89

What causes this? I am publishing to the shared site (eg xxx.azurewebsites.net) -- so I don't have access to the server machine to make any changes --- beyond using the portal.

The code works as expected locally.

Also the javascript version (ADAL.js) works using the same tenant, clientID and returnURI

**Comment by vibronet** [comment]
As replied on the stackoverflow thread http://stackoverflow.com/questions/28798673/azure-adal-version-2-14-acquiretoken-error 
The token acquisition flow you are performing is meant to be ran on a desktop application, not a web one. The dialog that comes out on your desktop is driven by your local process and the existence of a local windows session. It cannot work within one web application, given that there is no windows session and the process is running elsewhere on a server machine. Please refer to our samples to understand how to acquire tokens from a web app, anything with "openid" or "oauth" from https://github.com/AzureADsamples will work.
