### ISSUE TITLE
ADAL should not suggest to use *SerializeMsalV3 exclusively

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/azure-activedirectory-library-for-dotnet#1593]
**Which Version of ADAL are you using ?**
ADAL 5.0.4

**Which platform has the issue?**
net45

**Repro**

1. Write custom serialization
2. Comments on the serialization methods, including on Serialize(), Deserialize(), all suggest users to use 

```SerializeMsalV3``` and ```DeserializeMsalV3```

**Actual**: These APIs do **not** save ATs and IDTs. This is by design, because only RTs can be used across v1 and v2 endpoints

Impact: Because ATs are not persisted, they will be requested every time from AAD, causing slowness   in the app and high load on AAD.

**Comment by jennyf19** [comment]
fixed in [adal 5.0.5](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/5.0.5)
