### ISSUE TITLE
Access token expired Issue

### ISSUE THREAD

**Issue by Humour0625** [AzureAD/azure-activedirectory-library-for-dotnet#1596]
**Which Version of ADAL are you using ?**
4.5.1

**Which platform has the issue?**
.net MVC5

I met a strange issue .

#1.I use the ADAL to get access token :

 
```
private const string LoginResource = "https://login.microsoftonline.com/";

string authority = LoginResource + _tenantName;
                    var authContext = new AuthenticationContext(authority);
var cac = new ClientAssertionCertificate(_clientId, _certificate);

 authResult = await authContext.AcquireTokenAsync(ResourceUrl, cac); 

return authResult .AccessToken;
```

  #2.After I get the access token,  I send a request using Microsoft Graph API to search users:

```
GraphServiceClient client; 
if (client == null)
                    {
                        client = CreateGraphClient(accessToken);
                    }
                    var filter = string.Format($"startswith(displayname,'{keyword}') or startswith(mail,'{keyword}') or startswith(userPrincipalName,'{keyword}')");
                    var pagedUsers = await client.Users
                        .Request()
                        .Select(selectField)
                        .Filter(filter)
                        .Top(limit)
                        .GetAsync();

```
It works well.

After the token expired(about one hour later, by default the token expires in one hour), I use the same code of #1 to request a new token. the new token returns successfully. But when I call the #2, an error occurred:

```
Microsoft.Graph.ServiceException: Code: InvalidAuthenticationToken
Message: Access token has expired.

```
After some requests, the error will change to

```
erviceException occurred: Code: timeout
Message: The request timed out.

```
Could anyone tell me why the token expired? If the method I use is something wrong, could you tell me how to best handle the access token before it expires?   Why the time out error occurres?

Any help is much appreciated.

**Comment by Humour0625** [comment]
Before the access token expired, I use this to get a new access token:
```

var items = authContext.TokenCache.ReadItems().ToList();
                    
                    foreach (var item in items)
                    {

                        Logger.Debug($"Expire on: {item.ExpiresOn},DisplayableId: {item.DisplayableId},UniqueId: {item.UniqueId},Token:{item.AccessToken}");
                        if (!string.IsNullOrEmpty(item.AccessToken) && DateTime.UtcNow.AddMinutes(10) < item.ExpiresOn)
                        {
                            Logger.Debug("Get access token from cache.");
                            return item.AccessToken;
                        }
                    }
                    Logger.Debug("Begin to obtain new access token.");`
    //Get new access token method
             authResult = await authContext.AcquireTokenAsync(resourceUrl, cac);
```

**Comment by jmprieur** [comment]
@Humour0625 
you need to use the token cache to make sure ADAL.Net refreshes your token when needed (tokens don't last for ever)

See this sample: 
https://github.com/azure-samples/active-directory-dotnet-webapi-onbehalfof

Note that we just GAed MSAL.NET, so you if you are starting a new project you might want to start with https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2

**Comment by henrik-me** [comment]
@Humour0625 : Closing the issue. Please re-open if you have additional questions.
