### ISSUE TITLE
Which calls are required to be done from UI thread?

### ISSUE THREAD

**Issue by marnilss** [AzureAD/azure-activedirectory-library-for-dotnet#1597]
### Documentation Related To Component:
AuthenticationContext.AcquireTokenAsync(…)

### Please check those that apply

- [ ] typo
- [x] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue
Please note in IntelliSense XML and wiki documentation which calls needs be to invoked from UI thread. 
In comments on issues  #1316 , #1548  I read such indications - please document which calls!

**Comment by bgavrilMS** [comment]
I don't think any calls need to be made from the UI thread. We typically have ways of marshalling to the UI thread from any thread.

**Comment by MarkZuber** [comment]
VS was having issues on their end if they didn't call from the UI thread as well on Windows.  So there's still a possible issue lurking in here.

**Comment by henrik-me** [comment]
No call's should be needed on the UI thread. It's the responsibility of the caller when we call back to sync to the UI thread as needed. This should only depend on the calling application. Please re-open if you identify a scenario where this is not the case.
