### ISSUE TITLE
Credentials required for second resource on iOS

### ISSUE THREAD

**Issue by aweFalafelApps** [AzureAD/azure-activedirectory-library-for-dotnet#1603]
**Which Version of ADAL are you using ?**
ADAL 5.0.5

**Which platform has the issue?**
Xamarin.iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
Existing app but just added the second resource.

We're using two separate web apis secured against the same ADFS 2.0 server. When requesting a token for the first resource everything works as expected, the webview to ADFS prompts for credentials and returns a token just fine. On Xamarin.Android, when requesting a token for the second resource, users are not prompted for credentials again even though an additional token is necessary. However, on iOS the ADFS login webview is shown again.

**Expected behavior**
No additional user interaction required when requesting a token for a second resource after successfully getting a token for the first resource.

**Actual behavior**
An authentication webview is presented for the second resource even after successful authentication to the first.

**Comment by jmprieur** [comment]
Did you use the recommended pattern? (AcquireTokenSilentAsync / AcquireTokenAsync)
BTW, now that MSAL.NET GA-ed, if you are starting a new project, we recommend that you switch to MSAL.NET. This is where all the future innovation will happen (and we can help you updating)

**Comment by aweFalafelApps** [comment]
I did use the recommended pattern, yes. An AdalSilentTokenAcquisitionException is thrown and caught from AcquireTokenSilentAsync and then AcquireToken is called with PromptBehavior.Auto. Does MSAL support ADFS 2.0?

**Comment by aweFalafelApps** [comment]
The AdalSilentTokenAcquisitionException is thrown on both platforms btw. AcquireToken just doesn't prompt again on Android. And thank you for the very prompt reply!

**Comment by jmprieur** [comment]
@aweFalafelApps  Oh no, sorry, I overlooked that you are using ADFS 2.0. MSAL will only support ADFS 2019. that's not an option for you.

Could it be that the second resource has a conditional access policy requiring re-sign-in when the client is on iOS? (not sure conditional access policies exist with ADFS ....)

**Comment by aweFalafelApps** [comment]
@jmprieur There are no conditional access policies

**Comment by jmprieur** [comment]
@jennyf19 @trwalke  @oldalton would we know why the behavior could be different (additional sign-in) on iOS?

**Comment by oldalton** [comment]
If I remember correctly, ADFS 2.0 doesn't support MRRTs. So, getting exception in silent call is expected. Regarding why additional interaction is required, I'd analyze what kind of webview ADAL.NET is using. Both AAD and ADFS set session-only cookies as opposed to persistent cookies. On iOS, for UIWebView, those cookies will be gone as soon as process is killed. For WKWebView, cookie jar will be reset when new WKWebView or WKProcessPool is created. On Android, I've seen the behavior when session only cookies are persisted by webview component for a longer period than expected, so it might seem as SSO is achieved. 

In any case, I'm just speculating here based on the input information. We should verify those assumptions by logs and/or network traces.

**Comment by aweFalafelApps** [comment]
@jmprieur what do you need from me?

**Comment by jennyf19** [comment]
@aweFalafelApps Could we get the iOS logs from you? thanks.

**Comment by aweFalafelApps** [comment]
Hey @jennyf19 sorry for the delay! I've got that log for you. I'd probably be more comfortable emailing it to you though instead of posting it publicly. Is that possible?

**Comment by jennyf19** [comment]
@aweFalafelApps sounds great -> jeferrie@microsoft.com. Thanks!

**Comment by jennyf19** [comment]
@aweFalafelApps ...sorry...did you end up sending the logs? If so, could you resend, and we'll take this off-line. thanks.
