### ISSUE TITLE
AccessToken from AcquireTokenAsync is not valid for resource

### ISSUE THREAD

**Issue by m12lrpv** [AzureAD/azure-activedirectory-library-for-dotnet#1615]
**Which Version of ADAL are you using ? --> 4.5.1.0

**Which platform has the issue?**
net45,

* Web App
    * [ ] Authorization code

Other? - please describe;

 The app is in production, and I have upgraded to a new version of ADAL

Initially working Code

                string resource = "https://api.businesscentral.dynamics.com";
                AuthenticationContext authContext = new AuthenticationContext("https://login.windows.net/8c4f0235-f47a-40e5-b86f-57be234c1fe4/oauth2/authorize?resource=https://api.businesscentral.dynamics.com", false);

                ClientCredential clientCredential = new ClientCredential(clientId, clientSecret);
                Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResult externalResult = await authContext.AcquireTokenAsync(resource, clientCredential);

This produced a token that could be used to make api calls to Dynamics Business Central

However from this bug (https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1346)

the change to this code...
                string resource = "https://api.businesscentral.dynamics.com";
                AuthenticationContext authContext = new AuthenticationContext("https://login.windows.net/8c4f0235-f47a-40e5-b86f-57be234c1fe4", false);

                ClientCredential clientCredential = new ClientCredential(clientId, clientSecret);
                Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResult externalResult = await authContext.AcquireTokenAsync(resource, clientCredential);

results in a token that is not valid when used to call Dynamics Business Central API's.

**Expected behavior**
The token should be valid for the specified resource.

**Actual behavior**
The token is not valid for the specified resource. Simple test is to copy the token to postman

**Comment by jmprieur** [comment]
@m12lrpv : is there an issue? or was it something on your side?

**Comment by m12lrpv** [comment]
Sorry there is an issue but it's not really ADAL's responsibility which is why I quickly closed it.

The Azure AD and Dynamics teams need to get together to fix client credentials authentication such that web jobs in azure can obtain the necessary Bearer Token to allow said web job to call the Dynamics Business Central API's.

Additionally MS Dynamics Basic Authentication is not supported with ADAL version 3 and doesn't work at all with version 4.

At present the only authentication that works is username and password via user impersonation and that is not ideal given that provides full portal access to the user account in question.

But like I said not ADAL responsibility. Microsoft need to fix this a little bit higher up the food chain.

**Comment by jmprieur** [comment]
Thanks for the update @m12lrpv 
@henrik-me FYI

**Comment by JhonatanRamirezS** [comment]
Hi

is it working now? I am facing this error.

thanks in advance

**Comment by henrik-me** [comment]
@m12lrpv : Who provide the client secret? Can you pls. provide some additional details on where this should work?
@JhonatanRamirezS @m12lrpv  please provide more details on repro steps and test environment etc, documentation on how this is supposed to work.

**Comment by henrik-me** [comment]
Reading: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#setting-up-basic-authentication

It should be possible to get this to work with a client secret. Can you pls. share the detailed error response?

**Comment by m12lrpv** [comment]
I apologise but I'm not really in a position to replicate this anymore. It was a work project to demonstrate an API link between our app and MS Dynamics.

It's been a while since I looked at this but I recall that it is fine to use Azure AD to get a token to use for the API's.

But that's completely useless for an Azure web Job because a working AAD token can only be created and updated by user interaction.

Azure Web Job != End User Application

**Comment by JhonatanRamirezS** [comment]
> @m12lrpv : Who provide the client secret? Can you pls. provide some additional details on where this should work?
> @JhonatanRamirezS @m12lrpv please provide more details on repro steps and test environment etc, documentation on how this is supposed to work.

Hi @henrik-me thanks a lot for your answer,

My steps:
1. I created an app registration on Azure portal
 1.1. I added Business Central as API permission
 1.2. Created the secret key for that App registration.

2. create a console application to get token:

using System;
using System.Threading.Tasks;
using System.Net.Http;
using System.Net.Http.Headers;
using RestSharp;
using Newtonsoft.Json;
using AuthenticationContext = Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext;
using Microsoft.IdentityModel.Clients.ActiveDirectory;

namespace BCTestConnectApi
{
    class BCAPIReq
    {
		static string resource    = "https://api.businesscentral.dynamics.com";
		static string authorityUri = "https://login.windows.net/e53d2a43-6254-40d3-bf7e-6cb773a25285";
		static string clientId = "d7f6b8e1-b3a0-4454-c4bb-fb8de6a3e2c5";
        static string clientSecret = "=_X@gsLAvoRNQR?WzbSASrDMjx4c6G82";
		static string accessToken = null;
		static string bcResponse;
		static void Main(string[] args)
        {
			ClientCredential clientCredential = new ClientCredential(clientId, clientSecret);
            var authenticationContext = new AuthenticationContext(authorityUriv2, true);
			AuthenticationResult authenticationResult = authenticationContext.AcquireTokenAsync(resource, clientCredential).GetAwaiter().GetResult();
			accessToken = authenticationResult.AccessToken;
			
			var clientBC = new RestClient("https://api.businesscentral.dynamics.com/v2.0/Production/api/v1.0/companies");
			clientBC.Timeout = -1;
            var requestBC = new RestRequest(Method.GET);
            requestBC.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            requestBC.AddHeader("Authorization", "Bearer " + accessToken);
            requestBC.AddHeader("Accept", "*/*");
            requestBC.AddHeader("Cache-Control", "no-cache");
            requestBC.AddHeader("Host", "api.businesscentral.dynamics.com");
            requestBC.AddHeader("Accept-Encoding", "gzip, deflate, br");
            requestBC.AddHeader("Connection", "keep-alive");
            requestBC.AddParameter("application/x-www-form-urlencoded", "", ParameterType.RequestBody);
            IRestResponse responseBC = clientBC.Execute(requestBC);
            bcResponse = responseBC.Content;
            object resposeDataBC = JsonConvert.DeserializeObject(bcResponse);

            Console.Write(resposeDataBC);
            Console.ReadKey();
		}
	}
}

But I received that credentials are not vaild, my app registration secret, are ok because I tested with postman and works, however here in my console is not working.

Thanks a lot in advance for your help

**Comment by jmprieur** [comment]
@JhonatanRamirezS 
Using your code: `authorityUriv2` is not defined
The applicationID does not seem to exist in the tenant you mentioned in  `authorityUri `

Can you tell us more about the HttpResponse you get? What resource (audience) is your token for, what's the expected audience for your resource?

**Comment by JhonatanRamirezS** [comment]
Thanks @jmprieur 
yes, you are correct I copy the wrong variable correct is:
static string resource = "https://api.businesscentral.dynamics.com";
static string authorityUriv2 = "https://login.microsoftonline.com/e53d2a43-6254-40d3-bf7e-6cb773a25285";
static string clientId = "d7f6b8e1-b3a0-4454-b4bb-fb8de6a3e2b5";
static string clientSecret = "=_X@gsLAvoRNQR?WsvSASrDMjx4c6G82";
static string accessToken = null;
static string bcResponse;




what I receive in on my request is:
{"error":{"code":"Authentication_InvalidCredentials","message":"The server has rejected the client credentials.  CorrelationId:  67c94374-2aad-45ab-a601-1a2ce0e31c08."}}

resource is dynamics microsft business central

thanks a lot for your answer

**Comment by jmprieur** [comment]
It means the client_secret you provided is not the right one. you  need to go back to the app registration in the Azure portal for your app, and generate a new client secret and paste it in your code (please don't share it publicly)

**Comment by m12lrpv** [comment]
@jmprieur I think you'll find that the client secret JhonatanRamirezS used was valid as will any regenerated ones be.

Dynamics is simply not able to handle it.
