### ISSUE TITLE
cannot convert from 'Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior' to 'Android.App.Activity'      cannot convert from 'Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior' to 'UIKit.UIViewController'

### ISSUE THREAD

**Issue by akoh-victor** [AzureAD/azure-activedirectory-library-for-dotnet#1620]
**Which Version of ADAL are you using ?**
version 5.1.0

**Which platform has the issue?**
 xamarin forms

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
  
* Web App
    * [ ] Authorization code

Other? - please describe;

**Is this a new or existing app?**
new app in development
**Repro**

```csharp

            try
            {
                        string cloud = "https://login.microsoftonline.com/common/oauth2";
                        string tenantId = App.tenantId;
                        string authority = $"{cloud}/{tenantId}";

                        // Application
                        string clientId = App.clientId;
                        Uri redirectUri = App.redirectUrl;

                        // Application ID of the Resource (could also be the Resource URI)
                        string resource = clientId;
                         AuthenticationResult authResult = null;
                         AuthenticationContext authContext = new AuthenticationContext(authority);

                        try
                        {
                
                        if (authContext.TokenCache.ReadItems().Count() > 0)
                            {
                                authContext = new AuthenticationContext(authContext.TokenCache.ReadItems().First().Authority);
                                authResult = await authContext.AcquireTokenSilentAsync(resource, clientId);
                            }
                            else
                            {
                                authResult = await authContext.AcquireTokenAsync(resource, clientId, redirectUri, new PlatformParameters(PromptBehavior.Auto));
                            }
                        }
                        catch (AdalSilentTokenAcquisitionException ee)
                        {
                            authResult = await authContext.AcquireTokenAsync(resource,clientId,  redirectUri,null);
                        }
            }
            catch (Exception e){
              var err=  e.Message;
            }
//below is the line causing the error
 authResult = await authContext.AcquireTokenAsync(resource, clientId, redirectUri, new PlatformParameters(PromptBehavior.Auto));
```

**Expected behavior**
A build and display Microsoft login page

**Actual behavior**
i get error 

    cannot convert from 'Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior' to 'Android.App.Activity'

    cannot convert from 'Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior' to 'UIKit.UIViewController'

**Comment by jennyf19** [comment]
@ideal-it-solutions The `PlatformParameters` have to be set in the respective Android or iOS projects. 
Here's how we're doing it for our sample app for [ios](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/devApps/XFormsApp.iOS/iOSPlatformParametersFactory.cs#L34) and setting the factory to the [correct UIViewController](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/devApps/XFormsApp.iOS/SecondPageRenderer.cs#L53)

Hope this helps.

btw...if this is for a new app, you should consider moving directly to [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-supports-multiple-application-architectures-and-multiple-platform) which handles the multiple platforms better. 
More [info on the differences between ADAL and MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal)

**Comment by akoh-victor** [comment]
@jennyf19  Thank you very much i would try that. For MSAL i tried after integration. the token i got does not tally when i call the api

**Comment by jennyf19** [comment]
@ideal-it-solutions So when using MSAL, you are not getting an access token back? have you checked the scopes are correct? You might want to check out this [documentation on acquiring tokens in msal](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-Tokens#pattern-to-acquire-tokens-in-msal-3x).

**Comment by akoh-victor** [comment]
@jennyf19 I do get access token but when I make a call to our api I get an invalid token .

**Comment by jennyf19** [comment]
@ideal-it-solutions what's the exact error message?

**Comment by akoh-victor** [comment]
@jennyf19 Sorry for delayed response i was on break.

**Comment by akoh-victor** [comment]
To get the exact error message i will need to re implement it again. 
I have been able to work with the ADAL the challenge am having now is the redirect uri.
on that i have two questions
1 how do i register the url on the android 
2 how do i register the url on ios
here is my redirect uri from azure portal
msalfa10xxxxxxx-4d88-b477-ec54e54xxxxxxxx://auth

**Comment by akoh-victor** [comment]
![Screenshot_2019-06-24-12-40-19](https://user-images.githubusercontent.com/16347216/60016247-8fd9ba00-967d-11e9-9c49-e3cd3817ca87.png)
here is the error i get once i provide the user name and password

**Comment by jmprieur** [comment]
ideal-it-solutions : this means the user you try to sign-in does not exist in the tenant. I don't understand how this relates to the title of this issue?

**Comment by akoh-victor** [comment]
@jmprieur 

> I don't understand how this relates to the title of this issue ?
the title have been resolved am having other issue relating to Redirecting as pointed above.

**Comment by jmprieur** [comment]
@ideal-it-solutions : thanks for the explanation (my advise, moving forward would be to raise a different issue for a different problem)
I don't think you even get to the redirect URI issue with the screenshot you are showing: Azure AD did not even accept the user.

**Comment by akoh-victor** [comment]
@jmprieur Okay that make sense i would close this issue and open an appropriate one
