### ISSUE TITLE
Azure AD B2C error trying to sign in / change Password 

### ISSUE THREAD

**Issue by rkshnair** [AzureAD/azure-activedirectory-library-for-dotnet#1621]
I am using Microsoft.Idendity.Client(V4.0.0) library along with Xamarin for login to Azure AD B2C account.

Previously I was using external browse(chrome) for opening the login window. And yesterday I changed the code like given below.

```
var result = await _authenticationClient.AcquireTokenInteractive(_settings.Scopes)
                    .WithParentActivityOrWindow(ParentActivityOrWindow)
                    .WithPrompt(Prompt.ForceLogin)
                    .WithUseEmbeddedWebView(true)
                    .ExecuteAsync();
```
I have changed the behaviour to open the embedded browser for login by adding the   `.WithUseEmbeddedWebView(true)` configuration.

After changing this, I am getting an error page(intermittently) saying that **"Bad Request - Header Field too long"**

**HTTP Error 400 - Request Header field is too long.**

Attaching the error image for your reference. 
![image](https://user-images.githubusercontent.com/3647522/59831160-7e24a980-9341-11e9-91b0-f810d62763d7.png)

Could you please let me know why this issue is coming and how I can resolve it. Do I need to consider for something else, in case if I am using **EmbeddedWebView**. 

Also I have noticed that It is not coming every-time. Seems like something weird happen with my code.  

Please help.

**Comment by jennyf19** [comment]
@rkshnair ADAL.NET does not support B2C, however we are discussing this in the [issue you created in MSAL.NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1225)...closing this issue as unrelated to ADAL.NET,
