### ISSUE TITLE
ADAL Sign in Dialog does handle UI Scaling beyond 150% correctly

### ISSUE THREAD

**Issue by acangialosi** [AzureAD/azure-activedirectory-library-for-dotnet#163]
I ran through a test with the native client sample from your the ADAL samples repository on a 24" / 1920x1200 resolution.
At 100% we show the sign in UI; no Scroll bars.
At 150% we shou the sign in UI with scroll bar even though there is enough vertical space for all the controls below the scroll bar.
At 200% we start to see overlapping controls 
At 250% - 400% the sign in button is not clickable and the dialog is not resizable. 

Ideally the dialog would size to fit the vertical space on the screen and add a scroll bar when there is not enough room.

**Comment by anangaur** [comment]
On high DPI the sign in window gets scroll bars and overlapped controls. On my surfacebook with resolution of 3000x2000, the UI doesn't scale and shows both horizontal and vertical scrollbars:
![attachfilehandler](https://cloud.githubusercontent.com/assets/14800916/18795828/39ae8df0-817b-11e6-9ddc-8b58da99fd68.png)

**Comment by kpanwar** [comment]
@anangaur - Is this still an issue? There was fix made on service side for this.

**Comment by crmann1** [comment]
This is still an issue. 

Some others have indicated they see this with the TS into a VM using a laptop that has a high DPI screen with a low DPI external monitor attached, and the RDP window was on the high DPI screen.

**Comment by simoncal** [comment]
My TS into a VM also experienced the same issue today, but using a laptop only. Laptop at 3000x2000, same as VM machine

**Comment by AArnott** [comment]
@jmprieur Thanks for fixing this. Can you link to the commit that fixed it?

**Comment by jmprieur** [comment]
@AArnott: actually this was not an issue in ADAL.NET, but in the service.

**Comment by AArnott** [comment]
I saw the bug Repro today. Has the service fix already been deployed? If so I think there's still an issue.
