### ISSUE TITLE
Perf degradation in Confidential Client flow 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/azure-activedirectory-library-for-dotnet#1630]
ADAL version: 5.0.5
ADAL version where this doesn't repro: 3.13.7

```csharp
X509Certificate2 aadCert = CertificateManager.Instance.FindCertificateByThumbprint(AAD_CERT_THUMBPRINT, StoreName.My);
ClientAssertionCertificate clientAssertionCert = new ClientAssertionCertificate(WebAppClientId, aadCert);
UserAssertion userAssertion = new UserAssertion(userAccessToken, USER_ASSERTION_TYPE, userName);
result = await authContext.AcquireTokenAsync("https://graph.microsoft.com", clientAssertionCert, userAssertion);
```

Our most recent deployment shows that dependency call as taking longer and longer over time, eventually resulting in our service being unable to handle any more requests. Strangely enough other calls to AcquireTokenAsync, for other resources don’t seem to exhibit that behavior. 

We noticed the below O(n*m) loop that was added 4 months ago to Microsoft.IdentityModel.Clients.ActiveDirectory (https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/commit/034f0876ccf4f478ff4eefc462af07628c0497fb), it seems like a good performance opportunity as accounts is literally getting constructed a few lines earlier as a List and constructing it as a Dictionary instead would provide O(n+m) performance.

Note - in the code above, the customer notices they have some 2000+ accounts  (line 107).

**Comment by bgavrilMS** [comment]
Note: Please investigate if equivalent issue exists in MSAL. The code above is in `FindMsalEntryForAdal`, so there isn't an exact equivalent for this in MSAL, but we should still try to find smth. 

I would also suggest that we cut this piece of functionality - ADAL reading MSAL entries is not really a supported scenario, GetAccounts / RemoveAccounts in ADAL ignore the MSAL cache etc.

**Comment by jmprieur** [comment]
@bgavrilMS @henrik-me 
Proposing to not fix this one, as we want people to move to MSAL anyway.

Any objection?

**Comment by jmprieur** [comment]
Please use MSAL.NET. See https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration
Closing for now.
