### ISSUE TITLE
UWP USER Canceled authentifiction 

### ISSUE THREAD

**Issue by XamarinTounsi** [AzureAD/azure-activedirectory-library-for-dotnet#1639]
Hello,

Native application no longer available in azure(application legacy is despairing)
I can't found my native application
I created another using the new steps but now idea if there are anther alternatives
 error : User cancled authentification. On an android device, this could be due to the lack of capabilities, such as custom tabs, for the system browser. See 
https://aka.ms/msal-net-system-browsers for more information

Cordially

**Comment by jennyf19** [comment]
@XamarinTounsi the error means that the user cancelled the authentication process. Since you are starting over, you should use [msal](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal) and the error message there is decided based on the platform

**Comment by XamarinTounsi** [comment]
thanks for your answer, i have changed my laptop and the authentification work fine ?
Maybe the webview cache had problem, any idea ? please

**Comment by bgavrilMS** [comment]
ADAL / MSAL have no control the webview cache. Please reopen if you can repro / have logs etc.
