### ISSUE TITLE
AccessToken / RefreshToken are not put in cache when retrieved for the current app

### ISSUE THREAD

**Issue by simonferquel** [AzureAD/azure-activedirectory-library-for-dotnet#164]
The token cache is not populated when an access token / refreshtoken is retrieved for the current app (ie without specifying an external resource) when calling GetTokenFromAuthorizeCodeAsync. 
That is a blocker for my web based scenario, since I need to persist it per user (in a protected cookie or in db) to use the refresh token in subsequent requests if I need to access other web APIs.

My current workaround, is to manage the caching of the result of my initial GetTokenFromAuthorizeCodeAsync. That is far from ideal.

**Comment by afshins** [comment]
@simonferquel: I cannot repro the issue you reported. What version of ADAL are you using? Also, can you provide ADAL logs? Instructions can be find at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/README.md#logs
