### ISSUE TITLE
Assistance needed in getting Xamarin Android + broker working

### ISSUE THREAD

**Issue by kshalini9** [AzureAD/azure-activedirectory-library-for-dotnet#1641]
Hello Team,

I need help on android broker part.
I followed the same steps which you suggested in below link, but no luck always regular browser is populating for authentication.

Referred below link
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/leveraging-brokers-on-Android-and-iOS

Could you plz help on this issue and we are using Microsoft.IdentityModel.Clients.ActiveDirectory 4.5.1 version (Xamarin.forms). and latest microsoft authenticator(6.5.22)
Note: i have seen Android broker is not supporting .
May i know Android broker is supporting from which version?

since 15 days we are struggling for this issue. 
Kindly guide me how to enable broker in android.

Thanks in advance.

**Comment by jennyf19** [comment]
@kshalini9 sorry it's taken us a while to get back to you on this. 
Can you try w/the latest version of ADAL (5.2.0) and send us [logs](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net#new-way-of-logging-controlling-pii-adalnet--318)? We've had some small updates to android broker, especially around logs between 4.5.1 and 5.2.0. 

You can include logs here or via email: jeferrie@microsoft.com

Thanks.

**Comment by negberts** [comment]
@jennyf19 I think we have the same problem. What should we look for in the logs to see if the broker is really triggered?

**Comment by negberts** [comment]
Also this part doesn't seem to work as well


`protected override void OnResume()
        {
            base.OnResume();

            if(!this.promptedForAccount)
            {
                this.promptedForAccount = true;
                const string WORK_AND_SCHOOL_TYPE = "com.microsoft.workaccount";

                // The docs state that you should call NewChooseAccountIntent so that the user grants access
                Intent intent = AccountManager.NewChooseAccountIntent(null, null, new[] { WORK_AND_SCHOOL_TYPE }, null, null, null, null);
                CrossCurrentActivity.Current.Activity.StartActivityForResult(intent, 999);

                // Now you should have access
                var accManager = AccountManager.Get(Application.Context);
                accManager.GetAccountsByType(WORK_AND_SCHOOL_TYPE);
            }
        }`

In the OnActivityResult the result is always cancelled, at least in the android emulator. We use the latest ADAL version 5.2.1

**Comment by negberts** [comment]
2019-09-16T13:13:21.9512040Z: 8c9e8658-06d6-4262-afa1-63104d729e72 - AdalLoggerBase.cs: BrokerProxy: Getting the Android context
2019-09-16T13:13:57.9062070Z: 8c9e8658-06d6-4262-afa1-63104d729e72 - AdalLoggerBase.cs: ADAL PCL.Android with assembly version '5.2.1.0', file version '5.2.1.0' and informational version '5.2.1' is running...
2019-09-16T13:14:30.5802950Z: 8c9e8658-06d6-4262-afa1-63104d729e72 - AdalLoggerBase.cs: Either a token was not found or an exception was thrown.
2019-09-16T13:14:46.2884250Z: 8c9e8658-06d6-4262-afa1-63104d729e72 - AdalLoggerBase.cs: Is Android Broker use configured via PlatformParamters? True
2019-09-16T13:15:05.0271910Z: 8c9e8658-06d6-4262-afa1-63104d729e72 - AdalLoggerBase.cs: Permission android.permission.GET_ACCOUNTS is missing from package manifest
2019-09-16T13:15:24.8488020Z: 8c9e8658-06d6-4262-afa1-63104d729e72 - AdalLoggerBase.cs: Can invoke broker? False
2019-09-16T13:15:42.4789630Z: 8c9e8658-06d6-4262-afa1-63104d729e72 - AdalLoggerBase.cs: Cannot invoke the broker directly, may require install …

I've found these in the logs... The android.permission.GET_ACCOUNTS is definitly in the manifest. 

`<uses-permission android:name="android.permission.GET_ACCOUNTS" />
  <uses-permission android:name="android.permission.MANAGE_ACCOUNTS" />
  <uses-permission android:name="android.permission.USE_CREDENTIALS" />`

So what is going wrong here?

**Comment by CyberNyanta** [comment]
GET_ACCOUNTS is a permission that has a dangerous protection level
[Google docs GET_ACCOUNTS](https://developer.android.com/reference/android/Manifest.permission.html#GET_ACCOUNTS)
so you need to ask for permission before broker call
[Google guide](https://developer.android.com/training/permissions/requesting#make-the-request)

**Comment by jmprieur** [comment]
+ @shoatman for guidance.

**Comment by shoatman** [comment]
@CyberNyanta - For reasons unknown to me Xamarin ADAL was not upgraded to call the bound service that the Android broker provided as a workaround for the required for GET_ACCOUNTS that the Android Open Source Project introduced with Android 6.  I understand that MSAL.Net will support the bound service so that this permission will not be required.  Broker support for MSAL Android is going to be available quite soon.  I expect MSAL.Net to support shortly thereafter.

**Comment by CyberNyanta** [comment]
@shoatman what do you mean by 
> the bound service

**Comment by shoatman** [comment]
@CyberNyanta - Android broker exposes a ["bound service" ](https://developer.android.com/guide/components/bound-services).

**Comment by jmprieur** [comment]
@jennyf19 @trwalke @bgavrilMS 
do we need to plan to use the bound service?

**Comment by bgavrilMS** [comment]
@jmprieur - ADAL for Android has been using the bound service for many years now. ADAL for Xamarin.Android has not been updated. We know it provides a poor experience (but it should work!). MSAL for Xamarin.Android with broker support (coming soon?) should make use of the bound service.

**Comment by jmprieur** [comment]
Won't fix in ADAL
We'll use a better version of the account manager in the Xamarin.Android support for broker.
Closing for now. Feel free to reopen if you disagree.
