### ISSUE TITLE
MSBuild and nuget update to support netstandard2.0

### ISSUE THREAD

**Issue by JBaltika** [AzureAD/azure-activedirectory-library-for-dotnet#1643]
**Hi guys,**
Could it possible update nuspec and msbuild to support netstandard2.0. Its late 2019 and king of jungle is netstandard2.0. I understand that current netstandard1.3 library works, but first project pulling useless nugets and runtime binding redirect section is getting bigger by day. Now for some organization who has for example 350+ project to manage these bindings become major issue.  As build master, i know its quite easy can be done.... 

![decompiler](https://user-images.githubusercontent.com/1755340/63824777-4f6d1580-c926-11e9-9ad9-2fbf495a1c05.jpg)

Thanks in advance,
Jim

**Comment by jmprieur** [comment]
@JBaltika ; this is not so much about adding a platform, than expanding the test matrix.
Is it an option for you to move to MSAL.NET ?

**Comment by JBaltika** [comment]
Thanks, I will forward the info to developers .... Its time to switch anyway ....
