### ISSUE TITLE
AdalError.DuplicateQueryParameter state

### ISSUE THREAD

**Issue by joshardt** [AzureAD/azure-activedirectory-library-for-dotnet#1644]
I've updated the ADAL version from 3.19.8 (which was working fine) to 5.2.0 which is causing the problem that the extra query parameter `state` is not working anymore.

**Which Version of ADAL are you using ?**
ADAL 5.2.0

**Which platform has the issue?**
xamarin android, xamarin iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Username Password

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of ADAL

**Repro**

```csharp
var authContext = new AuthenticationContext(EnvironmentConstants.AdfsServer.Authority, false);
var authenticationResult = await authContext.AcquireTokenAsync(EnvironmentConstants.AdfsServer.Scope, EnvironmentConstants.AdfsServer.ClientId, new Uri(EnvironmentConstants.AdfsServer.RedirectUrl), platformParameter, UserIdentifier.AnyUser, $"state={customState}&hide-registration-option=1&login_hint={customLogin}");
```

**Expected behavior**
A valid AuthenticationResult is returned.

**Actual behavior**
An exception is thrown:
AdalError.DuplicateQueryParameter
`Duplicate query parameter 'state' in extraQueryParameters`

**Comment by jennyf19** [comment]
@JFMG thanks for bringing this to our attention...we will take a look, and update here.

**Comment by rherlt** [comment]
@jennyf19 Any news here? The issue still exists.

**Comment by jennyf19** [comment]
@rherlt I'm not able to repro this. do you have a repro you can share or the code you're using, so i can try the same?

**Comment by jennyf19** [comment]
@JFMG @rherlt ADAL sets the state parameter for you, so you do not need to include it in the query parameters.

closing, as we will not be fixing this in ADAL. If there is a problem with this (using the state parameter ADAL generates and not sending your own), please let us know.

**Comment by joshardt** [comment]
@jennyf19 Microsoft consultants told us about 2 years ago to use the state parameter for a 2 factor login. Now it’s not working anymore. I’m a bit disappointed. It forces us to implement a new concept.

**Comment by jmprieur** [comment]
@JFMG . I understand your frustration: 
Today, 2 factor authentication is done by the tenant admin applying conditional access policies to the users and/or the app in the tenant. What happens if you don't send the state yourself given that ADAL does send it.
