### ISSUE TITLE
Get token to use with custom API app uses Intune Xamarin Binding with conditional access

### ISSUE THREAD

**Issue by jlhernandez1388** [AzureAD/azure-activedirectory-library-for-dotnet#1645]
Hello,

I have been trying for a long time now to retrieve a token with ADAL for .Net. The problem is that our client uses conditional access and prevents login in if it's not from a Microsoft approved app or Intune MAM app. (Please note that this is an app that will be distributed via Intune.)

I'm able to login and register with the Intune SDK successfully. But the Intune SDK doesn't provide a token so we can use it with our custom API. 

My understanding is that I can use broker to share a keychain between Intune SDK and ADAL for .Net. If I try to acquire a token silently after login in with the Intune SDK, it doesn't find anything in the cache. If i use the acquiretokenasync it asks for credentials and then it throws the same error "You cannot access the resource from this browser on your device."

Steps I have taken:

- I have added the keychain-access-groups
- Added scheme to LSApplicationQueriesSchemes
- Added IntuneMAMSettings 
- Added URL Types
- Added URI Redirects
- etc.

I have been following this references: 

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/leveraging-brokers-on-Android-and-iOS#brokered-authentication-for-android

https://github.com/AzureAD/azure-activedirectory-library-for-objc#brokered-authentication

https://docs.microsoft.com/en-us/intune/app-sdk-ios

https://docs.microsoft.com/en-us/intune/app-sdk-xamarin

Please any help will be appreciated.

Thanks!

**Comment by jennyf19** [comment]
@jlhernandez1388 Are you just targeting iOS apps? if so, I would recommend moving to [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/How-to-migrate-from-using-iOS-Broker-on-ADAL.NET-to-MSAL.NET), if possible, as we have iOS broker support there (android broker is coming soon). 

In the meantime, what are you using for the keychain access group? and can you get us [logs](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net#new-way-of-logging-controlling-pii-adalnet--318)? Logs can be sent via email, if that's easier -> jeferrie@microsoft.com

cc: @Kyle-Reis your thoughts here?

**Comment by jlhernandez1388** [comment]
Hi @jennyf19!

Thank you for your prompt response. We will be targeting iOS only for now. If have sent you the Pii logs via email. The keychain access groups  are com.microsoft.intune.mam, com.microsoft.adalcache and our custom bundle id.

 I will migrate this to MSAL to see if I have any luck.

If you see something on the logs please let me know.

Thanks!

**Comment by jennyf19** [comment]
Thanks @jlhernandez1388 ...got your email and included @Kyle-Reis ...could you update to 5.2.1 and send new logs (w/pii enabled)? 

Seeing this error in the logs:
`-canOpenURL: failed for URL: "msauth://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"` which means ADAL is not able to open broker. Which version of authenticator (iOS broker) are you using?

**Comment by jlhernandez1388** [comment]
@jennyf19 Sorry about that I downgraded just to test. Please note that this has never worked as this app is in development and when we went into production we found out that our client has conditional access set in AAD and that changed all the login logic.

When you asked if the broker even opened do you mean Company Portal or MS Authenticator. I read somewhere that Company Portal acts as the broker too, is that correct? We don’t have MS Authenticator installed but we do have the Company Portal. 

The Company Portal is version 3.13.0

I have sent the new logs via email.

**Comment by Kyle-Reis** [comment]
@jlhernandez1388 Company Portal does not act as the broker on iOS, so that error is likely due to Authenticator not being installed. Also, are you setting the iOSKeychainSecurityGroup property as mentioned in step 4 here: https://docs.microsoft.com/intune/app-sdk-xamarin#enabling-intune-app-protection-polices-in-your-ios-mobile-app

**Comment by jlhernandez1388** [comment]
@Kyle-Reis @jennyf19 I installed the MS Authenticator but now I have an error when the MS Authenticator opens. I do have the property iOSKeychainSecurityGroup setup. Please see the logs that I sent via email. Thanks for your help!

**Comment by Kyle-Reis** [comment]
@jlhernandez1388, are you overriding the default AAD Authority URI/Client ID/Redirect URI used by Intune to match the values used by the app’s call to acquire a token?

**Comment by jlhernandez1388** [comment]
@Kyle-Reis Yes I do! On the IntuneMAMSettings on the info.plist

**Comment by jlhernandez1388** [comment]
@Kyle-Reis In what format should my redirect Uri be setup?

**Comment by Kyle-Reis** [comment]
@jlhernandez1388 do you mean in general, or in the IntuneMAMSettings?

**Comment by jennyf19** [comment]
@jlhernandez1388 following up on this...any update?

**Comment by jennyf19** [comment]
@jlhernandez1388 any update?

**Comment by jmprieur** [comment]
Closing as there is no update. Feel free to reopen
