### ISSUE TITLE
Username Password Flow (ROPC) is not querying the user realm endpoint.

### ISSUE THREAD

**Issue by trwalke** [AzureAD/azure-activedirectory-library-for-dotnet#1648]
**Which Version of ADAL are you using ?**
5.2.1
**Which platform has the issue?**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Repro**
Perform a ROPC flow with a federated account with fiddler enabled.
Check the trace to see that ADAL tries to perform authentication using open ID connect.

**Expected behavior**
ADAL should first query the user realm endpoint to determine the account type. Then perform either WS-Trust for federated accounts or Open ID Connect for managed accounts based on the response.

**Actual behavior**
ADAL queries the instance discovery endpoint and uses Open ID Connect to authenticate.

**Possible Solution**
Make ADAL perform user realm discovery during the ROPC flow

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net. Don't post logs containing PII on GitHub!

**Comment by dmprantz** [comment]
Is this my issue?

**Comment by trwalke** [comment]
> Is this my issue?

No. not this one. This one is no longer needed
