### ISSUE TITLE
Using subject and issuer Authentication with ADAL

### ISSUE THREAD

**Issue by nebadr** [AzureAD/azure-activedirectory-library-for-dotnet#1649]
We are currently trying to migrate to using the subject issuer authentication with our first party AAD application. We added the sendx5c parameter to AcquireTokenAsync(string, IClientAssertionCertificate, UserAssertion) to achieve this. However, there is no overload for the method AcquireTokenSilentAsync (taking the resource, client assertion certificate and userIdentifier) that accepts the boolean sendx5c parameter, so what should be done?

**Comment by jmprieur** [comment]
@nebadr : is it an option for you to move to MSAL.NET:?
It has the feature https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.acquiretokenonbehalfofparameterbuilder.withsendx5c?view=azure-dotnet.

If needed we can help you update.

**Comment by nebadr** [comment]
@jmprieur  So what's the cost of moving to MSAL? and is there any other option other than this one?

**Comment by jennyf19** [comment]
@nebadr We didn't get back to you on this. 

here's information on the differences between [ADAL and MSAL](https://github.com/azuread/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal)

the extensiveness of your code base determines the cost in making the move, but long term, definitely worth it, as new features and development work will be happening in MSAL. If you need help w/the migration, please let us know. we are here to help.
