### ISSUE TITLE
The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache' threw an exception. 

### ISSUE THREAD

**Issue by themicrosoftguy** [AzureAD/azure-activedirectory-library-for-dotnet#1650]
**MSAL is the recommended auth library for use with the Microsoft identity platform**

No new features will be implemented on ADAL. The team's efforts are on improving [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the next-gen auth library. MSAL's wiki contains a [migration guide](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal) from ADAL.

Only regressions, high severity issues and security issues will be fixed on ADAL. Other issues are likely to have already been fixed in MSAL. 

If you think that your issue falls into the above categories, please fill in the form below.

**Which Version of ADAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

5.2.1

**Which platform has the issue?**

.Net Standard 2.0, Xamarin.iOS 12.8.02

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

> Mobile > Interactive / Integrated Windows Auth

Other? - please describe;
We are getting Type initializer error while trying to init AuthenticationContext (refer below):
Code:
authContext = new AuthenticationContext("https://login.microsoftonline.com/common"); //Also tried https://login.windows.net/common

Note: We have migrated our solution projects from PCL - Profile 44 to .Net Standard 2.0. We are performing this migration in order to consume the AspNet Core SignalR client in our Xamarin iOS App so that we are able to receive SignalR messages through our Azure SignalR Service implementation.

 
**Is this a new or existing app?**

This is a New App, however we have a release coming up in 1st week of October and ran into this issue after migrating to .Net Standard 2.0

**Repro**

```csharp
private static string azureCommonAuthority = "https://login.microsoftonline.com/common"; //"https://login.windows.net/common";

var authContext = new AuthenticationContext(azureCommonAuthority);
```

**Expected behavior**
The AuthenticationContext gets initialised successfully in order to consume the ADAL library and authenticate the user.

**Actual behavior**
Currently, it just exits and throws the type initializer error.   

**Possible Solution**

**Additional context/ Logs / Screenshots**

Error details:
2019-09-13 15:16:52.840007+0530 OtisONE[58458:1442247] Message: The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache' threw an exception.
Resolved pending breakpoint at 'AuthenticationService.cs:209,1' to void OtisONE.Business.Authentication.AuthenticationService.<AuthenticateUser>d__16.MoveNext () [0x00052].
Error while resolving expression: Value must be positive.
Parameter name: count2019-09-13 15:17:16.843856+0530 OtisONE[58458:1442247] Message: The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache' threw an exception.

Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net. Don't post logs containing PII on GitHub!

Please assist us with this on priority as it is a very high severity and big impediment for our new app release.

**Comment by jmprieur** [comment]
@mehul19851 
You might need to reference the iOS library as well. Did you read https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Understanding-multi-targetting-and-NetStandard ?

**Comment by slnali** [comment]
@mehul19851  I am running into same issue, did you find a solution?

**Comment by themicrosoftguy** [comment]
> @mehul19851 I am running into same issue, did you find a solution?

We had to migrate the library from ADAL to MSAL for compatibility issues.
