### ISSUE TITLE
AdalClientException when initializing AuthenticationContext: TeamId returned null from the iOS keychain 

### ISSUE THREAD

**Issue by slnali** [AzureAD/azure-activedirectory-library-for-dotnet#1652]
followed these instructions to rectify issue but after adding Entitlements.plist to custom entitlements, i now get could not find any provisioning profiles for iOS error?
![image](https://user-images.githubusercontent.com/9381704/64990768-5dc8a480-d8c8-11e9-9979-c0adfa10486a.png)

**Comment by jennyf19** [comment]
@slnali Are you setting the `.iOSKeychainSecurityGroup` property? Here's an [example](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/devApps/XFormsApp.iOS/SecondPageRenderer.cs#L56)

And if you go to properties for the iOS application, then iOS Bundle Signing, do you have the Entitlements there in Custom Entitlements? If not, please add them. |
![image](https://user-images.githubusercontent.com/19942418/64991850-82505c80-d887-11e9-9d50-ec884e510e53.png)

**Comment by slnali** [comment]
Yes, it's been set. 
![image](https://user-images.githubusercontent.com/9381704/64993385-dbdb7a00-d8cd-11e9-83e6-b22147d34337.png)

It's actually when I set it that I get the provisioning profiles issue. When I remove the custom entitlement and just add it in the Entitlements.plist file I don't get the error anymore but then I run into the same AdalClientException issue. 
![image](https://user-images.githubusercontent.com/9381704/64993649-7fc52580-d8ce-11e9-868e-323b6d2122aa.png)


This issue is happening before setting the .iOSKeyChainSecurityGroup (on initialisation of the AuthContext) 
![image](https://user-images.githubusercontent.com/9381704/64993546-44c2f200-d8ce-11e9-967a-be63c967c1c1.png)

**Comment by jennyf19** [comment]
@slnali you should have something in your provisioning profile. 
![image](https://user-images.githubusercontent.com/19942418/64995192-6f418a80-d88f-11e9-8d8b-2083b779e4ef.png)

**Comment by slnali** [comment]
@jennyf19  so does this requires setting up an apple developer account? Didn't know this was required for testing the app via iOS Simulator locally.

**Comment by jmprieur** [comment]
@slnali ; yes it requires an apple developer account 
😼

**Comment by jennyf19** [comment]
@slnali please reopen if necessary.
