### ISSUE TITLE
Different Broker URI expected than generated

### ISSUE THREAD

**Issue by negberts** [AzureAD/azure-activedirectory-library-for-dotnet#1654]
I've followed this article to enable brokers for Android: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/leveraging-brokers-on-Android-and-iOS 

However, when I try to generate the broker URL from your generateRedirectUriForBroker.ps1 file it is missing the signature.cmd file so it fails to run.  So I used https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/GetBrokerRedirectURI.ps1 instead. It generated the following redirect URI: msauth://nl.piminfra.Pim.MobileApp.prd/szeN2o%2bCHciVK%2bDtj4aSg3fGLew%3d

This worked like a charm yesterday. But today a new deployment was done to the play store and suddenly ADAL now says it needs a different redirect URI: msauth://nl.piminfra.pim.mobileapp.prd/UK0cOC8noJ7JWt%2bDK37H8F8v2m8%3d
If I download the APK from the play store it still generates the original redirect URI in the powershell script. So why does ADAL expect a different URI?

Is this going to change every deployment? Should I maybe use the GetRedirectUriForBroker method from the "Redirect URI during development" section every time?

I've found this issue as well: https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/729 
Looks like the same?

**Comment by jmprieur** [comment]
@jennyf19 @oldalton : would a deployment of authenticator explain this?

**Comment by oldalton** [comment]
It might. Or it might be because of using a different signature (prod vs dev). Adding Shane to take a look: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1654

Thanks,
Olga

________________________________

**Comment by negberts** [comment]
@jmprieur @oldalton another problem that we seem to have is that the redirect URI is now generated as msauth://nl.piminfra.pim.mobileapp.prd/UK0cOC8noJ7JWt+DK37H8F8v2m8= but the Azure Portal doesn't allow it to be registered, it doesn't allow the = at the end. 

![image](https://user-images.githubusercontent.com/20299260/65123892-8ea5f800-d9f4-11e9-825c-1bca31a7c9e1.png)

If I change it to msauth://nl.piminfra.pim.mobileapp.prd/UK0cOC8noJ7JWt%2bDK37H8F8v2m8%3d with %2b for the + sign and %3d for the = sign, than the azure portal accepts the URI but the app now complains that the URI is not registered at Azure Portal:

![image](https://user-images.githubusercontent.com/20299260/65124045-dfb5ec00-d9f4-11e9-8290-9b79b4acaba5.png)

How can we fix this?

**Comment by jmprieur** [comment]
@negberts : did you read this article ? 
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-use-brokers-with-xamarin-apps#step-7-make-sure-the-redirect-uri-is-registered-with-your-app

**Comment by shoatman** [comment]
There is a doc and portal bug here.  @hamiltonha - We need to file a bug with the portal team to update the scripts used to generate the redirect URI to ensure that it's base64 and url encoded.  The current powershell scripts do that in the Android project... however the documentation for Xamarin and the scripts in the portal do not do that.

**Comment by negberts** [comment]
> @negberts : did you read this article ?
> https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-use-brokers-with-xamarin-apps#step-7-make-sure-the-redirect-uri-is-registered-with-your-app

@jmprieur if broker support is not available for Android, why is it in your documentation than? 

@shoatman thank you! Could you maybe also add the signature.cmd file to github that your powershell file is revering to?

**Comment by jmprieur** [comment]
@negberts : sorry it is in ADAL, not in MSAL yet. my bad.

**Comment by negberts** [comment]
@jmprieur that's a good thing because I cannot migrate to MSAL as long as MSAL doesn't support setting the tenant ID after initialization.

**Comment by jmprieur** [comment]
@negberts : MSAL.NET supports setting the tenant ID after initialization (with the `.WithAuthority()` on the acquire token xx builder

app.AcquireTokenXXX(scopes)
 .[WithAuthority](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.abstractacquiretokenparameterbuilder-1.withauthority?view=azure-dotnet)(authority)
 .ExecuteAsync();

**Comment by negberts** [comment]
@jmprieur yes but on the IOS and Android apps I have to add a fixed client id to the android manifest and the IOS info.plist

We have 8 different tenants that each have configured the app in their own active directory. On startup of the app they choose their own tenant to login to and authenticate against their own active directory. This scenario works with ADAL. Not with MSAL, because of these limitations.

**Comment by oldalton** [comment]
Recommended Redirect Uri format has changed for both iOS and Android, and you shouldn't need to have your clientId in Info.plist anymore. Please take a look at some documentation here: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-mobile-app-configuration

**Comment by negberts** [comment]
@oldalton thank you, that looks promising!

**Comment by jennyf19** [comment]
@negberts are you still having issues w/this?

**Comment by negberts** [comment]
@jennyf19 Yes and no. I am using the GetRedirectUri method in my app to generate the redirect URI. But I did do a deployment lately and at least it did not generate a 'new' URI since I have not seen issues about a redirect URI missing in Azure. However, it is still a different URI then the powershell generated.

**Comment by jennyf19** [comment]
@negberts should we close the issue and have you reopen if/when it happens again?

**Comment by negberts** [comment]
@jennyf19 okay

**Comment by jennyf19** [comment]
@negberts closing, but please reopen if you encounter it again.
