### ISSUE TITLE
broker_response_hash_mismatch: Unencrypted broker response hash did not match the expected hash when using iOS 13.1.x, MS Authenticator 6.3.22 and ADAL 5.5.2.

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-library-for-dotnet#1666]
more information included in this [issue](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1657)
Not only happening on iOS 13.

**Comment by jennyf19** [comment]
@biozal and @marnilss I have opened a separate issue here for what you're seeing.

**Comment by aaronlabeau** [comment]
@jennyf19 this is @biozal, this is my other GitHub account - my current one is locked out because my Google authenticator app sucks.  I'm going to try and get it unlocked today and I'll post more logs here.

**Comment by jennyf19** [comment]
@marnilss have identified the issue..if you'd like to try out a build to see if it works for you, please send me an email -> jeferrie@microsoft.com

**Comment by jmprieur** [comment]
@jennyf19 : I added it for 5.2.3.

**Comment by jennyf19** [comment]
Included in 5.2.3 release

**Comment by jennyf19** [comment]
@aaronlab @marnilss
