### ISSUE TITLE
Can't login with Galltin(Chinese) Azure AD

### ISSUE THREAD

**Issue by isaaciaac** [AzureAD/azure-activedirectory-library-for-dotnet#1677]
**MSAL is the recommended auth library for use with the Microsoft identity platform**

No new features will be implemented on ADAL. The team's efforts are on improving (MSAL)[https://github.com/AzureAD/microsoft-authentication-library-for-dotnet], the next-gen auth library. MSAL's wiki contains a (migration guide)[https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal] from ADAL.

If you require a new feature, there's a good chance it has already been implemented in MSAL. If it isn't, please open an (issue)[https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/new/choose] on MSAL's GitHub repo to let us know the details.

**Comment by jmprieur** [comment]
@negoe : do you have insights?

**Comment by jmprieur** [comment]
@isaaciaac : do you have repro steps?

**Comment by jmprieur** [comment]
@isaaciaac closing as you have not provided repro steps.
Feel free to reopen
