### ISSUE TITLE
ADAL dialog's content not readable with Windows 8.1 High Contrast #1 theme

### ISSUE THREAD

**Issue by jkwon2013** [AzureAD/azure-activedirectory-library-for-dotnet#168]
Repro Steps: 
1. In Windows 8.1, switch theme to High Contrast #1
2. In Visual Studio, try sign in.

![high contrast adal sign in dialog](https://cloud.githubusercontent.com/assets/11651452/6830662/8faa6ed4-d2d8-11e4-8993-4c19605e2bde.PNG)

**Comment by RandalliLama** [comment]
Server issue that has hopefully been fixed by now.
