### ISSUE TITLE
In Visual Studio's sign in page, account / email field doesn't have the right property set for the narrator

### ISSUE THREAD

**Issue by jkwon2013** [AzureAD/azure-activedirectory-library-for-dotnet#169]
Steps to reproduce:
Visual Studio 2015 RC

1. Turn on Narrator
2. Open Server Explorer.
3. Choose "Manage and Filter Subscriptions" from the Azure top level node's context menu.
4. Click on Add an account.
5. Tab out and tab back into the field that is asking for you email account. 

![adal sign in](https://cloud.githubusercontent.com/assets/11651452/6834053/90f2d928-d2ee-11e4-9f95-b2470d2e4e4d.PNG)

Expected: 
Says something like enter you email id etc.
 
Actual:
Says "end of line" or "empty line"
 
Note: Same happens on the password field further down the sign in experience.

**Comment by afshins** [comment]
This requires a server side change and we redirected the request to the team.

**Comment by afshins** [comment]
I could not repro it in the browser or Visual Studio 2013, but could repro it in Visual Studio 2015 RC as reported in the bug. 
 
Repro steps:
 
-          Create a new “ASP.NET Web Application” project in VS.
-          Choose “Host in the cloud” option (is set by default).
-          Click on Sign In button
-          Activate narrator (Start+Enter)
-          Tab and then Shift-Tab

**Comment by afshins** [comment]
I managed to repro on the browser as well, but only on the Windows 10 machine. It seems the difference is not in the request sent in VS 2015 vs. VS 2013. It is about the browser component on the machine which provides the WebBrowser control. This is the version on Windows 10 which repros the issue:
 
 


 
And this is the uri for the repro:
 
https://login.windows.net/common/oauth2/authorize?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=872cd9fa-d31f-45e0-9eab-6e460a02d1f1&response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&client-request-id=4770af9b-0e5c-4064-b5de-fd59631aad40&prompt=login&x-client-SKU=.NET&x-client-Ver=2.11.0.0&x-client-CPU=x64&x-client-OS=Microsoft+Windows+NT+10.0.10041.0&site_id=500879&display=popup&nux=1

**Comment by afshins** [comment]
A bug was filed for the IE team to address this issue.
