### ISSUE TITLE
AcquireTokenSilentAsync using a cached token is not working with Xamarin forms

### ISSUE THREAD

**Issue by badarilr** [AzureAD/azure-activedirectory-library-for-dotnet#1690]
AcquireTokenSilentAsync using a cached token is not working with Xamarin forms with the latest ADAL version. This is the snippet used in order to refresh the token. 

                    try
                    {
                        AppData.AuthenticationResult = await AppData.AzureActiveDirectoryContext.AcquireTokenSilentAsync(
                                                AppConstants.SecuredInfo[AppConstants.Selected{app}InstanceIndex].GraphResourceUri,
                                                AppConstants.SecuredInfo[AppConstants.Selected{app}InstanceIndex].ClientId,
                                                new UserIdentifier(email, UserIdentifierType.RequiredDisplayableId));
                    }

**Comment by bgavrilMS** [comment]
Hi @badarilr - please fill in the entire form when logging bugs. I have no idea what you mean "not working". A few more things: 

1. can you use MSAL instead ? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet (ADAL is being deprecated and we only fix regressions and security bugs)
2. Are you sure the token cache is not empty or that the email matches the user you have in cache?

Some things to read: 

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/User-management

**Comment by badarilr** [comment]
Hi @bgavrilMS 

I had issues with refresh token and it wasn't get extended after token expiry time out w.r.t Xamarin forms. As suggested by will have a look at MSAL and the second point mentioned by you was working as expected.

**Comment by Druffl3** [comment]
Hey @badarilr , did you manage to get it fixed? If yes, can you share your soultion?
