### ISSUE TITLE
Updaing ADAL library from 3.19.6 to 4.5.1 version breaks serilization deserilization of object

### ISSUE THREAD

**Issue by tyaginidhi** [AzureAD/azure-activedirectory-library-for-dotnet#1691]
There is a regression in Deserilization of AuthenticationResult object between versions above that is blocking us form updating to the later version of ADAL library. Can anyone help fix this issue for us?

Test method Microsoft.VisualStudio.Services.ArtifactServices.App.Shared.L0.Tests.VsoCredentialHelperAadTests.VsoCredentialHelperGetAADCredentialsIgnoresPromptBehaviorIfNotEnvironmentUserInteractive threw exception:
System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.Services.ArtifactServices.App.Shared.L0.Tests.SucceedingAuthenticationContext' threw an exception. ---> System.Runtime.Serialization.InvalidDataContractException: No set method for property 'IdToken' in type 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResult'. The class cannot be deserialized.

Seems serialization was broken and reported here before: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/930

**Comment by bgavrilMS** [comment]
Seems like a regression from 3.19. Affects other people's unit tests.

**Comment by bgavrilMS** [comment]
@tyaginidhi - note that if you have some AuthenticationResult objects serialized for your tests, they might not work from 3.19 to latest ADAL anway. But I agree that this object used to be serializable (and marked with DataContract), and today it is not.

**Comment by bgavrilMS** [comment]
@jmprieur @henrik-me - would we want to take this one? The regression is there since 3.x, this is the first complaint. 

@tyaginidhi - if I understand correctly, you deserialize this object from a json file to be able to mock ADAL. I believe there is a workaround in creating the a test object AuthenticationResult via reflection instead of using deserialization - can you try that?

**Comment by tyaginidhi** [comment]
@bgavrilMS : sure let me give that a try. But that will only fix the test cases. My concern is about the break in functionality due to this regression.

**Comment by bgavrilMS** [comment]
@tyaginidhi - we have quite a lot of test coverage for ADAL, and it's also in use by many developers. 

The fact that `AuthenticationResult` is no longer serializable only impacts tests - ADAL itself does not use serialization to create this object.

**Comment by tyaginidhi** [comment]
@bgavrilMS : Got it! We are updating our L0 to work around the issue. We do expect the regression to be fixed in the next package version to avoid any potential issues.

**Comment by bgavrilMS** [comment]
I recommend the following: 

1. Move to MSAL. It's much better. We fix bugs there. 
2. Wrap the `AuthenticationResult` object into an object that you control. Then you can test it. 
3. Use reflection, smth like

```csharp
            var adalResultType = typeof(AuthenticationResult).Assembly.GetTypes().Single(t => t.Name == "AdalResult");
            var adalResult = typeof(AuthenticationResult).Assembly.CreateInstance(
                adalResultType.FullName,
                false,
                BindingFlags.Instance | BindingFlags.NonPublic,
                null,
                new object[] { "Bearer", "access_token_string", DateTimeOffset.UtcNow.AddMinutes(60) }, 
                null, null);

// set some properties
// invoke AuthenticationResult constructor
```
