### ISSUE TITLE
NullReferenceException in CryptographyHelper.GetCryptoProviderForSha256

### ISSUE THREAD

**Issue by miaobinxu** [AzureAD/azure-activedirectory-library-for-dotnet#1701]
Our project is using Microsoft.IdentityModel.Clients.ActiveDirectory version 2.28.3. Recently we got an error `System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.GetCryptoProviderForSha256(RSACryptoServiceProvider rsaProvider)`. After checking the source code, I noticed that we have a null checker in `CryptographyHelper.SignWithCertificate` in version 3.19.1, but there is no null checker in 2.28.3, which causes the error. Is it possible to add a null checker in version 2.28.3? That would solve our issues. Thanks!

**Comment by jmprieur** [comment]
@miaobinxu 

As you can see in the [README.md - Update to MSAL.NET now](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/README.md#update-to-msalnet-now) of this repository:
- ADAL.NET 2.x is no longer supported. Therefore we won't fix this issue.
- MSAL.NET is now the recommended library and we are asking people to move away from ADAL.NET to MSAL.NET. If you are a first party partner, we can even help you to do so

If you really want to stay with ADAL.NET, we recommand that you move to the latest version (currently 5.2.7)

Copying an extract of the README.md for your convenience:

#### Update to MSAL.NET now!

[MSAL.NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) is the new authentication library to be used with the Microsoft identity platform

Building on top of ADAL, MSAL works with the new and Open ID Connect certified Azure AD V2 endpoint and the new social identity solution from Microsoft, Azure AD B2C.

ADAL.NET is in maintenance mode and no new features will be added to ADAL.NET anymore. All our ongoing efforts will be focused on improving the new [MSAL.NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet). MSAL’s documentation also contains a [migration guide]( https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration) which simplifies upgrading from ADAL.NET, including how to migrate Xamarin.iOS apps using brokers.

#### ADAL.NET 2.x is no longer supported

ADAL.NET 2.x is no longer supported. ADAL.NET 3.x became generally available more than 3 years ago, superseding ADAL 2.x which was last released in August 2017
If you are still using 2.x, we recommend that you update directly to MSAL.NET
