### ISSUE TITLE
Update nuget description to point to MSAL.NET

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/azure-activedirectory-library-for-dotnet#1707]
Ship an update to ADAL.NET which updates the nuget metadata package description to have people going directly to nuget.org/adal.net to find an easy to click link to the newest library version.

**Suggesting to add the following to the description:**
There is a newer version of this library available here: https://www.nuget.org/packages/Microsoft.Identity.Client/

- Ideally this would be the first information for the description
- Could add an additional link to the migration guide here as well

This is based on learnings from Azure SDK's (e.g. [KeyVault Nuget](https://www.nuget.org/packages/Microsoft.Azure.KeyVault)) and is something we are currently implementing for Java and [Python](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/231).

**Comment by bgavrilMS** [comment]
Fixed in 5.2.8
