### ISSUE TITLE
user is not able to login

### ISSUE THREAD

**Issue by shristikatiyar** [AzureAD/azure-activedirectory-library-for-dotnet#1716]
**MSAL is the recommended auth library for use with the Microsoft identity platform**

No new features will be implemented on ADAL. The team's efforts are on improving [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the next-gen auth library. MSAL's wiki contains a [migration guide](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal) from ADAL.

Only regressions, high severity issues and security issues will be fixed on ADAL. Other issues are likely to have already been fixed in MSAL. 

If you think that your issue falls into the above categories, please fill in the form below.

**Which Version of ADAL are you using ?**
5.2.7

**Which platform has the issue?**
xamarin iOS

**What authentication flow has the issue?**
     Mobile Interactive

Other? - please describe;

**Is this a new or existing app?**

b. The app is in production, uses the same version of ADAL, but started seeing this issue

**Expected behavior**
User should be able to login

**Actual behavior**
User is not able to login

[O365MobileAppLog - 2021-01-11T113705.690.txt](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/files/5794242/O365MobileAppLog.-.2021-01-11T113705.690.txt)

**Comment by jmprieur** [comment]
@shristikatiyar: is this a transient error? or something you still see now?
The logs seem to say that this is a transient error from the service (Internal Server Error, Gateway Timeout and Service Unavailable.)

**Comment by shristikatiyar** [comment]
This user is seeing this error since a long time and is not able to login.

**Comment by jennyf19** [comment]
@shristikatiyar we'd recommend updating to MSAL .NET, as that supports the last iOS OS. ADAL is on the deprecation path.
