### ISSUE TITLE
Missing PlatformParameters constructor for .net core version of MS.IdentityModel.Clients.ActiveDirectory

### ISSUE THREAD

**Issue by trevors20** [AzureAD/azure-activedirectory-library-for-dotnet#1717]
**Which Version of ADAL are you using ?**
5.2.8

**Which platform has the issue?**
.Net Core/Net48

Other? - please describe;
I created a .Net Core app and started consuming a 3rd party dll that was using MS.IdentityModel.Clients.ActiveDirectory.  When I went to run my app I received a method not found exception.  This is because the 3rd party binary that I'm referencing is calling the "**public PlatformParameters(PromptBehavior promptBehavior)**" constructor for the PlatformParameters object.  But, for some reason this constructor is missing in the .Net Core implementation of MS.IdentityModel.Clients.ActiveDirectory.
Does anyone know why this was not implemented in the .Net Core version.?

I have unfortunately had to redo my project to be a .Net framework app instead to make it easier to use MS.IdentityModel.Clients.ActiveDirectory.

**Comment by jmprieur** [comment]
@trevors20 : ADAL.NET is on the deprecation path.
Please use MSAL.NET: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
