### ISSUE TITLE
Cannot install. Install-Package: Dependency loop detected for package 'Microsoft.IdentityModel.Clients.ActiveDirectory'

### ISSUE THREAD

**Issue by konrad-jamrozik** [AzureAD/azure-activedirectory-library-for-dotnet#1718]
I cannot install the package

```
~\.nuget> Remove-item -Force -Recurse packages
~\.nuget> Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory -Source https://api.nuget.org/v3/index.json
The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'nuget.org'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
Install-Package: Dependency loop detected for package 'Microsoft.IdentityModel.Clients.ActiveDirectory'.

```

**Comment by jmprieur** [comment]
@konrad-jamrozik 
ADAL.Net does not depend on anything else than the .NET framework

![image](https://user-images.githubusercontent.com/13203188/109872668-06112b00-7c6d-11eb-83c9-64767b80bb4d.png)

Also this is concerning that nuget would be not trusted?
I think you might have some issues with your nuget.config files ?

**Comment by konrad-jamrozik** [comment]
@jmprieur my nuget.config below. Note I passed the `-Source https://api.nuget.org/v3/index.json` parameter. I would expect that the content of my nuget.config should not matter given this argument.

It took NuGet several minutes before it output that error.

In any case, if it should work, later I can do some investigation with verbose logging etc. to figure out the root cause and report it back here. For now I have a workaround by directly attaching .dll from the package with `Add-Type` to the script I am trying to run.

--- 

My nuget.config:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <clear />
    
    <add key="INTERNAL_NAME" value="INTERNAL_VALUE" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageSourceCredentials>
    <INTERNAL_NAME>
      <add key="Username" value="PAT" />
      <add key="ClearTextPassword" value="PAT_VALUE" />
    </INTERNAL_NAME>
  </packageSourceCredentials>
</configuration>
```

**Comment by konrad-jamrozik** [comment]
@jmprieur  this is my nuget.config:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <clear />
    
    <add key="INTERNAL_NAME" value="INTERNAL_VALUE" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageSourceCredentials>
    <INTERNAL_NAME>
      <add key="Username" value="PAT" />
      <add key="ClearTextPassword" value="PAT-VALUE" />
    </INTERNAL_NAME>
  </packageSourceCredentials>
</configuration>
```

**Comment by jmprieur** [comment]
@konrad-jamrozik you might want to clear you Nuget cache?
under C:\users\yourAlias\.nuget\packages remove the folder for ADAL for instance.

It's safe to remove all the folders if you don't mind re downloading them, btw

**Comment by konrad-jamrozik** [comment]
@jmprieur that was the first thing I did. Observe the first line in my first post:

`~\.nuget> Remove-item -Force -Recurse packages`

**Comment by jmprieur** [comment]
@konrad-jamrozik is your project using the PackageReference? or still the old package.config?

**Comment by konrad-jamrozik** [comment]
@jmprieur pardon my ignorance, but to my understanding there is no project to speak of. I am trying to run a powershell `.ps1` file that fails on following line:

`$platformParameters = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters" -ArgumentList "Auto"`

with error:

```
Cannot find type [Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters]: verify that the assembly containing this type is loaded.
```
hence I concluded I probably need to install the package.

**Comment by jmprieur** [comment]
@konrad-jamrozik : if you're using it from PowerShell, then please rather use https://github.com/AzureAD/MSAL.PS/, which is maintained and tested, and using MSAL.NET (ADAL.NET is deprecated)

**Comment by konrad-jamrozik** [comment]
@jmprieur OK thx. I installed the module:

```
Install-Module MSAL.PS -Repository PSGallery
```

but the script fails the same way. I understand the answer then is "this problem won't be fixed as the script I am using is unsupported", correct?

**Comment by jmprieur** [comment]
@konrad-jamrozik, I suggest you ask the question in the MSAL.ps repo (I'm not familiar with the usage of MSAL in PowerShell, but I know this works very well)

**Comment by konrad-jamrozik** [comment]
OK, thanks @jmprieur. Closing this as a hybrid between "answered", "redirected" and "won't fix" ;)
