### ISSUE TITLE
MS Docs:  Please clarify what AssertionTypes would be valid here, or provide links to other documentation. 

### ISSUE THREAD

**Issue by jsquire** [AzureAD/azure-activedirectory-library-for-dotnet#1719]
### Documentation Related To Component:
`Microsoft.IdentityModel.Clients.ActiveDirectory`

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Notification of Issue Transfer
This issue was opened by @seannybgoode in the Azure SDK Docs repository and is being transferred.  _([original issue](https://github.com/Azure/azure-docs-sdk-dotnet/issues/760))_ Please be sure to address questions and responses to the original author.

### Description Of The Issue
The documentation here is incredibly sparse. Would really appreciate some elaboration.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda09a3d-ffad-2ce0-5723-3d3659015d5c
* Version Independent ID: b995f2b5-4994-9984-8625-ad20def2b269
* Content: [UserAssertion.AssertionType Property (Microsoft.IdentityModel.Clients.ActiveDirectory)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.userassertion.assertiontype?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_UserAssertion_AssertionType)
* Content Source: [xml/Microsoft.IdentityModel.Clients.ActiveDirectory/UserAssertion.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory/UserAssertion.xml)
* Service: **active-directory**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jmprieur** [comment]
@jsquire ADAL is deprecated. We are not going to update the XML comments for the reference documentation
Please use MSAL.NET instead

See https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.userassertion?view=azure-dotnet
