### ISSUE TITLE
User is not able to signin

### ISSUE THREAD

**Issue by shristikatiyar** [AzureAD/azure-activedirectory-library-for-dotnet#1724]
**MSAL is the recommended auth library for use with the Microsoft identity platform**

**Which Version of ADAL are you using ?**
5.2.7

**Which platform has the issue?**
Xamrin.ios

**What authentication flow has the issue?**
Mobile
 Interactive

Other? - please describe;

**Is this a new or existing app?**
 The app is in production, uses the same version of ADAL, but started seeing this issue

**Repro**

```csharp
var your = (code) => here;
```

**Expected behavior**
User should be able to sign in

**Actual behavior**
User is not able tt sign in Error
--> Inner Exception Details
Exception type: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException
, ErrorCode: service_returned_error
, StatusCode: 408
---> Inner Exception

**Additional context/ Logs / Screenshots**
[O365MobileAppLog - 2021-03-30T202149.785.txt](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/files/6229988/O365MobileAppLog.-.2021-03-30T202149.785.txt)

User is a Global Admin and have a conditional access policy assigned enforcing MFA.
User have Company Portal and Authenticator installed
User is enrolled in Intune
  
Authenticator app Incident ID is: ZWRGTMY7
Company Portal Incident ID is: D5DF910E

**Comment by bgavrilMS** [comment]
Apps need to move to MSAL. We will not be fixing Adal issues.

**Comment by shristikatiyar** [comment]
Hi @bgavrilMS  can we root cause the issue,  will it be fixed after migration to MSAL.net
error code is sevice_not_available

**Comment by bgavrilMS** [comment]
It's just a timeout, see HTTP status code 408. Could be bad internet connection, could be an AAD outage (we had one last week).

**Comment by shristikatiyar** [comment]
> It's just a timeout, see HTTP status code 408. Could be bad internet connection, could be an AAD outage (we had one last week).

Yes agrred form the error it seems service_not_available , but recently we got some more errors with this error code,.
