### ISSUE TITLE
[Bug] Auth Redirect failure in ADAL on iOS

### ISSUE THREAD

**Issue by Deloyuri** [AzureAD/azure-activedirectory-library-for-dotnet#1726]
**Logs and Network traces**
network trace contains sensitive data and was submitted through support ticket 

**Which Version of MSAL are you using ?**
ADAL .NET  v3.19.8

**Platform**
xamarin iOS: 14.4.2 and 14.5

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;
 * [x] Authorization Code
 
**Is this a new or existing app?**
b. The app is in production, I haven't upgraded MSAL, but started seeing this issue

**Repro**
Able to reproduce on several devices with iOS Beta 14.5 (one 14.4.2), and any apps using ADAL 3.19.8 to authenticate. 

**Expected behavior**
After entering password on company IDP in the webview of the app, I should be redirected back to the native app.

**Actual behavior**
I see a screen that says "Object moved to _here_".  The link is as follows (app registration configured with reply URL for native app). 
https://login.microsoftonline.com/urn%3aietf%3awg%3aoauth%3a2.0%3aoob%3fcode%3d0.ASYA8UXaNizdH02vE1q-RrmZIe37.......hDhXDof9-Guni2eluEYp85IAA%26session_state%3d312c6e64-1d4a-4310-8df4-9b56de6f 

**Possible Solution**

**Additional context/ Logs / Screenshots**
![IMG_7006D8F7D074-1](https://user-images.githubusercontent.com/31288840/115338167-e1fba180-a167-11eb-9f28-c089719f6491.jpeg)

**Comment by jmprieur** [comment]
This is an issue happening on ADAL.NET. I transferred it to the ADAL.NET repo.
@bgavrilMS @trwalke @jennyf19 @pmaytak : do we have a way of trying if MSAL.NET is also affected?

**Comment by Deloyuri** [comment]
Can you please send me link to the new issue?

Sent from my iPhone

On Apr 20, 2021, at 3:50 AM, Jean-Marc Prieur ***@***.***> wrote:

﻿

This is an ADAL.NET issue. I transferred it to the ADAL.NET repo.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1DXdgkOMjqB5sGX1XRVCjxVK0I5E96Iz3tubNySa-U7o6Fs5AhNL5B2SeEC6mmc9ppxCy0TzCVLIxJ4Tqm8U-t5R88Lb3pnxgBtm54u-EEMAHqW0M8tU-KP-RmRNb_OgTGQK_Q8OWQUKrDZ6vU1TUd-_UFqd8lZdUqT324xNch-GurFMVwufciChoN_DMBbAL9XpSGdnXxW2Q38__Y-KeAHMx8dD-S6t7vnYgHrzNYWj05WUWSABIiyjqRrjEENBnGDdeLkTPf7FuhsNouBih-RiS9QXv7y_DQ99woUcjsWxMMawMv97UBQrLMCzeex1HEYmhHMcsBjxO1gv8aTFqJhW5fPwdA_dQ8CCweQEsuWEZZpS1HlsQsMW_W9pTW6zjz0TJhQ3dThDa_uI4tooNyGDQyYFIJf3Z8xgLNbYaQwtIrVc2FdqtENreGpZ99iNqHwsCXAhoaQd-ysdpeOrjdXp1isMaJ7fD2ruNstq0BIbXucJuVbwqjpVzB_Ipi68k4XUELGStG28I1nrehrUDYQ/https%3A%2F%2Fgithub.com%2FAzureAD%2Fazure-activedirectory-library-for-dotnet%2Fissues%2F1726%23issuecomment-823102326>, or unsubscribe<https://secure-web.cisco.com/1z1KkoubCyxwEw5pd4PQoJssp6owQAmfD3y7nGWOWn4oXYdwGIy0FV1oc6HdKMERdLw5Exjc9x8pHvtB1DNz9DBjYQUibwmu3LfozYz9DrUC89l5YBTopIHbYQfm4ieSbTY32sLQSebKaFS-qNx1CBP7U3kbPPP2TlXNpqOE1qE3NZRqicTqkcuZtIqGgyj0hXTbUGrHZpKnU3fIvdhdb0cxD92y_RLh2xwkyXHs7le7EF6qSiH0HnQtaakGElR0zAPJwgdjkJZhdzc7UVOpyXMbdk0opk7Ws_wi5ZAIr7LFEOor5C-5UA6f-cJX4hVOiWhkp9KCiaDqyW43u82eDOnfLBLUAChS1ImeDoTnpAfUz4nBX1c3XWLPA7EsbGiNQ0Nj2yB-j31kKhrdEy4Spqrj4GLXOmgcYuq36HG0KhQbAKvlV2UPokK_XgMH7vkCwYWkL4OIcUGq9NR_f49RtpEHzWIr-wtV14X4Et9IJt4_alY1IjOaqgSrUpqyRvOBzJbAEkXvYGbgzZcC4m8Q_Vg/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHOW4CDH2WQJMOGFAOVPDVTTJU56NANCNFSM43HWM2NA>.

This message (including any attachments) contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and any disclosure, copying, or distribution of this message, or the taking of any action based on it, by you is strictly prohibited.

Deloitte refers to a Deloitte member firm, one of its related entities, or Deloitte Touche Tohmatsu Limited ("DTTL"). Each Deloitte member firm is a separate legal entity and a member of DTTL. DTTL does not provide services to clients. Please see www.deloitte.com/about to learn more.

v.E.1

**Comment by jmprieur** [comment]
Which new issue, @Deloyuri : this is the same (just transferred from one repo to another)

**Comment by jennyf19** [comment]
@Deloyuri have you considered moving to MSAL.NET?

**Comment by Deloyuri** [comment]
Absolutely – we are a huge organization with many apps. Most, have been transitioned.  We were under impression that we have another year to go for the remaining handful.

Best,
Yuri Livshitz

--
Please consider the environment before printing.


From: jennyf19 ***@***.***>
Reply-To: AzureAD/azure-activedirectory-library-for-dotnet ***@***.***>
Date: Tuesday, April 20, 2021 at 10:21 AM
To: AzureAD/azure-activedirectory-library-for-dotnet ***@***.***>
Cc: "Livshitz, Yuri" ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [AzureAD/azure-activedirectory-library-for-dotnet] [Bug] Auth Redirect failure in ADAL on iOS (#1726)


@Deloyuri<https://secure-web.cisco.com/1233B7Gmixa7xnzojSoR3mmaEm2PTmXlu49g-JQGmcj923PofpB_WB3so5fe_EMNijSQnuK4qZlLOW9mUEmTooYM8onJ9dAGQ3rPUnoo8wuayzYaKxqpKGUdi5l9lmwA1YVa4O_9P1Dt3VdYj2gSMqkiAktS5sE4F1dGLPJwlHzUdNNINW-doQXIR6D2mo5ARjulXdjCiZFMbhp-axzbJS6d7I6NOjB9liAdgeLW3RF7FojQq3DUClp_Uua6W5u-9u0maqKKP7LeNwUDhNk9b1kpH3iquii9Psq09WS-cJegV1m1cERcQBxyrdqpEaVL6lhptJ8ZIfWNF5EZt-7d5_Xhspr3ZH4aTeJsQRi4Vz5-vApJsWfCq5P-IuiAUsOIb_60AlQK5A9q55n_f6bG1kpPNFw0-iPhfAvxHI4h_PKdHR230lFoEOGyxqZyQsXtCCnUE5yHHdi4Ems3GJoSvxUjd6DJ28zWDDJvDoAK46Eo_0PFIjMSAwTLfhmdqgARkQDT6e74n_q5wUqqBLYbSlQ/https%3A%2F%2Fgithub.com%2FDeloyuri> have you considered moving to MSAL.NET?

**Comment by jennyf19** [comment]
@Deloyuri i understand. 

Which xamarin version are you on?

You can pass in an HttpClientFactory for iOS...can you try passing in one that uses the managed handler, which doesn't care about the app going into the background and see if that one works? You would do something like this for the iOS factory: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/bc9b6cc15ad271c1f4f9f1ccdbad6360b826080f/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Core/Http/HttpClientFactory.cs#L59

Providing an HttpClient · https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Providing-an-HttpClient

**Comment by Deloyuri** [comment]
I’m not sure we’ll be able to sub custom HTTPClient in that version of ADAL.  Either way, if we’re going to try to fix the code, it probably makes sense to move to MSAL.  The concern is that several apps are currently affected, so we’re really looking for a solution that affects all of the existing apps and hopefully a root cause.

Best,
Yuri Livshitz
Deloitte Application Studios
615-495-5187 (cell)
--
Please consider the environment before printing.


From: jennyf19 ***@***.***>
Reply-To: AzureAD/azure-activedirectory-library-for-dotnet ***@***.***>
Date: Tuesday, April 20, 2021 at 12:14 PM
To: AzureAD/azure-activedirectory-library-for-dotnet ***@***.***>
Cc: "Livshitz, Yuri" ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [AzureAD/azure-activedirectory-library-for-dotnet] [Bug] Auth Redirect failure in ADAL on iOS (#1726)


@Deloyuri<https://secure-web.cisco.com/1zNZPnIiBO_DZmVCze5lvEUkcn_wZNuGtITdn63lOu5OeVd6X3kIG07yuPHSffWR30R4lirIEcUSJpgA3qjAL3NYOxZKnrGIWNn-TZ682u-kGETsotNM_rxhInXyyGBQnTFpAB-8NFwR174WlNLfoLV3vxkfyPLUizEHeM8tMj9CxNllRnn_yQWQEGaTusHQCVJD3s2ErpcCk3waClyDCwyvF0W43pmYlamZFPWK0allzmoJsAb_F1eACLnYRQWy3A-QXvePjUOMzS0PMXL8BFq81QLcDxN1OzgMSTS_nY8WE2hBBuDq8V2kqMTIRhBYMZm-k3LwgLbxm6sYA5D1d3B1B7eu2Z6qqJUStVHyLQUPyyGtjzYTWsgoz68bm3I5XuElNYrZuDLGUdywAu4vuG0-tmrR0VTX9DvWN8sSpjBtimPQix7t3rb_pJjsbh3Jp644vLR8IK_ZADItU0kwPoYUUxaWn69iV3AmNHRJpFOT6-CI_iRBkpRs8SjqpoUixNFiDEYcCfkjNJ4ZE5nUsHw/https%3A%2F%2Fgithub.com%2FDeloyuri> i understand.

Which xamarin version are you on?

You can pass in an HttpClientFactory for iOS...can you try passing in one that uses the managed handler, which doesn't care about the app going into the background and see if that one works? You would do something like this for the iOS factory: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/bc9b6cc15ad271c1f4f9f1ccdbad6360b826080f/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Core/Http/HttpClientFactory.cs#L59<https://secure-web.cisco.com/138nF4JVjAZf4XfO1cfHMGzfNDIntkQfVrT0LP8KKwhXacWHqMxguQzkdWL3LOcUVF0xqEOtNYauGaUTQ5e6nCOUbafNriJ2-iNPPk7pyam2LjcoSWSvKzidT1cR3jmNToJZBpoC9A566SvbSEftRoCPgdWi8Eb-Npjc1ayQf2jbOq_MeZxuDz6gLQNgM5uBlyHAdL8WUpPpNCwV6C8KYhQ-dYoIZg_Ry-BU4eosCi8_SBTYbdej72I6j3_gBP07Yw9q5iL2QEAf-6kB75oDVFvs6veTxOAmtHL_Qx9mjIHZMqG20-OhQMCnqzv4nG3nsUTBsP5hinwnzuw-CHV16xyR1kAbyT5Fan-N875QIBBmPTvmY94jBW27DO5SRYFCY6PYd1l2xrLuupIADLl8FUCshO_rJqh_QgPNv0e1K2EfuI6up5eJbVIk70U1uNcRKco6U_Av4G6rkwBkp8LObcAo8zJ17eLWZJmEtCrVEceB-Lp5TaZSmKZ17_t1o1vVbmri5plk_wIQBmHL7FY4kwg/https%3A%2F%2Fgithub.com%2FAzureAD%2Fazure-activedirectory-library-for-dotnet%2Fblob%2Fbc9b6cc15ad271c1f4f9f1ccdbad6360b826080f%2Fsrc%2FMicrosoft.IdentityModel.Clients.ActiveDirectory%2FCore%2FHttp%2FHttpClientFactory.cs%23L59>

Providing an HttpClient · https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Providing-an-HttpClient<https://secure-web.cisco.com/1MI5uBjPzMUdqQNR7CIAmSxRLKh5r0soeR4Lo093j-ZSz69A2JNRxZ9CCWyaZPgMO5U4UhnFHTOdLxLp5LCXn_A8pwiRYDgaZ8RX0GKUASA46elteJkJMc68s79ySds1ZmO1BD3dpemPWBJntiuPq8iFH-BdQzQCyASGwrDGh0iSw_51XccQc0iznltM3PB_VP1MlArIgPgbZbXAF_aj0x6ze1-nt9Gz0q_lO7lEP-YX27fYHnaAEkasUogGS9kGT1BS75pvCnrPIshTjPmpPmjH3kkg3dVlihFztgVgme15DUt8e570gjFnEhyAXpw-nKTPS9sz5RaI_B1JxwkowJg9Rvhp6Q2KrpA1Nq8IPdI1FYie06lQuiPz9YWee1PnX04hVwi9P10xiwfYyZYSOQlCwPVqdP53-phPj8YVeko0y3AVaEmCK6GB-KJgdoZFgJsf3le9J-QgagCgSZh2_tKbbGvR5b8lQTz7Iki40GO33hbYKD4WIJ9rzuZGLdRhWg1imKvOboKMsEfQnGP7YiQ/https%3A%2F%2Fgithub.com%2FAzureAD%2Fazure-activedirectory-library-for-dotnet%2Fwiki%2FProviding-an-HttpClient>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1vbPOUeqEYuRKwl1Ly1vcbKbE7LqCspUpqO5jbb4ofYJdHRLBZ45LUc3leIn8iAs-Y6L3-PSxk16VYFt58JefsWEDFtk0wrZieEIDkcD76N_7vIZco2ofSwI573GoUKY71EGzcXtMKO4Ggs_VtdpoM8QAEsCNWz1QIHzDJ5RMaO2ugUEp_YobmJ1GGOx4gLEVlB9_owevAK_lh2456oBzY5lXAYtcT9DLWUE1vz3SznFnHF7jeZxHBGZz4oxQViTSUHL0o7eF5AEEsgUlvdSbGv3f2MYDorqumuy7bsJmbUkGSYy_sklnLlf7nSby4V6YwOyega2nLTNGolMqfsdw5lXUNqbsy-QNa4bJ6H_FoyH2JvSoymAGBdL7_YtFiNWreiLHF8sQMT7iqkY0bovMkpUBec09bsDRHu0nLsoadc6BwxxYvBxbMPoC_aWZf_xxwyc2-4GnC8spDD9HbFADc4xjza5ck77a0sH6pRsSWgJIFOQJI68ZqQnhvIEyPDUufp0hyOX8VhZLvCsHM6iltw/https%3A%2F%2Fgithub.com%2FAzureAD%2Fazure-activedirectory-library-for-dotnet%2Fissues%2F1726%23issuecomment-823457293>, or unsubscribe<https://secure-web.cisco.com/1X_lb50v-uFLvR-ZaTUriCFwMxqxrCbcL-UdYT_4zENKhNBgaf1hrrwPh6MgUgjZ2cQYLO6Ers0XmBEiYJtuvt3s5mz8s4NVQSFCJOYp02hhZ4f39P4KZiWDiHbMpTqMzxQ6eovJT2QzoKg01Cfr58b7dI8NY80rnHPOPrLPJ3aegIJkWplHT9SjP336XzmYVcCMU31dektra9YW77UcJS5Kj3N8S1763sn2gYY9wLlMoMLJr4duDpmiEXNdo0qDJPji1svIQPHOhsXDy40isMfjDq3Cx1HrBMREbS5nuWGoGSj-HIuBbtE3YV8H22ja6rM-LpugVx6Pe-_8KS1eZ0cxMtztlCScC15RgzXfa9uH2iQyee9OBYalaehd-PxKkmbyFN76XbvqmtojbAjt5w0N1tq63wAGYye4zO1B8D07l3nRAZRfUM66D4e-XgsY2An-ckVVsj9buksW-vj0eZn0G6776yY0bJtRfYJlbdL9o4bpZE_qUFcGhxsEx2G0om-P-TfJ6YDincksTegsWeg/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHOW4CA735JZK3NKJEWTNBTTJWY6ZANCNFSM43HWM2NA>.

This message (including any attachments) contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and any disclosure, copying, or distribution of this message, or the taking of any action based on it, by you is strictly prohibited.

Deloitte refers to a Deloitte member firm, one of its related entities, or Deloitte Touche Tohmatsu Limited ("DTTL"). Each Deloitte member firm is a separate legal entity and a member of DTTL. DTTL does not provide services to clients. Please see www.deloitte.com/about to learn more.

v.E.1

**Comment by jennyf19** [comment]
@Deloyuri i would suggest passing in the HttpClient, as the solution. It shouldn't be a huge change in your code, do you have a test environment where you can try it?

and which version of Xamarin is being used?

**Comment by bgavrilMS** [comment]
@jennyf19  - note that injecting an HttpClient was implemented sometime in ADAL 5.x, pretty sure it isn't possible in ADAL 3.x. Why would a custom HttpClient fix this issue? Are you thinking about the recent Xamarin SDK bug?

**Comment by jennyf19** [comment]
@bgavrilMS i would like to see if the managed httpclient is not working as well, either netcore/mono has the issue.

@Deloyuri, as @bgavrilMS mentioned, you would need to move to latest ADAL version first.

> recent Xamarin SDK bug

it wasn't a bug in Xamarin, it was a bug in the customer code.

**Comment by jennyf19** [comment]
also @Deloyuri I gave our css engineer the link to the MSAL.NET repro, and not ADAL.NET, sorry about that, but @jmprieur got it sorted out

**Comment by Deloyuri** [comment]
you guys lost me a bit. As @bgavrilMS mentioned, the version of ADAL we have doesn't allow for swapping out HttpClient.  Has anyone on your team been able to reproduce this?  I'd suggest trying with the same version of ADAL as above, and on an iOS 14.5 beta device.

**Comment by jennyf19** [comment]
@Deloyuri we can try to repro on the latest version, but not on 3.x. our suggestion would be to use the HttpClient, as I mentioned above. Or move to MSAL.NET

**Comment by Deloyuri** [comment]
Please let me know what you see when you try to reproduce with ADAL and iOS 14.5 beta.

**Comment by bgavrilMS** [comment]
@Deloyuri - just to set expectations, we do support ADAL 5.x but not ADAL 3.x. Each major version of the library has 1 year support from the team. We are not setup to repro ADAL 3.x bugs, we always ask developers to upgrade (ideally to MSAL, as making changes in ADAL is unlikely).

**Comment by Deloyuri** [comment]
Ok, got it.  Are you able to reproduce with ADAL 5.x?

**Comment by jennyf19** [comment]
@Deloyuri yes, @trwalke is on point to try and repro w/5.x and iOS 14.5

**Comment by jennyf19** [comment]
@Deloyuri can you try updating to Xamarin iOS 14.14 and see if the issue repros there? There is an issue in mono, so you can either update the Xamarin iOS version to 14.14 or try passing in your own HttpClient, or updating to MSAL. Probably the move to 14.14 is least invasive to your app.
