### ISSUE TITLE
ADAL webview with secure certificate on App UWP

### ISSUE THREAD

**Issue by vinhdp195** [AzureAD/azure-activedirectory-library-for-dotnet#1727]
Getting tokens through ADAL, I am having the following problem:
Can't login at site organization (requires certificate)
Detail error:
1 / I have a UWP app
2 / At the app, open the authentication window (Webview)
3 / Enter user organization
4 / Redirect to the organization's authentication page (example: adfs.xyzcompany.co.jp)
5 / Input userid and password
=> Error: Select the certificate to use for authentication. If you want to cancel the operation, close the browser and try again.

In Browser Chrome, IE does not have the above error
I added a certificate to Chrome, IE. I still login successfully using the browser

=> I think in step number (2), Webview has no right to find the added certificate in IE browser
Is there any information about the error above or not?
I also tried with MSAL but still got the same error

ADAL version is in use: 5.2.4
Code is at my UWP app:

```
// Get access token
Uri redirectURI = new Uri(Constants.REDIRECT_URL);
AuthenticationContext authenticationContext = new AuthenticationContext(endpointUrl, true);
PlatformParameters platformParameters = new PlatformParameters(promptBehavior, false);
AuthenticationResult authenticationResult = await authenticationContext.AcquireTokenAsync(Constants.RESOURCE_ID, applicationId, redirectURI, platformParameters);
```

**Comment by jmprieur** [comment]
@vinhdp195 : ADAL.NET is on the deprecation path and does not support device authentication.
you'd definitively want to move to MSAL.NET which supports WAM (use the `.WithBroker(true)` expression);
For details see  https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam
