### ISSUE TITLE
When using clientcredential method for getting access token, token does not refresh after expiration time is passed.

### ISSUE THREAD

**Issue by Prashanth85** [AzureAD/azure-activedirectory-library-for-dotnet#173]
The access token should refresh before the expirationtime is passed. However it does not, 

 string loginAuthority = String.Format(loginAuthorityFormat, requestInfo.TenetID);
  ClientCredential clientCredential = new ClientCredential(requestInfo.ClientID, requestInfo.AppKey);
 AuthenticationContext authenticationContext = new AuthenticationContext(loginAuthority, false);
 AuthenticationResult authenticationResult = authenticationContext.AcquireToken(requestInfo.ResourceID, clientCredential);

the authentication result returned by,
 AuthenticationResult authenticationResult = authenticationContext.AcquireToken(requestInfo.ResourceID, clientCredential);
Contains the same access token 1 minute before the expiry datetime and remains the same even after the expiry datetime is passed. Please let me know how I can provide the additional logging requested.

**Comment by afshins** [comment]
I also could not repro this. Please either send me a repro or logs. Fiddler trace would help too. You can learn how to collect ADAL logs from here: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/README.md#logs
