### ISSUE TITLE
GetAuthorizationRequestUrlAsync breaking change adds response_type=form_post

### ISSUE THREAD

**Issue by mtucker2112** [AzureAD/azure-activedirectory-library-for-dotnet#1735]
Somewhere between 3.18.0 and 4.5.1 a change was made to GetAuthorizationRequestUrlAsync() that automatically adds a response_mode=form_post to the request.  This seems to cause the response sent to the redirectUri to use a POST (with the code in the body) instead of a GET (with code as a URL param). 

Perhaps this is known\documented somewhere already, but thought I should log this to help others that wonder why there flows stop working.

**Comment by bgavrilMS** [comment]
Please use MSAL, ADAL is on a deprecation path.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
