### ISSUE TITLE
"Read beyond end of stream" exception when deserializing cache

### ISSUE THREAD

**Issue by afshins** [AzureAD/azure-activedirectory-library-for-dotnet#176]
Customer reports:

We have seen a couple of instances where after we serialize our adal token cache and read the contents back from disk there is an exception thrown in the deserialize code indicating the binary reader was “Unable to read beyond the end of the stream”. 

The stack we see is 

TokenCache.Deserialize
BinaryReader.ReadString
BinaryReader.Read7BitEncodedInt
BinaryReader.ReadByte

Here is the version of the token cache we are using
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/v2.11.10918.1222/src/ADAL.Common/TokenCache.cs

Looking at the code is could be coming from reading the key
string keyString = reader.ReadString();
or later when reading the authentication result 
        AuthenticationResult result = AuthenticationResult.Deserialize(reader.ReadString());
                
Have you had any reports of this kind of exception from any other sources?

We do not have a repro for this issue, it is something that seems to happen every once and a while.

**Comment by afshins** [comment]
I tried to repro this, but failed.

**Comment by RandalliLama** [comment]
Will reopen if we get any more reported issues.
