### ISSUE TITLE
TokenCache returning and mutating live entry

### ISSUE THREAD

**Issue by crmann1** [AzureAD/azure-activedirectory-library-for-dotnet#182]
In TokenCache.cs LoadFromCache queries the ADAL cache for any items that match the requested authority/resource/client/userid.  

It will return a result in two cases. 
1) If there is an exact match of all the fields.  
2)If the fields other than resource match and one of the tokens is an MRRT. 

The problem comes with case 2.  If an MRRT is returned the code immediately checks to see if the cached item's resource matches the requested resource.  Since they do not since this is case #2 the access token on the live cache items is nulled out.   We have just mutated the cached item that matched a resource other than the one we are requesting an access token for. 

This causes additional server calls since we are refreshing access tokens when we do not need to. 

Instead a copy of the authentication result should be returned from the LoadFromCache instead with the access token cleared.

**Comment by afshins** [comment]
@crmann1: Fixed.
