### ISSUE TITLE
IsMRRT flag not updated correctly when server does not pass refresh token when refreshing an access token

### ISSUE THREAD

**Issue by crmann1** [AzureAD/azure-activedirectory-library-for-dotnet#183]
If the server does not respond with a refresh token and we used a refresh token to get the access token the IsMRRT flag is not correctly updated. 

azure-activedirectory-library-for-dotnet-2.11.10918.1222\src\ADAL.Common\OAuth2Response.cs 
                ParseTokenResponse
When a token is requested from the server using a refresh token the response that comes back 
does not include a refresh token itself. This means that the Authentication result created has a resource but no refresh token at the point of creation. Therefore its IsMultipleResourceRefreshToken flag is false. This is then returned into SendTokenRequestByRefreshTokenAsync

Later in azure-activedirectory-library-for-dotnet-2.11.10918.1222\src\adal.common\acquiretokenhandlerbase.cs
                SendTokenRequestByRefreshTokenAsync

After we have finished parsing the response and getting the authentication result from parsetokenresponse there is a check to see if there is a refresh token on the result. Since this result was requested through a refresh token 
the value will be null. We take the refresh token we sent with the response and set that on the refresh token property. 

The problem is here

           if (result.RefreshToken == null)
           {
                result.RefreshToken = refreshToken;
           }

Note that even though we set the refresh token we do not go back and set the IsMultipleResourceRefreshToken flag to true.

The code should be 

          if (result.RefreshToken == null)
          {
               result.RefreshToken = refreshToken;
               result.IsMultipleResourceRefreshToken = (!string.IsNullOrWhiteSpace(result.RefreshToken) && !string.IsNullOrWhiteSpace(result.Resource));
          }

**Comment by afshins** [comment]
@crmann1: Fixed.
