### ISSUE TITLE
Better exception when using AcquireTokenSilent with Common Authority

### ISSUE THREAD

**Issue by ricardopolo** [AzureAD/azure-activedirectory-library-for-dotnet#185]
I just found that you cannot use AcquireTokenSilent() with the Common Authority.

It tooks me 2 days for found it http://stackoverflow.com/a/29768742/909974
So would be great an exception saying that not use the common authority instead a silent fail.

**Comment by RandalliLama** [comment]
Agree.

**Comment by jmprieur** [comment]
@ricardopolo, please reopen if you disagree.
