### ISSUE TITLE
Suggest to have better actionable message when error "Failed to acquire token silently. Call method AcquireToken" happens

### ISSUE THREAD

**Issue by xiaowodp** [AzureAD/azure-activedirectory-library-for-dotnet#188]
I got "Failed to acquire token silently" when call method AcquireTokenSilentAsync. At end it was because there was no matching item in the token cache because the resource I used in AcquireTokenSilentAsync() was different  from what being used when the cache was set in AcquireTokenByAuthorizationCode(). It would be nice if the message can indicate some root causes to help people resolve the issue.”

**Comment by kpanwar** [comment]
added inner exception for over the wire exceptions

**Comment by xiaowodp** [comment]
Thank you very much !

Xiao


On Feb 26, 2016, at 7:19 PM, Kanishk Panwar <notifications@github.com<mailto:notifications@github.com>> wrote:


added inner exception for over the wire exceptions
