### ISSUE TITLE
Check for IE session count and increment before opening new browser to maintain session cookies

### ISSUE THREAD

**Issue by afshins** [AzureAD/azure-activedirectory-library-for-dotnet#190]
ADAL is incrementing this in a static constructor, and only if the count is 0. If when the static constructor is run (i.e. the dialog is shown for the first time, or the library is loaded for the first time) the count isn’t 0 – because the user has an IE window open, no increment will happen. Now, if the user closes that IE window while the app hosting ADAL is still loaded. In this case, the count may still be 0 – and the static constructor will not run again.

**Comment by afshins** [comment]
Fixed in v3. Needs to be fixed in v2 as well.

**Comment by RandalliLama** [comment]
@kpanwar Please take a look at this.  I think we saw another incident of this in the recent history.
