### ISSUE TITLE
Windows Phone gives "User Canceled Sign In" error when WP emulator can't connect to internet.

### ISSUE THREAD

**Issue by dstrockis** [AzureAD/azure-activedirectory-library-for-dotnet#192]
Minor bug, and I'm not sure if it repros on an actual device or not.  But when developing for WP in Visual Studio, if the emulator does not have internet access, ADAL returns "User Canceled Sign In" before showing the AAD sign in page.  It was pretty misleading for me :)

**Comment by dstrockis** [comment]
Using version 2.14.201151115.  Specifically running this sample: https://github.com/AzureADQuickStarts/NativeClient-WindowsPhone.

Using Windows Phone 8.1 Emulator launched from Visual Studio.  Fiddler proxy on the machine prevented the emulator from reaching any websites via browser or WAB dialog.

**Comment by RandalliLama** [comment]
@dstrockis Given the lack of other complaints on this issue I don't think that it is a high enough priority look in to.  Please reopen if you disagree.
