### ISSUE TITLE
Remove the "remember this device" checkbox for 2 factor authentication in Visual Studio

### ISSUE THREAD

**Issue by jkwon2013** [AzureAD/azure-activedirectory-library-for-dotnet#196]
![2fa sign in page](https://cloud.githubusercontent.com/assets/11651452/7693668/c4b9229c-fd89-11e4-956c-0c71c333ae97.png)

When showing the sign in dialog for users with 2 factor authentication in Visual Studio, the checkbox highlighted above in the image should not appear, as clicking on it affects nothing in Visual Studio. 
A better fix would be to remember that the device is a safe device when the user checks the checkbox. But if that is not possible, we should at least not show the checkbox so that customers don't think taking an action to check it does anything in VS. 

We get steady feedback from customers expressing confusion as to why the checkbox doesn't work.

**Comment by RandalliLama** [comment]
@jkwon2013 This is not related to ADAL as MSA accounts are only supported as guest accounts in AAD tenants.  Let me know if that is actually your scenario.
