### ISSUE TITLE
On high-dpi screen the ADAL MS account login dialog for azure is not properly scaled

### ISSUE THREAD

**Issue by jkwon2013** [AzureAD/azure-activedirectory-library-for-dotnet#199]
This was a bug reported by a VS customer: 
1. Install Visual Studio on high-dpi screen laptop. In My case it's Dell XPS15 with 3200x1800 
2. Use recommended 200% scaling 
3. Try to connect to MS Azure, you will see a login dialog with scrollbars 

![wrongly scaled msa sign in dialog](https://cloud.githubusercontent.com/assets/11651452/7873349/189b60cc-0556-11e5-9a02-fd08229a9d36.JPG)

**Comment by RandalliLama** [comment]
@kpanwar Can you attempt a repro of this?

**Comment by kpanwar** [comment]
This issue was related to MSA not rendering UI that was high DPI. It has been for a while.
