### ISSUE TITLE
ADAL sign in dialog content overlapping

### ISSUE THREAD

**Issue by jkwon2013** [AzureAD/azure-activedirectory-library-for-dotnet#200]
This was reported by a VS customer: 
[Repro Steps]
Create an Asp.Net MVC project
right lick on solution explorer and choose Add Application Insights
click enter with your azure account
put your email account

![capture](https://cloud.githubusercontent.com/assets/11651452/7874064/51bface2-055f-11e5-96ba-0d65c1e6d756.JPG)

**Comment by RandalliLama** [comment]
@jkwon2013 Is this still an issue.  This would be a rendering problem on the server side.  My guess is that this has been fixed by now.

**Comment by kpanwar** [comment]
@jkwon2013: I am going to close this issue. If you still see it as a problem then please feel free to reopen it.
