### ISSUE TITLE
Authenticator type initialization is failing on some WinRt devices

### ISSUE THREAD

**Issue by omercs** [AzureAD/azure-activedirectory-library-for-dotnet#202]
It failed to initialize AuthenticatorTemplateList  for some WinRT devices.

```cs
internal class Authenticator
    {
        private const string TenantlessTenantName = "Common";

        private static readonly AuthenticatorTemplateList AuthenticatorTemplateList = new AuthenticatorTemplateList();
    
```

AuthenticatorTemplateList's ctor reads the environment variable to create the list. This could be causing the issue for some devices. App can't recover from this exception.

**Comment by kpanwar** [comment]
This is because they are trying to use .NET 4.0  and it is not supported
