### ISSUE TITLE
"Remember me" check box is not displayed for onmicrosoft.com accounts

### ISSUE THREAD

**Issue by relusion** [AzureAD/azure-activedirectory-library-for-dotnet#216]
If I try to login with "someusername@mydomainname.onmicrosoft.com the "remember me" check box is not displayed. For instance for live accounts it does show up and I can save my credentials.

![ok](https://cloud.githubusercontent.com/assets/13152136/8479125/f2eb07e2-20d5-11e5-9219-8ad520edf8c7.png)
![wrong](https://cloud.githubusercontent.com/assets/13152136/8479126/f2f00652-20d5-11e5-8b36-262fec3879b3.png)

**Comment by kpanwar** [comment]
Microsoft Accounts page has the checkbox, but AAD does not support it. This is by design.
