### ISSUE TITLE
Adal with UWP style applications

### ISSUE THREAD

**Issue by Jeremiad** [AzureAD/azure-activedirectory-library-for-dotnet#217]
Hi,

Adding question also to here since haven't received answer in stackoverflow http://stackoverflow.com/questions/31137374/active-directory-authentication-library-with-windows-universal-app

**Comment by Jeremiad** [comment]
Any information would be highly appreciated.

**Comment by merill** [comment]
Seriously guys. Windows 10 is launching in 5 days and you don't have support for UWP apps.
It's hilarious that Microsoft is providing sample applications for web authentication with Facebook, Twitter, Flickr and Google https://github.com/Microsoft/Windows-universal-samples/tree/master/webauthentication

**Comment by Jeremiad** [comment]
Thank merill
