### ISSUE TITLE
Implement in Unity3d

### ISSUE THREAD

**Issue by Zyngie** [AzureAD/azure-activedirectory-library-for-dotnet#218]
hi, I want to ask is it possible to implement this library to Unity3d project to build for android/ios application?

**Comment by RandalliLama** [comment]
@Zyngie It's not something that is on a  our current roadmap.

**Comment by kpanwar** [comment]
Adal v3 supports Xaamrin iOS/android.

**Comment by etiennemargraff** [comment]
@kpanwar : I think you misread the title. It mentions Unity3D et you talk about Xamarin. 
Can you re-open it?

Thank you a lot.

**Comment by jennyf19** [comment]
@jmprieur can comment on our roadmap and plans for Unity3D support.
