### ISSUE TITLE
In VS, MSA sign in dialog's "Sign up now" link just closes the sign in dialog and doesn't work

### ISSUE THREAD

**Issue by jkwon2013** [AzureAD/azure-activedirectory-library-for-dotnet#219]
Repro steps: 
1. Click "Add an account" link in VS's File > Account Settings dialog
2. enter in a MSA
3. When the MSA sign in dialog pops up, click on the "Sign up now" link

Expected: 
Take the user through a MSA sign up flow

Actual: 
The sign in dialog closes and nothing happens

I've attached a fiddler trace here: http://1drv.ms/1fJKMeZ

**Comment by RandalliLama** [comment]
@jkwon2013 This library does not support MSAs unless they are guest accounts in an AAD tenant.  That doesn't sound like the scenario you are describing.
