### ISSUE TITLE
AcquireTokenAsync fails in a UWP app

### ISSUE THREAD

**Issue by arturl** [AzureAD/azure-activedirectory-library-for-dotnet#222]
Repro:

```
TokenCache TC = new TokenCache();
authContext = new AuthenticationContext(authority, true, TC);
var authresult = await authContext.AcquireTokenAsync(resourceUri, clientID, new Uri(redirectUri));
token = authresult.AccessToken;
```

Result:

ErrorDescription = "authentication_ui_failed: The browser based authentication dialog failed to complete. The system cannot locate the resource specified. (Exception from HRESULT: 0x800C0005)"

**Comment by arturl** [comment]
More info: the auth dialog comes up and lets me enter my user name (...@microsoft.com), then shows "Can't connect to service"

**Comment by kpanwar** [comment]
It looks like your machine might have privacy restrictions. Try checking all settings->privacy->account info and ensure it is turned on.

**Comment by arturl** [comment]
Yes, it is turned on.

**Comment by kpanwar** [comment]
@arturl - Is this still an issue with the windows GA?

**Comment by afourney** [comment]
I am also experiencing this problem when using version 2.28.1 (via the Cordova Plugin https://github.com/AzureAD/azure-activedirectory-library-for-cordova).

I've filed a similar bug with them: [https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/105](https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/105)

But I think it's an issue with *this* native library. Here are more details:

When users (under @microsoft.com) attempt to login from a laptop connected to the corporate network, they receive the error:

"We can't connect to service right now. Check your internet connection or try this again later"

This occurs after they type their email address on the first screen, and are redirected.

The problem occurs only when users are connected to the corporate WiFi, or to public WiFi +Corporate VPN. It works fine with wired connections to the corporate network.

**Comment by afourney** [comment]
I may have resolved the issued by adding:

&lt;preference name="adal-use-corporate-network" value="true" /&gt;

To the application manifest.

**Comment by afourney** [comment]
Ok, more progress.
When working in visual studio, adding:
&lt;Capability Name="privateNetworkClientServer" /&gt;
to the manifest file fixes the problem.

However, this does not work when side loading apps. When side loading, one has to create an LoopbackExemption exemption for AuthHost.exe

E.g., CheckNetIsolation LoopbackExempt -a -n="microsoft.windows.authhost_8wekyb3d8bbwe"

This appears to be the same problem as is documented here:

[Understanding and debugging the web authentication broker workflow (XAML)](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/Hh750287.aspx)

(Please re-open this issue)

**Comment by CharlesHe21** [comment]
Hi @afourney , I have the same issue, have you solved it or do you have any workaround?

Thanks

**Comment by kpanwar** [comment]
This issue is not because of the library, so it does not warrant to be re-opened. @CharlesHe21 - you also need to enable sharedUserCertificates capability to make it work for microsoft accounts.

**Comment by CharlesHe21** [comment]
@kpanwar , got it, I'll have a try, thank you!
