### ISSUE TITLE
WER crash in ADAL hosted browser 

### ISSUE THREAD

**Issue by jkwon2013** [AzureAD/azure-activedirectory-library-for-dotnet#234]
Most of Dev14 RTM hits are due to this assembly - 

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll

The type of interest is -

Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.CustomWebBrowser

The callstack is 

KERNELBASE!RaiseException+0x48
clr!RaiseTheExceptionInternalOnly+0x27c
clr!UnwindAndContinueRethrowHelperAfterCatch+0x90
clr!GetCOMIPFromRCWHelper+0x22f
clr!StubHelpers::GetCOMIPFromRCW+0x1e3
System_Windows_Forms_ni!DomainNeutralILStubClass.IL_STUB_CLRtoCOM(IntPtr ByRef)+0x3f
System_Windows_Forms_ni!System.Windows.Forms.WebBrowserBase.WndProc(System.Windows.Forms.Message ByRef)+0x8e81f8
System_Windows_Forms_ni!System.Windows.Forms.WebBrowser.WndProc(System.Windows.Forms.Message ByRef)+0x1e
System_Windows_Forms_ni!System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)+0x13
System_Windows_Forms_ni!System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)+0x35
System_Windows_Forms_ni!System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)+0x5e
CLRStub[StubLinkStub]@95c7a7be11ad2d52
user32!_InternalCallWinProc+0x2b
user32!InternalCallWinProc+0x1b
user32!UserCallWinProcCheckWow+0x18e
user32!DispatchClientMessage+0xdc
user32!__fnDWORD+0x49
ntdll!KiUserCallbackDispatcher+0x36
System_Windows_Forms_ni!DomainNeutralILStubClass.IL_STUB_PInvoke(System.Runtime.InteropServices.HandleRef)+0x37
System_Windows_Forms_ni!System.Windows.Forms.UnsafeNativeMethods.DestroyWindow(System.Runtime.InteropServices.HandleRef)+0x12

Cabs -

107387163827

107387163502

DDElementary link: https://ddwatson.cloudapp.net/?q=f%3A579505c8-6325-e25d-a2d1-413f9ce729ad%20e%3ACrash32%20q%3AAllSources&f=579505c8-6325-e25d-a2d1-413f9ce729ad&e=Crash32

**Comment by kpanwar** [comment]
@jkwon2013 - what ADAL version are you using?

**Comment by RandalliLama** [comment]
@jkwon2013 Reopen this when you have more info.
