### ISSUE TITLE
China Azure exception

### ISSUE THREAD

**Issue by VaanPan** [AzureAD/azure-activedirectory-library-for-dotnet#238]
in "AuthenticatorTemplateList.cs", at Line 54

```
                // We only check with the first trusted authority (login.windows.net) for instance discovery
                await this.First().VerifyAnotherHostByInstanceDiscoveryAsync(host, tenant, callState);
```

this will force just use login.windows.net host. 

But if customer is using China Azure, and config web.config to China Azure URL, AuthenticationContext.AcquireTokenByAuthorizationCode will throw a 400 HTTP error (bad request), and cannot get any token.

You can contact me by gapan@microsoft.com, thanks.

![aa](https://cloud.githubusercontent.com/assets/12791293/9269851/c19303b6-429f-11e5-8526-e12e8e7c149f.png)

**Comment by RandalliLama** [comment]
@VaanPan The expected behavior is that login.windows.net is aware of all of the other AAD instances and will correctly verify that they are valid.  

What version of ADAL are you using?  What is the authority that you are passing to ADAL.

**Comment by kpanwar** [comment]
@VaanPan: Is this still an issue?

**Comment by jmprieur** [comment]
Closing: No response from @RandalliLama for more than one year
