### ISSUE TITLE
Exception is thrown when ID returned by server does not match ID in request

### ISSUE THREAD

**Issue by makhdumi** [AzureAD/azure-activedirectory-library-for-dotnet#242]
This totally breaks Visual Studio's Server Explorer (logs in successfully, but thanks to this, cannot proceed past that!) and causes issue with the PowerShell Tools. Why is an exception being thrown on the *client* side when no failures or errors were reported on the server side? 

Azure returns a different ID in several very valid situations, like when a user's Microsoft email address has been changed or uses an alias. It isn't the job of the client to declare this a problem and fail the authentication process - thereby preventing any use of the underlying software.

The server is already authenticated and trusted, so it really doesn't make sense to me that the client should make up its own error. This behaviour is just wrong and completely out of place in a server-client channel.

FYI this wasted several of my hours. Azure support would not help, so I ended up "hacking" Visual Studio's copy of the assemblies to remove this moronic exception:
https://github.com/makhdumi/azure-activedirectory-library-for-dotnet/commit/b9f57cf9da5bc9ad5640fce9502b0aa7d20e750d

**Comment by RandalliLama** [comment]
@makhdumi I'm sorry this is causing you issues.  For an explanation of why we do this, please see this StackOverflow post.  It is directed at iOS, but the same principles apply.

http://stackoverflow.com/questions/26694432/adal-ios-different-user-was-authenticated-expected-useramydomain-com-actual/26727024#26727024

In ADAL.NET V2 you can use an overload of AcquireToken that takes the following enum to get the behavior that your are after:

```cs
    /// <summary>
    /// Indicates the type of <see cref=" UserIdentifier"/>
    /// </summary>
    public enum UserIdentifierType
    {
        /// <summary>
        /// When a <see cref=" UserIdentifier"/> of this type is passed in a token acquisition operation,
        /// the operation is guaranteed to return a token issued for the user with corresponding <see cref=" UserIdentifier.UniqueId"/> or fail.
        /// </summary>
        UniqueId,

        /// <summary>
        /// When a <see cref=" UserIdentifier"/> of this type is passed in a token acquisition operation,
        /// the operation restricts cache matches to the value provided and injects it as a hint in the authentication experience. However the end user could overwrite that value, resulting in a token issued to a different account than the one specified in the <see cref=" UserIdentifier"/> in input.
        /// </summary>
        OptionalDisplayableId,
        
        /// <summary>
        /// When a <see cref=" UserIdentifier"/> of this type is passed in a token acquisition operation,
        /// the operation is guaranteed to return a token issued for the user with corresponding <see cref=" UserIdentifier.DisplayableId"/> (UPN or email) or fail
        /// </summary>
        RequiredDisplayableId
    }
```
