### ISSUE TITLE
Are we able to get more detailed HTTP related trace if we cannot get auth token?

### ISSUE THREAD

**Issue by linweigao** [AzureAD/azure-activedirectory-library-for-dotnet#244]
Are we able to get more detailed HTTP related trace if we cannot get auth token?
And the time used to get the token?

**Comment by kpanwar** [comment]
ADAL returns everything in the payload that was sent by the server. Any error and the details about it displayed in the web view is not controlled by the library.

**Comment by kpanwar** [comment]
We now return the error details if acquireTokenSilent fails.
