### ISSUE TITLE
Windows Phone not receiving user_interaction_required on AcquireTokenSilentAsync

### ISSUE THREAD

**Issue by maxpert** [AzureAD/azure-activedirectory-library-for-dotnet#247]
Hey guys,

 I have been having issues in refreshing token when user changes his password I can see from WinRT test cases we should receive as error user_interaction_required on Windows Phone however I am receiving failed_to_acquire_token_silently (Failed to acquire token silently. Call method AcquireToken). Calling AcquireTokenAndContinue is not feasible in my case because my case user is in middle of app and requirements dictate to show an error message on password expiry instead of directly opening authorization workflow.

 Is it supported on Windows Phone?

Thanks,
Zohaib

**Comment by RandalliLama** [comment]
@maxpert Can you be more specific about which AcquireToken api you are calling?

**Comment by maxpert** [comment]
I am calling AcquireTokenSilentAsync

**Comment by maxpert** [comment]
Basically here is the flow when I realize that the token has expired I try to refresh the token with AcquireTokenByRefreshTokenAsync that returns me authentication_failed as Error, I then make a call to AcquireTokenSilentAsync in effort to get the token by doing a silent acquire. I looked at some of test cases where I can see user_interaction_required coming down telling me I need to redirect the user to login once more. The best example I could find was in WinRT unit tests but that doesn't help me at all on Windows Phone 8.1

 If you need more details I can provide you more details. But so far I can't see a way in source code to get "user_interaction_required" as part of AcquireTokenSilentAsync (which I hope is the right end point for such stuff).

**Comment by kpanwar** [comment]
For your scenario to display a message that the user password has expired will not work because the server does not return any messages related to user state.

**Comment by maxpert** [comment]
What do you suggest I should do? How can I accurately see if password expired without invoking AcquireTokenAndContinue.

**Comment by kpanwar** [comment]
Only way would be to show the UI and if the user password has expired, he/she will be asked to change the password within the webview.

**Comment by maxpert** [comment]
But that will authenticate and give be back the updated access token, plus I also verified with iOS they seem to get the error code. Why is this issue only specific to WP?

**Comment by kpanwar** [comment]
Error codes are not guaranteed to remain the same. It is a best effort on the server side and I would strongly advise you to not take a dependency on them.

**Comment by kpanwar** [comment]
We added the ability to get inner exception details when acquiring a refresh token fails.
