### ISSUE TITLE
DPI Scaling is causing usability issues in Azure PowerShell

### ISSUE THREAD

**Issue by devigned** [AzureAD/azure-activedirectory-library-for-dotnet#251]
> I use 4K display in my laptop and size of text is 250%.(recommended)
When I use "Add-AzureAccount", sign-in dialog is displayed.
The sign-in dialog is too small and it can't change size. It's user-unfriendly.

> https://yabumi.cc/150272f3db0e1eb47202608c.png

> Has anyone ever had this problem?

From: https://github.com/Azure/azure-powershell/issues/1043#issuecomment-145058226

**Comment by kpanwar** [comment]
What version of ADAL are you using?
