### ISSUE TITLE
WebException.Response and response stream not disposed properly in OAuth2Response.ReadErrorResponse()

### ISSUE THREAD

**Issue by ginach** [AzureAD/azure-activedirectory-library-for-dotnet#258]
In OAuth2Response.ReadErrorResponse() the stream of the response object isn't disposed after being retrieved. The calling code of this method doesn't dispose the WebResponse object from the exception or the stream on the response either.

**Comment by kpanwar** [comment]
@abhishek58g - can you confirm if this was fixed in both v2 and v3?

**Comment by kpanwar** [comment]
@abhishek58g - can you confirm?

**Comment by abhishek58g** [comment]
Yes.It is fixed in v2 and v3. The stream object is used inside a using construct which automatically calls Dispose at the end of the block.
MSDN Documentation link :- https://msdn.microsoft.com/en-us/library/system.io.memorystream(v=vs.110).aspx
