### ISSUE TITLE
Convergence-v4: A web app can't get a token without offline_access

### ISSUE THREAD

**Issue by dstrockis** [AzureAD/azure-activedirectory-library-for-dotnet#259]
We should probably enable web apps to get tokens without requiring offline_access.  Not sure how to do it though.  Probably needs a design discussion.

**Comment by kpanwar** [comment]
without offline_access there will be no refresh token. Currently we do not support "not getting refresh token". why is this a requirement now? We should follow up with convergence team and @vibronet

**Comment by dstrockis** [comment]
I'm not 100% sure this is a requirement - but certainly the protocol allows for it.  I'll discuss with V at next opportunity.

Customer question here: https://www.yammer.com/azureadvisors/#/threads/show?threadId=598432866&messageId=599308250

**Comment by kpanwar** [comment]
@dstrockis did you get a closure on this?
