### ISSUE TITLE
AcquireTokenAsync returning a token from the wrong directory

### ISSUE THREAD

**Issue by nigel-sampson** [AzureAD/azure-activedirectory-library-for-dotnet#264]
I'm currently developing an app for a client connecting to Azure AD.

Using the following code:

``` csharp
private const string Authority = "https://login.microsoftonline.com/client-domain.org.nz";

var context = new AuthenticationContext(Authority)
{
    UseCorporateNetwork = true
};

var result = result = await authenticationContext.AcquireTokenAsync(CrmContext.Uri, CrmContext.ClientId, redirectUri, promptBehavior).AsTask(cancellationToken);
```

What we're seeing that when on my development machine we're not seeing a prompt for credentials any more (we used, but something has changed externally to the code) but it will automatically return a token for my work Active Directory `nigel.s@markermetro.com` rather than the client's AD.

This is worrisome for a few reasons.
- I'm not logged into this machine with that account so where is it finding it?
- That account is not in the client's AD.

This code previously used to work so we're trying to isolate what's changed.

Thanks

**Comment by kpanwar** [comment]
@nigel-sampson - I was going through the old issues list and realized that your issue was never addressed. I apologize for the lack of attention to your issue. :( I hope you were able to resolve it.

**Comment by nigel-sampson** [comment]
@kpanwar I've since moved on from the role / project that had that issue, but as of around May 2016 it was an issue.

It appeared that when `UseCorporateNetwork` was set to true then it would pick up Microsoft accounts associated with the logged on user account.

**Comment by jmprieur** [comment]
@kpanwar : do you know if that was fixed?

**Comment by kpanwar** [comment]
This happens because you have corpnetwork flag enabled and it attempts to do kerberos auth using WAB. You have a choice to either not use the flag or build some runtime setting in your app to switch the flag. In your case, you should not use the flag.

**Comment by nigel-sampson** [comment]
Thanks for the answer, we had a solution much like you described with a build configuration so that local builds didn't set `UseCorporateNetwork`.
