### ISSUE TITLE
Profile 259 not supported?

### ISSUE THREAD

**Issue by IlSocio** [AzureAD/azure-activedirectory-library-for-dotnet#270]
I tried to install both the latest stable release 2.19 and the latest pre-release 3.5, but both the libraries fails the installation on a PCL which targets the profile 259.

`You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

As my understanding, this library should support the Profile 259... is there any problem with the nuget package, or I'm missing something?

In order to install the package I must remove Silverlight from the supported targets (Profile 111).

**Comment by kpanwar** [comment]
windows 8.0 (v2 and v3) and Windows Phone 8.1 (v3) are not supported.
