### ISSUE TITLE
AcquireTokenAsync in test code with UserCredentials fails with FormatException 'The format of value 'application/soap+xml;' is invalid.'

### ISSUE THREAD

**Issue by juturu** [AzureAD/azure-activedirectory-library-for-dotnet#271]
I'm using -pre release version of ADAL nuget package in unit test code to get auth tokens using UserCredentials.
```
UserCredential uc = new UserCredential("foo", "bar");
var authToken = await authContext.AcquireTokenAsync(resource, clientId, uc);
```

AcquireTokenAsync fails with error "'System.FormatException" with message "The format of value 'application/soap+xml;' is invalid.". 

This issue didn't repro with latest stable version of Adal package.

**Comment by kpanwar** [comment]
Fixed in release 2.19.
