### ISSUE TITLE
AcquireTokenAsync fails if scopes are capitalized

### ISSUE THREAD

**Issue by jasonjoh** [AzureAD/azure-activedirectory-library-for-dotnet#275]
Repro setup: Basic WPF application, Visual Studio 2015, latest pre-release experimental version of the library.

This code results in a null `AuthenticationResult.Token':

    string[] scopes = { "https://outlook.office.com/Mail.Read" };
    AuthenticationResult result = null;
    result = await authContext.AcquireTokenAsync(scopes, null, clientId, 
      redirectUri, new PlatformParameters(PromptBehavior.Auto, null));

Changing the scopes to an all-lowercase version fixes it:

    string[] scopes = { "https://outlook.office.com/mail.read" };

Using `https://outlook.office.com/Mail.Read' should be valid. If you check the network traffic a token is returned, the library just decides it isn't valid and doesn't return it.

**Comment by kpanwar** [comment]
Please use MSAL instead of experimental.
