### ISSUE TITLE
System.NullReferenceException in ADAL 3.0 in Xamarin.Android

### ISSUE THREAD

**Issue by Bonelol** [AzureAD/azure-activedirectory-library-for-dotnet#289]
Error: Java.Lang.RuntimeException: java.lang.reflect.InvocationTargetException ---> Java.Lang.ReflectiveOperationException: Exception of type 'Java.Lang.ReflectiveOperationException' was thrown. ---> System.NullReferenceException: Object reference not set to an instance of an object
at Microsoft.IdentityModel.Clients.ActiveDirectory.WebUI.SetAuthorizationResult (Microsoft.IdentityModel.Clients.ActiveDirectory.AuthorizationResult authorizationResultInput) [0x00006] in :0 
at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationAgentContinuationHelper.SetAuthenticationAgentContinuationEventArgs (Int32 requestCode, Result resultCode, Android.Content.Intent data) [0x0003a] in :0 
at MySIT.Mobile.Droid.MainActivity.OnActivityResult (Int32 requestCode, Result resultCode, Android.Content.Intent data) [0x00009] in :0 
at Android.App.Activity.n_OnActivityResult_IILandroid_content_Intent_ (IntPtr jnienv, IntPtr native__this, Int32 requestCode, Int32 native_resultCode, IntPtr native_data) [0x00014] in :0 
at (wrapper dynamic-method) System.Object:f6aed3f3-fe94-4c7a-90b9-35d9452f7d42 (intptr,intptr,int,int,intptr)
--- End of inner exception stack trace ---

One interesting thing is, all these errors occurred in Samsung cellphones (only one for LG).
Here is a list collected by my error logger:
Android version: JellyBeanMr2
Device: samsung GT-I9300

Android version: LollipopMr1
Device: samsung SM-J110M

 Android version: Lollipop
Device: samsung SM-G900F

Android version: Lollipop
Device: samsung SM-G900I

Android version: Lollipop
Device: LGE LG-F240S

The ADAL package version is 3.8.301280212-alpha

**Comment by kpanwar** [comment]
@Bonelol - Can you provide more details as to when does this happen? Is this method called before calling acquireToken, Upon completion of a successful auth or cancellation?

**Comment by Bonelol** [comment]
@kpanwar - Here is the details. When user click Login button, it calls AcquireToken and should open a webview in a new activity that loads azure auth page. But some Samsung phone screen lost response here and after a few seconds the app crashed. So it's before user enter password and hit the Login button in the webview. Hope I make it clear enough

**Comment by kpanwar** [comment]
@Bonelol - I was unable to repro your issue on SM-G900V running Lollipop (5.0). Can you please try to use the sample app bundled in the project at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/tree/dev/tests/TestApp/AdalAndroidTestApp and see if the issue repros for you?

**Comment by Bonelol** [comment]
@kpanwar - I have let my user to test the sample app (I don't have a samsung cellphone). After click 'Acquire Token' button, it show up auth page with no problem, then he typed in username and redirect to our ADFS auth server and app crashed when he try to type in password. So I think there may be some issues in either page redirecting or our ADFS auth page. Do you know if there is any service has their own ADFS auth page I can test with?

**Comment by Bonelol** [comment]
@kpanwar - forgot to tell you that we use Xamarin Forms to design the app, but I don't think there are differences in ADAL between Xamarin Android and Xamarin Forms, am I right?

**Comment by kpanwar** [comment]
@Bonelol - Is your ADFS trying to do Client TLS auth by any chance? If so, then it is not supported at the moment.

**Comment by Bonelol** [comment]
@kpanwar - Found the reason, some CSS style will cause webview crash. So it's not ADAL issue.
