### ISSUE TITLE
Ensure cross tenant RT does not get used across environments (PROD vs PPE)

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/azure-activedirectory-library-for-dotnet#290]
Ensure cross tenant RT does not get used across environments (PROD vs PPE)

**Comment by jmprieur** [comment]
@kpanwar : there are not enough details. What does it mean? is it still relevant?

**Comment by kpanwar** [comment]
When ADAL does not find an access or refresh token for a given authority, it attempts to use refresh token from another tenant for the same user. this matching only works when searching by UPN because unique id is different per tenant. This could also mean that ADAL could potentially choose a RT from a different cloud instance for the same UPN. We need to avoid this. We need to make sure url authority(login.microsoftonline.com, login.microsoftonline.de etc ) saved in token cache is same as the one for which the token is requested.

**Comment by kpanwar** [comment]
@SomkaPe - we need to fix this for sovereign cloud support.

**Comment by kpanwar** [comment]
@SomkaPe - can you reference the PR that was used to fix this? Also, please close the issue.

**Comment by SomkaPe** [comment]
it was fixed in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/757, TokenCache.cs LoadSingleItemFromCache method
