### ISSUE TITLE
PCL - AcquireTokenAsync results in 400 Bad Request - The size of request headers is too long.

### ISSUE THREAD

**Issue by sjwaight** [AzureAD/azure-activedirectory-library-for-dotnet#315]
Running the v4.0.209160138-alpha release a Xamarin app and after a period I hit a scenario where the Logins no longer work and I simply get a web response of "400 Bad Request - The size of request headers is too long." which looks suspiciously like this issue with the JS library: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/179

**Comment by kpanwar** [comment]
Though this is a server side issue, I would strongly recommend to use https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/dev for building apps using v2 model. Preview is also available in nuget.org (http://www.nuget.org/packages/Microsoft.Identity.Client/1.0.303282006-alpha)
