### ISSUE TITLE
CreateByDiscoveryAsync failed with message "Federation Metadata Url is missing for federated user"

### ISSUE THREAD

**Issue by lucadibiagio** [AzureAD/azure-activedirectory-library-for-dotnet#316]
hi all,
we are trying to acquire token using the the AcquireTokenAsync using the following overload:

**AcquireTokenAsync(string resource, string clientId, ClientCredential **clientCredential)**
unfortunatelly we obtain this error

**Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: missing_federation_metadata_url: Federation Metadata Url is missing for federated user. This user type is unsupported.**
debugging the code we have find that the application crash in the Method:

**internal static async Task<UserRealmDiscoveryResponse> CreateByDiscoveryAsync(String userRealmUri, String userName, CallState callState)**
when trying to call:

**return await adalHttpClient.GetResponseAsync<UserRealmDiscoveryResponse>("user_realm");
with a URL like this one:
https://login.microsoftonline.com/common/UserRealm/SAMPLE ACCOUNT@hotmail.it?api-version=1.0**

**is there a problem with our approach or am I doing wrong using ADAL ?**

**Comment by kpanwar** [comment]
Live Accounts are not supported for username password flow.
