### ISSUE TITLE
Cannot find ContinueAcquireTokenAsync for Windows Phone 8.1 in ADAL v4

### ISSUE THREAD

**Issue by KaiWalter** [AzureAD/azure-activedirectory-library-for-dotnet#334]
I want to implement a B2C-flow for Windows Phone 8.1 with v4.0.209160138-alpha. At the point when the App comes back with WAB from `ContinueWebAuthentication(WebAuthenticationBrokerContinuationEventArgs args)` I cannot find the `ContinueAcquireTokenAsync(args)` in the v4 library. See also [my StackOverflow question](http://stackoverflow.com/questions/36071143/adal-4-experimental-behaves-different-for-windows-desktop-native-and-windows-p).

**Comment by kpanwar** [comment]
@KaiWalter - I am sorry I have been busy with other high priority work. I will try to get back to you tomorrow.

**Comment by KaiWalter** [comment]
@kpanwar - That's good to hear. I'm somehow dead in the water here. Thanks for the update.

**Comment by kpanwar** [comment]
Issue resolved in SO.
