### ISSUE TITLE
AuthenticationContext.AcquireToken  issues access token for user with account locked out!

### ISSUE THREAD

**Issue by belaie** [AzureAD/azure-activedirectory-library-for-dotnet#343]
AuthenticationContext.AcquireToken  issues access token while user account is Locked out in Azure Active Directory.

We have observed:

User which has account locked out in the Azure Active Directory still gets the Access token from ADAL using AuthenticationContext.AcquireToken  as long as the username and password combination is given correct.

Code:

UserToken userToken = new UserToken();
            authContext = new AuthenticationContext(authority);
            
            Microsoft.IdentityModel.Clients.ActiveDirectory.UserCredential uc = new Microsoft.IdentityModel.Clients.ActiveDirectory.UserCredential(userId, userPassword);
            AuthenticationResult result = null;
            
            result = authContext.AcquireToken(_resourceUrl, _clientId, uc);
            userToken.Token = result.AccessToken;
            
            if (result.AccessToken != null)
                userToken.UserId = result.UserInfo.DisplayableId;

**Comment by kpanwar** [comment]
I would need more information for this issue. Was the account locked within one hour of the token acquisition? If so, then ADAL will return you the cached token.

**Comment by belaie** [comment]
Okay, I would check this and let you know. While can you point me to the ADAL cached token documentation to understand how this works?

**Comment by kpanwar** [comment]
http://www.cloudidentity.com/blog/2014/07/09/the-new-token-cache-in-adal-v2/

**Comment by kpanwar** [comment]
@belaie - Any updates?
