### ISSUE TITLE
ADAL v3 beta does not seem to work properly in the latest Windows 10 Preview build.

### ISSUE THREAD

**Issue by andersosthus** [AzureAD/azure-activedirectory-library-for-dotnet#348]
Active Directory Authentication Library (ADAL) v3 does not work properly in preview build 14316-rs1_release.160402-2217 when used outside of an UAP app (for instance console app or WPF app).

Instead of showing the proper login frame, it just shows an blank white page. Also it doesn't respond when trying to close it, and the only way to end it is to kill the process.

I've tried versions:

- 3.1.203031538-alpha
- 3.6.something
- 3.9.302261508-alpha

In the previous fast ring release of Windows 10, this worked.

I've also registered this as an issue in the Windows Feedback Hub: feedback-hub:?contextid=379&feedbackid=71e5fd9c-f3b8-45b1-a57a-6db64baff303&form=1&src=2

**Comment by kpanwar** [comment]
ADAL delegates all the web authentication to Web Authentication Broker (WAB) and does not (cannot) control any web flows. I will communicate the issue with the WAB team.

**Comment by andersosthus** [comment]
Thank you. If they need me to provide any logs, please put them in contact with me.

**Comment by darrelmiller** [comment]
I tried rolling back to the stable 2.23 and saw the same behaviour.

**Comment by kpanwar** [comment]
It is because the issue is with Windows. Consider filing a report with Windows.

**Comment by andersosthus** [comment]
@kpanwar I've submitted it through the feedback hub, but if you have and tips about other (better?) places to submit it I'm all ears.

**Comment by blumu** [comment]
I had the same issue and was able to resolve it with the following steps:
- Kill all browsers including Chrome IE and Edge
- Kill lync, outlook, all command prompts
- Start a single powershell command window
- **Kill explorer.exe under task explorer** This step is important. Just killing browsers is not enough!
- In the remaining powershell window run any command that triggers the AD prompt that would normally hang with a white window. (I used Azure Powershell command Login-AzureRmAccount.)
- Surprise surprise: the AD window now shows up correctly!
- Now you can restart explorer.exe and the AD window will keep working
