### ISSUE TITLE
Does not support v2 token endpoint

### ISSUE THREAD

**Issue by kpeek** [AzureAD/azure-activedirectory-library-for-dotnet#353]
When creating an AuthenticationContext and then calling AcquireTokenByAuthorizationCodeAsync, the /v2.0 is stripped from the token endpoint URL.

If the provided authority is https://login.microsoftonline.com/{tenant}/v2.0, the expected token endpoint is https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token, but it's building https://login.microsoftonline.com/{tenant}/oauth2/token instead

**Comment by kpanwar** [comment]
V2 is supported in the new library under preview. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
