### ISSUE TITLE
lastest nuget includes source code

### ISSUE THREAD

**Issue by tgilgil** [AzureAD/azure-activedirectory-library-for-dotnet#364]
Nuget 2.24304111323 installs the source code instead of the release dlls. I'm thinking this is not normal!

The packages folder contains source files and .pdb files

**Comment by kpanwar** [comment]
I cannot repro the problem. I see both lib and src in the packages folder and my test project does refer to DLLs. Could be an issue with nuget.exe

**Comment by tgilgil** [comment]
The packages folder contains source files and and associated pdb files. Is this expected?

**Comment by kpanwar** [comment]
Package folder contains lib/ and SRC/. Lib contains pdb and DLL and SRC/ contains the source code.

**Comment by tgilgil** [comment]
Alright! The older versions on NuGet did not have the source code and pdb included when installed so I thought there was a problem :)

**Comment by alaincroisetiere** [comment]
This is the only version on nuget.org packaged with source.
