### ISSUE TITLE
Pin certificates for STS endpoints

### ISSUE THREAD

**Issue by mababey** [AzureAD/azure-activedirectory-library-for-dotnet#371]
When apps authenticate to AAD, a Man-in-the-Middle (MITM) would be able to intercept AAD access tokens, enabling the attacker to impersonate the AAD end user and access directory data and perform user operations against AAD, Graph and other federated services, or modify response data in transit back to the device in an attempt to inject a remote compromise of the client.

ADAL only establishes secure HTTP (HTTPS) connections to the STS, and validates server certificates according to the standard protections of the platform.  However, there are still other vectors for a MITM attack to occur.  For example:
- A compromised CA, or one run by an unfriendly nation state, could be used to generate a valid server certificate that chains to a trusted root and purports to authenticate the AAD domains.
- A malicious store application on the device could leverage a platform 0-day or unpatched vulnerability to evade the sandbox and compromise the device, and install a self-signed certificate for the STS.

One protection for attacks like these is to "pin" certificates, effectively whitelisting a certain set of certificates or authorities for the host: https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning.  The ideal is to pin the certificates at development time.  The OWASP article and associated RFC have recommendations for how to implement this, and deal with issues like certificate rotation.

So while a prerequisite for the attacks is to compromise the network path, pinning is still recommended as an additional layer of protection (reducing attack surface).

**Comment by jmprieur** [comment]
Won't do in ADAL.NET.
WIll be considered in MSAL.NET based on requests
