### ISSUE TITLE
authority_not_in_valid_list: 'authority' is not in the list of valid addresses

### ISSUE THREAD

**Issue by vijayaramb** [AzureAD/azure-activedirectory-library-for-dotnet#379]
i am trying to acquire token silent on behalf of the user in my webapi service. I am left out with this error. Could someone help me out

**Comment by kpanwar** [comment]
can you provide more details? what authority did you pass in to the authentication context constructor etc?

**Comment by vijayaramb** [comment]
aadInstance = "https://login.microsoftonline.com/{0}{1}{2}"

code snippet:
 //string userObjectID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
                string userObjectID = _sessionLogic.GetUserObjectIDFromAAD(_userDetails);

                string authority = String.Format(CultureInfo.InvariantCulture, Startup.aadInstance, Startup.tenant, string.Empty, string.Empty);
                ClientCredential credential = new ClientCredential(Startup.clientId, Startup.clientSecret);

                // We don't care which policy is used to access the TaskService, so let's use the most recent policy
                //string mostRecentPolicy = ClaimsPrincipal.Current.FindFirst(Startup.AcrClaimType).Value;

                // Here you ask for a token using the web app's clientId as the scope, since the web app and service share the same clientId.
                // AcquireTokenSilentAsync will return a token from the token cache, and throw an exception if it cannot do so.
                AuthenticationContext authContext = new AuthenticationContext(authority, new NaiveSessionCache(userObjectID));
                AuthenticationResult result = await authContext.AcquireTokenSilentAsync(Startup.clientId, credential, new UserIdentifier(userObjectID, UserIdentifierType.UniqueId));

**Comment by vijayaramb** [comment]
today i am getting this error: Failed to acquire token silently. Call method AcquireToken

**Comment by kpanwar** [comment]
did your first issue get resolved? If you use latest ADAL there will be an inner exception that you can check for actual failure details.

**Comment by vijayaramb** [comment]
first issue got rosolved, but getting the next one "Failed to acquire token silently. Call method AcquireToken". could you help me out, where i am failing. 
FYI, i am not using the above code in mvc web application, where we can pop up microsoft login page for user login. Instead i am using this code in web api (say signin api) where i will get the user credentials, impilictly call AAD and get back the token for the user. Thats why i trying to use 'AcquireTokenSilentAsync'. But this is not working.

**Comment by rengarajan75** [comment]
I am facing the same issue. Any answer Graph API fails when we try to connect to Graph.
