### ISSUE TITLE
Failed to acquire token silently. Call method AcquireToken

### ISSUE THREAD

**Issue by vijayaramb** [AzureAD/azure-activedirectory-library-for-dotnet#380]
I am getting error "Failed to acquire token silently. Call method AcquireToken". 
could you help me out, where i am failing.

FYI, i am not using the above code in mvc web application, where we can pop up microsoft login page for user login. Instead i am using this code in web api (say signin api) where i will get the user credentials, impilictly call AAD and get back the token for the user. Thats why i trying to use 'AcquireTokenSilentAsync'. But this is not working.

**Comment by kpanwar** [comment]
discussion in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/379
