### ISSUE TITLE
missing_federation_metadata_url: Federation Metadata Url is missing for federated user. This user type is unsupported.

### ISSUE THREAD

**Issue by vijayaramb** [AzureAD/azure-activedirectory-library-for-dotnet#381]
I am getting federation metadata url missing error, when i try to acquire token using user credential in my web api service.

I am using the below code snippet:

UserCredential uc = new UserCredential(credentials.Username, credentials.Password);
                var authContext = new AuthenticationContext(Startup.Authority, new NaiveSessionCache());
                var result = await authContext.AcquireTokenAsync(Startup.resourceId, Startup.clientId, uc);

**Comment by kpanwar** [comment]
Are yiu using a Microsoft account like outlook.com or Hotmail.com? If so then it is not supported.

**Comment by kpanwar** [comment]
I mean username and password flow for that user type.

**Comment by vijayaramb** [comment]
no i am using azure active user account

**Comment by vijayaramb** [comment]
to make it simple,  i am trying to get access token and refresh token for azure active directory users from my web api service which is already registered as an application in B2C

**Comment by kpanwar** [comment]
You really should not be using username and password flow for confidential clients like a web API. This feature is enabled as an error and will be disabled soon.

**Comment by vijayaramb** [comment]
so what is the library and approach should i use for getting access token and refresh token for my users who will call my login web api service with just username and password.

**Comment by kpanwar** [comment]
@vijayaramb what kind of app did you create in b2c portal? Native client or web API?

**Comment by vijayaramb** [comment]
i am creating web api in b2c portal

**Comment by kpanwar** [comment]
@vijayaramb How is the developer calling your web API? Ideally, you should have a native client that acquires tokens for the web API. The access token is then sent to your web API that you can later redeem to get more access tokens for other resources using on behalf of flow.
