### ISSUE TITLE
Need to be able to use UISafariWebView from within ADAL.iOS

### ISSUE THREAD

**Issue by AlexBrownShi** [AzureAD/azure-activedirectory-library-for-dotnet#410]
We are using certificate authentication, but unfortunately, Safari's client certs do not appear to be available for the default UIWebView to access.  Can we give a user-configurable option that allows it to use the UISafariWebView instead?

**Comment by kpanwar** [comment]
for Objc issues, please file them at https://github.com/AzureAD/azure-activedirectory-library-for-objc

**Comment by AlexBrownShi** [comment]
This is not an Obj-C issue.  There is a line of code in THIS project https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/src/ADAL.PCL.iOS/AuthenticationAgentUIViewController.cs#L64

I believe that that UIWebView object could be switched out for a UISafariWebView Object and my problem will be solved.  

I believe that is C# code in Xamarin.iOS.  I'd do it myself - and I might if I have more time.  But probably would be better if someone familiar with the project did it.

**Comment by kpanwar** [comment]
We do not think it is right to add SFSafariViewController in ADAL API.

The way OAuth2 flows work is that the server redirects the user back to the redirect URI provided by the app and returns a authorization code as a query parameter. SFSafariViewController can only return data back to the calling app launching the said app using the app-scheme. This means your app's redirect uri should be <your-app-scheme>://<bundle-id>. This is not a secure approach because there is no guarantee that SFSafariViewController  calling <your-app-scheme>:// will actually launch your app. If there is a malicious app with same app scheme then it may receive the information intended for your app.

On a side note, we also do not support the same in our native ADAL Objective-C library.

**Comment by AlexBrownShi** [comment]
I'm confused about why you would use an App redirect uri of ://?  Can you explain that?  My expectation would be that your redirect scheme would be your app's custom scheme as registered in the plist file.  For example, our app might be shisolutions://, when the SFSafariWebView gets a redirect for this custom scheme, it will call the openURL method in the AppDelegate for our app.  From here we should be able to parse the properties out.   See this pattern: [http://strawberrycode.com/blog/sfsafariviewcontroller-and-oauth-the-instagram-example/](http://strawberrycode.com/blog/sfsafariviewcontroller-and-oauth-the-instagram-example/).  

I'm not sure how your code would modify the AppDelegate, that would be an additional step for an implementor.  

Naturally, custom url schemes are not registered with apple, but there should be a way of dealing with this in the OS when there is more than one subscriber to a custom scheme.  Was this your concern?  That another app maker could leverage the same custom scheme?

**Comment by AlexBrownShi** [comment]
Would the use of universal links be a safe way to avoid this issue? 

For example, the Redirect in the SafariWebView would take the user to a web page that is associated with the app.  

I'm not sure how one would launch a universal link from a browser, however - my understanding is that universal app linking is implemented on the client library.

**Comment by AlexBrownShi** [comment]
Also, I'm confused as to why the iOS objective C example seems to be using a <scheme>://<bundle> redirection url.  Is it redirecting from a Safari web view instead of UIWebView?

**Comment by AlexBrownShi** [comment]
https://azure.microsoft.com/en-us/documentation/articles/active-directory-devquickstarts-ios/

**Comment by kpanwar** [comment]
You are correct about the concern where another app gets the auth code. 
Sample is using appscheme://bundle-id redirect uri so that the app can communicate with azure authenticator got device auth and SSO.
