### ISSUE TITLE
Nuget Package Version

### ISSUE THREAD

**Issue by titobf** [AzureAD/azure-activedirectory-library-for-dotnet#411]
The readme.md of this repo states that "The latest stable release is 3.10.305110106". However, I was unable to find that version in the NuGet Manager. It says that the latest stable version is 2.26.305102204.

However, I was able to install v3 by running the following command in the PMC:

Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory -IncludePrerelease -Version 3.10.305110106

I'm planning on using part of the code of a sample project that was recently upgraded to ADAL v3: [active-directory-dotnet-webapp-webapi-multitenant-openidconnect](https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-multitenant-openidconnect/commit/439c582b79de9605627e78764436374ba6860a45)

**Comment by kpanwar** [comment]
I have updated the package to be listed.

**Comment by titobf** [comment]
Great. I can see the new version now. Thanks
