### ISSUE TITLE
DictionaryRequestParameters bug in recent versions?

### ISSUE THREAD

**Issue by smourier** [AzureAD/azure-activedirectory-library-for-dotnet#412]
In ADAL older versions (Experimental), the DictionaryRequestParameters used to override the ToString() method. Now it doesn't any more which causes this code to build an incorrect auth url:

            var url = authContext.GetAuthorizationRequestUrlAsync(scope, clientId, etc..) or
            var result = authContext.AcquireTokenAsync(scope, clientId, etc..)

The build url now has this form:
https://login.microsoftonline.com/common/oauth2/authorize?Microsoft.IdentityModel.Clients.ActiveDirectory.DictionaryRequestParameters

which is of course 100% invalid.

**Comment by kpanwar** [comment]
Fixed the issue in 3.10.305161347
