### ISSUE TITLE
Dependencies error after upgrading from 2.0 to 3.0

### ISSUE THREAD

**Issue by ricardopolo** [AzureAD/azure-activedirectory-library-for-dotnet#416]
After updating the Nuget since yesterday we are getting this exception

```
Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
````

Meanwhil we will downgrade, but please check it. We also tryi installing and uninstalling the latest version back and it sill fails.

**Comment by kpanwar** [comment]
What kind of application are you running?

**Comment by ricardopolo** [comment]
Website, .Net framework 4.6

**Comment by kpanwar** [comment]
Is this a standard ASP.NET website running in windows environment?

**Comment by ricardopolo** [comment]
MVC, Windows 10 Environment. Also tested in a bran new machine compiling in Appveyor

**Comment by kpanwar** [comment]
@ricardopolo I am unable to repro your problem. I just created a simple website where I create authenticationcontext within page_load. My app loads just fine. My web config is below.
`<configuration>
  <system.web>
    <compilation debug="true" targetFramework="4.6">
      <assemblies>
        <add assembly="System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A"/>
        <add assembly="System.Threading.Tasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A"/>
      </assemblies>
    </compilation>
    <httpRuntime targetFramework="4.6"/>
  </system.web>
</configuration>`

**Comment by kpanwar** [comment]
@ricardopolo any updates?

**Comment by ricardopolo** [comment]
@kpanwar I'll replicate it tomorrow and post updates :)

**Comment by ricardopolo** [comment]
I fixed uninstalling and installing it back.
