### ISSUE TITLE
Version 3 doesn't seem to support Interactive Login for MFA

### ISSUE THREAD

**Issue by MarkDordoy-JustEat** [AzureAD/azure-activedirectory-library-for-dotnet#417]
Hello 

With version 2 of this library i was able to do the following (using powershell):

```
$script:apiEndpoint = "https://aws.just-eat.com/adfs
$script:authority = "https://sts.just-eat.com/adfs"
$script:ClientID = "31e1ae37-054b-422f-abf1-11112312312"
$script:redirect = New-Object System.Uri("https://aws.just-eat.com/")

$AuthContext = new-object Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext($authority,$false)
$script:result = $AuthContext.AcquireToken($redirect,$clientID,$redirect)
```

and i would get the following pop up:

![twofactor](https://cloud.githubusercontent.com/assets/7372737/15322810/cc46f4a4-1c36-11e6-86f2-8197c2389f67.PNG)

On successful credentials/two factor i would have an access token i could then use. 

Im unable to get the same result in version 3. I can see AcquireToken has been removed and i now need to use AcquireTokenasync, but it doesnt seem to support the same construction variables. 

Can i still do what im attempting in version 3? 

Thanks

**Comment by kpanwar** [comment]
You should be using something like 
`            AuthenticationContext context = new AuthenticationContext("https://sts.just-eat.com/adfs", false);
            var result = await context.AcquireTokenAsync("https://aws.just-eat.com/adfs", "31e1ae37-054b-422f-abf1-11112312312", new Uri("https://aws.just-eat.com/"),new PlatformParameters(PromptBehavior.Always, null));
`
