### ISSUE TITLE
ADAL for .NET does not account for WS-Trust responses where returned token type is SAML 1.1

### ISSUE THREAD

**Issue by jaevan** [AzureAD/azure-activedirectory-library-for-dotnet#420]
# Issue:
1. AcquireToken(string resource, string clientId, UserCredential userCredential) overload is used
2. User is federated with WS-Trust
3. IDP returns WS-Trust tokens with type <t:TokenType>http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV1.1/t:TokenType

In this scenario we will see the user successfully retrieve a SAML 1.1 type WS-Trust token from their IDP, but then ADAL will redirect the client to oauth2 token endpoint with a grant-type referencing SAML2 (rather than SAML 1.1). This would look like:

https://login.windows.net/contoso.onmicrosoft.com/oauth2/token
POST Data:
resource=00000002-0000-0000-c000-000000000000&client_id=1e983b13-3836-4cec-ba6a-8b86b693713c&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Asaml2-bearer&assertion=<Truncated>&scope=openid

I've reviewed the logic in ADAL.NET and believe the following is causing this:

Line 111 in AcquireTokenNonInteractiveHandler.cs is making the determination for which grant type to send based on the WS-Trust response it received
    this.userAssertion = new UserAssertion(wsTrustResponse.Token, (wsTrustResponse.TokenType == WsTrustResponse.Saml1Assertion) ? OAuthGrantType.Saml11Bearer : OAuthGrantType.Saml20Bearer);

If the <tokenType> tag within the WS-Trust response is an exact string match of "urn:oasis:names:tc:SAML:1.0:assertion" we set grant_type to saml1_1-Bearer
Else we will set the grant_type to saml2-bearer

There are 3 valid values depending on the SAML version of the token returned. These are:
SAML 1.0 - <t:TokenType>urn:oasis:names:tc:SAML:1.0:assertion/t:TokenType
SAML 1.1 - <t:TokenType>http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV1.1/t:TokenType
SAML 2.0 - <t:TokenType>http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0/t:TokenType

Based on this, SAML 1.1 token types will always be converted into a grant_type = saml2-bearer

The end result in the clients case is we make a request to login.windows.net with grant_type of saml2-bearer , but supply a SAML 1.1 assertion. 
# Expected behavior:

We would expect the client to make a call to login.windows.net with grant_type=urn:ietf:params:oauth:grant-type:saml1_1-bearer IF the returned token type from their IDP was SAML 1.0 or SAML 1.1
# Repro Steps:

We have only been able to reproduce this with a PingFederate IDP so far. ADFS works fine as it returns a SAML 1.0 token type, and this is correctly handled

**Comment by jmprieur** [comment]
Closing as won't fix. The IdP needs to behave like AD FS if you want the scenario to work.
