### ISSUE TITLE
PromptBehavior.Always is not work in UWP.

### ISSUE THREAD

**Issue by yamamoWorks** [AzureAD/azure-activedirectory-library-for-dotnet#422]
PromptBehavior.Always is not work in UWP application.

`var authContext = new AuthenticationContext("https://login.windows.net/common");` 
`var platformParams = new PlatformParameters(PromptBehavior.Always, false);`
`var result = await authContext.AcquireTokenAsync("https://management.core.windows.net/", "xxxx", new Uri("xxx"), platformParams);`

I guess the reason is that 'GetCacheLoadPolicy' method of  'PlatformInformation' in 'ADAL.PCL.WinRT' project is not overrided.

'GetCacheLoadPolicy' method is always return true.
Then, 'LoadFromCache' property in 'AcquireTokenInteractiveHandler' class become true.
So, do not show login prompt.

**Comment by kpanwar** [comment]
fixed in 3.10.305231913

**Comment by yamamoWorks** [comment]
great !
