### ISSUE TITLE
Getting JavaScript-errors when authenticating using ADAL

### ISSUE THREAD

**Issue by casaout** [AzureAD/azure-activedirectory-library-for-dotnet#424]
I am using the Microsoft Graph API (in a WPF app, .Net Framework 4.5) and successfully connecting a user to the API with ADAL. Two users (testing the application) reported a JavaScript-error during the authentication process with Office 365 (using ADAL), see Screenshot below.

A few months ago I noticed these pop-ups too, but they were gone after I've updated the ADAL **Nuget-Package.** I just checked and there is no update available (current version: 4.0.209160138-alpha). 

I myself cannot reproduce the issue. It might be that using different O365 tenants cause this issue in some cases (as they load different login-screens), or something else.

Did somebody experience similar errors, knows why/when this happens and a fix for it?
![3lyo5](https://cloud.githubusercontent.com/assets/5212692/15469473/bb929f7e-20ea-11e6-9338-47b7e6ad12c0.png)

**Comment by kpanwar** [comment]
This is a server side error that ADAL has no control over. I will communicate with the server team to fix this. More importantly, the library you are using is unsupported. You should consider using our next-gen library MSAL available at https://www.nuget.org/packages/Microsoft.Identity.Client.

**Comment by casaout** [comment]
hi @kpanwar Thanks for your quick response! I will have a look at MSAL. However, I am not sure if this is the right thing to do, as the official tutorial/documentation from @dstrockis still refers to ADAL (https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-devquickstarts-wpf/). Thanks for a clarification!

**Comment by casaout** [comment]
@kpanwar Could you please elaborate a little more on what you meant with your comment two weeks ago? CC: @dstrockis  Thanks!

**Comment by kpanwar** [comment]
We will be updating the documentation soon to remove references to the experimental library.

**Comment by casaout** [comment]
Perfect. @kpanwar  Can you please let me know when the documentation is updated? Thanks!

**Comment by casaout** [comment]
@kpanwar and @dstrockis We are planning to release our tool July, 1st and it would be great if we could use the official libary instead of the unsupported/old ADAL. When are you planning to update the documentation? Or do you have any other resource I could use to migrate from ADAL to MSAL? Thanks!
