### ISSUE TITLE
Support for more profiles (like 259)

### ISSUE THREAD

**Issue by ravensorb** [AzureAD/azure-activedirectory-library-for-dotnet#428]
Are there any plans to update this library to be usable in more profiles. I am targeting iOS, Android, Windows Mobile 8.1 and Windows 10 Mobile.  Right now i get errors about unsupported profile 259 when trying to add the package.

**Comment by kpanwar** [comment]
There are no plans on supporting Windows Phone 8.1. We only only support UWP apps.

**Comment by ravensorb** [comment]
That's great -- only issue is, the current package will not install into a PCL project that targets anything over 8.0.  The main ADAL.PCL project needs its profile updated (or its nuspec updated) so that it will install into some of the newer profiles like 151 or 259.
