### ISSUE TITLE
PromptBehavior in Android and iOS

### ISSUE THREAD

**Issue by yamamoWorks** [AzureAD/azure-activedirectory-library-for-dotnet#437]
You know the PlatformParameters in UWP has PromptBehavior.
`var platformParams = new PlatformParameters(PromptBehavior.Always, false);`

But the PlatformParameters in Android and iOS dose not have PromptBehavior.
I think that implementation of PromptBehavior is not depend platform.

Are these will be implemented in the near future?
I hope so.

Regards

**Comment by kpanwar** [comment]
PR is already provided at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/582. We need to update it ensure that the API throws when developer attempts to use PromptBheavior.Never on iOS and Android. We don't support that option.

**Comment by mjcheetham** [comment]
@yamamoWorks, we've taken the work from your PR (#582) and updated it (#723) to prevent using `PromptBehavior.Never` on Android and iOS platforms (as we don't support that option on those platforms).
Thanks again for your contribution 😄
