### ISSUE TITLE
Login-AzureRmAccount UI - We require a web browser plugin but it won't install here.

### ISSUE THREAD

**Issue by markcowl** [AzureAD/azure-activedirectory-library-for-dotnet#438]
Cross-posting from: https://github.com/Azure/azure-powershell/issues/2303
```
For our corporate SSO, every time we connect with an unregistered browser we have to get a security code from Symantec Validation and ID protection. We have the option of saving/remembering the browser. If we do that it needs to download the "Symantec Authentication Client Plugin". The file downloads and I get a popup about running or saving the file. If I hit "Run", Powershell immediately gives me an error "Add-AzureRmAccount : The browser based authentication dialog failed to complete for an unknown reason. StatusCode: 
200", however the plugin installer did run. But it must not be working, since the next time I'll get asked again.

Any thoughts on how to get around it?
```
This is the dialog that is displayed when executing ```AuthenticationContext.Authenticate``` in Adal 2.18.x using interactive login.  How can the customer work around this browser restriction?

**Comment by kpanwar** [comment]
what is the minimum browser version supported by the plugin? ADAL use browser control (trident) provided by .NET framework. By default it runs in IE 7 mode. You could try to update the version to see if the plugin works. https://weblog.west-wind.com/posts/2011/May/21/Web-Browser-Control-Specifying-the-IE-Version

**Comment by kpanwar** [comment]
@markcowl any updates?
