### ISSUE TITLE
AcquireToken method is missing from AuthenticationContext class in Powershell

### ISSUE THREAD

**Issue by sgreenlee11** [AzureAD/azure-activedirectory-library-for-dotnet#443]
I have noticed that the AcquireToken method is no longer available for a PowerShell object created with the AuthenticationContext class in v3 of the library. This existing code is still working when tested using v 2 of the ADAL library. Here is the process used to create the AuthenticationContext object:

Add-Type -Path "Microsoft.IdentityModel.Clients.ActiveDirectory.dll"
$authority = "https://login.windows.net/common"
$authContext = New-Object Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext -ArgumentList $authority
$authContext.AcquireToken($resource, $clientID, $credential)

Attempting this is in the current ADAL v3 library generates this error:

$authContext.AcquireToken()
Method invocation failed because [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does not contain a method named 'AcquireToken'.
At line:1 char:1
+ $authContext.AcquireToken()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by kpanwar** [comment]
You have to use UserPasswordCredential class in ADAL v3

**Comment by jeffpatton1971** [comment]
I'm actually working on some cmdlets in powershell for working with some of the azure rest api stuff. I use the acquiretoken method just fine and I don't know that i'm using what @kpanwar mentioned.

https://github.com/jeffpatton1971/ARA/blob/master/Authentication/Authentication.psm1#L33

**Comment by sgreenlee11** [comment]
Thanks Jeff. It seems that some of my issues may have been coming from using the preview version of PowerShell ISE. I was eventually able to use the acquiretoken method with ADAL v3 and the UserCredential class to bypass the credential prompt in the standard ISE version.

**Comment by leonbravo** [comment]
yes, with version 3 this method works differently. You can downgrade your library version using Nuget Package manager (tool -> Nuget Package manager  -> Manage Nuget ...).

Search for Microsoft.IdentityModel.Clients.ActiveDirectory on the top left and install a version 2.XX from droplist at the right.
