### ISSUE TITLE
What happend to AcquireTokenByRefreshTokenAsync in version 3?

### ISSUE THREAD

**Issue by JohanPetersson** [AzureAD/azure-activedirectory-library-for-dotnet#446]
Can we achieve the same functionality in another way?

**Comment by kpanwar** [comment]
We have removed the support to return refresh token to the developer to avoid abuse by misinformation. What is your scenario where you need the refresh token? Maybe we can suggest alternatives.

**Comment by JohanPetersson** [comment]
> We have removed the support to return refresh token to the developer
So by using ADAL 3 there is no refresh token in the users claims anymore?

We're using the user's refresh token to acquire an access token to SharePoint Online.

**Comment by kpanwar** [comment]
Refresh token is still present but it is internal implementation details as far as the developer is concerned. You should call acquireTokenSilent(<sharepoint resource>, UserIdentifier) to get the token for another resource. ADAL already supports acquiring tokens for multiple resources.

**Comment by JohanPetersson** [comment]
I guess this requires that the refresh token is already present in the token cache? Which is not the case in our code, since the user obtains the refresh token outside ADAL in Microsoft.Owin.Security.WsFederation. 

Backstory...
We're integrating with Auth0 through their WS-FED plugin and they integrate in their turn with our client's ADFS through OpenId Connect.
Then we need to make authenticated calls to our client's SharePoint Online without the user needing to login again, that's why we're acquiring new tokens to another resource by using their refresh tokens.

I think we will stick with version 2 at this moment. Unless you have any suggestions how we could solve this?

**Comment by MikeStall** [comment]
This Microsoft Graph sample https://github.com/microsoftgraph/aspnet-webhooks-rest-sample hit the problem too - graph webhooks encourage you to cache the refresh token 

I hit this too - my refresh token is coming from outside the ADAL token cache. Anybody that caches the refresh token for server-side operations will hit this.  

Is there a way to populate the ADAL cache with the refresh token?

**Comment by ntheile** [comment]
I am in the same boat, trying to acquire a token for SharePoint using the "on-behalf flow" in a very badly configured Azure AD tenant. It sucks ADAL does not expose refresh tokens. Guess I can just roll my own middleware and handle the refresh token myself. ADAL 3 with .net core kinda sucks for advanced use-cases.

**Comment by jmprieur** [comment]
@ntheile : is it an option for you to use MSAL.NET? The support for .NET core is better than in ADAL.NET
Also, we are going to add AcquireTokenByRefreshToken in MSAL.NET very soon.

**Comment by ntheile** [comment]
@jmprieur ,

Great hear about the upcoming support! Yeah the V2 endpoint is not an option for my organization yet....we have a pretty messed up config with on-prem ADFS and improper user agent string sniffing combined with weird intune device compliance settings. Basically when I use V2 I get device compliance errors and it rarely works on mobile devices. Our security department really flipped too many switches and made an ugly Frankenstein setup, not to mention user consenting is turned off :(

But I do really like the standard openid connect approach that Microsoft took in Azure AD V2 and MSAL.  Hopefully one day I can use it!!!

**Comment by jmprieur** [comment]
@ntheile also coming - although a bit later - is the broker support (Company portal / Microsoft Authenticator) for the AAD v2.0 endpoint, which should solve your Intune issues. 
We'll also support ADFS 2019 (not sure that will help you much)
