### ISSUE TITLE
Link to samples and docs redirects to 404

### ISSUE THREAD

**Issue by AlfredoMS** [AzureAD/azure-activedirectory-library-for-dotnet#448]
The link to the samples and documentation  in the README.md file redirects to https://github.com/AzureADSamples which returns 404.

**Comment by SaadBinShahid** [comment]
Anybody found the correct link ?

**Comment by kpanwar** [comment]
duplicate of https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/452
