### ISSUE TITLE
ADAL dialog content shows logo that does not meet high contrast expectations

### ISSUE THREAD

**Issue by AArnott** [AzureAD/azure-activedirectory-library-for-dotnet#449]
#168 fixed most of the issues, but the VS logo itself still does not conform to high contrast theming.
![image](https://cloud.githubusercontent.com/assets/3548/15915000/59af9d90-2d9a-11e6-8fd2-d18604621f96.png)

**Comment by kpanwar** [comment]
Does it look as expected in a browser like IE?

**Comment by AArnott** [comment]
No. It looks bad there too:
![image](https://cloud.githubusercontent.com/assets/3548/15943712/356f759a-2e3f-11e6-91b1-d49cbdc32ffc.png)

**Comment by kpanwar** [comment]
I will let the service team know that this needs to be fixed.

**Comment by AArnott** [comment]
Thanks.
