### ISSUE TITLE
TokenCache is not working in a Xamarin.Android Release Build

### ISSUE THREAD

**Issue by stefffdev** [AzureAD/azure-activedirectory-library-for-dotnet#450]
When I'm running a release build of my xamarin.forms app on android, the tokencache is not working, failing with the error 
`06-09 07:47:27.153: W/(12494): 09.06.2016 05:47:27:  - TokenCachePlugin.cs: Failed to save cache: System.Runtime.Serialization.InvalidDataContractException: No set method for property 'OffsetMinutes' in type 'System.Runtime.Serialization.DateTimeOffsetAdapter'.`

Everything works fine in the debug build, this seems to be a linking issue, when I add
"System.Runtime.Serialization" to the "Skip linking assemblies" in the settings of my xamarin.android project in Visual Studio everything is working as expected.

**Comment by kpanwar** [comment]
This is a known issue in xamarin. https://forums.xamarin.com/discussion/58736/crash-in-release-build-when-using-datacontractjsonserializer
Sadly, no action has been taken on this bug yet. :(
