### ISSUE TITLE
Converged Model Authentication

### ISSUE THREAD

**Issue by titobf** [AzureAD/azure-activedirectory-library-for-dotnet#453]
I'm looking to be able to authenticate both Office 365 accounts and Microsoft accounts, and I found this: [microsoft-graph-authentication-with-the-converged-model-preview/](http://simonjaeger.com/microsoft-graph-authentication-with-the-converged-model-preview/)

Does this library supports or provides tools to authenticate against the OAuth v2.0 Endpoints?

**Comment by kpanwar** [comment]
it does not. You need to use https://github.com/AzureAD/microsoft-authentication-library-for-dotnet. Nugets are at https://www.nuget.org/packages/Microsoft.Identity.Client

**Comment by titobf** [comment]
Thanks!

**Comment by titobf** [comment]
This post could be helpful to someone else going through the same path:

http://simonjaeger.com/microsoft-authentication-library-preview/
