### ISSUE TITLE
SecurePassword.Clear is throwing "Instance is read-only"

### ISSUE THREAD

**Issue by normanhh3** [AzureAD/azure-activedirectory-library-for-dotnet#458]
Hi Folks,

I'm trying to use the System.Security.SecureString to forward on user credentials from my apps user to authenticate with.

When I do that using a SecureString the ApplyTo method of [this class](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/c6b050a160b79f88e5efc9e3014a0ad836b98d67/src/ADAL.PCL.Desktop/UserPasswordCredential.cs) is doing a Clear which is resulting in an InvalidOperationException with the message "Instance is read-only."

My usual searching has not turned up sufficient advise to help me through this issue.

1. Am I creating the SecureString incorrectly?  I am using the AppendChar method.
1. Should there be a check on the Clear method that uses the IsReadOnly property of SecureString to determine if it can be done safely?

Thanks for the feedback!

**Comment by kpanwar** [comment]
Fixed in 3.13.0
