### ISSUE TITLE
PCL UserCredential no longer supports password.

### ISSUE THREAD

**Issue by hock2k5** [AzureAD/azure-activedirectory-library-for-dotnet#462]
I see that the password from the constructor of the `UserCredential` was removed.  For Desktop.PCL the `UserPasswordCredential` is available to pass in a password but now nothing is available to use on the non-desktop PCL. 

I am using Xamarin.iOS and have a  custom login screen with a username/password text entry where the user logs in.  How should I pass in the password to authenticate?

**Comment by kpanwar** [comment]
We only allow for using webview in Xamarin iOS and android.

**Comment by hock2k5** [comment]
This functionality worked in 3.5.207081303-alpha.

Will this be coming back or do I need to change my app to use the webview?

**Comment by kpanwar** [comment]
This functionality is not coming back.
