### ISSUE TITLE
Unexpected multiple_matching_tokens_detected even when User has been provided - v3

### ISSUE THREAD

**Issue by dzimchuk** [AzureAD/azure-activedirectory-library-for-dotnet#469]
I noticed the following error when calling AcquireTokenSilentAsync:

> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: multiple_matching_tokens_detected: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more arguments (e.g. UserId)

I pretty much understand what it means but the problem is that I do provide a UserId (unique id) and still get this error even though I see distinct items in the cache itself.

The problem occurs because `AcquireTokenHandlerBase` initializes `CacheQueryData` in its constructor and it uses fields such as `this.UniqueId` and `this.DisplayableId` that have not been initialized yet. They get initialized by subclasses such as `AcquireTokenSilentHandler` or `AcquireTokenInteractiveHandler` after the base class constructor exits.

Thus, search by user id or displayable name never works and we get this error about duplicates.

**Comment by kpanwar** [comment]
Duplicate of https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/460

**Comment by dzimchuk** [comment]
@kpanwar Could you please elaborate in what way this issue is a duplicate of #460?

**Comment by kpanwar** [comment]
In both the bugs, the root cause is the same. CacheQueryData initialization is causing various errors. Thanks for the GREAT description though. I have made the fix in ADAL v2. I need to port it to ADAL v2.

**Comment by kpanwar** [comment]
I will open this again to commit the v2 fix.

**Comment by kpanwar** [comment]
Fixed in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/480
