### ISSUE TITLE
Why was the SecureString parameter removed from ClientCredential?

### ISSUE THREAD

**Issue by acgritt** [AzureAD/azure-activedirectory-library-for-dotnet#470]
We are currently using ADAL 2.26.305102204 within our Service Fabric application for accessing the Azure Key Vault.  Due to how we are securing the Client Secret in the settings.xml, when we retrieve it, it returns as a SecureString.  In the version of ADAL we are using we are able to pass this into the ClientCredential.  In the most current version of ADAL this support has been removed and we are curious to know the reason for this removal and if it my be coming back.

As there isn't a safe/clean way to convert a SecureString back into a regular string this is a piece of functionality that we would prefer to have remain.

**Comment by kpanwar** [comment]
Portable libraries don't have support for SecureString, but we will make API update to include the support in a different way.

**Comment by kpanwar** [comment]
Fixed in 3.13.0
