### ISSUE TITLE
AdalError does not contain invalid_grant and user_password_expired error codes

### ISSUE THREAD

**Issue by nickuraltsev** [AzureAD/azure-activedirectory-library-for-dotnet#472]
I am using ADAL to authenticate users against Windows Azure Active Directory. I'm getting error codes that are not included in [`AdalError`](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/src/ADAL.PCL/Constants.cs#L58):

- `invalid_grant` *(when the specified user credentials are invalid)*
- `user_password_expired`

Is `AdalError` supposed to contain all possible error codes that can be returned by the Active Directory Authentication API or just a subset?
 
Also, is there a complete list of authentication related error codes elsewhere? I tried to find it, but to no avail.

Thank you!

**Comment by kpanwar** [comment]
AdalError only contains errors represented by the library. any server error would come back as ServiceReturnedError.
