### ISSUE TITLE
Documentation for Controlling ADAL Logging

### ISSUE THREAD

**Issue by smflorentino** [AzureAD/azure-activedirectory-library-for-dotnet#479]
In the readme under "Logs/Desktop Applications" there are 2 different lines of code that control trace output:
`AdalTrace.LegacyTraceSwitch.Level = TraceLevel.Info;`

and a few lines down:
`AdalTrace.TraceSource.Switch.Level = SourceLevels.Information;`

In my .NET 4.5.2 Desktop App, I had to set **both** options above to get my desired trace output when running in Visual Studio. Why are both required? The documentation isn't clear.

**Comment by abhishek58g** [comment]
Visual Studio implements listeners on both LegacyTraceSwitch and TraceSource. Hence you see logs from both in Visual Studio.But you can use AdalTrace.TraceSource in your app and implement a listener for it to get the logs.
