### ISSUE TITLE
Xamarin.iOS - JWT validation failed: IDX10214: Audience validation failed.

### ISSUE THREAD

**Issue by hock2k5** [AzureAD/azure-activedirectory-library-for-dotnet#495]
Looking for guidance getting around this issue.

I have a Xamarin.iOS project using a PCL.  I can authenticate and access the web service just fine and test it through the browser and it works.  On my mobile app I get prompted for credentials, enter in my credentials and successfully get a token back.  I pas the token as 'Bearer' in the authorization header to a simple web service and get the following message on azure using the 'Steaming logs' with application logging enabled.

Additionally when I pass the token into https://jwt.io it says it has an 'Invalid Signature'.

`2016-07-19T14:44:59  PID[11640] Verbose     Received request: GET https://[webapi].azurewebsites.net/api/Test
2016-07-19T14:44:59  PID[11640] Warning     JWT validation failed: IDX10214: Audience validation failed. Audiences: 'https://[webapi].azurewebsites.net'. Did not match:  validationParameters.ValidAudience: '[web api ad client ID]' or validationParameters.ValidAudiences: 'null'.
`

Thank you.

**Comment by kpanwar** [comment]
Tokens are issued by the service and ADAL simply returns them back to the developer. I would suggest that you look if you are expecting a trailing slash '/' or something for your audience.
