### ISSUE TITLE
Could not install ADAL for Xamarin.Forms PCL

### ISSUE THREAD

**Issue by benrbray** [AzureAD/azure-activedirectory-library-for-dotnet#496]
Does the current version of the ADAL package support Xamarin.Forms PCL projects?  When I open up a new Xamarin.Forms PCL project and attempt to install the latest ADAL package (v3.12.0) I get the following unhelpful error:

```
Could not install package 'Microsoft.IdentityModel.Clients.ActiveDirectory 3.12.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

I'm using Visual Studio 2015 with Xamarin.Forms v2.3.0.107.  Is this a bug?

**Comment by kpanwar** [comment]
Actually the error tells you that Profile111 is not supported. This is because WinPhone8.1 is not supported  by ADAL.

**Comment by benrbray** [comment]
Which profiles are supported?  Does the documentation specify this somewhere?

**Comment by kpanwar** [comment]
Profile7

**Comment by benrbray** [comment]
Thanks for the suggestion, I got a bit farther this time but still ran into errors.  Here are the steps I took:

1. Create a new Xamarin PCL project.  Change `<TargetFrameworkProfile>` in the .csproj file corresponding to the PCL to `Profile7`.  Reload project.
2. Install `Microsoft.IdentityModel.Clients.ActiveDirectory` v3.12.0 via NuGet to both the PCL and Xamarin.Android projects.
3. Rebuild solution.

After taking these steps, I get an error about a missing `webauthenticationbroker.xml` file, as below.  This issue is similar to #497.

```
Unexpected error - Please file a bug report at http://bugzilla.xamarin.com. Reason: Could not find a part of the path "c:\users\t-bebray\documents\visual studio 2015\Projects\MissionControlAuth2\MissionControlAuth2\MissionControlAuth2.Droid\obj\Debug\__library_projects__\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform\library_project_imports\res\layout\webauthenticationbroker.xml"	MissionControlAuth2.Droid			
```

Where did I go wrong?  Is there documentation somewhere that explains how to properly install this package?

**Comment by kpanwar** [comment]
I am guessing your system path is exceeding 256 characters at build time. Can you try moving the project to a root folder and see if that works please?

**Comment by benrbray** [comment]
That's... insane.  No more errors.  Thanks for your help, I can't believe that's what the problem was.

**Comment by kpanwar** [comment]
Insane would be one word. :)

**Comment by akkhigan** [comment]
Hi benrbray,

I am unable to find the .csproject in PCL to change the  <TargetFrameworkProfile> to Profile7
Can you please suggest me some steps to edit.

thank you

**Comment by benrbray** [comment]
(Luckily) I no longer have to deal with Xamarin so I'm not familiar with the latest version.  As far as I know there should be a .csproj file somewhere in your solution or at least some kind of config file.  Good luck!
