### ISSUE TITLE
Missing Resources after installing ADAL package with Xamarin.Forms

### ISSUE THREAD

**Issue by benrbray** [AzureAD/azure-activedirectory-library-for-dotnet#497]
I am developing a Xamarin.Forms PCL mobile application and need access to an internal API that requires authentication via Azure.  My coworker gave me a code snippet that works in a console application, and I am attempting to adapt it for my mobile application.

I am able to successfully add the [ADAL package](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.5.207081303-alpha) to the PCL.  However, authentication requires that I pass along a set of `PlatformParameters` for each platform-specific version.  When I attempt to add the ADAL package to the Xamarin.Android project, I get the following errors in my `Resource.Designer.cs` file:

```
ERROR: 'Resource.Id' does not contain a definition for 'agentWebView'
ERROR: 'Resource.Layout' does not contain a definition for 'WebAuthenticationBroker'
````

The relevant (auto-generated) lines of code in `Resource.Designer.cs` are:

````
global::Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory.Resource.Id.agentWebView = global::MissionControlAuth.Droid.Resource.Id.agentWebView;	        global::Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory.Resource.Layout.WebAuthenticationBroker = global::MissionControlAuth.Droid.Resource.Layout.WebAuthenticationBroker;
````

The names of these missing resources suggest that I need to point the ADAL package to a webview that can be used to display a login page to the user.  Unfortunately, I haven't been able to find any mention of this on StackOverflow or on the Xamarin forums.  How can I correctly set up the ADAL package for my Xamarin.Forms PCL?

**Platform / Library Versions**

 - .NET Framework 4.5
 - Xamarin.Forms v2.0.0.6482 targeting Xamarin.Android and UWP
 - Visual Studio 2015
 - Microsoft.IdentityModel.Clients.ActiveDirectory v3.5.207081303-alpha ([relevant answer](https://forums.xamarin.com/discussion/56749/cannot-add-active-directory-authentication-library-package-to-xamarin-forms-and-droid-application))
     - *Alternatively*, Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory v4.0.209160138-alpha ([relevant answer](http://stackoverflow.com/questions/33028388/correct-adal-package-for-b2c-xamarin-pcl-project))

**Steps to Reproduce**

1. Create a new Xamarin.Forms PCL project.
2. Choose one of the ADAL package versions above and add it to the PCL.
3. Add the same package version to the Xamarin.Android project.  The library will install successfully, but there will be missing resource errors in the "Error List" tab in Visual Studio.

**Comment by kpanwar** [comment]
Experimental library is not supported. consider using https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

**Comment by benrbray** [comment]
Like I said in my original post, I've also tried the non-experimental ADAL v3.5.207081303-alpha version, and the same errors occur.  From the MSAL documentation, it looks like there is no way to authenticate against an existing Azure AD, an instead a new project must be configured from an MSAL-specific dashboard.

The errors I mentioned are also a bit cryptic--why did the packages (both experimental and not) install correctly if they aren't supported?

**Comment by jennyf19** [comment]
@benrbray - did you ever get this figured out?

**Comment by benrbray** [comment]
Short-term, I think I ended up doing something hacky that I don't quite remember involving multiple projects and older versions of certain packages.  It still never quite worked though.  We actually ended up abandoning Xamarin because at the time, it wasn't mature enough for our needs.  Good luck!
