### ISSUE TITLE
AcquireTokenAsync fails for UserPasswordCredential

### ISSUE THREAD

**Issue by RipalV** [AzureAD/azure-activedirectory-library-for-dotnet#506]
For automated tests, I am trying to issue token from AD using user authentication.

Below is the code snippet used to issue token, it is using UserPasswordCredentials to authenticate:

`var authContext = new AuthenticationContext("https://login.microsoftonline.com/mytestdomain.com");`
`var resourceAppClientId = "E70FFF8D-16A9-4436-A16A-C7AD6A54DE32";`
`var clientId = "A0F33560-F4F5-42BB-868F-16AB04434A68";`
`var token = authContext.AcquireTokenAsync(resourceAppClientId, clientId, new UserPasswordCredential("admin@mytestdomain.com", "Password")).Result;`

Call is failing with exception, suggesting to specify client_secret but there is no methods that allows to specify ClientCredentials and UserCredentials both: 

`Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'.
`

Am I missing something here? Code is inspired from below:
http://www.cloudidentity.com/blog/2014/07/08/using-adal-net-to-authenticate-users-via-usernamepassword/

http://stackoverflow.com/questions/37465949/adal-net-v3-does-not-support-acquiretoken-with-usercredential

I have application added to the Azure AD and is working fine and allowing authentication through implicit flow, but failing for the sample code above.

**Comment by kpanwar** [comment]
You are using confidential client (web API) to authenticate the user. You need to create a native application to not get prompted for client secret.

**Comment by RipalV** [comment]
Thanks a lot for your quick response.
As you pointed out, it was failing as I was using WebApi app. registering a separate native app for automation tests worked.
I guess proper error message from AD might have helped.
