### ISSUE TITLE
Make exceptions serializable

### ISSUE THREAD

**Issue by older** [AzureAD/azure-activedirectory-library-for-dotnet#507]
Is there any reason why AdalServiceException is not serializable? I'm getting the following exception when I'm trying to use ADAL in BizTalk application:

> Inner exception: Type 'Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException' in Assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.1.846, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.

And according to Microsoft's own [Design Guidelines for Developing Class Libraries](https://msdn.microsoft.com/en-us/library/ms229064%28v=vs.100%29.aspx) exceptions must be serializable:

> Do make exceptions serializable. An exception must be serializable to work correctly across application domain and remoting boundaries.

**Comment by kpanwar** [comment]
Portable has no support for Serializable attribute.

**Comment by older** [comment]
Is there any possibility to add non-portable desktop version to NuGet?
Otherwise it makes it impossible to use even in the latest BizTalk 2016 which was released just couple of weeks ago.

**Comment by kpanwar** [comment]
Sorry, we won't be able to provide that.
