### ISSUE TITLE
AcquireTokenAsync with UserCredentials gets unhandled exception HttpRequestWrapperException

### ISSUE THREAD

**Issue by egoebel** [AzureAD/azure-activedirectory-library-for-dotnet#510]
This only seems to happen if the password for the user is incorrect.  The error is unhandled and causes a crash: An unhandled exception of type 'Microsoft.IdentityModel.Clients.ActiveDirectory.HttpRequestWrapperException' occurred in mscorlib.dll

This works correctly in version 2.*

**Comment by kpanwar** [comment]
Is this a federated or a managed user?

**Comment by egoebel** [comment]
It was a federated user.

**Comment by kpanwar** [comment]
fixed in 3.13.4
