### ISSUE TITLE
TokenCache not working after last update

### ISSUE THREAD

**Issue by ravensorb** [AzureAD/azure-activedirectory-library-for-dotnet#512]
Before the last update, the TokenCache was automatically saved/loaded for all the platforms -- ever since the last update, this stopped working and now the TokenCache is always empty when the application first starts up.  Did something change in the design or is this a bug?

I am currently using 3.13.1 in Visual Studio 2015 with Update 3 and running in my app on Windows UWP, Android, and IOS.

**Comment by kpanwar** [comment]
Can you confirm if your issue is not related to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/486

**Comment by ravensorb** [comment]
Hmm, good question, here is my current code for my UWP 

```
var authContext = new AuthenticationContext(authority);
if (authContext.TokenCache.ReadItems().Any())
	authContext = new AuthenticationContext(authContext.TokenCache.ReadItems().First().Authority);
						
var uri = new Uri(returnUri);
var platformParams = new PlatformParameters(PromptBehavior.Auto, false);

var authResult = await authContext.AcquireTokenAsync(resource, clientId, uri, platformParams).ConfigureAwait(false);
```

**Comment by kpanwar** [comment]
Code looks fine. What is the version of UWP framework?

**Comment by ravensorb** [comment]
Building against: 10.0; Build 10586
App Running Env: Windows Mobile 10.0.10586.0

**Comment by kpanwar** [comment]
I meant universal platform framework version in your project references.

**Comment by ravensorb** [comment]
Ahh, 5.2.2

**Comment by kpanwar** [comment]
This is a known issue as mentioned before.

**Comment by ravensorb** [comment]
I am not getting the exception though -- wouldn't that indicate it is a separate issue?

**Comment by kpanwar** [comment]
can you capture ADAL logs from your app? ADAL writes to logcat by default. you could also provide a callback via https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/src/ADAL.PCL/IAdalLogCallback.cs
