### ISSUE TITLE
Acquire multi-resource token

### ISSUE THREAD

**Issue by rogerthealien** [AzureAD/azure-activedirectory-library-for-dotnet#519]
How do I acquire a multi-resource token in version 3+?

Tried calling ```AcquireTokenSilentAsync``` for ```otherResourceId```, right after acquiring token for ```graphResourceId```:

```
result = await authContext.AcquireTokenAsync(graphResourceId, clientCred, userAssertion);
accessToken = result.AccessToken;

AuthenticationResult otherResult = await authContext.AcquireTokenSilentAsync(otherResourceId, clientCred, new UserIdentifier(userName, UserIdentifierType.RequiredDisplayableId));
```
<del>
but it fails with:

Failed to refresh access token. AADSTS90014: The request body must contain the following parameter: 
'client_secret or client_assertion'.

Is this still possible? I can see #446 concluded that using an older version of the library would be a solution.
</del>

The ```AcquireTokenSilentAsync``` call seems to success, but is missing ```IsMultipleResourceRefreshToken``` flag, as referenced <a href="http://www.cloudidentity.com/blog/2013/10/14/adal-windows-azure-ad-and-multi-resource-refresh-tokens/">here</a>. Is this flag not visible anymore because the refresh token is hidden in versions 3+? Might be useful to know the AuthenticationResult can access multiple resources.

Also, can this token be cached and used later (in a ```new AuthenticationContext```), to acquire tokens for multiple resources?

I'm going to leave this here in case anyone is reading the same out-dated blog posts / documentation as I am.

**Comment by kpanwar** [comment]
What authority did you pass to your API?
