### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by netogallo** [AzureAD/azure-activedirectory-library-for-dotnet#525]
I have observed the following three error messages returned by ADAL:

1) Network request '' failed. Status=InternalServerError, ReasonPhrase='Internal Server Error'. Runtime Error

2) Network request '' failed. Status=Ok, ReasonPhrase='OK'. Sign in to your account

3) Network request '' failed. Status=InternalServerError, ReasonPhrase='Internal Server Error'. Category=InternalServerError, Message=Cannot find tenant Url, Code=500010, ErrorId=SharePointUnauthorizedError

4) Network request '' failed. Status=ServiceUnavailable, ReasonPhrase='Service Unavailable'. Outlook Web App

Sorry for posting it here, but I have tried really hard to figure out what is wrong or whom to ask for more details but haven't been  successful. I would like being able to inform the user:

1) What went wrong (in a language he understands)
2) What actions can he take (if any)
3) Does it make sense to retry authentication under any of these errors? I mean a "InternalServerError" response could succeed if retried.

Thank you and feel free to ask me more questions if necessary.

Ps.

I am using the package: "Microsoft.IdentityModel.Clients.ActiveDirectory": "2.26.305102204"

**Comment by kpanwar** [comment]
I don't think those messages are returned by ADAL. ADAL or AAD don't return messages that are specific to sharepoint.
