### ISSUE TITLE
TokenCache Serialization fails UWP

### ISSUE THREAD

**Issue by jacob-ebey** [AzureAD/azure-activedirectory-library-for-dotnet#526]
After upgrading from 3.10.305231913 to 3.13.4 and Microsoft.NETCore.UniversalWindowsPlatform from 5.1.0 to 5.2.2, TokenCache.Deserialize fails.

I believe I saw this documented somewhere already so feel free to delete if a duplicate.

**Comment by kpanwar** [comment]
this is a known issue with NetCore.

**Comment by jacob-ebey** [comment]
Thank you, I was able to find the filed issue.
