### ISSUE TITLE
ADALTrace removed; diagnostics instructions need updating?

### ISSUE THREAD

**Issue by ScottArbeit** [AzureAD/azure-activedirectory-library-for-dotnet#527]
The [README.md](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/README.md) file refers to the `ADALTrace` static class as a way to configure diagnostic logging for ADAL.NET. That class seems to have been removed now.

Is there a new method for enabling diagnostic logging that we can update the documentation for?

Thanks!

**Comment by JosephEarl** [comment]
We had the same problem and found you can use `LoggerCallbackHandler.Callback` and set it to a custom implementation of `IAdalLogCallback` - https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/src/ADAL.PCL/IAdalLogCallback.cs.

**Comment by ssaroiu** [comment]
JosephEarl's solution worked for me for ADAL version 3.13.5. Thanks!

**Comment by hamish-tushar** [comment]
Can you tell me how to enable logging and diagnostics for ADAL?

**Comment by pschaeflein** [comment]
Sample implementation at https://www.schaeflein.net/adal-v3-diagnostic-logging/

**Comment by hamish-tushar** [comment]
Thank you so much
