### ISSUE TITLE
iOS: Allow setting preferred UIStatusBarStyle

### ISSUE THREAD

**Issue by MKuckert** [AzureAD/azure-activedirectory-library-for-dotnet#528]
Since iOS 7 each ViewController may override [preferredStatusBarStyle](https://developer.apple.com/reference/uikit/uiviewcontroller/1621416-preferredstatusbarstyle) to return one of the [UIStatusBarStyle](https://developer.apple.com/reference/uikit/uistatusbarstyle) values. This is required when using [UIViewControllerBasedStatusBarAppearance](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW29).

One may use UIStatusBarStyleDefault to display a dark status bar on light backgrounds and UIStatusBarStyleLightContent to display a light status bar on dark backgrounds.

The ADAL does not currently implement preferredStatusBarStyle resulting in a dark status bar on a dark navigation bar:
![simulator screen shot 01 09 2016 09 03 30](https://cloud.githubusercontent.com/assets/426586/18158369/3101d432-7023-11e6-8f35-0a13dd80ca12.png)

The `PlatformParameters` class in the iOS platform project should be extended with a new property `UIStatusBarStyle PreferredStatusBarStyle`. The `WebUI` should transfer this value to the created `AuthenticationAgentUINavigationController`. The later one should then implement `preferredStatusBarStyle` and return the passed value.

**Comment by kpanwar** [comment]
fixed in https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.13.7
