### ISSUE TITLE
iOS: ViewController passed with PlatformParameters is leaked

### ISSUE THREAD

**Issue by MKuckert** [AzureAD/azure-activedirectory-library-for-dotnet#534]
The ViewController passed into `AcquireTokenAsync` is leaked by the library and never collected by the garbage collector.
The `AcquireTokenInteractiveHandler` class assigns the given parameters instance to `PlatformPlugin.BrokerHelper.PlatformParameters`, which in turn is never null-ed. This leads to a hard reference to the given ViewController.

**Comment by kpanwar** [comment]
I will make the view controller assignment a weak reference

**Comment by kpanwar** [comment]
@MKuckert - I have been super busy. Feel free to send me a PR and I will review, merge and release it.

**Comment by kpanwar** [comment]
We need to update processBrokerResponse() to set platformParameters = null
