### ISSUE TITLE
NuGet: fwlink 258232 links to V2.x

### ISSUE THREAD

**Issue by alexangas** [AzureAD/azure-activedirectory-library-for-dotnet#536]
The "Project URL" link in the NuGet package links to a page discussing V2.x ("Important: The API topics in this reference apply to ADAL version 2.19.208020213 for .NET Desktop)".

It should probably link to https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-libraries/.

**Comment by jmprieur** [comment]
This is blocked (owners of the fwlink have left the company :()

**Comment by jmprieur** [comment]
Let's create a new link.
