### ISSUE TITLE
UWP fails when handling WebAuthenticationStatus.ErrorHttp

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/azure-activedirectory-library-for-dotnet#539]
The problem originates in WebUI.ProcessAuthorizationResult (from src\ADAL.PCL.WinRT\WebUI.cs). In the event that the system returns WebAuthenticationStatus.ErrorHttp, it creates an AuthorizationResult with the returned HTTP status code in the returnedUriInput field.

    case WebAuthenticationStatus.ErrorHttp:
        result = new AuthorizationResult(AuthorizationStatus.ErrorHttp, webAuthenticationResult.ResponseErrorDetail.ToString(CultureInfo.CurrentCulture));

However, the AuthorizationResult c’tor (in src\ADAL.PCL\AuthorizationResult.cs) only has special handling for the UserCancel and UnknownError result statuses. So, ErrorHttp results are passed off to the ParseAuthorizeResponse method which tries parsing the returnedUriInput as a Uri and throws. This exception isn’t being wrapped up in an AdalException, so it’s not processed by our auth code and eventually crashes the app.

**Comment by abhishek58g** [comment]
@kpanwar Can we close this issue ?

**Comment by kpanwar** [comment]
merged. Pending release.

**Comment by kpanwar** [comment]
fixed in https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.13.7
