### ISSUE TITLE
Issue when accessing Office 365 social api with ADAL

### ISSUE THREAD

**Issue by devlanfear** [AzureAD/azure-activedirectory-library-for-dotnet#543]
We are trying to access Office 365 Social API with ADAL library (Microsoft.IdentityModel.Clients.ActiveDirectory - 3.13.1.846, Microsoft.IdentityModel.Clients.ActiveDirectory.Platform-3.13.1.846) - 
https://test.sharepoint.com/_api/social.feed/actor(item=@v)/feed?@v=%27https://test.sharepoint.com/sites/Demo/newsfeed.aspx%27

We get HTTP response with StatusCode = 401:
x-ms-diagnostics: 3000003;reason="Invalid audience Uri 'https://test.sharepoint.com/'.";category="invalid_client"

Response:
{"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown."} 

Azure Active Directory app has permission for Office 365: Have full control of all site collections.

Can you please provide any details for this issue?

**Comment by kpanwar** [comment]
This is not an ADAL issue. You should file the issue in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
