### ISSUE TITLE
Exception in ADAL webview on EvoSTS consent screen

### ISSUE THREAD

**Issue by abhishek58g** [AzureAD/azure-activedirectory-library-for-dotnet#544]
The javascript code is getting accounted as non https url in ADAL.

**Comment by kpanwar** [comment]
fixed via https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/546

**Comment by kpanwar** [comment]
fixed in https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.13.7
