### ISSUE TITLE
Support for setting custom WebProxy with ADAL

### ISSUE THREAD

**Issue by venknar** [AzureAD/azure-activedirectory-library-for-dotnet#552]
We are using the ADAL client library to fetch token from AAD.
Since the ADAL client library is making a network call to the AAD service for fetching the AAD token, I wish to know how to configure a web proxy ?

The code that we use to fetch the AAD token is as follows:

var authenticationContext = new AuthenticationContext(authority);
var clientAssertion = new ClientAssertionCertificate(AadAccessConfiguration.AadConfiguration.ClientId, AadAccessConfiguration.AadConfiguration.Certificate);
var authenticationResult = authenticationContext.AcquireTokenAsync(resource, clientAssertion).Result;

Could not find any way to configure the web proxy explicitly on the ADAL.

We are using ADAL with the dotnet core release. In Dotnetcore we need to use the HttpClient and there is no way to use a global web proxy.

In the context of dotnetcore we are running on dotnet environment that it is minimal. There would be no IE/Edge browser even installed. We would need a way to set an IWebProxy(system.net) on ADAL.

**Comment by balajimadgundi** [comment]
Hello,
we also have the same requirement to use custom web-proxy with ADAL. 
Code used to fetch AAD token is same as below:

var uri = new Uri(_authenticationEndpoint, endpoint.Connection);
var _context = new AuthenticationContext(uri.ToString(), false);
result = _context.AcquireToken(_graphUrl, credentials);

Do we have any other way to configure web proxy on ADAL?

If this is being already taken up as an enhancement do we have the ETA for this?

**Comment by VaanPan** [comment]
I have confirmed with ADAL development team.
Below is the reply.

1.	Currently ADAL for .NET doesn’t support WebProxy configuration.
2.	Please configure proxy at the system level. Httpclient used by Adal should be able to use it. 
3.	Production team has planned to add this function in future version, but currently they don’t have estimation time.

**Comment by blairmc-ms** [comment]
ADAL.Net does now consume the DefaultWebProxy if set, but this has no effect on .net core because .Net core does not support IWebProxy. See http://stackoverflow.com/questions/37571215/set-a-custom-webproxy-for-a-single-http-request-in-net-core-uwp for more details
