### ISSUE TITLE
SHA 256 signed assembly

### ISSUE THREAD

**Issue by crmann1** [AzureAD/azure-activedirectory-library-for-dotnet#561]
Is ADAL planning on updating the signing of the shipping assemblies from SHA1 to SHA256?  

For the application I am working on we are trying to get as many of the dlls we depend on signed with SHA256 as possible.

**Comment by jmprieur** [comment]
compliance

**Comment by blairmc-ms** [comment]
We are working on this for the next release.

**Comment by jmprieur** [comment]
ADAL v3.14 is SHA-256 signed
