### ISSUE TITLE
Overcoming ADAL exception in VSTests in build service

### ISSUE THREAD

**Issue by rebro-msft** [AzureAD/azure-activedirectory-library-for-dotnet#562]
We are experiencing the following exception on our Rolling Build Machine (RBM) during the test run portion of our build service:
```
The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext' threw an exception.
[inner exception]
Type 'System.Diagnostics.TraceEventCache' in assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.
```
The exception does not occur on our local dev boxes, nor does it occur when we run the tests manually on the RBM (ie. open VS, and run tests via Test Explorer).  Our build definition is using the older XAML-based format.  We recognize this is an old format and that we should upgrade to the latest version, but that migration may take several months and we would rather just overcome this exception than rewrite our entire build definition.

We know the exact line of code the exception is coming from:  the AuthenticationContext initializer.  However, the exception is being masked by the above de/serialization exception, so we can’t even see the actual exception to resolve it.  I am working with .NET help folks to understand the TraceEventCache exception now, but perhaps you could help me understand what might be causing the underlying exception?  

Our KeyVaultHelper code that is throwing the exception:
```csharp
public sealed class KeyVaultHelper
    {
        private static KeyVaultClient _keyVaultClient;
        private static ClientAssertionCertificate _clientCredential;
 
        public static void Initialize(string clientId, string clientAuthCertThumbprint)
        { 
            X509Certificate2 clientCert = FindCertificateByThumbprint(clientAuthCertThumbprint);
           _clientCredential = new ClientAssertionCertificate(clientId, clientCert);
            _keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(GetTokenAsync));
        }
 
        public static string GetSecretValue(string url)
        { 
            Secret secret = _keyVaultClient.GetSecretAsync(url).GetAwaiter().GetResult();
            return secret.Value;
        }
 
        private static async Task<string> GetTokenAsync(string authority, string resource,
            string scope)
        {
            try
            {
                var context = new AuthenticationContext(authority, TokenCache.DefaultShared);
                var result = await context.AcquireTokenAsync(resource, _clientCredential).ConfigureAwait(false);
                return result.AccessToken;
            }
            catch (Exception e)
            {
                Assert.Fail(…);   
            }
            return null;
        }
        …
   }
```
The specific line is `new AuthenticationContext(authority, TokenCache.DefaultShared);`

We're using Microsoft.IdentityModel.Clients.ActiveDirectory 2.19.208020213 .

Any insights or thoughts would be greatly appreciated.

Thanks,
Rebecca

**Comment by kpanwar** [comment]
As discussed previously, you have to work with .NET and VSO team for clarity on this. I close this issue for now, until there is clear evidence of ADAL misbehavior. We can open it again if needed and will make the necessary fixes.

**Comment by rebro-msft** [comment]
Our email thread also said to try contacting ADAL (from Lee), this was that follow-up.  Alright, I'll investigate with .NET folks first.
