### ISSUE TITLE
App referencing 3.13.7 fails to build on dotnet core 1.1

### ISSUE THREAD

**Issue by eamodio** [AzureAD/azure-activedirectory-library-for-dotnet#563]
```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

I have a couple web apps that I've just upgraded to dotnet core 1.1 and using 3.13.7 causes them to fail to build, while`3.13.6` works fine
```
error NU1001: The dependency NetStandard.Library >= 1.6.0 could not be resolved.
```

**Comment by timmydo** [comment]
seems like it works if you change it to "NETStandard" in the project json lock file?

**Comment by kpanwar** [comment]
@eamodio - does @timmydo's suggestion works for you?

**Comment by eamodio** [comment]
@kpanwar Not sure, but the lock files are regenerated on a restore. So even if it worked it wouldn't be a good solution. For now I have just version locked it to 3.13.6 which works.

**Comment by jraadt** [comment]
Same here.  I had to revert back to 3.13.6 for it to work.

**Comment by TheSamsterZA** [comment]
@kpanwar I was just bitten by this and @timmydo's fix got me past the error above. Please expedite a 3.13.8 release that fixes the .nuspec file.

**Comment by TheSamsterZA** [comment]
I am now getting a different error:

```
The type or namespace name 'ClientAssertionCertificate' could not be found (are you missing a using directive or an assembly reference?)
```

Which has left me bewildered since I can clearly see that I am referencing the assembly:

![image](https://cloud.githubusercontent.com/assets/4981594/20742188/f5eac22c-b722-11e6-9929-0493977c9c8c.png)

`Microsoft Visual Studio  Professional 2015 Update 3, version 14.0.25431.01`

`Microsoft.IdentityModel.Clients.ActiveDirectory, version 3.13.7`

Runtime:
```
dotnet

Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

Tooling:
```
dotnet --version
1.0.0-preview2-1-003177
```

Why is this happening?

**Comment by kpanwar** [comment]
Clientassertioncertificate class is not yet supported for .net core.

**Comment by TheSamsterZA** [comment]
I've switched from

```
Microsoft.IdentityModel.Clients.ActiveDirectory, version 3.13.7
```

to

```
Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory, version 4.0.209160138-alpha
```

and had to change my code from:

```
var authenticationContext = new AuthenticationContext(authUri, false, tokenCache);
var authenticationResult = await authenticationContext.AcquireTokenAsync(
	resource: resourceUrl,
	clientCertificate: clientAssertionCertificate);
```

to

```
var authenticationContext = new AuthenticationContext(authUri, false, tokenCache);
var authenticationResult = await authenticationContext.AcquireTokenAsync(
	scope: new[] { AppSettings.AdminClientId },
	additionalScope: new [] {""},
	clientId: AppSettings.AdminClientId,
	redirectUri: new Uri(AppSettings.AdminRedirectUri),
	parameters: new PlatformParameters());
```

I now get:

```
NotImplementedException: The method or operation is not implemented.
Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory.WebUIFactory.CreateAuthenticationDialog(IPlatformParameters parameters)
```

This code is used to get the AppToken for the first time.

I feel like I am missing something that should be obvious. Please help.

**Comment by kpanwar** [comment]
Pleas don't use v4. It was an experimental release and incompatible with AAD v1

**Comment by TheSamsterZA** [comment]
@kpanwar So where does this leave me? Should I not target .NET Core since there seems to be many issues with getting ADAL to work on it?

If you could point me in the right direction (advice, docs, tutorials, sample code) that would be much appreciated.

**Comment by kpanwar** [comment]
I will make the typo fix tomorrow

**Comment by kpanwar** [comment]
3.13.8 has been released
