### ISSUE TITLE
ADAL missing System.Runtime.Seralization.Json dependency on NetCoreApp

### ISSUE THREAD

**Issue by onovotny** [AzureAD/azure-activedirectory-library-for-dotnet#569]
The .NET Core dependencies aren't getting `System.Runtime.Seralization.Json` included. You have to manually add that additional dependency or you'll get a typeinitialization exception.

Right now ADAL is only pulling in `NETStandard.Library` but that doesn't include the aforementioned dependency within that meta-package.

**Comment by kpanwar** [comment]
I am pushing out a fix today to address this and another issue.

**Comment by kpanwar** [comment]
@onovotny - I am updating the dependency to 
`
<group targetFramework="netstandard1.4">
	<dependency id="NETStandard.Library" version="1.6" />
        <dependency id="System.Runtime.Serialization.Json" version="4.0.2" />
 	<dependency id="System.Runtime.Serialization.Primitives" version="4.1.1" />
 </group>
`

**Comment by onovotny** [comment]
I don't think you need to have the primitives on explicitly? That should be transitively brought in via the `System.Runtime.Serialization.Json`

**Comment by onovotny** [comment]
FWIW, version 4.3 is the latest nuget package, and that goes along with NETStandard.Library 1.6.1.

**Comment by kpanwar** [comment]
@onovotny - I was asked by Fowler and Eric from NET team to add it. 3.13.8 has been released
