### ISSUE TITLE
Remove Console.WriteLine from iOS Logger implementation

### ISSUE THREAD

**Issue by MKuckert** [AzureAD/azure-activedirectory-library-for-dotnet#571]
... or at least make it configurable. I'm using `LoggerCallbackHandler.Callback` to register my own implementation (delegating to `NLog` n stuff) and I don't want ADAL to spam my console with log messages like
```
[...] - AcquireTokenHandlerBase.cs: === Token Acquisition started:
	Authority: https://logon.nobilis-group.com/adfs/
	Resource: http://nobilis-esales.localhost
	ClientId: 3032b2a0-912e-420c-ad7e-26cce741cf53
	CacheType: null
	Authentication Target: User
```

The current implementation of `Microsoft.IdentityModel.Clients.ActiveDirectory.Logger` in the iOS project directly leverages `Console.WriteLine` to write directly to the console. What is great as a default but pretty annoying in an extended usage. More badly `PlatformPlugin` and `LoggerBase` are internal and I can't directly set the `PlatformPlugin.Logger` property to anything not spamming the Console.

Is there any possibility to expand the logging interfaces of the implementation?

**Comment by abhishek58g** [comment]
The fix is under review https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/578
