### ISSUE TITLE
Code should expect RSACng returned from GetAsymmetricAlgorithm

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-library-for-dotnet#572]
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/src/ADAL.PCL.Desktop/CryptographyHelper.cs#L62

Changes to .Net framework may result in RSACng being returned from GetAsymmetricAlgorithm. This code should be modified to expect this.

**Comment by kpanwar** [comment]
GetAsymmetricAlgorithm()  can return RSACng object instead of RSACryptoServiceProvider in .NET 4.6 and above. Code should be able to handle that case.

**Comment by kpanwar** [comment]
We target 4.5 and we cannot support RSACng as this class only exists in 4.6.1
