### ISSUE TITLE
Question: Is this a managed equivalent of the native Adal.dll?

### ISSUE THREAD

**Issue by saurabh500** [AzureAD/azure-activedirectory-library-for-dotnet#579]
I have a few questions about this library. 

Is this repo an equivalent of the native Adal.dll that ships on Windows? 
System.Data.SqlClient in the .Net Core repo has customer ask to support FedAuth using AAD. This feature is supported on .Net Framework on Windows and uses the APIs exposed by ADAL.dll 

Can this repo be considered a managed version of adal.dll ? 

Is this repo tested on *Nix based platforms as well ?

**Comment by kpanwar** [comment]
It cannot be considered manged version of native ADAL because native version has quite different API surface and handles several scenarios like caching differently.
We support .Net Core in ADAL v3 except client certificate flow.
