### ISSUE TITLE
PlatformParameters null reference exception on iOS

### ISSUE THREAD

**Issue by sccrgoalie1** [AzureAD/azure-activedirectory-library-for-dotnet#580]
Hello,

In the latest version 3.13.8.999 on iOS I am getting an error when call 
`AquireTokenAsync(string resourceId, ClientCredential clientCredentials)`  
I downloaded the source and discovered the root of the problem is in the BrokerHelper the CanInvokeBroker getter doesn't check for a null PlatformParameters.  If I add a null check then the authentication flow works as designed.

**Comment by kpanwar** [comment]
You are attempting to use confidential client flow in a native app. This is incorrect usage of the API.
