### ISSUE TITLE
ADAL Library not able to display Login page on Google Pixel (android 7.1.1)

### ISSUE THREAD

**Issue by abhiongithub** [AzureAD/azure-activedirectory-library-for-dotnet#581]
Using this version of ADAL in Xamarin Android project
**Microsoft.IdentityModel.Clients.ActiveDirectory  version="3.13.8" targetFramework="monoandroid70"** 

Same build is working fine on Android 6.0 and even 5.1.

While in Android 7.1.1 it generated following log after opening up Sing In Screen as blank screen

here are logs from output window

[NetworkSecurityConfig] No Network Security Config specified, using platform default
[cr_BindingManager] Cannot call determinedVisibility() - never saw a connection for the pid: 29849
[chromium] 
[INFO:CONSOLE(128)] "**Uncaught ReferenceError: $ is not defined**", source: https://login.microsoftonline.com/microsoft.onmicrosoft.com/oauth2/authorize?resource=[my www project website domain ]%2F&client_id=[myprojectclientid]&response_type=code&haschrome=1&redirect_uri=[my project redirect uri]&client-request-id=985a8585-e62d-4dc8-90d3-629e3911e738&prompt=login&x-client-SKU=PCL.Android&x-client-Ver=3.13.8.999 (128)

**looks like ADAL login page is using jquery and WebView is nto able to resolve $ symbol of jquery.**

**Comment by kpanwar** [comment]
ADAL simply hosts AAD's sign in page inside the webview. The issue is on AAD server side. I will communicate the same to them.

**Comment by stefffdev** [comment]
FYI, I encountered the same Problem und Android 6.0.1 after a Firmware Update from Samsung.

I could solve the problem by updating the "Android System WebView" app and the Chrome app from the Play Store. According to the changelog from the System WebView app there where some "bugfixes" so I think that was the cause of the problem.
