### ISSUE TITLE
Caching with Redis not working

### ISSUE THREAD

**Issue by hamish-tushar** [AzureAD/azure-activedirectory-library-for-dotnet#584]
I am trying to make use of ADAL in a web application and caching via REDIS. The problem is that in AfterAccessNotification I always get hasStateChanged true even though in BeforeAccessNotification I Deserialize the byte[] from redis in to the ADAL cache. So every time I want access token it calls state changed and I need to serialize and store back in redis. Basically there is a cache miss and I get no advantage from ADAL.

The code is pretty minimal.
void AfterAccessNotification(TokenCacheNotificationArgs args)
{
// if the access operation resulted in a cache update
if (HasStateChanged)
{
var cachedBits = Serialize();
cache.Set(string.Format("key_{0}", userEmail), cachedBits, new TimeSpan(1, 0, 0));
HasStateChanged = false;
}
}

And
void BeforeAccessNotification(TokenCacheNotificationArgs args)
{
var cachedBits= cache.Get<byte[]>(
string.Format("key_{0}", userEmail);
Deserialize(cachedBits);
}

Can someone please let me know if there is something very important missing in my code.

**Comment by kpanwar** [comment]
I think cache miss is an orthogonal issue and I would like to see how you are calling the API to acquire tokens.

**Comment by hamish-tushar** [comment]
Thanks for having a look at this.

This is my function to call GetToken async.

public async Task<string> GetToken(string email, string userObjectId, string resourceId)
        {
            var clientCredential = new ClientCredential(AppSettings.O365ClientId, AppSettings.O365ClientSecret);
            var userIdentifier = new UserIdentifier(userObjectId, UserIdentifierType.UniqueId);

            var authContext = new AuthenticationContext(AppSettings.Authority, TokenCacheFactory.Get(email));
             var result = await authContext.AcquireTokenSilentAsync(resourceId, clientCredential, userIdentifier);
            return result.AccessToken;
        }

And the code to access it is
var accessToken = await o365Service.GetToken(email, userObjectId,         AppSettings.O365TokenResource);


The cache miss i mentioned above is the fact that every time I call the API to acquire token, I get a call to BeforeAccessNotification() and then after reading the bytes from REDIS Cache once is deserialize i always get a call to AfterAccessNotification with hasStateChanged. After reading the documentation, what i understood was hasStateChanged should be false if tokens are valid between 2 calls to get access tokens.

**Comment by kpanwar** [comment]
What is the value for authority?

**Comment by hamish-tushar** [comment]
https://login.windows.net/common/

**Comment by kpanwar** [comment]
Once an authenticationresult is acquired you must create authenticationcontext again with tenant specific authority like https://login.windows.net/<tenant-id>.
Tenant id is a part of authenticationresult. See http://www.cloudidentity.com/blog/2014/08/26/the-common-endpoint-walks-like-a-tenant-talks-like-a-tenant-but-is-not-a-tenant/ for details.

**Comment by hamish-tushar** [comment]
Thank you so much. It works as expected . Appreciate the help.
Should the tenantId be persisted once the accessToken is received from the AcquireTokenByAuthorizationCodeAsync.(Oauth2.0) . Or the claim principal would always have it in the request and we can use that.
context.AuthenticationTicket.Identity.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;
