### ISSUE TITLE
Impersonation not working with acquiretokenasync

### ISSUE THREAD

**Issue by namratavirk** [AzureAD/azure-activedirectory-library-for-dotnet#585]
I have a windows authenticated website. I am using the below code to get the access token.
I am trying to pass the impersonated user's credentials for acquireasync token but it is still picking up the application pool account. 

Note-I saw the  code of ADAL client and found that it is using httpclient is using default credentials to make  request for windows integrated authentication.
I'd like to pass the impersonated user credential for http client._

Code:
  try
            {
                var x = ((WindowsIdentity)System.Threading.Thread.CurrentPrincipal.Identity);
                WindowsImpersonationContext ctx = x.Impersonate();
                var userCredential = new UserCredential();
                result = authContext.AcquireTokenAsync("http://somesite.azurewebsites.net/", "some-guid", userCredential).Result;
                ctx.Undo();
                return result.AccessToken;
            }

**Comment by kpanwar** [comment]
Using default credentials would result in using user's identity if not impersonated. See this thread with the exact same issue. http://stackoverflow.com/questions/12212116/how-to-get-httpclient-to-pass-credentials-along-with-the-request
