### ISSUE TITLE
ADAL should ignore validateAuthority parameter if the underlying identity system does not support it like ADFS

### ISSUE THREAD

**Issue by mtandon80** [AzureAD/azure-activedirectory-library-for-dotnet#586]
This is one hindrance for same codebase which uses ADAL to get token from AAD or ADFS. Both support Open Id Connect and user has to pass ValidateAuthority true or false based on identitySystem type. Its supposed to be true for AAD and false for ADFS. 

ADAL already able to determine that in use identitySystem is AAD or not - In fact it even know if its ADFS. So it can always ignore validateAuthority in this case. So users of ADAL can have same code irrespective of check weather identity system is AAD or ADFS.

**Comment by kpanwar** [comment]
This is a security issue because in the future ADFS would be capable of doing authority validation and then the applications could be left with weaker security choice made by ADAL on developer's behalf.
