### ISSUE TITLE
on_behalf_of parameter should be subject_token

### ISSUE THREAD

**Issue by ycrumeyrolle** [AzureAD/azure-activedirectory-library-for-dotnet#597]
Probably not the correct repository for this issue... 

According to https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-07, the `on_behalf_of` parameter that contain the user assertion has been changed to `subject_token` (see https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-07#appendix-C, revision 03). 

This is an Azure AD issue, not an Azure AD library issue.

**Comment by kpanwar** [comment]
thanks, I will communicate the same to the AAD service team.
