### ISSUE TITLE
ClientAssertionCertificate not available in NETStandard 1.6.1

### ISSUE THREAD

**Issue by dimkanewtown** [AzureAD/azure-activedirectory-library-for-dotnet#598]
Is there a timeframe when ClientAssertionCertificate will be available on NETStandard?
I'm currently on
        "Microsoft.IdentityModel.Clients.ActiveDirectory": "3.13.8",
        "NETStandard.Library": "1.6.1",

Thanks.

**Comment by kpanwar** [comment]
There is no known timeframe yet.

**Comment by StummeJ** [comment]
I've got a solution for this.  I'll work on this and make a PR :)

**Comment by kpanwar** [comment]
Can you share your solution?

**Comment by StummeJ** [comment]
By using the `Microsoft.IdentityModel.Tokens` it has all of the classes and crypto needed to implement a core version of the `ClientAssertionCertificate` class.  Then that can be used in the `Microsoft.Extensions.Configuration.AzureKeyVault` library to allow access to AzureKeyVaults in dotnet core.  This is our use case, but I cannot supply the code directly from that project.  I want to implement it here and then once it's released update the `Microsoft.Extensions.Configuration.AzureKeyVault` library to support cert based auth in core.

**Comment by StummeJ** [comment]
Is there a branch for .NETStandard code?

**Comment by StummeJ** [comment]
https://github.com/aspnet/Configuration/pull/606 contains the `ClientAssertionCertificateCore` class that is needed to get it to work on dotnet core.

**Comment by kpanwar** [comment]
Your solution is not really going to work if you are planning to add it in ADAL itself. The PR that you shared only works when ICllientCertificateAssertion is passed from the outside. The "Netstandard" binary that you see in the nuget is actually just a PCL. There was no tooling available to have a netstandard library reference a PCL before. This has changed. The correct change IMO, would require to update the platform specific project (ADAL.PCL.CoreCLR) to netstandard, and add the code as needed. This would also require a massive change to our internal build system.

**Comment by StummeJ** [comment]
Is it possible to start using an open build server like AppVeyor or TravisCI?  I'd be happy to start porting this over in my free time.

**Comment by kpanwar** [comment]
It won't be possible and TravisCI does not support xamarin builds. It still would require a massive change to build process. We are putting a plan in place to get this supported in Adal and cannot commit to a date publicly, unfortunately.

**Comment by StummeJ** [comment]
Ahh, AppVeyor would still work for that as they have xamarin enabled build nodes, and @aspnet is using it too.

**Comment by kpanwar** [comment]
Public CI systems only offer a visibility into the stability of the built source code. Official releases still come from internal build systems as they require more process. But as I mentioned, we want to add support to Adal and are working on it.

**Comment by kpanwar** [comment]
@StummeJ - Great suggestion about appveyor though. It would be nice to have it integrated with our .NET repos. Thanks!

**Comment by StummeJ** [comment]
Can you elaborate a little more on what the extra processing power is?  I ask because we are using AppVeyor to do code releases for other projects I'm on and it seems to be great for that, especially when deployment conditions are setup on things like tags.

Cheers!

**Comment by StummeJ** [comment]
Also glad to help 😄   Any suggestion on which toolchain to use for a netstandard library?  I've been working with dotnet core sdk preview4 and it's been a bit of work.  preview2 has project.json support which seems to work great for most things right now.

**Comment by kpanwar** [comment]
Authenticode signing, codescan tools and other security validations require internal build.

**Comment by dimkanewtown** [comment]
I implemented IClientAssertionCertificate like this in my solution and it seems to cover my needs. Any potential issues here?
```
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.IdentityModel.Tokens;

namespace My.Utilities
{
    #if !NET46
    internal class ClientAssertionCertificate : IClientAssertionCertificate
    {
        private readonly X509Certificate2 _certificate;

        public ClientAssertionCertificate(string clientId, X509Certificate2 certificate)
        {
            _certificate = certificate;
            ClientId = clientId;
        }

        public byte[] Sign(string message)
        {
            using (var key = _certificate.GetRSAPrivateKey())
            {
                return key.SignData(Encoding.UTF8.GetBytes(message), HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
            }
        }

        public string ClientId { get; private set; }

        public string Thumbprint => Base64UrlEncoder.Encode(_certificate.GetCertHash());
    }
    #endif
}
```

**Comment by kpanwar** [comment]
@dimkanewtown - where are you checking your public key length?

**Comment by blairmc-ms** [comment]
We are working on this for the next release

**Comment by HSAR** [comment]
Hi all, thanks for bringing this issue to our attention. We implemented this feature in releases from 3.14.0 upwards, with [3.14.1](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/v3.14.1) being the most recent patch.

--
Sam

**Comment by afedyashov** [comment]
So, how to use it now? We have 3.16.1.24801 version of Microsoft.IdentityModel.Clients.ActiveDirectory and ClientAssertionCertificate is not known. How to update existing code using it?

**Comment by jmprieur** [comment]
@afedyashov : do you want to try with ADAL.NET 3.19.8 ? or ADAL.NET 4.0.0-preview?

**Comment by afedyashov** [comment]
@jmprieur 3.19.8 resolved it, thanks!
