### ISSUE TITLE
Errors should return 'ErrorUri'

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-library-for-dotnet#6]
Errors from OAuth have 3 parts: ErrorCode, ErrorDescription, ErrorUri.  This library doesn't surface ErrorUri.

**Comment by mzayarnyuk** [comment]
yes, uri is bad, plain correct description better;

but for some wide issues better provide link to FAQ where we will able fast lookup and resolve issue if someone had it and shared what can be wrong;
