### ISSUE TITLE
Add log level check in Logger

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/azure-activedirectory-library-for-dotnet#604]
ADAL currently does not have logic to filter out logs by levels.
We should set the levels in the following order - 
- ERROR
- WARNING
- INFO 
- VERBOSE

If level is set to ERROR then then no message except ERROR are logged.
If level is set to WARNING then no message expect ERROR and WARNING are logged.
and so on...

**Comment by jmprieur** [comment]
I don't think it's a customer request. Proposing to cut it.
