### ISSUE TITLE
Update docs to include continuation event when external broker is used on Xamarin iOS/Android

### ISSUE THREAD

**Issue by anujb** [AzureAD/azure-activedirectory-library-for-dotnet#616]
When using an external broker (like MS Authenticator) with platform parameters it looks like the caller does not return from an awaited result.

```
AuthenticationResult authResult = await authContext.AcquireTokenAsync(apiUrl, clientId, uri, new PlatformParameters(this, true));
Console.WriteLine(authResult.AccessToken);
```

**Comment by kpanwar** [comment]
did you update your app delegate like this? https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/samples/AdaliOSTestApp/AppDelegate.cs#L75

**Comment by anujb** [comment]
@kpanwar I've updated the issue title to reflect the need for documentation:

Here is the relevant code snippets that need to be documented:

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/samples/AdalAndroidTestApp/MainActivity.cs#L76

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/samples/AdaliOSTestApp/AppDelegate.cs#L75
