### ISSUE TITLE
ADAL Displays Blank Login Page

### ISSUE THREAD

**Issue by anujb** [AzureAD/azure-activedirectory-library-for-dotnet#623]
It looks like we bumped the min supported version of TLS for the URI that ADAL uses in Azure. This is breaking a bunch of existing customers who use the GA ADAL libraries on Android.

I noticed we updated MSAL to use Chrome which is updated to support TLS 1.2, but did not back port this to ADAL.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/a103c7bfbed771bcbbcc1ead1596382043bd6827/src/MSAL.PCL.Android/AuthenticationActivity.cs

Also, it looks like others are hitting this issue on devices where Android WebView is not updated:

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/581

Please keep in mind a few customers might have MDM systems which prohibit calling out to an external browser, so you may need to implement a custom TLS negotiation. This is more common in the Enterprise where AzureAD will be used more prevalently.

Tagging @kpanwar to investigate

**Comment by kpanwar** [comment]
There is no plan to backport system webview support in ADAL at this point. The user must update the webview.
External browser/System webview are the future of authentication and there would be no way to implement custom TLS negotiation for it. Also, launching external browser is the last fallback. We are going to require minimum Android version that support chrometabs. They run in elevated mode, but not seen as a separate app by the OS.

**Comment by jmprieur** [comment]
Won't Fix

**Comment by cmw9706** [comment]
So are you saying ADAL can't be used anymore?

**Comment by jmprieur** [comment]
No, ADAL can be used, but we won't innovate with ADAL. We'll be GA-ing MSAL.NET soon, and it supports system web view, and this is where the innovation will happen on top of the Microsoft identity platform (formerly Azure AD v2.0). Because ADAL and MSAL share the cache, you can migrate at your own pace.
