### ISSUE TITLE
WinRT project does not load in VS2017

### ISSUE THREAD

**Issue by j0tt** [AzureAD/azure-activedirectory-library-for-dotnet#631]
when opening ADAL.NET.sln the project ADAL.PCL.WinRT fails to load saying it is "incompatible"

**Comment by Branyac** [comment]
Visual Studio 2017 does not support WinRT. You must install Visual Studio 2015.

Please see https://www.visualstudio.com/en-us/productinfo/vs2017-compatibility-vs
