### ISSUE TITLE
Getting Unknown Error

### ISSUE THREAD

**Issue by samprith-p** [AzureAD/azure-activedirectory-library-for-dotnet#642]
Hi,
I have a class library file which authenticates to AAD using certificate and clientid. For testing purpose I have created the console program and added a reference to it. When I run the console program in local, I get the Access Token successfully. I have run it in the ACCPT server where it runs successfully too. But, In my production server which has the same environment as that of ACCPT, it throws the below error. Can anyone guide me in the right direction?

The program execution throws the error at AcquireTokenAsync method. I'm using Microsoft.IdentityModel.Clients.ActiveDirectory 3.13.5. 

`
private static async Task GetAuthenticationResult(AuthenticationContext authContext, string mfdServiceResourceId,
            ClientAssertionCertificate certCred)
        {
            if (isDebugMode)
                LogMessage("Inside  GetAuthenticationResult  ");

            //return Task.Run(async () =>
            //{
            //    authenticationResult = (await authContext.AcquireTokenAsync(mfdServiceResourceId, certCred));
            //});
            try
            {
                // ADAL includes an in memory cache, so this call will only send a message to the server if the cached token is expired.
                authenticationResult = await authContext.AcquireTokenAsync(mfdServiceResourceId, certCred);
            }
            catch (AdalException ex)
            {
                using (StreamWriter writer = new StreamWriter(LogfilePath, true))
                {
                    writer.WriteLine(ex.Message);
                    writer.Close();
                }
                LogError(ex);
            }
            catch (Exception e)
            {
                LogError(e);
            }
        }`

Message: unknown_error: Unknown error
StackTrace:    at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SharepointCopyWebSrvCOM.SharepointWebServiceWrapper.<GetAuthenticationResult>d__0.MoveNext()
Source: Microsoft.IdentityModel.Clients.ActiveDirectory
TargetSite: Void MoveNext()

**Comment by kpanwar** [comment]
This error is completely on your environment. You should log the inner exception to find out the exact details of the error. this is not a library issue

**Comment by sonalinoolkar** [comment]
Hi

We are facing the similar error while generating AAD token. See below exception stack trace:



PublicKeyToken=null","method":"xxx.xxx.xxx.xxxx..ctor","level":3,"line":0},{"assembly":"Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","method":"lambda_method","level":4,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext+<>c__DisplayClass1.<GetBuildMethod>b__0","level":5,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp","level":6,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp","level":7,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp","level":8,"line":0},{"assembly":"Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","method":"lambda_method","level":9,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext+<>c__DisplayClass1.<GetBuildMethod>b__0","level":10,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp","level":11,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp","level":12,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp","level":13,"line":0},{"assembly":"Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","method":"lambda_method","level":14,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext+<>c__DisplayClass1.<GetBuildMethod>b__0","level":15,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp","level":16,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp","level":17,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp","level":18,"line":0},{"assembly":"Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","method":"lambda_method","level":19,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext+<>c__DisplayClass1.<GetBuildMethod>b__0","level":20,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp","level":21,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp","level":22,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp","level":23,"line":0},{"assembly":"Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","method":"lambda_method","level":24,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext+<>c__DisplayClass1.<GetBuildMethod>b__0","level":25,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp","level":26,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp","level":27,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp","level":28,"line":0},{"assembly":"Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","method":"lambda_method","level":29,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext+<>c__DisplayClass1.<GetBuildMethod>b__0","level":30,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp","level":31,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp","level":32,"line":0},{"assembly":"Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f","method":"Microsoft.Practices.Unity.UnityContainer.DoBuildUp","level":33,"line":0}],"outerId":"47816643","message":"One or more errors occurred.","type":"System.AggregateException","id":"50138462"},{"parsedStack":[{"assembly":"Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient+<GetResponseAsync>d__21`1.MoveNext","level":0,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":1,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":2,"line":0},{"assembly":"Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient+<GetResponseAsync>d__21`1.MoveNext","level":3,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":4,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":5,"line":0},{"assembly":"Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient+<GetResponseAsync>d__20`1.MoveNext","level":6,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":7,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":8,"line":0},{"assembly":"Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase+<SendHttpMessageAsync>d__67.MoveNext","level":9,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":10,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":11,"line":0},{"assembly":"Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase+<SendTokenRequestAsync>d__64.MoveNext","level":12,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":13,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":14,"line":0},{"assembly":"Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase+<RunAsync>d__55.MoveNext","level":15,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":16,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":17,"line":0},{"assembly":"Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext+<AcquireTokenForClientCommonAsync>d__49.MoveNext","level":18,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":19,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":20,"line":0},{"assembly":"Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.IdentityModel.Clients.ActiveDirectory.Authenti**cationContext+<AcquireTokenAsync>d__26.MoveNext","level":21,"line":0}],"outerId":"50138462","message":"unknown_error: Unknown error","type":"Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException","id":"44514054"},{"parsedStack":[{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowFor**NonSuccess","level":0,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":1,"line":0},{"assembly":"Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper+<GetResponseAsync>d__29.MoveNext","level":2,"line":0}],"outerId":"44514054","message":"A task was canceled.","type":"System.Threading.Tasks.TaskCanceledException","id":"52329287"}]

**Comment by samprith-p** [comment]
In my case issue was the service was running as a "LOCAL SYSTEM". If I change it to run as a specific user account it was authenticating successfully. 
So, please check if the user account which runs the Service/exe has the necessary permissions.
