### ISSUE TITLE
x-ms-PKeyAuth header causes 401 error from AD FS 4.0 when getting refresh_token

### ISSUE THREAD

**Issue by hallatore** [AzureAD/azure-activedirectory-library-for-dotnet#644]
When using ADAL against AD FS 4.0 the refresh token logic fails with an server response code 401. It is caused by [this line](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/src/ADAL.PCL/Http/AdalHttpClient.cs#L84) which adds `x-ms-PKeyAuth: 1.0` to the request.

**Comment by hallatore** [comment]
I see that this header is related to [MS-PKAP]: Public Key Authentication Protocol. https://msdn.microsoft.com/en-us/library/mt223996.aspx

Why is this header appended by default? It looks like an optional feature to me.

**Comment by kpanwar** [comment]
the header is appended by default to advertise to the STS that the client is incapable of doing client TLS. The cert thumbprint should not be empty or the ADFS should be returning a list of cert authorities that is trusts.
