### ISSUE TITLE
What are the supported configurations for CoreCLR?

### ISSUE THREAD

**Issue by nrandell** [AzureAD/azure-activedirectory-library-for-dotnet#646]
I'm struggling with using this on the CoreCLR. It works fine with AcquireDeviceCodeAsync and AcquireTokenByDeviceCodeAsync.

However if I try to use 
`var result = await AuthenticationContext.AcquireTokenAsync(ResourceUri, ClientId, new UserCredential(Username)).ConfigureAwait(false);
`
I get the following stack trace
```
[xUnit.net 00:00:01.9296216]   Starting:    PowerBIClientTests
[xUnit.net 00:00:02.8819211]     PowerBIClientTests.AuthenticationTests.VerifyUserLoginWorks [FAIL]
[xUnit.net 00:00:02.8838648]       System.NotImplementedException : The method or operation is not implemented.
[xUnit.net 00:00:02.8855339]       Stack Trace:
[xUnit.net 00:00:02.8875652]            at Microsoft.IdentityModel.Clients.ActiveDirectory.WebUIFactory.CreateAuthenticationDialog(IPlatformParameters parameters)
[xUnit.net 00:00:02.8877692]            at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__54.MoveNext()
```

It's a great library, but it looks like the CoreCLR support is not fully there yet. Or have I misunderstood how to use this?

**Comment by jmprieur** [comment]
The support of .NET Core only arrives with ADAL.NET 3.14 (which should be available soon)
