### ISSUE TITLE
Android multiple certificate issue

### ISSUE THREAD

**Issue by spsteve10** [AzureAD/azure-activedirectory-library-for-dotnet#649]
If the user has multiple certs and the wrong one is selected the first time the user isn't authenticated.  We try it again, but this time selecting the correct certificate the company portal STILL doesn't authenticate.  It seems as if its caching preselected certificates.

**Comment by kpanwar** [comment]
This is completely an Android OS behavior and out of library's control. It would be nice to know you complete setup and scenario though.

**Comment by jmprieur** [comment]
Closing as we did not get an answer to Kanishk's question.
