### ISSUE TITLE
Update MRRT logic based on open id connect document

### ISSUE THREAD

**Issue by afshins** [AzureAD/azure-activedirectory-library-for-dotnet#65]
The current behavior to determine whether a refresh token is MRRT or not is based on presence of the field 'resource' in token response, but that needs to change as MRRT is a behavior of the STS, not the refresh token and needs to be determined from STS metadata using Open ID Connect Discovery.

**Comment by RandalliLama** [comment]
@kpanwar I don't understand how important this is.  Can you follow up?
@vibronet Do you have an opinion?

**Comment by blairmc-ms** [comment]
@kpanwar , doing a scrub through. This is an old issue that hasn't been actioned and it's not clear that there is any need to make this change. Please re-open if you disagree.
