### ISSUE TITLE
ADAL token caching fails in iOS?

### ISSUE THREAD

**Issue by pritchie99** [AzureAD/azure-activedirectory-library-for-dotnet#658]
Hi - I already posted this question on StackOverflow.  Happy to re-enter it here if required.
[http://stackoverflow.com/questions/43690427/adal-token-caching-fails-in-ios](http://stackoverflow.com/questions/43690427/adal-token-caching-fails-in-ios)

Basically I am getting the following message in iOS (simulator) which was not happening previously:-
"TokenCachePlugin.cs: Failed to save cache record: -34018"

kind regards,
Paul

**Comment by kpanwar** [comment]
This is a known issue with iOS. http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-in-ios-10-simulator
