### ISSUE TITLE
AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.

### ISSUE THREAD

**Issue by anaili** [AzureAD/azure-activedirectory-library-for-dotnet#659]
Azure AD Version : 3.13.9.1126

AcquireTokenAsync with a WebAPI application is failing with the following exception even after adding the client_secret param as extraQueryParameter.

> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException : AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.

```
string clientSecretQueryParam = "client_secret=<client_secret_pasted_here>";
AuthenticationResult result = authenticationContext.AcquireTokenAsync(Office365Endpoint, applicationId, redirectUri, new PlatformParameters(PromptBehavior.Auto), userId, clientSecretQueryParam).Result;
```

**Comment by ShakeySnake** [comment]
+1 Unable to use this overload due to the same error.
`public Task<AuthenticationResult> AcquireTokenAsync(string resource, string clientId, Uri redirectUri, IPlatformParameters parameters);`

Also note resource and clientID are the same value due to AAD requiring guid based app identifier for the resource field:

> AADSTS90009: Application 'xxxxxxx' is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier.

**Comment by kpanwar** [comment]
you are calling a public client API on server and it is attempting to show UI. You need to call https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/src/ADAL.PCL/AuthenticationContext.cs#L226

**Comment by jdwilemo** [comment]
@kpanwar link is broken.

**Comment by kpanwar** [comment]
Sorry, I commented on that 5 months back. It was totally working then 🙂

**Comment by ThomasMldr** [comment]
@jdwilemo And almost another 5 months later, your link is broken too :-D

**Comment by jmprieur** [comment]
@ThomasMldr : that's the problem with providing links to code that evolves. Sorry about that (there have been a code refactoring in progress to have a common code base for ADAL.NET and MSAL.NET)

This wiki page will give you all the information about the overrides you can use in Web applications
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Confidential-client-applications-flows 

BTW, you might want to read the whole conceptual documentation : https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki (work in progress)
