### ISSUE TITLE
Does not work with a proxy server which requires authentication.

### ISSUE THREAD

**Issue by relusion** [AzureAD/azure-activedirectory-library-for-dotnet#660]
Hi there,

it seems that the library doesn't use system proxy settings specified firstly in IE and then in app.config.
I have a call:```

var authContext = new AuthenticationContext(authority);
var authRes = await authContext.AcquireTokenAsync(resourceId, appId, new Uri(replyUrl),
                new PlatformParameters(PromptBehavior.Auto),
               UserIdentifier.AnyUser, UserIdentifierType.OptionalDisplayableId));
```
AcquireTokenAsync brings the browser dialog as expected(so the browser widnow picks the settings right) but when I press the login button there it fails with the following error and call stack:

> The remote server returned an error: (407) Proxy Authentication Required.

```
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
```

This is my settings in IE:

https://cloud.githubusercontent.com/assets/13152136/25749128/be45ef94-31ad-11e7-9636-0117b74720bd.png

and I have the fidler tool running as a proxy server on that port 8888 with option set to true "Require Proxy Authentification"

app.config:
```
<configuration>
  <system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true">
      <proxy usesystemdefault="True" bypassonlocal="False"/>
    </defaultProxy>
  </system.net>
</configuration>
```

any help would be appreciated,

Versions:
Microsoft.IdentityModel.Clients.ActiveDirectory - 3.13.9.1126
Microsoft.IdentityModel.Clients.ActiveDirectory.Platform - 3.13.9.1126

thanks!

**Comment by kpanwar** [comment]
@blairmc-ms - can you please add a little blurb about why it is by design?

**Comment by tebeco** [comment]
@kpanwar can we reopen this issue ?

This library is a transitive one, used when using `Azure KeyVault` as a Configuration Provider for `AspNet Core` application.
Some of our application here has to stay in our LAN for connectivity reason with other services and we would like to use `Azure KeyVault`

Details are available here :

https://github.com/Azure/azure-sdk-for-net/issues/4404#issuecomment-433921227
