### ISSUE TITLE
Xamarin ADAL library

### ISSUE THREAD

**Issue by sowsan** [AzureAD/azure-activedirectory-library-for-dotnet#661]
Hello Team -

Trying to integrate Azure B2C with Xamarin. Using Xamarin Forms PCL with Android & IOS. Documentation talking about a alpha preview library called "Microsoft.Identity.Client" which was not udpated since April 2016. AD [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries) pointing to "Microsoft.IdentityModel.Client.ActiveDirecttory". Now, issue I'm facing is, while trying to add this nuget in my VS 2017 Xamarin Project its failing for adding the library for the PCL project. Heard something about the Windows 8.1, which I removed and still having the issue. Any idea around this? Which client need to use for my scenario, and how can fix the issue ?

**Install-Package : Could not install package 'Microsoft.IdentityModel.Clients.ActiveDirectory 3.13.9'. You are trying to install this package into 
a project that targets '.NETPortable,Version=v4.0,Profile=Profile24', but the package does not contain any assembly references or content files 
that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory**

Regards,
Sowmyan

**Comment by kpanwar** [comment]
VS 2017 does not support Win RT. You have to use VS 2015. Also, you cannot use ADAL to integrate with B2C. You need to use https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

**Comment by sowsan** [comment]
so to be clear, if I want to use VS for developing a Xamarin application with Azure B2C Integration, I have to use VS 2017 with the preview library : https://www.nuget.org/packages/Microsoft.Identity.Client/1.0.304142221-alpha ?

**Comment by kpanwar** [comment]
Yes. That is an old version though. We will be updating to a new version soon. If you want, you can play with the myget feed that produces nightly builds.

**Comment by sowsan** [comment]
Thank You. When I add that library to my PCL Xamarin forms its throwing the below error

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.Identity.Client 1.0.304142221-alpha'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile24', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by kpanwar** [comment]
Try the latest from myget.

**Comment by sowsan** [comment]
Thank you, is there is a direct url for the correponding package in myget?

**Comment by sowsan** [comment]
never mind, got it, thank you so much :) 

https://www.myget.org/feed/aad-clients-nightly/package/nuget/Microsoft.Identity.Client
