### ISSUE TITLE
AdalSilentTokenAcquisitionException: Xamarin Forms with ADAL 3.13.9 and ADFS

### ISSUE THREAD

**Issue by mariolobar** [AzureAD/azure-activedirectory-library-for-dotnet#663]
Hello

I'm trying to refresh the token calling the method AcquireTokenSilentAsync. Now I'm trying on iOS version. The parameters that I'm sending are these:

authenticationContext = new AuthenticationContext(ServicesUrls.AuthorityUrl, false, new TokenCache(serializedTokenCache));
var controller = UIApplication.SharedApplication.KeyWindow.RootViewController;
			var platformParams = new PlatformParameters(controller);
			var authResult = await authContext.AcquireTokenSilentAsync("appname/8FD28466-7C69-48AC-9929-CEC8A15826F9", "8FD28466-7C69-48AC-9929-CEC8A15826F9", UserIdentifier.AnyUser, platformParams);

This is the exception that I'm receiving:

Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException: Failed to refresh access token ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: MSIS9603: The received 'scope' parameter is invalid. The authorization server does not support the specified scope. ---> System.Net.Http.HttpRequestException:  Response status code does not indicate success: 400 (BadRequest). ---> System.Exception: {"error":"invalid_scope","error_description":"MSIS9603: The received \u0027scope\u0027 parameter is invalid. The authorization server does not support the specified scope."}
   --- End of inner exception stack trace ---
  at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper+<GetResponseAsync>d__30.MoveNext () [0x0037e] in <97581c6894a642ef95d008cded8ad4ac>:0 
   --- End of inner exception stack trace ---
  at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient+<GetResponseAsync>d__21`1[T].MoveNext () [0x004d1] in <97581c6894a642ef95d008cded8ad4ac>:0

**Comment by kpanwar** [comment]
This error is coming back from your ADFS. Library is simply bubbling it back to you as an exception. I assume this is ADFS v4?
