### ISSUE TITLE
ESTS returning 408 or 504 may result in empty access token and no exception

### ISSUE THREAD

**Issue by ccrookms** [AzureAD/azure-activedirectory-library-for-dotnet#664]
Behavior was discovered during a recent Sev-0 ESTS incident:

<img width="846" alt="nullaccesstokennoexceptionfor408or504" src="https://cloud.githubusercontent.com/assets/22584109/25924041/8a2f9db8-3595-11e7-91b0-314ca24104ac.png">

**Comment by kpanwar** [comment]
Thanks! ADAL should be failing in this case.

**Comment by tehcrashxor** [comment]
We've seen a few cases in my service's telemetry that we occasionally have a null AccessToken as well, though we do not have any information on what the Status Code from eSTS was.

It seems like it would be helpful to put the eSTS Correlation and Trace IDs on the `AuthenticationResult` object as well, as we cannot supply them any useful value for investigating issues like this...

**Comment by kpanwar** [comment]
All ADAL requests have an associated correlation id. As a developer you should be collecting ADAL logs, which in turn would give you the correlation id of the failed request.
