### ISSUE TITLE
Xamarin.Android (Xamarin.Forms) not prompting to use user certificate

### ISSUE THREAD

**Issue by MatFillion** [AzureAD/azure-activedirectory-library-for-dotnet#671]
We have a Azure AD setup and via the webview, the identity manager is supposed to retrieve information from a User Certificate installed on the device (it was pushed via an entreprise portal).

Our app is built on Forms and targets both iOS and Android.

On iOS it works, there is no prompt required. User enters his email address in the webview and after a few redirects, receives the token.

On android, the flow should be the same with the addition that the webview should prompt the user to pick which certificate to use (even if there's 0 or multiple certificates installed). Our problem is it doesn't prompt us to choose a certificate, and in the log cat we can see a log "Chromium: [...] No client certificate selected", and then the webview presents an error page saying access denied.

To confirm the problem was coming from our code or the .net SDK (versus the azure setup) we tried the sample from the android-specific project (in java) https://github.com/AzureAD/azure-activedirectory-library-for-android and it does work with our azure ad setup, we are prompted with the certificate dialog.

We're using AcquireTokenAsync(string resource, string clientId, uri redirect, platformparameters params) broker mode = false.

We tested on Android 6.0 and 7.1. We double checked we have the same permissions as the sample-app and also accept them at runtime.

Is it a flow that's not supported by the .net SDK or we're missing something?

Thanks!

**Comment by MatFillion** [comment]
We solved the issue by implementing onReceivedClientCertRequest in the SDK. The webview needs to call  KeyChain.ChoosePrivateKeyAlias

**Comment by kpanwar** [comment]
Thats exactly what our native android SDK does. We plan on looking at this at a later time.

**Comment by keithfry-gm** [comment]
We also have the same experience as MatFillion and would also like this Enhancement implemented so we don't have to patch it manually. 

Thanks.

**Comment by jennyf19** [comment]
Thanks for bringing this up again, @keithfry-gm 

cc: @jmprieur @henrik-me

**Comment by jmprieur** [comment]
Won't do in ADAL.NET.
In MSAL.NET this is not necessary as the System browser is used.

**Comment by xtremal** [comment]
> We solved the issue by implementing onReceivedClientCertRequest in the SDK. The webview needs to call KeyChain.ChoosePrivateKeyAlias

@MatFillion what is the "IKeyChainAliasCallback response" parameter you sending to KeyChain.ChoosePrivateKeyAlias ?

Thanks in advance!

**Comment by jmprieur** [comment]
@henrik-me FYI

**Comment by henrik-me** [comment]
@jmprieur : Suggesting to create a work item in MSAL for this?

**Comment by jmprieur** [comment]
@henrik-me : I'm not sure this would apply to MSAL as it's using the system web view by default? Or do we want to create a WI for MSAL when using the embedded Web view with Xamarin?

**Comment by MatFillion** [comment]
@xtremal 
Here's the quick way I have done it:
have `AdalWebViewClient`  implement `IKeyChainAliasCallback` then pass `this` to 
`KeyChain.ChoosePrivateKeyAlias(_activity, this, request.GetKeyTypes(), request.GetPrincipals(), request.Host, request.Port, null);`
