### ISSUE TITLE
Force ADAL to ask for credentials

### ISSUE THREAD

**Issue by SuperJMN** [AzureAD/azure-activedirectory-library-for-dotnet#686]
is there a way to make AuthenticationContext.GetTokenAsync() show the login window to force the user to authenticate again?

It's because I want to implement a log off button and I want to show the user to enter the credentials again.

**Comment by dimkanewtown** [comment]
You want to set PromptBehavior = PromptBehavior.Always

**Comment by SuperJMN** [comment]
In Android and iOS we don't have that option, only in UWP. How do we set that option in those platforms?

**Comment by kpanwar** [comment]
Those platforms should be forcing credential reentry by default.
