### ISSUE TITLE
Allow redirect to login page in a pop up window instead of full page

### ISSUE THREAD

**Issue by cserkaran** [AzureAD/azure-activedirectory-library-for-dotnet#690]
Kindly allow redirect to login page in a pop window instead of full page.
ADAL.js allows this but not this library.

**Comment by kpanwar** [comment]
MSHTML control is not launched in full screen mode. Can you post a screenshot of what you see?

**Comment by cserkaran** [comment]
it launches but it redirects the existing browser page to the login page. I want to see the login page in separate browser window as a pop up(like adal.js allows by setting popUp to true)? Is it possible currently.

**Comment by kpanwar** [comment]
It is not possible.

**Comment by cserkaran** [comment]
So ADAL.js can allow this but not possible for the counter part in adal.net ?  There is no way to show the browser page as a separate window ?

**Comment by kpanwar** [comment]
Adal.net does not use a browser. As explained before, it uses mshtml control. They are completely different things.
