### ISSUE TITLE
AAD fails with error code: authentication_ui_failed

### ISSUE THREAD

**Issue by almost92** [AzureAD/azure-activedirectory-library-for-dotnet#691]
Hi,

we are developing a Cordova app and we are using AAD Cordova plugin (https://github.com/AzureAD/azure-activedirectory-library-for-cordova)

in the plugin v0.10.0, ADAL.NET 3.13.8 is used.

some of our members are unable to authenticate with error code authentication_ui_failed, some of the error messages are:

- authentication_ui_failed: The browser based authentication dialog failed to complete. The system cannot locate the resource specified. (Excep_FromHResult 0x800C0005) 
- authentication_ui_failed: The browser based authentication dialog failed to complete. The system cannot find the file specified. (Excep_FromHResult 0x80070002) 
- authentication_ui_failed: The browser based authentication dialog failed to complete. Catastrophic failure (Excep_FromHResult 0x8000FFFF)

I've tried some solutions like moving our Cordova app to local-context and applying some capabilities like: 
- enterpriseAuthentication
- sharedUserCertificates
- internetClientServer
- privateNetworkClientServer

I enabled logging for AAD to get some better insight and here are some of the traces I got from one of our users:
 TokenCache.cs: Clearing Cache :- 0 items to be removed
 TokenCache.cs: Successfully Cleared Cache
 TokenCache.cs: Serializing token cache with 0 items.
 TokenCache.cs: Deserialized 0 items to token cache.
 TokenCache.cs: Deserialized 0 items to token cache.

 AcquireTokenHandlerBase.cs: === Token Acquisition started:
	Authority: https://login.windows.net/common/
	Resource: https://management.core.windows.net/
	ClientId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	CacheType: null
	Authentication Target: User

AcquireTokenHandlerBase.cs: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: authentication_ui_failed: The browser based authentication dialog failed to complete ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Excep_FromHResult 0x80070002)

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at SharedLibrary!<BaseAddress>+0x36fd1b

   at SharedLibrary!<BaseAddress>+0x36fbe9

   at SharedLibrary!<BaseAddress>+0x36fbb9

   at **CordovaApp**!<BaseAddress>+0x185de5

   Exception_EndOfInnerExceptionStack

   at **CordovaApp**!<BaseAddress>+0x185e47

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at SharedLibrary!<BaseAddress>+0x36fd1b

   at SharedLibrary!<BaseAddress>+0x36fbe9

   at SharedLibrary!<BaseAddress>+0x36fbb9

any ideas what causes this and how can it be resolved?

Thanks in advance

**Comment by jmprieur** [comment]
@almost92 : I'm not familiar with Cordova, so sorry if I'm asking nonsense. Did you make sure that your Cordova plug-in contain both the platform independent and platform specific DLLs of ADAL.js? 
Also on which platform / browser does this error happen? I understand it's not systematic? do you have repro steps?

**Comment by kpanwar** [comment]
We do not own or maintain Cordova layer over Adal
