### ISSUE TITLE
Integration Testing in DotNetCore2.0 (ASPNetCore)

### ISSUE THREAD

**Issue by pms1969** [AzureAD/azure-activedirectory-library-for-dotnet#692]
Hi, I've been converting our WebAPI application to dotnetcore2.0.  I'm pretty much at the end of that process now, and I've run into a bit of a blocker, and was wondering if I could get some guidance.

The systems integration tests we have run after deployment and hit our app (aspnet mvc - purely api returning json).  The api is protected via AAD, and that delegates out to our IDP.  The api is designed for user interaction but I can only find ways to call AAD with a native app token (not with userid/password).  Not that I can find it now, but I remember reading something that said this kind of workflow (ResourceOwnerPasswordFlow?) is not supported.  Because the native app workflow doesn't pass back a user context, the app barfs because it can't access user details that would normally be provided in the token which is provided by the IDP.  So how do I proceed?  The existing code used the UserPasswordCredentials class but this no longer seems available.

Thanks.

**Comment by pms1969** [comment]
Bump!..  be nice to get some feedback.

**Comment by jmprieur** [comment]
Sorry for the delay @pms1969 : Indeed, unlike ADAL.NET for .NET Framework (which has been providing it) in ADAL.NET for .NET core we do not provide a class for the username/password flow (the OAuth 2.0 Resource Owner Password Credential Grant flow). There is a good discussion about the reasons why, and alternative ways in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482. Can you please read it and reopen this issue if you don't find  a good answer?
