### ISSUE TITLE
SSL termination support for Adal

### ISSUE THREAD

**Issue by shbaruch** [AzureAD/azure-activedirectory-library-for-dotnet#705]
It seems that ssl termination doesn't work.
this is the response i get:

ERROR
The requested URL could not be retrieved
________________________________________
Invalid Request error was encountered while trying to process the request:
POST /common/oauth2/token HTTP/1.1
Accept: application/json 
x-client-SKU: PCL.Desktop 
x-client-Ver: 3.13.7.964 
x-client-CPU: x64 
x-client-OS: Microsoft Windows NT 10.0.14393.0 
x-ms-PKeyAuth: 1.0 
client-request-id: 6a1ac644-dd39-4c63-8423-1276a91515cb 
return-client-request-id: true 
Content-Type: application/x-www-form-urlencoded 
Host: login.windows.net 
Content-Length: 762 
Expect: 100-continue 
Connection: Keep-Alive 
Some possible problems are:
•	Missing or unknown request method.
•	Missing URL.
•	Missing HTTP Identifier (HTTP/1.0).
•	Request is too large.
•	Content-Length missing for POST or PUT requests.
•	Illegal character in hostname; underscores are not allowed.
•	HTTP/1.1 Expect: feature is being asked from an HTTP/1.0 software.
Your cache administrator is webmaster.
 
________________________________________
Generated Tue, 04 Jul 2017 14:33:29 GMT by squidproxy.local.secureislands.com (squid/3.1.19)
---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 417 (ExpectationFailed). ---> System.Exception:

**Comment by jmprieur** [comment]
This is by design as library must have a clear line of sight with AAD
