### ISSUE TITLE
System.ArgumentOutOfRange exception inside ADAL library

### ISSUE THREAD

**Issue by savy-g** [AzureAD/azure-activedirectory-library-for-dotnet#710]
Write Ideas ios app app uses ADAL for authentication. On June 3rd, we observed some crash incidents of the app.
The attached image contains the stack trace. It suggests that it has something to do with the logging logic of ADAL when trying to convert b/w date formats.

ADAL library version we're using is 3.13.8.

![stack trace](https://user-images.githubusercontent.com/24301049/28033677-df04ce3c-6563-11e7-8585-0e0fe6a72245.png)

This issue has blocked the release of our Ios app "Microsoft Write Ideas" on the apple store.

**Comment by savy-g** [comment]
Needs to be escalated because this has blovked a new release of our app on apple store.

**Comment by savy-g** [comment]
![image](https://user-images.githubusercontent.com/24301049/28332717-9fb03eea-6baa-11e7-83f9-3736b3798b00.png)

**Comment by mjcheetham** [comment]
Hi @savy-g,

Do you know which particular culture was the current culture during this exception?

Also, when you're building the app are you including the extra internationalisation settings?
https://developer.xamarin.com/guides/ios/advanced_topics/localization_and_internationalization/encodings/
![image](https://user-images.githubusercontent.com/5658207/28368107-27693c16-6c8b-11e7-818f-66a28bc9b963.png)

**Comment by savy-g** [comment]
@mjcheetham ,
 I just checked the build settings of our app.
We are not using the extra internationalization settings.
Will using them solve the problem?

**Comment by mjcheetham** [comment]
@savy-g, without being able to fully reproduce the problem I can't say this will fix it for sure.

The discussion on the Xamarin forums (linked above), and a [bug](https://bugzilla.xamarin.com/show_bug.cgi?id=30897) about the same exception being thrown when using the Thai locale, leads me to believe these settings _might_ cause this issue.

On the ADAL side, we're calling:

```cs
string.Format(CultureInfo.CurrentCulture, "{0} ...removed for brevity..", DateTime.UtcNow);
```

..which is resulting in the exception being thrown from within Mono types when it's getting the culture-specific string representation of the `DateTime`.

**Comment by mjcheetham** [comment]
@savy-g, we've updated ADAL so that it now always uses both the Invariant Culture and the ISO format for date-times when creating log messages. I also checked that we don't do culture-dependent date-time formatting anywhere else in ADAL.

Hopefully this will avoid this sort of issue, but again can't guarantee this without a repro.

```cs
string.Format(CultureInfo.InvariantCulture, "{0:O} ...removed for brevity..", DateTime.UtcNow);
```

**Comment by savy-g** [comment]
@mjcheetham , I was able to repro the bug on an iOS device yesterday by changing the device region to Thailand and language to Thai.
The bug was eradicated on choosing the international options under internationalization in build settings.

But, since you have updated the ADAL repo to not use any culture dependent formatting, I will update the library in the App and try to run the app on Thai locale without the internationalization build settings.

**Comment by mjcheetham** [comment]
@savy-g, a release of ADAL has been made which incorporates this fix.

v3.14.2: [Tag](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/v3.14.2), [NuGet package](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.14.2)
