### ISSUE TITLE
ADAL not resilient to UPN changes, throws exception with multiple_matching_token_detected 

### ISSUE THREAD

**Issue by tehcrashxor** [AzureAD/azure-activedirectory-library-for-dotnet#714]
When a user is signed into our service, and then changes their UPN via the AAD portal, the next call to `AcquireTokenAsync()` introduces a near-duplicate in the `TokenCache`, which has the same Authority, Client, Resource, and OID/UniqueId, but with a different UPN/DisplayableId.  Further calls to `AcquireTokenAsync()` after that point fail with `AdalException`s with an error code of `multiple_matching_token_detected`. 

Minimal example:
```csharp
// Create a new test user in an AAD tenant, and fill in its OID in place of the Guid in the line below\
var userIdentifier = new UserIdentifier("AAD_OID_HERE", UserIdentifierType.UniqueId);
 
var clientId = "CLIENT_ID_HERE"; 
var redirectUri = new Uri("urn:ietf:wg:oauth:2.0:oob"); // Out-Of-Bound redirect uri
var resource = "RESOURCE_ID_HERE";
var authority = "https://login.windows.net/common/";
 
var cache = new TokenCache();
 
var authCtx = new AuthenticationContext(authority, cache);
var platformParams = new PlatformParameters(PromptBehavior.Always);
 
// Grab a token with a test AAD user
var firstAuthResult = authCtx.AcquireTokenAsync(resource, clientId, redirectUri, platformParams).Result;
 
// Set breakpoint on next code line.
// Change the user's UPN in the Azure portal
// Either wait an hour for the AccessToken to expire, or cheat using the locals window to expire the current token
// via the locals window:  cache -> Non-Public members -> tokenCacheDictionary -> [0] -> Value -> Result -> ExpiresOn
// Proceed in debugging past this line
var secondAuthResult = authCtx.AcquireTokenSilentAsync(resource, clientId, userIdentifier).Result;
 
// At this point, the cache will have two entries for the same Resource and OID, but different UPNs
// Attempting to get a token will result in an AdalException with multiple_matching_tokens_detected
var thridAuthResult = authCtx.AcquireTokenSilentAsync(resource, clientId, userIdentifier).Result;
````

**Comment by kpanwar** [comment]
This is by design. Cache offers 2 ways of querying, unique id or displayable id. if your users are renaming UPN then you always remove the older token from cache based on token age. Token cache offers methods that allow you to do this using readItems and deleteItem

**Comment by tehcrashxor** [comment]
So consumers need to know to check the `TokenCache` after every call to any of the `AcquireToken` variants to prevent UPN changes from breaking their apps?

We could handle this in our service by throwing a 
```csharp
var itemsWithSameOidAndResourceButDifferentUPNs =
    cache.ReadItems()
        .Where(
            x =>
                string.Equals(x.UniqueId, oid, StringComparison.OrdinalIgnoreCase) &&
                string.Equals(x.Resource, resource, StringComparison.OrdinalIgnoreCase))
        .ToList();

if (itemsWithSameOidAndResourceButDifferentUPNs.Count > 1)
{
    var itemWithMostRecentRefreshToken = itemsWithSameOidAndResourceButDifferentUPNs
        .Aggregate((item1, item2) => item1.ExpiresOn > item2.ExpiresOn ? item1 : item2);

    foreach (var item in itemsWithSameOidAndResourceButDifferentUPNs.Where(x => x != itemWithMostRecentRefreshToken))
    {
        cache.DeleteItem(item);
    }
}
```
after every AcquireToken call, but @vibronet has said that ADAL does not expect their consumers to perform such gymnastics...

**Comment by Brijeet** [comment]
This is an older question but, was wondering if something more streamlined was figured out. I am using AzureAD auth for many webapps and running into the same "multiple_matching_token_detected" error when people's UPNs have changed. curious if there was some more streamlined method that was figured out.

**Comment by jmprieur** [comment]
@Brijeet : the recommendation is to move to MSAL.NET which does handle this scenario. We won't update ADAL.NET at that point. See also https://docs.microsoft.com/azure/active-directory/develop/msal-net-migration
