### ISSUE TITLE
TokenCache and Redis

### ISSUE THREAD

**Issue by dmcweeney** [AzureAD/azure-activedirectory-library-for-dotnet#728]
I've seen a few example lately of using Redis for the TokenCache storage.
This is confusing me as I thought that one needed to persist tokens to some storage medium for resilience against server crashes - my particular scenario is Azure hosted multitenant WebApps.
Am I off the mark on this?

Thanks

Donal

**Comment by kpanwar** [comment]
you are not. if you have highly degree of replication in your deployment then it is okay to use redis for token cache.

**Comment by dmcweeney** [comment]
Hi @kpanwar - no we are not using redis replication or redis persistence - just the Basic offering - so I guessing we need to consider something like Consmos Db Table Storage instead for our Token Cache persistence medium? Thanks Donal
