### ISSUE TITLE
Cannot get an auth token for service principals with symmetric key as secret

### ISSUE THREAD

**Issue by nazang** [AzureAD/azure-activedirectory-library-for-dotnet#730]
We have some service principals which are created use MSOnline powershell V1 and the key type of the SP is set as "Symmetric". I cannot use ADAL to get an auth token for these service principals. The error is "Client secret is not valid". If during creation, the key type is set as "Password", it works fine. Discussed this on the Microsoft internal support channel. It is said the "Symmetric key" SP authentication was not implemented. So, I am filing a feature ask to get implemented.

**Comment by jmprieur** [comment]
Thanks @nazang for reporting this issue. could you please provide detailed repro steps so that we can repro the issues and later verify that it's fixed?

**Comment by nazang** [comment]
@jmprieur thank you for looking into this. 

This is the repro step:

1.	First, create a service principal by passing in a pre-generated symmetric key 

a. Download MSODS v1 Powershell and create a SP https://www.powershellgallery.com/packages/MSOnline/1.1.166.0

Connect-MsolService  
New-MsolServicePrincipal -ServicePrincipalNames @("MyApp/myApp.com") -DisplayName "My Application" -Type Symmetric -Value <Symmetric key value>

2 . Generate an auth token using ADAL

AuthenticationContext context = new AuthenticationContext("https://login.windows.net/*****.onmicrosoft.com", true);
ClientCredential assersion = new ClientCredential("<SP AppPrincipalId>", @"<Symmetric key value>");
var result =await context.AcquireTokenAsync ("https://graph.windows.net/", assersion);

Error:
AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.

**Comment by jmprieur** [comment]
Indeed, the handler for client_assertion credentials is wired to RSA_SHA256. We don't support symmetric keys. Note that this is not a requirement for adal, but for the service. Closing this issue for now.
