### ISSUE TITLE
Public API surface is broken between 3.14.2 and 3.15.0

### ISSUE THREAD

**Issue by mjcheetham** [AzureAD/azure-activedirectory-library-for-dotnet#740]
The signature of the public method `AuthenticationContext::GetAuthorizationRequestUrlAsync` has changed from

```cs
// Before 3.15.0
public async Task<Uri> GetAuthorizationRequestUrlAsync(string resource, string clientId,
    Uri redirectUri, UserIdentifier userId, string extraQueryParameters)
```

to

```cs
// After 3.15.0
public async Task<Uri> GetAuthorizationRequestUrlAsync(string resource, string clientId,
    Uri redirectUri, UserIdentifier userId, string extraQueryParameters, string claims)
```

See the addition of the parameter `string claims`?

From the looks of it, there should be an overload introduced which only requires the original 5 parameters, as well as a new overload including the `claims` parameter.

**Comment by mjcheetham** [comment]
I would suggest that a new version of ADAL is released (either 3.15.1, or 3.16.0), and the 3.15.0 version is unlisted from NuGet.org to prevent others from discovering this broken package.

**Comment by mjcheetham** [comment]
This issue also exists in the PR #731 which back-ports the functionality to v2.x.

**Comment by kpanwar** [comment]
Thanks a lot @mjcheetham for your diligence! I am surprised that we missed it 😱

**Comment by mjcheetham** [comment]
Can confirm that [v3.16.0] restores the original overload of `GetAuthorizationRequestUrlAsync`.
Thanks! 😄
