### ISSUE TITLE
WebUIFactory not implemented for .net core 2.0 

### ISSUE THREAD

**Issue by janusznowak** [AzureAD/azure-activedirectory-library-for-dotnet#751]
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/src/ADAL.PCL.CoreCLR/WebUIFactory.cs

**Comment by kpanwar** [comment]
This is by design. There are no UI components for .net core. You must target specific platforms to consume interactive authentication.

**Comment by janusznowak** [comment]
How in that case it suppose to be used for application targeting .net core 2.0 on windows machine ?

**Comment by kpanwar** [comment]
Are you building a web app or a native client?

**Comment by janusznowak** [comment]
Hi I am migrating ArmClient to .net 462 and .netcore 2.0 I am getting issue here
https://github.com/janusznowak/ARMClient/blob/feature/net4.6.2Andnetcoreapp2.0Target/ARMClient.Authentication/AADAuthentication/BaseAuthHelper.cs

line 319

#if NET462
                        result = await context.AcquireTokenAsync(resource: resource, clientId: Constants.AADClientId, redirectUri: new Uri(Constants.AADRedirectUri), userId: new UserIdentifier(user, UserIdentifierType.OptionalDisplayableId), parameters: new PlatformParameters(PromptBehavior.Never));
#endif

#if NETCOREAPP2_0
                        result = await context.AcquireTokenAsync(resource: resource, clientId: Constants.AADClientId, redirectUri: new Uri(Constants.AADRedirectUri), userId: new UserIdentifier(user, UserIdentifierType.OptionalDisplayableId), parameters: new PlatformParameters());
#endif
                    }
                    else
                    {
#if NET462
                        result = await context.AcquireTokenAsync(resource: resource, clientId: Constants.AADClientId, redirectUri: new Uri(Constants.AADRedirectUri), parameters: new PlatformParameters(PromptBehavior.Always));
#endif

#if NETCOREAPP2_0
                        result = await context.AcquireTokenAsync(resource: resource, clientId: Constants.AADClientId, redirectUri: new Uri(Constants.AADRedirectUri), parameters: new PlatformParameters());
#endif

**Comment by kpanwar** [comment]
netcoreapp2_0 is meant for console and web apps. Console implies here that there is no interactive web UI. There is no API in netcore to show a web view.
