### ISSUE TITLE
Add Prompt=select_account support via prompt behavior 

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/azure-activedirectory-library-for-dotnet#754]
Add Prompt=select_account support by updating prompt behavior enum for desktop/winrt/iOS/android. The behavior of this flag should be exactly like promptbehavior.always where we skip the cache lookup and directly go to UI.

**Comment by jennyf19** [comment]
E2E testing validation complete for iOS, Android, UWP and desktop
