### ISSUE TITLE
Test drop-in compatibility of new binaries built using multi-target project

### ISSUE THREAD

**Issue by HSAR** [AzureAD/azure-activedirectory-library-for-dotnet#766]
Older NuGet packages targeted MonoAndroid10, this is now MonoAndroid7.

**Comment by kpanwar** [comment]
@trwalke - Please check out the following samples and test that latest nightly binaries work by simply updating the nuget packages without causing compilation or runtime errors.
- https://github.com/Azure-Samples/active-directory-dotnet-native-desktop
- https://github.com/Azure-Samples/active-directory-dotnet-native-multitarget
- https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential

We don't need to send PRs, but we need to validate the behavior.
