### ISSUE TITLE
DocBug :Adaltrace is not applicable to 3.0+ release?

### ISSUE THREAD

**Issue by amritanshujohri** [AzureAD/azure-activedirectory-library-for-dotnet#782]
In readme.md, Under the desktop application. I do see AdalTrace being mentioned and how to use it to log/debug the details this class doesn't exist post 3.0?

**Comment by kpanwar** [comment]
duplicate of https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/527
