### ISSUE TITLE
Backward compatibility with Android broker that does not return Authority

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/azure-activedirectory-library-for-dotnet#803]
Backward compatibility with Android broker that does not return Authority. This will result in failure in ADAL as it would expect the authority to be present per Sovereign cloud support.

**Comment by jmprieur** [comment]
We have made changes in the code where we expect the authority to be send back from the broker, and android brokers don't return the authority. We need to accept when the authority is not returned on Android only. The broker needs to be released first.

**Comment by jmprieur** [comment]
@jennyf19 : do you think it's still an issue?
