### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by larrxu** [AzureAD/azure-activedirectory-library-for-dotnet#834]
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/e80e8b5f8806eecf46af9e454224877e3b6486b4/src/Microsoft.IdentityModel.Clients.ActiveDirectory/AdalServiceException.cs#L39

This is copied from AdalUserMismatchException

**Comment by bgavrilMS** [comment]
Has already been fixed by @henrik-me with commit 45b1aa97
