### ISSUE TITLE
ClientAssertionCertificate is not available in Portable version of the library.

### ISSUE THREAD

**Issue by Pikhulya** [AzureAD/azure-activedirectory-library-for-dotnet#844]
There are valid scenarios which require leveraging [Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-1.3.4) from within UWP Applications. In this case there should be a possibility to authenticate with a secret as well as with a certificate. An absence of the class [ClientAssertionCertificate](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.clientassertioncertificate?view=azure-dotnet) in the Portable version of the library prevents from authenticating using a certificate.

**Comment by kpanwar** [comment]
Portable has no support for certificate because portable API surface does not include X509 classes.
