### ISSUE TITLE
Resource Owner Password Credentials Grant with Confidential Client.

### ISSUE THREAD

**Issue by tinod** [AzureAD/azure-activedirectory-library-for-dotnet#845]
Hi,

I see at https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/98 that we're not going to support Resource Owner Password Credentials Grant in combination with a Confidential Client. Why is that? https://tools.ietf.org/html/rfc6749#section-4.3 states:

> 4.3.  Resource Owner Password Credentials Grant
  4.3.2.  Access Token Request
    If the client type is confidential or the client was issued client
    credentials (or assigned other authentication requirements), the
    client MUST authenticate with the authorization server as described
    in Section 3.2.1.

Hence, I would love to see Confidential clients supporting Resource Owner Password Credential Grant.

Any thoughts on this?

**Comment by kpanwar** [comment]
we do not plan on supporting this because it defeats the purpose of Oauth. there are other flows like on behalf of that you can leverage to authenticate a user and get a refresh token for long term syncing of data.
