### ISSUE TITLE
Require Url in MockHttpMessageHandler

### ISSUE THREAD

**Issue by RPangrle** [AzureAD/azure-activedirectory-library-for-dotnet#847]
Currently if the `Url` in `MockHttpMessageHandler` is null then all of the Uri validation gets skipped, and this is possibly allowing tests to pass when the should be failing. Add a hard requirement for request url validation in all tests will improve the quality of your tests.

**Comment by kpanwar** [comment]
@trwalke - this PR was already merged. Why are commits being made by referencing this issue? You should also mark this as fixed.
