### ISSUE TITLE
Cannot get library to build local

### ISSUE THREAD

**Issue by kevingoos** [AzureAD/azure-activedirectory-library-for-dotnet#848]
I am trying to build the library in my local visual studio but I cannot get it to build. I have 3422 errors.

![image](https://user-images.githubusercontent.com/1328773/31375362-8f070414-ada1-11e7-9321-1f11fe3d4c61.PNG)

1. Opened the ADAL.NET.NoWinRT.
2. Install .NET framework 6.2 developer
3. Install Android 7.1
4. Lot's of build errors I cannot get to fix.

I am running visual studio 2017 version 15.4.0. And this in windows 10.

Can somebody help me to build this?

**Comment by kpanwar** [comment]
Use developer command prompt to run - msbuild Adal.net.nowinrt.sln /t:restore /p:configuration=release

Then run /t:build for the same command. Vs project should build now

**Comment by kevingoos** [comment]
@kpanwar I will write some documentation about how to build and run in the wiki. So that new people don't ask these questions again :)

**Comment by kevingoos** [comment]
@kpanwar thx for the awnser here is the documentation about it. [Documentation](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/ADAL-.NET-Build-&-Run)
