### ISSUE TITLE
3.17 not backward compatible with 3.16

### ISSUE THREAD

**Issue by ianlar** [AzureAD/azure-activedirectory-library-for-dotnet#854]
Not sure if this is expected behavior:

Scenario: Authentication library (MyAuth.dll) compiled using 3.16.0 uses the following code:

`` var authContext = new AuthenticationContext(authority);
            try
            {
                var platParams = new PlatformParameters(PromptBehavior.Never);
                return await authContext.AcquireTokenAsync(resource, this.ApplicationID, this.RedirectUri, platParams).ConfigureAwait(false);
            }
            catch
``

MyAuth.dll is exposed as NuGet package and is used in upstream applications with ADAL >= 3.16.0 package as a dependency. If an upstream application updates the package to 3.17, authentication fails with the following error:

ArgumentException: parameters should be of type PlatformParameters

I'm assuming this has to do with the removal of the .Platform package but it would be nice if this continued to work in the upstream application.

**Comment by kpanwar** [comment]
@ianlar - afaik, nuget should be restoring with lowest first behavior. It is not possible to support both from maintainability cost perspective. We moved away from platform.dll for various reasons documented in #511
