### ISSUE TITLE
Cannot get AdalDesktopTestApp to run.

### ISSUE THREAD

**Issue by kevingoos** [AzureAD/azure-activedirectory-library-for-dotnet#858]
When I try to run the AdalDesktopTestApp I get the following exception:

`System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)'`

Does somebody have an idea how to fix this?

**Comment by kpanwar** [comment]
you need to disable strong name validation from developer command prompt. run "sn.exe -Vr *,*"

**Comment by kevingoos** [comment]
@kpanwar thx for the awnser here is the documentation about it. [Documentation](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/ADAL-.NET-Build-&-Run)
