### ISSUE TITLE
3.17.0 fails to bring in AD.Packages assembly

### ISSUE THREAD

**Issue by tomgruszowski** [AzureAD/azure-activedirectory-library-for-dotnet#862]
Nuget install fails to bring in AD.Packages assembly (missing Microsoft.IdentityModel.Clients.ActiveDirectory.Packages)

Upgraded from 3.16.1 on .net 4.7 asp.net mvc (non-core) project. Going back to 3.16.1 fixes issue.

"Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.17.0.27603".

This is not a binding redirect issue as the assembly is missing from references and bin folder.

**Comment by kpanwar** [comment]
@tomgruszowski - what is this package that fails? AFAIK, we don't own this package. The owner needs to stop taking dependency on platform binary.

**Comment by kpanwar** [comment]
azure sdk team needs to update.
