### ISSUE TITLE
Cannot pack fork into nuget package

### ISSUE THREAD

**Issue by kevingoos** [AzureAD/azure-activedirectory-library-for-dotnet#863]
I run the following command on the Developer Command Prompt to try to pack my fork into a nuget package.
`nuget Pack src\Microsoft.IdentityModel.Clients.ActiveDirectory\Microsoft.IdentityModel.Clients.ActiveDirectory.csproj`

**And this is the error I get:**
`Unable to find 'bin\Debug\Microsoft.IdentityModel.Clients.ActiveDirectory\bin\Debug\'. Make sure the project has been built.`

But **the project is build succesfull and contains the following folder in the debug folder:**
![folder](https://user-images.githubusercontent.com/1328773/31671100-739f42aa-b359-11e7-946d-1450855679a2.PNG)

**Comment by kevingoos** [comment]
I sombody can explain this to me I will also add this info to the documentation I wrote: [Documentation](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/ADAL-.NET-Build-&-Run)

**Comment by kpanwar** [comment]
pack command is not really supported because our nuget package also includes netcore45 target that is build separately and merged into a single package.

**Comment by kevingoos** [comment]
@kpanwar is there then an other way to actually create a nuget package for xamarin?
