### ISSUE TITLE
UWP Not Prompting for Authentication after Cancel

### ISSUE THREAD

**Issue by aherrick** [AzureAD/azure-activedirectory-library-for-dotnet#868]
I have a UWP app where I am signing in user via library. What I'm noticing is the following.

The first time the app opens it will prompt for user to login with credentials. If they login it works fine. However, if the cancel out (X) I can't get it to prompt again. It simply immediately throws "authentication_canceled" error.

My goal is if I retry the following code in a "Cancel" scenario, it will prompt them again to login. What am I missing here?

Basic code below:

```
            AuthenticationResultResp authResultResp = new AuthenticationResultResp();
            try
            {
                AuthenticationContext authContext = new AuthenticationContext(authority);
                var platformParams = new PlatformParameters(PromptBehavior.Auto, false);

                authResultResp.AuthenticationResult = await authContext.AcquireTokenAsync(resource, clientId, new Uri(returnUri), platformParams);
            }
            catch (AdalException ex)
            {
                authResultResp.ErrorMsg = ex.ErrorCode;
            }
            catch (Exception ex)
            {
                authResultResp.ErrorMsg = ex.Message;
            }
```

**Comment by aherrick** [comment]
@kpanwar do you agree this is an issue with the current version? Just trying to understand. Thanks!

**Comment by kpanwar** [comment]
just assigning it a milestone for release, IF this is truly an issue

**Comment by henrik-me** [comment]
@aherrick is this an issue with the current version of MSAL? Is the code you provided run as is on e.g. a click of a button?

**Comment by aherrick** [comment]
I don't believe this to be an issue anymore.
