### ISSUE TITLE
'Method not found' exception for new adal v 3.17.0

### ISSUE THREAD

**Issue by Alezis** [AzureAD/azure-activedirectory-library-for-dotnet#872]
I catch crash for new version of adal.
**Issue**
I have dll that used adal, it was compiled against v 3.13.9. My clients use my assembly and adal itself. Everything was good utill both versions were aligned. Recent days my client updated adal to 3.17.0 and my dll start throwing exception 'Method not found' exception:

> Method not found: 
> 'System.Threading.Tasks.Task`1<Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResult> Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(System.String, Microsoft.IdentityModel.Clients.ActiveDirectory.IClientAssertionCertificate)'.

I found that the reason in moving some methods to extension class. Since that CLR couldn't find method I got exception.
This is not actually bug, but I prefer next time have some notes for such changes in release notes. 
Thanks

**Comment by JECROFT** [comment]
I am encountering the same issue and cannot get certificate based authentication to work from the fluent azure management libraries. How did you resolve the exceptions?

**Comment by jmprieur** [comment]
@JECROFT : we strongly advise that you move to the latest version of ADAL, or even better to MSAL.NET.
