### ISSUE TITLE
AuthenticationParameters fails to parse authenticate challenges where Bearer is not the only challenge

### ISSUE THREAD

**Issue by HaeusslerK** [AzureAD/azure-activedirectory-library-for-dotnet#888]
If a WWW-Authenticate header has a value like "Negotiate, NTLM, Bearer ..." then we fail to parse it correctly. Pls. also see issue https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1042.

**Comment by HaeusslerK** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/992

**Comment by jmprieur** [comment]
this was fixed in ADAL ObjectiveC and ADAL Android. the fix needs to be made in ADAL.Net

**Comment by henrik-me** [comment]
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.
