### ISSUE TITLE
F# Xamarin Android AcquireTokenAsync exception

### ISSUE THREAD

**Issue by ArthurFSharp** [AzureAD/azure-activedirectory-library-for-dotnet#890]
Hello,

I'm trying to authenticate through Azure AD in a Xamarin Android F# application. 

Here the sample project (https://github.com/ArthurFSharp/AdalAndroidXamarin) TestFSharpADAndroid and the same version in C# (TestADAndroid). 

The C# version run perfectly but the F# version is crashing at this line : 

`authContext.AcquireTokenAsync(resource, clientId, uri, new PlatformParameters(activity))`
https://github.com/ArthurFSharp/AdalAndroidXamarin/blob/7e4ab2bcf6fc0b9e85d37f895090991ae8a07383/TestFSharpADAndroid/TestFSharpADAndroid/MainActivity.fs#L44

with the following error : 

> W/ResourceType( 1612): Bad XML block: header size 18254 or total size 169478669 is larger than data size 7429
An unhandled exception occured.

Full exception stack (Visual Studio 2017 Windows) : https://gist.github.com/ArthurFSharp/e472958c01dfad0c5f5cb65be00890c2
and Visual Studio for Mac : https://gist.github.com/ArthurFSharp/d02ebab23e63ee7a67fc59e06dc5a87d

Regards,

**Comment by jmprieur** [comment]
We don't support F#
