### ISSUE TITLE
Getting 'You're already signed in' when trying to sign in to second live account

### ISSUE THREAD

**Issue by jj09** [AzureAD/azure-activedirectory-library-for-dotnet#892]
Hi,

We are adding multiple accounts support for <a href="https://aka.ms/azureapp">Azure Mobile App</a>.

When user is authenticated with some live account, trying to authenticate with different live account shows given screen:

![aad](https://snag.gy/XbtvOD.jpg)

In order to sign in with second account user need to click 'Sign out and sign in with a different account'...but that would be counter intuitive, because we don't really sign user out.

Is there any way to work this around?

**Comment by kpanwar** [comment]
MSA is single user system at the moment and there is no way to work around this.
