### ISSUE TITLE
Works fine on iPhone Simulator but fails to login on actual device

### ISSUE THREAD

**Issue by akeresztesgh** [AzureAD/azure-activedirectory-library-for-dotnet#898]
Hello,

I have a configuration that runs great on the iPhone Simulator, but when run on the actual iPhone, I get the following error (Img):

![iphone-fail-image](https://user-images.githubusercontent.com/1649410/33090813-42f53d5a-cec3-11e7-92b8-79f7aaedcc8f.png)

Any clue why this doesn't work on the actual device?  If there's more information that I can provide that will help, please let me know.

Thanks!
AJ

**Comment by kpanwar** [comment]
the problem is not with the device or the simulator. The error suggests that you have different configurations for simulator vs device builds (dev vs PROD). The configs could be different in terms of what resource  you are accessing, the user you are attempting to authenticate. The error says that you need to add the user as an external user in the directory you are attempting to authenticate into.

**Comment by akeresztesgh** [comment]
Here's my auth code:

 public async Task<AuthenticationResult> Authenticate()
        {
            var authContext = new AuthenticationContext(_authenticateSettings.Authority);
            if (authContext.TokenCache.ReadItems().Any())
                authContext = new AuthenticationContext(authContext.TokenCache.ReadItems().First().Authority);
            
            var controller = UIApplication.SharedApplication.KeyWindow.RootViewController;
            var uri = new Uri(_authenticateSettings.ReturnUri);
            var platformParams = new PlatformParameters(controller);
            try{
                var authResult = await authContext.AcquireTokenAsync(_authenticateSettings.SharePointResource,
                                                                     _authenticateSettings.ClientId, uri, platformParams);//, UserIdentifier.AnyUser, "domain_hint=accordcarton.com");
                Result = authResult;
                return authResult;

            }catch(Exception ex){
                var asdf = ex;
                throw ex;
            }
        }

On the device all of the settings are the same (and I'm trying to login with the same user) and this baffles me.

**Comment by kpanwar** [comment]
I am sorry but that is completely outside the purview of the library. error is quite clear that it is configuration issue. you should print out all the parameters being used on the simulator vs the device and compare from there on.

**Comment by akeresztesgh** [comment]
It is the EXACT SAME code on both. Literally the only difference is the device vs simulator
