### ISSUE TITLE
Xamarin Authentication Validate Connection Programatically

### ISSUE THREAD

**Issue by aherrick** [AzureAD/azure-activedirectory-library-for-dotnet#903]
Is there anyway to validate the connection programatically? Currently I don't see a way.

My App is enterprise and is configurable as to what Resource (URL) Client ID/Secret it points at.

I'd like to be able to ensure the Resource (URL) Client ID are able to return a valid login without the user having to have the webview pull up every time.

**Comment by jmprieur** [comment]
I don't fully understand your requirement @aherrick 
Do you want to check that a user (and its credendials) have access to the resource?

**Comment by aherrick** [comment]
I'm using the authentication to connect o a Dynamics D365 environment. In iOS/Android from Xamarin Forms I plug the URL/ClientID/Secret in and call AcquireAccessToken. This then prompts a webview with a login assuming the supplied URL/ClientID/Secret are correct.

I'm trying to validate these configurations and ensure a successful setup without having to open the webview. Example if the ClientID is wrong, the authentication page won't display or will throw an error.

**Comment by jmprieur** [comment]
Ok. Got it @aherrick . Thanks for explaining.
If you want to do that outside the application you could use PowerShell to verify that the clientID exists and that it has a client secret. 
See for example: https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential/blob/master/Configure.ps1 and https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential/blob/master/Cleanup.ps1

If you want to do it from the application (but this will require another ClientID which does not change), you might want to use the Microsoft Graph: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/application

Proposing to close this question. Feel free to reopen if you don't think I've answered.

**Comment by aherrick** [comment]
Thanks. So sounds like the Graph API might work, but creating a secondary application (ClientID) just for validation of the first application doesn't sound great. Is that what you're suggesting?

I'd also need have that secondary application have Application wide rights so I could it could request an access token without having to prompt for validation.

Seems convoluted :(

**Comment by jmprieur** [comment]
yes, that's what I'm suggesting, and this second application could use a confidential client flow, that is verify that the first application exists in its own name (not in the name of a user), which is why I sent you the link on the daemon with certificate. Now it depends on the plaform you use. If it's a device, you don't want to use a confidential client flow ...
