### ISSUE TITLE
Add support for previous versions of the token cache

### ISSUE THREAD

**Issue by mikeblakeuk** [AzureAD/azure-activedirectory-library-for-dotnet#904]
Azure PowerShell (5) saves a version 2 TokenCache when you `Save-AzureRmContext`
We are using version 3 of the ADL so the tokenCache json (bytes) is skipped. https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Clients.ActiveDirectory/TokenCache.cs#L52
Please add support for version 2 tokencaches (e.g. auto upgrade)

**Comment by jmprieur** [comment]
We don't have plans to add backward compatibility from ADAL.NET v2.0 to ADAL.NET v3.0 (we will, though bring backward and forward compatibility between ADAL.NET v3.0 and MSAL.Net)

Since you have the source code for both ADAL.NET v3 and v2, is it an option for you to craft a converter?
