### ISSUE TITLE
Xamarin iOS shouldn't send UniqueId as user identifier type to iOS broker, when AnyUser is selected

### ISSUE THREAD

**Issue by oldalton** [AzureAD/azure-activedirectory-library-for-dotnet#905]
The meaning for UniqueId is different between ADAL ObjC and ADAL Xamarin. Xamarin uses UniqueId by default for AnyUser, which when passed to iOS broker without username results in an error (different user returned).

UniqueId as a user identifier type tells ADAL to compare by OID, but Xamarin doesn't provide us an OID in that case, it provides an empty user identifier, which will always fail.

Sample request from Xamarin:

msauth://broker?authority=https%3A%2F%2Flogin.microsoftonline.com%2Fde08c407-19b9-427d-9fe8-edf254300ca7%2F&resource=https%3A%2F%2Fonecoresrvs-cognizantonline.msappproxy.net%2F&client_id=1d2fc107-95e9-41d3-b433-a2609583c8e0&correlation_id=09b97f54-f9bb-4cd6-aa15-50c2d5f25a38&client_version=3.17.2.31801&force=NO&**username=&username_type=UniqueId**&redirect_uri=x-msauth-onecognizant%3A%2F%2Fcom.onecognizantmob.onecpushtest1%2F&extra_qp=&claims=&broker_key=Xz342-pWHJAKEM8G1UQ_NEwVg4JoPv9sYuY-oYqGpiw&max_protocol_ver=2&skip_cache=YES sourceApplication:com.onecognizantmob.onecpushtest1

Expected:
1. pass expected OID for username
2. pass OptionalDisplayableId instead of UniqueId if you don't know the OID
3. pass RequiredDisplayableId with user's UPN

**Comment by zevsst** [comment]
Seems it was fixed. I did some tests with the latest version of ADAL and MS Authenticator and they are passed. 
BTW: In case of login with broker you don't need AcquireToken twice any more, just use PlatforParameters(with useBroker = true) and pass AnyUser.
Hope this helps.
