### ISSUE TITLE
ADAL.NET should have the possiblity of passing the Client IP address in the client assertion

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/azure-activedirectory-library-for-dotnet#913]
**Why?**
Some services (for instance VSTS) need to send the client IP to AAD via signed client assertions in order to enforce Conditional Access (for instance based on geography). However, each time a proxy is involved, ESTS cannot observe the real client API. 

**What?**
We want to update the ClientAssertion API surface, to allow the developer to pass extra claims to be included when creating signed assertions. .

Additionally it would be a nice to have to be able to pass the client real user agent, but that's not a priority.

**Comment by henrik-me** [comment]
temp pr (still lots of discussion points): https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/942

**Comment by henrik-me** [comment]
Change in design is being evaluated. STS now ready for the client.

**Comment by jmprieur** [comment]
this is done. Closing
cc: @henrik-me
