### ISSUE TITLE
ADAL should not pass unique id as a login hint to the STS for interactive auth

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/azure-activedirectory-library-for-dotnet#915]
ADAL should not pass unique id as a login hint to the STS for interactive auth. It should only be sending displayable id (if provided). STS does not allow authentication using unique Ids and it requires the user to delete the ID and type in their UPN.

**Comment by jmprieur** [comment]
@kpanwar : what are the repro steps? what user problem is surfaced and in which condition?

**Comment by kpanwar** [comment]
Developer calls broker and passes in unique ID. ADAL passes it to broker as a login hint, which results in populating the hint in the UI.

**Comment by kpanwar** [comment]
@SomkaPe - Has this been fixed as well?

**Comment by jmprieur** [comment]
@SomkaPe : can you please reference the PR
