### ISSUE TITLE
Unable to load adalsql.dll

### ISSUE THREAD

**Issue by dmarlow** [AzureAD/azure-activedirectory-library-for-dotnet#920]
I, and others, have run into an issue where the adalsql.dll can't be loaded. I believe this is due to maybe SSMS and the version that is shipped with it.

Here's some more info: https://connect.microsoft.com/SQLServer/feedback/details/3141578/unable-to-load-adalsql-dll

Hoping maybe this place here gets more visibility.

**Comment by kpanwar** [comment]
That is an internal C++ library and not this one. You are using correct support channel via that thread
