### ISSUE TITLE
AcquireTokenAsync() Logging to Console by Default?

### ISSUE THREAD

**Issue by markolbert** [AzureAD/azure-activedirectory-library-for-dotnet#928]
I'm accessing an Azure key vault, using C#, in a Net Core 2 console app. Whenever the app runs, the console window gets hit with messages like this when I retrieve a secret from the vault:

> 2017-12-26T18:03:49.8610049Z: 29c98a86-9e1d-4a5d-86d6-daf8f2cfdc56 -
> AcquireTokenHandlerBase.cs: ADAL PCL.CoreCLR with assembly version
> '3.17.3.35304', file version '3.17.41219.2324' and informational
> version 'b6afaeae7cff965e66649e0ee7e8c29071d5a7e6' is running...
> 2017-12-26T18:03:49.8621855Z: 29c98a86-9e1d-4a5d-86d6-daf8f2cfdc56 -
> AcquireTokenHandlerBase.cs: === Token Acquisition started:
>         Authority: https://login.windows.net/[...]/
>         Resource: https://vault.azure.net
>         ClientId: [...]
>         CacheType: null
>         Authentication Target: Client
> 
> 2017-12-26T18:03:49.8981211Z: 29c98a86-9e1d-4a5d-86d6-daf8f2cfdc56 -
> AcquireTokenHandlerBase.cs: Loading from cache.
> 
> 2017-12-26T18:03:49.9010018Z: 29c98a86-9e1d-4a5d-86d6-daf8f2cfdc56 -
> TokenCache.cs: Looking up cache for a token...
> 
> 2017-12-26T18:03:49.9060990Z: 29c98a86-9e1d-4a5d-86d6-daf8f2cfdc56 -
> TokenCache.cs: No matching token was found in the cache
> 
> 2017-12-26T18:03:50.2185881Z: 29c98a86-9e1d-4a5d-86d6-daf8f2cfdc56 -
> TokenCache.cs: Storing token in the cache...
> 
> 2017-12-26T18:03:50.2211369Z: 29c98a86-9e1d-4a5d-86d6-daf8f2cfdc56 -
> TokenCache.cs: An item was stored in the cache
> 
> 2017-12-26T18:03:50.2351165Z: 29c98a86-9e1d-4a5d-86d6-daf8f2cfdc56 -
> AcquireTokenHandlerBase.cs: === Token Acquisition finished 
> successfully. An access token was retuned:
> 
>          Access Token Hash: [...]
>          Expiration Time: 12/26/2017 7:03:49 PM +00:00
>          User Hash: null
> 

I don't recall doing anything in my code to set up any kind of logging for the key vault access. However, I have configured Serilog's ILogger throughout the app, so maybe that's being picked up, somehow.

In stepping through the code, the console messages get generated from within the GetSecretAsync() callback:

```
        private async Task<string> GetAccessTokenAsync(string authority, string resource, string scope)
        {
            var appCredentials = new ClientCredential(_appConfig.Azure.AppID, AzureKeyVaultAppID);

            var context = new AuthenticationContext(authority, TokenCache.DefaultShared);

            // this is the line that generates the console output
            var result = await context.AcquireTokenAsync( resource, appCredentials );

            return result.AccessToken;
        }
```

How do I suppress these messages from being displayed?

**Comment by jmprieur** [comment]
@kpanwar : please send the link to the class where the user can disable the logs

**Comment by markolbert** [comment]
Sorry about the delay in replying.

You can read the in-depth analysis someone did on this issue, and how to resolve it, at https://stackoverflow.com/questions/47982194/suppressing-console-logging-by-azure-keyvault/48223879#48223879

Let me know if you have any other questions.


  *   Mark

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jmprieur** [comment]
Thanks
A complete explanation on logging is provided in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net
