### ISSUE TITLE
Move AuthenticationResultEx to common core

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/azure-activedirectory-library-for-dotnet#929]
Move AuthenticationResultEx to common core. This is needed for cache code to work in core. The work includes
- Moving AuthenticationResultEx with rename.
- Create equivalent classes for AuthenicationResult and UserInfo because they are public and cannot be moved without issues of confusion and conflict with MSAL class with the same name.
- Update public AuthenticationResult class to return values from new equivalent class.
- Introcude CoreCacheItem class that contains both MSAL and ADAL cache objed representation. This is just an idea, but not finalized with approach.

**Comment by henrik-me** [comment]
closing
