### ISSUE TITLE
Null reference when clearing token cache in ADAL before acquiring a token at least once

### ISSUE THREAD

**Issue by trwalke** [AzureAD/azure-activedirectory-library-for-dotnet#936]
Clearing the token cache before calling acquiretokenasync at least once will result in a an unhandled null reference exception.
Reproduction steps:
1. Run the ADAL Automation app
2. Hit the clear cache button first.

The app will halt immediately and a null reference exception will be thrown

**Comment by jmprieur** [comment]
This is fixed
