### ISSUE TITLE
There is no longer a Readme.md ,License and Contributing.md files at the root of the repo

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/azure-activedirectory-library-for-dotnet#945]
**Repro steps**
Clone the repo

**Expected**
I should see a Readme.md file telling me what the repository is, and a contribution.md file explaining me how to build the repo and contribute, as well as a license file

**Actual**
I cannot find these files. There is a version for ADAL in the adal subfolder, but I would like to see a file explaining me that the repo is, for the moment, for the combined libraries and linking to the other readme. 

**bottom line**
We need to have a good experience for customers and contributors visiting the ADAL.Net and MSAL.NET repos:
- the repo is externally for ADAL, this is where users will raise issues
- there is another repo for MSAL where they would raise issues. and BTW we should probably change the readme there to say that to build MSAL > 1.1.1 Preview, one needs to clone the ADAL repo.
- better solution ? have a third repo, and keep these 2 for communication and raising issues?

**Comment by henrik-me** [comment]
verified.
