### ISSUE TITLE
Platform Parameters is not accepting any parameter for android with latest version of the ADAL

### ISSUE THREAD

**Issue by RamanathanC** [AzureAD/azure-activedirectory-library-for-dotnet#949]

**Comment by jmprieur** [comment]
@RamanathanC : can you please provide repro steps ? (or repro code)?

**Comment by reutann** [comment]
@RamanathanC, I was running into this as well - you need to change the lib type in your .csproj to monoandroid7 

![image](https://user-images.githubusercontent.com/25594617/35287441-55d74f3c-0030-11e8-9009-a8cb636761c2.png)

**Comment by jmprieur** [comment]
@RamanathanC 
Do you mean that when added the NuGet package the reference in your Xamarin.Android project was wrong?

**Comment by jmprieur** [comment]
Closing as by design, as ADAL.NET needs to be reference by the right type of project (if needed use multiple target frameworks)
