### ISSUE TITLE
3.19.0 UWP Initial Authentication Request Returns Cancel

### ISSUE THREAD

**Issue by aherrick** [AzureAD/azure-activedirectory-library-for-dotnet#969]
Updated from 3.17.3 to 3.19.0.

In 3.19.0 when I make an initial request to Authenticate and AquireToken, it instantly returns a "Cancelled" response. The next time the request happens however it works as expected.

Reverting back to 3.17.3 works as expected and allows for Authentication.

See example code:

```
            var authResultResp = new AuthenticationResultResp();
            try
            {
                var authContext = new AuthenticationContext(authority);
                var platformParams = new PlatformParameters(PromptBehavior.Auto, false);

                authResultResp.AuthenticationResult = await authContext.AcquireTokenAsync(resource, clientId, new Uri(returnUri), platformParams);
            }
            catch (AdalException ex)
            {
                authResultResp.ErrorMsg = ex.ErrorCode;
            }
            catch (Exception ex)
            {
                authResultResp.ErrorMsg = ex.Message;
            }
```

**Comment by jmprieur** [comment]
@aherrick thanks for the feedback
Which platform are you using? .NET Framework? Xamarin ? can you please share some repro code?

**Comment by aherrick** [comment]
This is Xamarin Forms 2.5.0.122203 UWP. 

The code is above calling into `AquireTokenAsync` It throws `AdalException `on initial attempt.

On second attempt it works fine. With 3.17.3 it works fine on first try.

**Comment by SomkaPe** [comment]
@aherrick  could you please provide details about AdalException - exception message, error code...

**Comment by aherrick** [comment]
Stack trace:

```
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.<PreTokenRequest>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AXLE_Driver.UWP.PlatformSpecific.Authenticator.<Authenticate>d__0.MoveNext()
```

**Comment by jmprieur** [comment]
@aherrick could you please check with ADAL.NET 3.19.1 (published yesterday): we fixed a deadlock which could happen if developers called the API blocking async calls on the UI thread. This does not seem to be the case of your code above, but maybe this code is called from a method which uses .Result or .Wait() ?

**Comment by aherrick** [comment]
Same issue with 3.19.1

**Comment by jennyf19** [comment]
Hi @aherrick Can you try with 3.18? Trying to narrow this down to a version if possible. Thanks.

**Comment by aherrick** [comment]
Just confirmed it does do it in 3.18

Still working fine in 3.17.3

**Comment by jmprieur** [comment]
@aherrick @GFlisch do you have repro code that we could check?

**Comment by jennyf19** [comment]
@GFlisch @aherrick We are actively investigating this and working on a fix.

**Comment by GFlisch** [comment]
Hi

Did you still need a repro code?

Any idea when the issue will be solved ?

Thanks,

Gilles


Sent from windows 10 mobile.
________________________________

**Comment by jennyf19** [comment]
@GFlisch @aherrick 

The fix will be in ADAL 3.19.2, which should be released early next week. 

The issue was due to a race condition. We did not enforce, on the UWP platform, the call of WIA (Web Integrated Authentication) from the UI thread. A recent addition related to "[authority aliases](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AuthenticationContext:-the-connection-to-Azure-AD#advanced-note-server-driven-aliases-of-authorities-adalnet--318)" surfaced the issue in a more repeatable way. Thanks again for bringing this to our attention.

cc: @henrik-me @SomkaPe

**Comment by GFlisch** [comment]
Hi jennyf19,

If you want that we test it when a prerelease of the package exists.

Don’t hesitate.

Gilles

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by henrik-me** [comment]
@GFlisch can you validate using the bits in pr #982 ? We will be releasing the bits this week however we are a bit stretched on the timing and will not be able to provide the package today. We expect to be able to release tomorrow or Wednesday.

**Comment by jennyf19** [comment]
@GFlisch @aherrick 
We just released [ADAL 3.19.2](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/v3.19.2) with the UWP fix. Please try it out and let us know if this resolves your issue.

**Comment by GFlisch** [comment]
Hi,

Just tested and it works.

Thanks for the fix.

Gilles

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jmprieur** [comment]
Thanks for confirming, @GFlisch
