### ISSUE TITLE
Please provide proper documentation on docs.microsoft.com

### ISSUE THREAD

**Issue by stijnherreman** [AzureAD/azure-activedirectory-library-for-dotnet#975]
So far, I've been able to find good documentation on docs.microsoft.com for the Azure parts I'm using. Various scenarios are covered for the components, step-by-step guides are provided, etc.

This library is an exception. What you have is better than nothing, of course, but I don't consider an API Reference and an unstructured collection of GitHub repos to be proper documentation.

For example, I want to connect to an Azure SQL database using a token, and I want to acquire this token by using a certificate. https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication-configure#azure-ad-token sends you to https://blogs.msdn.microsoft.com/sqlsecurity/2016/02/09/token-based-authentication-support-for-azure-sql-db-using-azure-ad-auth/ which provides a ZIP file containing a Word document and sample code. Further searches finally made me arrive at this repository.

Summarised: customer experience is not ideal, any improvements would be very appreciated.

**Comment by jmprieur** [comment]
Thanks very much for your feedback. I agree that there is plenty of room for improvement.
would it help to have a conceptual documentation about ADAL.Net?

**Comment by stijnherreman** [comment]
Yes, that would help a lot I think.

**Comment by jmprieur** [comment]
@stijnherreman : could you please tell us if this conceptual documentation is useful for you?
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki

**Comment by stijnherreman** [comment]
I've taken a look at all the new pages and they are very useful. I've already got my code working by now, but without a doubt with this new documentation it would have gone a lot faster :)

Thank you for looking into this so quickly!

**Comment by jmprieur** [comment]
Thanks for your feedback, @stijnherreman 
How strongly do you feel about:
1. having this documentation in docs.microsoft.com? 
2. having a link on docs.microsoft.com to these pages (from which docs.microsoft.com pages would you look for it, BTW) ?

**Comment by stijnherreman** [comment]
Having it on docs.microsoft.com would be good since it's the go-to place for documentation currently, but a link to these pages would also work fine I suppose.

I don't really navigate through docs.microsoft.com, instead I just use a search engine to look for docs, perhaps adding a `site:docs.microsoft.com` to the query.

**Comment by jmprieur** [comment]
this is on the backlog for after Ignite

**Comment by jmprieur** [comment]
Will be done for MSAL.NET, not ADAL.NET
