### ISSUE TITLE
Logging not working

### ISSUE THREAD

**Issue by iano123** [AzureAD/azure-activedirectory-library-for-dotnet#979]
Hi,

THe adal is not working on one of my backend services. It is not easy to debug.

I am puzzled on how to make logging happen. I am adding a class implementing IAdalLogCallback
`

public class AdalLoggerCallback : IAdalLogCallback
    {
        private ILog log;

        public AdalLoggerCallback()
        {
            this.log = log4net.LogManager.GetLogger("IRMa.SNA.WebApi");
        }
        public void Log(LogLevel level, string message)
        {
            // platform-specific code goes here
            switch (level)
            {
                case LogLevel.Error:
                    this.log.Error($"ADAL: {message}");
                    break;
                case LogLevel.Information:
                    this.log.Info($"ADAL: {message}");
                    break;
                case LogLevel.Verbose:
                    this.log.Info($"ADAL: {message}");
                    break;
                case LogLevel.Warning:
                    this.log.Warn($"ADAL: {message}");
                    break;
                default:
                    this.log.Info($"ADAL: {message}");
                    break;
            }

        }
`

Then I am adding that to my startup.auth
`

 public void Configuration(IAppBuilder app)
        {

            LoggerCallbackHandler.Callback = new AdalLoggerCallback();

            app.UseActiveDirectoryFederationServicesBearerAuthentication(
                new ActiveDirectoryFederationServicesBearerAuthenticationOptions
                {
                    MetadataEndpoint = AdfsMetadataEndpoint,
                    TokenValidationParameters = new TokenValidationParameters()
                    {
                        ValidAudience = Audience
                    },
                });
        }

I am also adding Microsoft.Owin" value="Verbose"  to system.diagnostics

**Comment by jmprieur** [comment]
@iano123 
Pleas have a look at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net

**Comment by iano123** [comment]
Hi Sir,

thank you for answering.

It is not working. I tried exactly the same. I am trying it in OWIN on asn.net MVC.  Is there something spechial I need to do to get it to work in mvc?

Many Thanks for your time.

**Comment by jmprieur** [comment]
@iano123,
- Are you using ADAL.NET < 3.18 ?
- Did you enable logging? ``LoggerCallbackHandler.UseDefaultLogging = true``
I'm not familiar with log4net. could the problem be on log4net not logging things up?

**Comment by jmprieur** [comment]
BTW, @iano123:
- I closed this issue because I believe I've answered, but feel free to re-open if your problem is not solved.
- the LoggerCallbackHandler is for ADAL, not for OWIN

**Comment by iano123** [comment]
Dear JM,

I will have to check the LoggerCallbackHandler.UseDefaultLogging = true 
If it does need be explicitly activated in code, then there is a possibility of it not being so. I will check tomorrow. (evening now and no access to the code)

THe problem is 4 sure not the log4net. It does not even hit a breakpoint.

Thank you again for your time. 

Jan

**Comment by iano123** [comment]
Dear JM,

I tried to add  LoggerCallbackHandler.UseDefaultLogging = true

Still I am not hitting a breakpoint. (so for sure it is not log4net)

This is the startup class I am using.

`//using IRMa.SNA.Logging;
using log4net;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.Owin;
using Microsoft.Owin.Logging;
using Microsoft.Owin.Security.ActiveDirectory;
using Owin;
using System.Configuration;
using System.IdentityModel.Tokens;
using System.Threading.Tasks;

[assembly: OwinStartup(typeof(IRMa.SNA.WebApi.Startup), "Configuration")]

namespace SNA.WebApi
{
    /// <summary>
    /// This class is used to bootstrap the claims based security
    /// </summary>
    public partial class Startup
    {
        //
        // The Client ID is used by the application to uniquely identify itself to Azure AD.
        // The Metadata Address is used by the application to retrieve the signing keys used by Azure AD.
        // The AAD Instance is the instance of Azure, for example public Azure or Azure China.
        // The Authority is the sign-in URL of the tenant.
        // The Post Logout Redirect Uri is the URL where the user will be redirected after they sign out.        

        private static string AdfsMetadataEndpoint = ConfigurationManager.AppSettings["ida:AdfsMetadataEndpoint"];
        private static string Audience = ConfigurationManager.AppSettings["ida:Audience"];
        public static void Log(LogLevel level, string message, bool containsPii)
        {
            var log = log4net.LogManager.GetLogger("IRMa.SNA.WebApi");
            switch (level)
            {
                case LogLevel.Error:
                    log.Error($"ADAL: {message}");
                    break;
                case LogLevel.Information:
                    log.Info($"ADAL: {message}");
                    break;
                case LogLevel.Verbose:
                    log.Info($"ADAL: {message}");
                    break;
                case LogLevel.Warning:
                    log.Warn($"ADAL: {message}");
                    break;
                default:
                    log.Info($"ADAL: {message}");
                    break;
            }
        }
        public void Configuration(IAppBuilder app)
        {

            // LoggerCallbackHandler.LogCallback = DelegateMethod;
            LoggerCallbackHandler.LogCallback = Log;
            LoggerCallbackHandler.PiiLoggingEnabled = true;
            LoggerCallbackHandler.UseDefaultLogging = true;

            app.UseActiveDirectoryFederationServicesBearerAuthentication(
                new ActiveDirectoryFederationServicesBearerAuthenticationOptions
                {
                    MetadataEndpoint = AdfsMetadataEndpoint,
                    TokenValidationParameters = new TokenValidationParameters()
                    {
                        ValidAudience = Audience
                    },
                });
        }

    }



}
`

**Comment by iano123** [comment]
I am using 3.19.1

**Comment by jmprieur** [comment]
@iano123, where do you call ADAL.NET?
so far I see middleware code, but I don't any any code which instantiate an AuthenticationContext to get a token. What is your scenario? did you start from a sample?

**Comment by jmprieur** [comment]
Examples of WebApps calling WebAPIs with ADAL are available from:
https://github.com/Azure-Samples?utf8=%E2%9C%93&q=webapp-webapi&type=&language=

**Comment by jmprieur** [comment]
Or would you be looking for OWIN/Middleware logging? (not ADAL Logging)

**Comment by iano123** [comment]
The scenario is that I have one website and two backend web API's. THe code is for one of the two web API's. in that web api I am not getting the claims principle.

THis is the code for the **website**:
`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Owin;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OpenIdConnect;
using System.Threading.Tasks;
using System.Configuration;
using Microsoft.Owin;
using System.Security.Claims;
//using System.IdentityModel.Tokens;
using Microsoft.Owin.Security.ActiveDirectory;
using Microsoft.Owin.Security.Notifications;
using Microsoft.IdentityModel.Protocols;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using IRMa.Web.UI.Utils;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Http;
using IRMa.Web.UI.Controllers;
using log4net;
using System.IdentityModel.Tokens;
using System.Threading;

[assembly: OwinStartup(typeof(IRMa.Web.UI.App_Start.Startup))]

namespace IRMa.Web.UI.App_Start
{
    public partial class Startup
    {
        private static string clientId = ConfigurationManager.AppSettings["ida:irmaWebClientId"];
        private static string metadataAddress = ConfigurationManager.AppSettings["ida:ADFSDiscoveryDoc"];
        private static string irmaWebPostLoginRedirectUri = ConfigurationManager.AppSettings["ida:irmaWebPostLoginRedirectUri"];
        private static string postLogoutRedirectUri = ConfigurationManager.AppSettings["ida:irmaWebPostLogoutRedirectUri"];
        private static string sharedSecret = ConfigurationManager.AppSettings["ida:irmaSharedSecret"];
        private static string Authority = ConfigurationManager.AppSettings["ida:Authority"];
        private static string AdfsMetadataEndpoint = ConfigurationManager.AppSettings["ida:AdfsMetadataEndpoint"];

        private static string irmaRTIdentifier = ConfigurationManager.AppSettings["RTSvcServer"];
        private static string irmaSNAIdentifier = ConfigurationManager.AppSettings["SNASvcServer"];

        /// <summary>
        /// Configures the open ID Configuration
        /// </summary>
        /// <param name="app"></param>
        public void Configuration(IAppBuilder app)
        {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
            app.UseCookieAuthentication(new CookieAuthenticationOptions());
            app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                {
                    ClientId = clientId,
                    AuthenticationType = OpenIdConnectAuthenticationDefaults.AuthenticationType,
                    MetadataAddress = metadataAddress,
                    RedirectUri = irmaWebPostLoginRedirectUri,
                    PostLogoutRedirectUri = postLogoutRedirectUri,
                    TokenValidationParameters = new System.IdentityModel.Tokens.TokenValidationParameters()
                    {
                        SaveSigninToken = true
                    },
                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        AuthenticationFailed = OnAuthenticationFailed,
                        AuthorizationCodeReceived = OnAuthorizationCodeReceived
                    }
                });

        }

        /// <summary>
        /// Redirect on authentication error
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        private Task OnAuthenticationFailed(AuthenticationFailedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> context)
        {
            context.HandleResponse();
            context.Response.Redirect("./Error?errorMessage=" + context.Exception.Message);
            return Task.FromResult(0);
        }

        /// <summary>
        /// Make sure a token is fetched for the RT services
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedNotification context)
        {         
            var log = LogManager.GetLogger("IRMa.Web.UI");
            var code = context.Code;
            log.Info($"Authorization Code: {code}");
            string userObjectID = context.AuthenticationTicket.Identity.FindFirst(ClaimTypes.NameIdentifier).Value;
            log.Info("Claims received");
            foreach (var claim in context.AuthenticationTicket.Identity.Claims) {
                log.Info($"Type {claim.Type}: Value {claim.Value}");
            }
            ClientCredential credential = new ClientCredential(clientId, sharedSecret);
            var authContext = new Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext(Authority, false, new ADFSSessionCache(userObjectID));
            AuthenticationResult result;
            string ip = context.Request.Headers["X-Forwarded-For"]; // AWS compatibility
            var  _httpContext = HttpContext.Current;
            Uri uri = new Uri(irmaWebPostLoginRedirectUri);
            result = await authContext.AcquireTokenByAuthorizationCodeAsync(code, uri, credential, irmaRTIdentifier);
            _httpContext.Cache.Add(userObjectID, result.AccessToken, null, System.Web.Caching.Cache.NoAbsoluteExpiration, new TimeSpan(0, 20, 0), System.Web.Caching.CacheItemPriority.Normal, null);
        }
    }
}
`
Then in the controller

`
/// <summary>
        /// fetch an access token
        /// </summary>
        /// <returns></returns>
        private async Task<string> GetAccessToken(string identifier)
        {
            string userObjectID = ClaimsPrincipal.Current.FindFirst(ClaimTypes.NameIdentifier).Value;
            AuthenticationContext authContext = new AuthenticationContext(Authority, false, new ADFSSessionCache(userObjectID));
            ClientCredential credential = new ClientCredential(clientId, sharedSecret);
            Uri uri = new Uri(irmaWebPostLoginRedirectUri);
            AuthenticationResult result;

            try
            {

                bool retry = false;
                int retryCount = 0;
                string accessToken = null;

                do
                {
                    retry = false;
                    try
                    {
                        result = await authContext.AcquireTokenSilentAsync(identifier, credential, new UserIdentifier(userObjectID, UserIdentifierType.UniqueId));
                        accessToken = result.AccessToken;
                    }
                    catch (AdalException ex)
                    {
                        log.Debug(ex);
                        if (ex.ErrorCode == "temporarily_unavailable")
                        {
                            // Transient error, OK to retry.
                            retry = true;
                            retryCount++;
                            Thread.Sleep(1000);
                        }
                        else
                        if (ex.ErrorCode == "failed_to_acquire_token_silently")
                        {
                            // There are no tokens in the cache. 
                            AuthenticationManager.SignOut(OpenIdConnectAuthenticationDefaults.AuthenticationType, CookieAuthenticationDefaults.AuthenticationType);
                            return null;
                        }
                        else
                        {
                            throw ex;
                        }
                    }
                }
                while ((retry == true) && (retryCount < 1));
                return accessToken;
            }
            catch (Exception ex)
            {
                log.Error(ex);
            }

            return "";
        }
`

**Comment by jmprieur** [comment]
Do you get into OnAuthorizationCodeReceived ?

**Comment by iano123** [comment]
Yes I do. It also returns an authorization token.
