### ISSUE TITLE
UserPasswordCredential not available on dotnet core 2.0

### ISSUE THREAD

**Issue by amanbha** [AzureAD/azure-activedirectory-library-for-dotnet#988]
Is this a work in progress, until its available, what are the workarounds?

Its being asked by customers in Service Fabric repo:
https://github.com/Azure/service-fabric-issues/issues/833

**Comment by jmprieur** [comment]
cc: @vibronet 
This is by design.  This page lists the ways to acquire a token.
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquring-a-token-return-AuthenticationResult-and-possibly-UserInfo

Are you writing a Desktop/mobile application? 
A Web App / Web API?
or a daemon (like windows service) application?

**Comment by amanbha** [comment]
@jmprieur  We are writing a Service Fabric service. This is available on full .net framework so why its omitted from .net core 2.0? Users migrating from full net framework to net core are running into issues because of this as mentioned in the linked issue from service fabric repo, so please  reconsider this design decision.

**Comment by binoypatel** [comment]
Got this showstopper as we are converting WCF to .net core, please consider to bring this

**Comment by gastart** [comment]
+1

**Comment by jmprieur** [comment]
+ @henrik-me

**Comment by henrik-me** [comment]
@rayluo @SomkaPe @jennyf19 let's consider this as part of our MSAL work on the u/p scenarios

**Comment by rayluo** [comment]
Implemented in [MSAL 2.1.0 Preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-v2.1.0)

**Comment by JHinW** [comment]
puzzled by this issue and rebuild a new  copy based on Netstandard2.0 for anyone who needs it => https://github.com/BCRDC/azure-activedirectory-library-for-dotnet/blob/dev/dotnetcore2Plus/BCRDC.ActiveDirectory/Test.App/Program.cs
