### ISSUE TITLE
AcquireTokenAsync is failing with an HttpRequestException on UWP

### ISSUE THREAD

**Issue by maxvella** [AzureAD/azure-activedirectory-library-for-dotnet#995]
I'm using ADAL 3.17.3 on a UWP client app. Everything was working perfectly up until yesterday. During the last 24 hours, AcquireTokenAsync has been throwing an HttpRequestException with an internal exception of type System.Runtime.InteropServices.COMException (0x80072F0D), with the following message: "The text associated with this error code could not be found. The certificate authority is invalid or incorrect"

This seems to be a problem which is external to my App as I haven't made any code changes which will affect this.

**Comment by jmprieur** [comment]
@maxvella. Are you using a [client credential with certificate](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows#client-credentials-with-certificate-in-adalnet) grant? 

Or otherwise which Authority do you pass-in when you instanciate your [AuthenticationContext](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AuthenticationContext:-the-connection-to-Azure-AD) ?

**Comment by maxvella** [comment]
@jmprieur 
Thank you for your prompt response.

I am using this constructor: public AuthenticationContext (string authority);

The authority is https://login.windows.net/{my tenant domain}. The tenant domain is an onmicrosoft.com domain.

The problem seems to be confined to UWP. Worked flawlessly until a couple of days ago, then this error started cropping up. Unit tests written against the full .Net Framework 4.7 using the same logic are still running fine.

thanks.

**Comment by maxvella** [comment]
I also replaced https://login.windows.net with https://login.microsoftonline.com but situation remains unchanged. Units tests running on 4.7 are OK, UWP fails

**Comment by maxvella** [comment]
Issue does seem to be with the App, after all. I created a stripped-down UWP project and it is working. I haven't quite figured out where the problem is, as yet.

**Comment by jennyf19** [comment]
@maxvella - Are you un-blocked or still getting the exception?

**Comment by maxvella** [comment]
Thank you jennyf19. Working on it but the problem appears to have been with the app itself, really strange because it just stopped working and I didn’t make any code changes which could affect it. It did work on a stripped down uwp app. Now am re-creating the solution and keeping my fingers crossed. Will keep you posted.
