### ISSUE TITLE
(Xamarin iOS) TokenCache is empty after authenticate

### ISSUE THREAD

**Issue by alexrainman** [AzureAD/azure-activedirectory-library-for-dotnet#997]
I am able to Authenticate and i get authResult back but the second time i run authentication TokenCache is empty.

Any ideas?

**Comment by jennyf19** [comment]
@alexrainman 
Thanks for reporting the issue. 

Can you please provide repro code?

cc: @SomkaPe

**Comment by alexrainman** [comment]
@jennyf19 i found out why it was empty. KeyChain Groups should be enabled at Entitlements.plist but it took me a while to find out Googling.

**Comment by jennyf19** [comment]
@alexrainman - glad you figured it out. We'll look at adding this to our documentation.

Have you considered using [broker](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Leveraging-brokers-on-Android-and-iOS) with Xamarin iOS? 

cc: @jmprieur

**Comment by jennyf19** [comment]
@alexrainman - going to close this issue, as you figured out the problem. let us know if you need more assistance or run into any other issues.

**Comment by alexrainman** [comment]
@jennyf19 will take a look at brokers
